### ISSUE TITLE
More informative error when group information is not available in getState(getEnergy=True, groups=groups)

### ISSUE THREAD

**Issue by jchodera** [openmm/openmm#1800]
The [docstring for `Context.getState`](https://github.com/pandegroup/openmm/blob/master/wrappers/python/src/swig_doxygen/swig_lib/python/extend.i#L33-L37) suggests that energies for any group up to `31` can be retrieved:
```
        groups : set={0,1,2,...,31}
            a set of indices for which force groups to include when computing
            forces and energies. The default value includes all groups. groups
            can also be passed as an unsigned integer interpreted as a bitmask,
            in which case group i will be included if (groups&(1<<i)) != 0.
```
However, attempting to retrieve the `State` object containing the energy for group 31 in a `set` yields a puzzling error on Python 3.5:
```python
mski1776:openmmtools choderaj$ python
Python 3.5.2 |Continuum Analytics, Inc.| (default, Jul  2 2016, 17:52:12) 
[GCC 4.2.1 Compatible Apple LLVM 4.2 (clang-425.0.28)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from simtk import openmm, unit
>>> from openmmtools.testsystems import AlanineDipeptideVacuum
>>> integrator = openmm.VerletIntegrator(1*unit.femtoseconds)
>>> testsystem = AlanineDipeptideVacuum()
>>> context = openmm.Context(testsystem.system, integrator)
>>> context.setPositions(testsystem.positions)
>>> state = context.getState(getEnergy=True, groups={31})
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/choderaj/miniconda3/lib/python3.5/site-packages/simtk/openmm/openmm.py", line 6204, in getState
    state = _openmm.Context_getState(self, types, enforcePeriodicBox, groups_mask)
NotImplementedError: Wrong number or type of arguments for overloaded function 'Context_getState'.
  Possible C/C++ prototypes are:
    OpenMM::Context::getState(int,bool,int) const
    OpenMM::Context::getState(int,bool) const
    OpenMM::Context::getState(int) const
```
Things work fine for groups 1 through 30:
```python
>>> state = context.getState(getEnergy=True, groups={0})
>>> state = context.getState(getEnergy=True, groups={1})
>>> state = context.getState(getEnergy=True, groups={2})
...
>>> state = context.getState(getEnergy=True, groups={30})
```

**Comment by jlmaccal** [comment]
I tried your example with python 2.7 and it works fine.

As an aside, the conda version of `openmoltools` doesn't have `testsystems`.

**Comment by peastman** [comment]
It's probably a bug in the conversion of sets to ints.  Does `groups=1<<31` work correctly?

**Comment by jchodera** [comment]
> As an aside, the conda version of openmoltools doesn't have testsystems.

`openmmtools`, not `openmoltools`

> It's probably a bug in the conversion of sets to ints. Does groups=1<<31 work correctly?

Will check!

**Comment by jlmaccal** [comment]
@jchodera oops...

This works for me (os x) with a fresh install of openmm from the omnia channel under both python 2.7 and 3.5.

@peastman The conversion code in `extend.i` seems off by one to me, shouldn't it be `>=0x80000000`, as `2^31 - 1` is the largest 32-bit unsigned integer.

**Comment by jlmaccal** [comment]
I suspect the error is that `2^31` can't be represented as a 32-bit integer, so swig can't find an appropriate overload to call.

No idea why it's working on my system, though.

**Comment by jlmaccal** [comment]
OK, I realize now it's a bit more complicated than that...

Wouldn't this be less error-prone if `groups` was unsigned everywhere in the API?

**Comment by jchodera** [comment]
> It's probably a bug in the conversion of sets to ints. Does `groups=1<<31` work correctly?

Nope.
```
>>> state = context.getState(getEnergy=True, groups={31})
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/choderaj/miniconda3/lib/python3.5/site-packages/simtk/openmm/openmm.py", line 6204, in getState
    state = _openmm.Context_getState(self, types, enforcePeriodicBox, groups_mask)
NotImplementedError: Wrong number or type of arguments for overloaded function 'Context_getState'.
  Possible C/C++ prototypes are:
    OpenMM::Context::getState(int,bool,int) const
    OpenMM::Context::getState(int,bool) const
    OpenMM::Context::getState(int) const

>>> state = context.getState(getEnergy=True, groups=1<<31)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/choderaj/miniconda3/lib/python3.5/site-packages/simtk/openmm/openmm.py", line 6204, in getState
    state = _openmm.Context_getState(self, types, enforcePeriodicBox, groups_mask)
NotImplementedError: Wrong number or type of arguments for overloaded function 'Context_getState'.
  Possible C/C++ prototypes are:
    OpenMM::Context::getState(int,bool,int) const
    OpenMM::Context::getState(int,bool) const
    OpenMM::Context::getState(int) const

>>> 
```

**Comment by peastman** [comment]
It's working fine for me too:

```Python
>>> context.getState(getEnergy=True, groups={31})
<simtk.openmm.openmm.State object at 0x101b3d630>
>>> context.getState(getEnergy=True, groups=1<<31)
<simtk.openmm.openmm.State object at 0x101b3d198>
```

That's with the latest OpenMM code and Python 3.4.5 running on OS X.

**Comment by jchodera** [comment]
That's odd.

I just tried upgrading my Python 3.5 (on OSX 10.11.6) and it still seems broken:
```
mski1776:benchmark choderaj$ conda update --yes conda
Fetching package metadata .............
Solving package specifications: .

# All requested packages already installed.
# packages in environment at /Users/choderaj/miniconda3:
#
conda                     4.3.16                   py35_0  
mski1776:benchmark choderaj$ conda update --yes python
Fetching package metadata .............
Solving package specifications: .

Package plan for installation in environment /Users/choderaj/miniconda3:

The following packages will be UPDATED:

    python: 3.5.2-0 --> 3.5.3-1

mski1776:benchmark choderaj$ python
Python 3.5.3 |Continuum Analytics, Inc.| (default, Mar  6 2017, 12:15:08) 
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.57)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from simtk import openmm, unit
>>> from openmmtools.testsystems import AlanineDipeptideVacuum
>>> integrator = openmm.VerletIntegrator(1*unit.femtoseconds)
>>> testsystem = AlanineDipeptideVacuum()
>>> context = openmm.Context(testsystem.system, integrator)
>>> context.setPositions(testsystem.positions)
>>> state = context.getState(getEnergy=True, groups={31})
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/choderaj/miniconda3/lib/python3.5/site-packages/simtk/openmm/openmm.py", line 6204, in getState
    state = _openmm.Context_getState(self, types, enforcePeriodicBox, groups_mask)
NotImplementedError: Wrong number or type of arguments for overloaded function 'Context_getState'.
  Possible C/C++ prototypes are:
    OpenMM::Context::getState(int,bool,int) const
    OpenMM::Context::getState(int,bool) const
    OpenMM::Context::getState(int) const
```

**Comment by peastman** [comment]
Which OpenMM version is this?  Is it a conda build, or did you build it from source?

If the latter, make sure nothing has gotten out of sync in your build directory.  Try deleting the "wrappers" and "python" subdirectories, then rerun CMake and rebuild.

**Comment by jchodera** [comment]
Should be the 7.1.0 release:
```
>>> print(openmm.version.version)
7.1.0.dev-b37e257
```

**Comment by peastman** [comment]
Do you still have this issue?  I was never able to reproduce it.
