### ISSUE TITLE
TypeError: object of type 'AmberInpcrdFile' has no len()

### ISSUE THREAD

**Issue by apbhati1** [openmm/openmm#2551]
Hi there,

I am quite new to OpenMM so may be asking a very trivial question but I could not find the solution to this over the forum or elsewhere, so please bear with me. I am trying to perform MD simulation with explicit water molecules. I input the AMBER inpcrd and prmtop files and then use the modeller to add solvent molecules to the loaded structure. However, I get the error message as mentioned in the title. I am not sure what is going wrong here and what needs to be done now. Can someone suggest anything?

I am working on Summit. Below are the relevant files: 

OpenMM input script:
```
from simtk.openmm import app
import simtk.openmm as mm
from simtk import unit

prmtop = app.AmberPrmtopFile('apo.prmtop')
#inpcrd = app.PDBFile('apo.pdb')
inpcrd = app.AmberInpcrdFile('apo.inpcrd')
forcefield = app.ForceField('amber14/tip3p.xml')
modeller = app.Modeller(prmtop, inpcrd)
modeller.addSolvent(forcefield, padding=1.4*unit.nanometer)
system = forcefield.createSystem(modeller.topology, nonbondedMethod=app.PME, nonbondedCutoff=1.0*unit.nanometer,
        constraints=app.HBonds)
integrator = mm.LangevinIntegrator(300*unit.kelvin, 1.0/unit.picosecond, 0.002*unit.picosecond)
platform = mm.Platform.getPlatformByName('CUDA')
properties = {'Precision': 'double'}
simulation = app.Simulation(modeller.topology, system, integrator, platform, properties)
simulation.context.setPositions(modeller.positions)
simulation.minimizeEnergy()
simulation.reporters.append(DCDReporter('traj.dcd', 5000))
simulation.reporters.append(StateDataReporter('sim.log', 5000, step=True,
potentialEnergy=True, temperature=True))
simulation.reporters.append(CheckpointReporter('traj.chk', 5000))
simulation.step(10000)
positions = simulation.context.getState(getPositions=True).getPositions()
PDBFile.writeFile(simulation.topology, positions, open('output.pdb', 'w'))
potential = simulation.context.getState(getEnergy=True).getPotentialEnergy().value_in_unit(unit.kilojoule/unit.mole)
print("%f".format(potential))
```
 and the error file:

```

Activating Modules:
  1) spectrum-mpi/10.3.0.1-20190611

The following have been reloaded with a version change:
  1) gcc/8.1.0 => gcc/6.4.0

Traceback (most recent call last):
  File "test.py", line 10, in <module>
    modeller.addSolvent(forcefield, padding=1.4*unit.nanometer)
  File "/gpfs/alpine/scratch/apbhati/chm155/miniconda/envs/openmm/lib/python3.7/site-packages/simtk/openmm/app/modeller.py", line 465, in addSolvent
    if len(self.positions) == 0:
  File "/gpfs/alpine/scratch/apbhati/chm155/miniconda/envs/openmm/lib/python3.7/site-packages/simtk/unit/quantity.py", line 727, in __len__
    return len(self._value)
TypeError: object of type 'AmberInpcrdFile' has no len()
```
Agastya

**Comment by peastman** [comment]
Welcome!  You have it almost right.  Just change the line

```python
modeller = app.Modeller(prmtop, inpcrd)
```

to

```python
modeller = app.Modeller(prmtop.topology, inpcrd.positions)
```

One other issue I notice in your script is that you probably want to create the ForceField as

```python
forcefield = app.ForceField('amber14-all.xml', 'amber14/tip3p.xml')
```

Otherwise you're loading only the force field parameters for water but not for anything else.

**Comment by apbhati1** [comment]
Thanks for the suggestions. This small tweak solved my problem!
