### ISSUE TITLE
Error in passing parameter values to CustomExternalForce

### ISSUE THREAD

**Issue by lucentdm** [openmm/openmm#2607]
Hi Everybody,
Having trouble with CustomExternalForce.addParticle producing an assertion error.  With the simple example:
```
from simtk import openmm as mm
from simtk import unit as u
from simtk.openmm import app

print(mm.version.full_version)
pdb = app.PDBFile("alanine-dipeptide.pdb")
force = mm.CustomExternalForce("k * ((x - x0)^2 + (y-y0)^2 + (z - z0)^2)")
k = 1000 * u.kilojoule_per_mole / u.nanometer**2
force.addGlobalParameter("k", k)
force.addPerParticleParameter("x0")
force.addPerParticleParameter("y0")
force.addPerParticleParameter("z0")
for idx, pos in enumerate(pdb.positions):
    r = pos.value_in_unit(u.nanometer)
    force.addParticle(idx, r)
print(mm.XmlSerializer.serialize(force))
```
and https://github.com/choderalab/openmmtools/blob/master/openmmtools/data/alanine-dipeptide-gbsa/alanine-dipeptide.pdb

I get the expected output on 7.3.1.dev-4a269c0 but the following error on 7.4.1.dev-068f120

```
7.4.1.dev-068f120
Traceback (most recent call last):
  File "force_test.py", line 15, in <module>
    force.addParticle(idx, r)
  File "/Users/lucent/anaconda3/envs/md/lib/python3.6/site-packages/simtk/openmm/openmm.py", line 9040, in addParticle
    return _openmm.CustomExternalForce_addParticle(self, *args)
NotImplementedError: Wrong number or type of arguments for overloaded function 'CustomExternalForce_addParticle'.
  Possible C/C++ prototypes are:
    OpenMM::CustomExternalForce::addParticle(int,std::vector< double,std::allocator< double > > const &)
    OpenMM::CustomExternalForce::addParticle(int)
```

**Comment by jchodera** [comment]
Hi @lucentdm! Hope you folks are doing well.

`CustomExternalForce.addParticle()` is supposed to accept a `list` of parameters, even if you have just a single parameter---can you try changing
```python
    force.addParticle(idx, r)
```
to
```python
    force.addParticle(idx, [r])
```
?

**Comment by lucentdm** [comment]
Hey John!  Same at to you, hope you're all okay in NY.  Yeah, unfortunately the suggested edit generates the same error.  I've tried it with [x, y, z], Vec3(x,y,z), and [Vec3(x,y,z)] and all give the same error.

**Comment by ajsilveira** [comment]
I tried your script with 7.5.0.dev and it worked. Another possibility, that also works, is 
```
force.addParticle(idx, [r[0], r[1], r[2]])
```

**Comment by lucentdm** [comment]
@ajsilveira thanks for your reply.  The suggested edit works on 7.3.1 but not on 7.4.0/7.4.1, haven't tried 7.5.0 as I'm using the binaries from omnia.

**Comment by peastman** [comment]
I just tested your script with the 7.4.1 conda package.  It worked fine without any changes.  What Python version and OS are you using?

**Comment by lucentdm** [comment]
I've been able to reproduce the error with `conda install openmm=7.4.1 -c omnia` on OS X 10.13.6, python 3.6.10 and Ubuntu 18.04.3, python 3.6.10.  On both platforms `conda install openmm=7.3.1 -c omnia` and rerunning the script produces the expected output.

**Comment by jchodera** [comment]
Could this be an issue with numpy version? Maybe post `conda list`?

**Comment by lucentdm** [comment]
Sure thing.  numpy is 1.11.3.  Here is the conda list for the environment I've been using:
```
ambertools                19.0                          0    ambermd
appnope                   0.1.0           py36h9f0ad1d_1001    conda-forge
astroid                   2.3.3                    py36_0  
backcall                  0.1.0                      py_0    conda-forge
bhmm                      0.6.1               np111py36_0    omnia
blosc                     1.17.1               h4a8c4bd_0    conda-forge
bzip2                     1.0.8                h0b31af3_2    conda-forge
ca-certificates           2020.1.1                      0  
certifi                   2019.11.28               py36_1  
cycler                    0.10.0                     py_2    conda-forge
cython                    0.29.15          py36h0130604_1    conda-forge
decorator                 4.4.2                      py_0    conda-forge
fftw3f                    3.3.4                         2    omnia
freetype                  2.10.1               h8da9a1a_0    conda-forge
hdf5                      1.10.4          nompi_h0cbb7df_1106    conda-forge
ipython                   7.13.0           py36h9f0ad1d_2    conda-forge
ipython_genutils          0.2.0                      py_1    conda-forge
isort                     4.3.21                   py36_0  
jedi                      0.16.0           py36h9f0ad1d_1    conda-forge
joblib                    0.14.1                     py_0    conda-forge
kiwisolver                1.1.0            py36h863e41a_1    conda-forge
lazy-object-proxy         1.4.3            py36h1de35cc_0  
libblas                   3.8.0               14_openblas    conda-forge
libcblas                  3.8.0               14_openblas    conda-forge
libcxx                    9.0.1                         1    conda-forge
libffi                    3.2.1             h4a8c4bd_1007    conda-forge
libgfortran               3.0.1                         0    conda-forge
liblapack                 3.8.0               14_openblas    conda-forge
libopenblas               0.3.7                hd44dcd8_1    conda-forge
libpng                    1.6.37               hbbe82c9_1    conda-forge
matplotlib                3.1.0                    py36_0    conda-forge
matplotlib-base           3.1.0            py36habd5b94_0    conda-forge
mccabe                    0.6.1                    py36_1  
mdtraj                    1.9.1                    py36_0    omnia
mmpbsa-py                 16.0                     pypi_0    pypi
mock                      3.0.5            py36h9f0ad1d_1    conda-forge
msmtools                  1.2.1               np111py36_0    omnia
ncurses                   6.1               h0a44026_1002    conda-forge
numexpr                   2.6.9           py36h1702cab_1000    conda-forge
numpy                     1.11.3          py36hdf140aa_1207    conda-forge
openmm                    7.4.1           py36_cuda101_rc_1    omnia
openssl                   1.1.1e               h0b31af3_0    conda-forge
packmol-memgen            1.0.5rc0                 pypi_0    pypi
pandas                    0.23.4          py36h1702cab_1000    conda-forge
parmed                    3.2.0                    pypi_0    pypi
parso                     0.6.2                      py_0    conda-forge
pdb4amber                 1.7.dev0                 pypi_0    pypi
pexpect                   4.8.0            py36h9f0ad1d_1    conda-forge
pickleshare               0.7.5           py36h9f0ad1d_1001    conda-forge
pip                       20.0.2                     py_2    conda-forge
progress_reporter         1.3.1                    py36_0    omnia
prompt-toolkit            3.0.4                      py_0    conda-forge
psutil                    5.7.0            py36h37b9a7d_1    conda-forge
ptyprocess                0.6.0                   py_1001    conda-forge
pyemma                    2.4                 np111py36_1    omnia
pygments                  2.6.1                      py_0    conda-forge
pylint                    2.4.4                    py36_0  
pymsmt                    19.0                     pypi_0    pypi
pyparsing                 2.4.6                      py_0    conda-forge
pytables                  3.5.1            py36h689b3ec_1    conda-forge
python                    3.6.10          hce46be0_1009_cpython    conda-forge
python-dateutil           2.8.1                      py_0    conda-forge
python_abi                3.6                     1_cp36m    conda-forge
pytraj                    2.0.5                    pypi_0    pypi
pytz                      2019.3                     py_0    conda-forge
pyyaml                    5.3.1            py36h37b9a7d_0    conda-forge
readline                  8.0                  hcfe32e1_0    conda-forge
sander                    16.0                     pypi_0    pypi
scipy                     1.2.1            py36hbd7caa9_1    conda-forge
setuptools                46.1.1           py36h9f0ad1d_0    conda-forge
six                       1.14.0                     py_1    conda-forge
sqlite                    3.30.1               h93121df_0    conda-forge
thermotools               0.2.6               np111py36_0    omnia
tk                        8.6.10               hbbe82c9_0    conda-forge
tornado                   6.0.4            py36h37b9a7d_1    conda-forge
tqdm                      4.43.0                     py_0  
traitlets                 4.3.3            py36h9f0ad1d_1    conda-forge
typed-ast                 1.4.1            py36h1de35cc_0  
wcwidth                   0.1.8                      py_0    conda-forge
wheel                     0.34.2                     py_1    conda-forge
wrapt                     1.12.1           py36h1de35cc_1  
xz                        5.2.4             h0b31af3_1002    conda-forge
yaml                      0.2.2                h0b31af3_1    conda-forge
zlib                      1.2.11            h0b31af3_1006    conda-forge
```

**Comment by Meiwei1988** [comment]
Hi， @lucentdm ，I have encounted the same problem as you met, and I updated the python from 3.5 to 3.7, and updated the scipy and numpy. And then the problem is disappeared. and hope this helps you.
