### ISSUE TITLE
Alchemical Free Energy tutorial producing `nan` particle coordinates

### ISSUE THREAD

**Issue by BradenDKelly** [openmm/openmm#2758]
I have installed openmm, as well as run the simtk test, and it checkout out as okay.

Currently I am running the alchemical tutorial for a LJ system to get a feel for openmm. I have run into 2 issues.
Issue 1: after a random number of steps, but inevitable eventually, the simulation fails due to an `Exception Particle coordinate is nan`.

When running

```
        # Run some dynamics
        integrator.step(nsteps)
```
I get the error 
```
Minimizing energy...
state     0 iteration     0 /    50
state     0 iteration     1 /    50
state     0 iteration     2 /    50
state     0 iteration     3 /    50
state     0 iteration     4 /    50
Traceback (most recent call last):
  File "C:/Users/Zarathustra/openMM/alchemical-example.py", line 67, in <module>
    integrator.step(nsteps)
  File "C:\Users\Zarathustra\anaconda3\envs\openMM\lib\site-packages\simtk\openmm\openmm.py", line 15579, in step
    return _openmm.LangevinIntegrator_step(self, steps)
Exception: Particle coordinate is nan
```

(my feeling is that the energy minimization must not be minimizing enough so that initial forces lead to an unstable simulation?)

Sometimes the simulation will manage to complete, leading to the next issue. 

issue 2: for the runs that do all alchemical windows for the LJ, the tutorial then calculates free energy using MBAR.

When running
```
mbar = MBAR(u_kln, N_k)
[DeltaF_ij, dDeltaF_ij, Theta_ij] = mbar.getFreeEnergyDifferences()
```
I get the error.
```
Traceback (most recent call last):
  File "C:/Users/User1/openMM/alchemical-example.py", line 84, in <module>
    [DeltaF_ij, dDeltaF_ij, Theta_ij] = mbar.getFreeEnergyDifferences()
ValueError: not enough values to unpack (expected 3, got 2)
```
Again, to be clear, this is the tutorial script found [http://openmm.org/tutorials/alchemical-free-energy/](url)

**Comment by peastman** [comment]
Take a look at https://github.com/openmm/openmm/wiki/Frequently-Asked-Questions#nan.  It discusses common causes for the first error message.

I don't know about the MBAR code.  Perhaps someone familiar with that code can answer that part.

**Comment by BradenDKelly** [comment]
The argon example found here [openMM example](https://github.com/openmm/openmm/blob/master/examples/argon-chemical-potential.py) works, although I had to make a modification for it to run

On line 162 I made the following change
```
try:
    from pymbar import timeseries
    #from timeseries import subsampleCorrelatedData
    from pymbar import MBAR
except:
    raise ImportError("pymbar [https://simtk.org/home/pymbar] must be installed to complete analysis of free energies.")
```
and on line 172 I added` indices = timeseries.subsampleCorrelatedData(u_kln[k, k, :])` to reflect the need to pull subsampleCorrelatedData from the timeseries object.

MBAR also works fine in the second example.

I will dig around a bit and see why one example works and the other doesn't and report back what I find.

**Comment by ljmartin** [comment]
Hi @BradenDKelly I can run the LJ fluid simulation fine, but found that it's more reliable at a lower time step. Try `timestep = 2.0*unit.femtoseconds` instead of `timestep = 2.5*unit.femtoseconds`.

**Comment by BradenDKelly** [comment]
Hi @ljmartin I found that dropping the pressure worked well. The initial state point is a highly compressed liquid, and it appears to be using random generation for initial coords. Lowering the density helped alot.

A very simple fix would be to simply start LJ particles in a FCC type of crystal lattice. I haven't looked, but I have my suspicions this would be very easy to add to the function `LennardJonesFluid`

When I have a bit more time, perhaps the weekend, I will look into it and submit a PR if this fixes it "completely"

**Comment by ljmartin** [comment]
I'd be interested to see what you come up with. Keep in mind the `LennardJonesFluid` testsystem is actually from opennmmtools, which is an extension to, but separate from, openmm. I guess it doesn't come pre-equilibrated because it equilibrates very quickly by itself.

**Comment by BradenDKelly** [comment]
I am at a bit of a loss. It turns out `LennardJonesFluid` can do a lattice
`def __init__(self,
             nparticles=1000,
             reduced_density=0.05,
             mass=39.9 * unit.amu,  # argon
             sigma=3.4 * unit.angstrom,  # argon,
             epsilon=0.238 * unit.kilocalories_per_mole,  # argon,
             cutoff=None,
             switch_width=3.4 * unit.angstrom,  # argon
             shift=False,
             dispersion_correction=True,
             lattice=False,
             charge=None,
             ewaldErrorTolerance=None,
             **kwargs):`
So I tried using `lattice=True`, but it really didn't make much difference. I took the time step down to 0.1, it still would act  up. The only thing that did work consistently was using a low pressure. This is just strange though.

I thought perhaps then that it might be the energy minimizer, so I made its criteria more stringent using `openmm.LocalEnergyMinimizer.minimize(context, maxIterations=1000, tolerance=0.5*unit.kilojoule_per_mole)` , however, this did not help either. 

I also tried doing NVT rather than NPT, this did not help if I started the system from a high density i.e., reduced_density=0.75. I tried a few higher as well.

If I do not use `LennardJonesFluid`, instead using the older example which just generates positions at random (I have tried NVT and NPT at high pressure), I can run any density or pressure just fine. I have gone up to reduced_density = 0.95 or pressure = 100 atm, and it purrs along.

Now I am leaning towards there being something wrong in fluid.systems which is calculated using `LennardJonesFluid`
`fluid = LennardJonesFluid(nparticles=864, sigma=sigma, epsilon=epsilon, lattice=True)`
`[system, positions] = [fluid.system, fluid.positions]`

Last note: the softcore potentials may be different. They are at least defined differently. A typo here might lead to incorrect forces and  a `nan` on the ghost particle.
