### ISSUE TITLE
Disulfide Linkages in CHARMM-Drude 2019

### ISSUE THREAD

**Issue by arcaian** [openmm/openmm#2848]
Hi all,

I'm excited about the update to the 2019 version of the Drude force field that is upcoming in OpenMM 7.5, and to make sure I knew my way around these simulations when the 7.5 release comes out, I've been testing with the latest source code. Hopefully this isn't a faux pas - my assumption is that with all issues and work related to the Drude update completed, the issues I've encountered here would be present in the 7.5 release. If this assumption is incorrect, my apologies. 

 To ensure any issues I've found are relevant, I've repeated all of my testing with the latest version of the code (after pull request #2844 ), which is well after work on the Drude FF implementation has stopped. To try and maintain consistency in my tests, I've used the openmm-setup program to solvate all the proteins tested with a 10A water buffer, and neutralised the charge of the system. Any missing residues or atoms were modelled using openmm-setup. The default parameters from the Drude-2013 implementation were used for the simulation - as the primary focus of these tests was of successful system construction. Initial testing on the 1DKZ crystal structure showed no issues with system construction or running the simulation, but testing on the 3I3Z crystal structure revealed an error relating to an error in the cysteine residue template:

```
Traceback (most recent call last):
  File "run_openmm_simulation.py", line 45, in <module>
    modeller.addExtraParticles(forcefield)
  File "/opt/anaconda3/envs/openmmDrudeTest/lib/python3.8/site-packages/simtk/openmm/app/modeller.py", line 1051, in addExtraParticles
    templates = forcefield._matchAllResiduesToTemplates(ForceField._SystemData(self.topology), self.topology, {}, False, True, False)
  File "/opt/anaconda3/envs/openmmDrudeTest/lib/python3.8/site-packages/simtk/openmm/app/forcefield.py", line 1391, in _matchAllResiduesToTemplates
    raise ValueError('No template found for residue %d (%s).  %s' % (res.index+1, res.name, _findMatchErrors(self, res)))
ValueError: No template found for residue 6 (CYS).  The set of atoms is similar to CYS, but it is missing 11 atoms.
```

In my past experience, this error is associated with the system incorrectly applying disulfide linkages. I searched the issues in this project for similar occurrences in the past, and this confirmed the suspicion - in issue #2039 , the same error occurred in the CHARMM36 distribution. The pull request that fixed this issue, #2040 , performed the final testing on the 1BNG crystal structure, which was stated to be added as a test case - so my subsequent testing was performed on this structure. The same error with the application of the disulfide patch occurred with the native 1BNG crystal structure, and so as a test I truncated the protein after the first 100 residues; this removes one of the two cysteine residues involved in the disulfide linkage. Removing the disulfide linkage in this way allowed the protein to complete system building without error. Repeating the simulations using the CHARMM36 force field provided no errors in system building, regardless of the presence of disulfide linkages. 

As best as I can tell, the automated detection and application of disulfide linkages is not functioning with Drude2019 - I've attached a .zip file with the processed .pdb files (both the full-length 1BNG and the truncated 1BNG that does not contain a disulfide linkage) as well as the scripts I have been using to run the CHARMM36 and Drude2019 simulations. 

Hopefully this is sufficient information (and I'm describing a real issue, not user error)!
Thanks,

[1bngDrudeTest.zip](https://github.com/openmm/openmm/files/5253450/1bngDrudeTest.zip)

**Comment by peastman** [comment]
It looks like the force field is missing the DISU patch.  Let's see if I can figure out what happened to it...

**Comment by jchodera** [comment]
I believe we had to add `DISU` manually for the standard CHARMM force field as well. We likely just forgot about this!

**Comment by peastman** [comment]
Good to know.  I was dreading having to dive into the ParmEd code to try to figure out what was going on!

**Comment by arcaian** [comment]
Given the previous manual patch (#2040) wasn't too complicated, I figured I'd give a shot at converting this one myself. However, the Drude patch is a lot more complicated to convert across, and I'm struggling to figure this one out. I'm hoping that there's some source for this that I missed  The first issue I've had is that there are no other multi-residue patches for me to compare against in the Drude FF. I tried to use the same logic as the DISU patch from CHARMM36, but the AtomTypes have the DISU atoms separated out into DISU-1(atom name) and DISU-2(atom name), so I'm not certain if the patch should be doing so as well. My second issue is related, and is due to virtual sites - their definition seems to be sufficiently different in multi-residue patches that I can't figure out how they should be handled. Whichever way I'm defining them I'm getting errors, so for now I think I'm not able to make more progress. I'm also just unclear as to how to determine the local coordinates and weighting values from the information present in the original Drude force field files - the values currently present are placeholders, the same as the first virtual site in the ASPP patch. If anyone could point my in the direction of examples I could look at, documentation that's relevant, or the like, I would appreciate that. Otherwise, perhaps my doing some of the grunt work could speed it up for people who are more familiar with the system. This is the current state of my patch:

`    <Patch name="DISU" residues="2">
      <RemoveAtom name="1:HG1"/>
      <RemoveAtom name="1:LPGA"/>
      <RemoveAtom name="1:LPGB"/>
      <RemoveAtom name="2:HG1"/>
      <RemoveAtom name="2:LPGA"/>
      <RemoveAtom name="2:LPGB"/>
      <ChangeAtom charge="2.31446135114075" name="CB" type="DISU-1CB"/>
      <ChangeAtom charge="-2.38446135114075" name="DCB" type="Drude-DISU-1CB"/>
      <ChangeAtom charge="0.087" name="HB1" type="DISU-1HB1"/>
      <ChangeAtom charge="0.087" name="HB2" type="DISU-1HB2"/>
      <ChangeAtom charge="2.84408319817730" name="SG" type="DISU-1SG"/>
      <ChangeAtom charge="-2.84408319817730" name="DSG" type="Drude-DISU-1SG"/>
      <AddAtom charge="-0.052" name="LPSA" type="DISU-1LPSA"/>
      <AddAtom charge="-0.052" name="LPSB" type="DISU-1LPSB"/>
      <AddBond atomName1="1:SG" atomName2="2:SG"/>
      <AddBond atomName1="1:SG" atomName2="1:LPSA"/>
      <AddBond atomName1="1:SG" atomName2="1:LPSB"/>
      <AddBond atomName1="2:SG" atomName2="2:LPSA"/>
      <AddBond atomName1="2:SG" atomName2="2:LPSB"/>
      <VirtualSite atomName1="1:SG" atomName2="1:CB" atomName3="2:SG" p1="-0.0005235721931185042" p2="-0.029995430854691738" p3="0" siteName="1:LPSA" type="localCoords" wo1="1" wo2="0" wo3="0" wx1="-1.0" wx2="0.0" wx3="1.0" wy1="0" wy2="-1" wy3="1"/>
      <VirtualSite atomName1="1:SG" atomName2="2:SG" atomName3="1:CB" p1="-0.0005235721931185042" p2="-0.029995430854691738" p3="0" siteName="1:LPSB" type="localCoords" wo1="1" wo2="0" wo3="0" wx1="-1.0" wx2="0.0" wx3="1.0" wy1="0" wy2="-1" wy3="1"/>
      <VirtualSite atomName1="2:SG" atomName2="2:CB" atomName3="1:SG" p1="-0.0005235721931185042" p2="-0.029995430854691738" p3="0" siteName="2:LPSA" type="localCoords" wo1="1" wo2="0" wo3="0" wx1="-1.0" wx2="0.0" wx3="1.0" wy1="0" wy2="-1" wy3="1"/>
      <VirtualSite atomName1="2:SG" atomName2="1:SG" atomName3="2:CB" p1="-0.0005235721931185042" p2="-0.029995430854691738" p3="0" siteName="2:LPSB" type="localCoords" wo1="1" wo2="0" wo3="0" wx1="-1.0" wx2="0.0" wx3="1.0" wy1="0" wy2="-1" wy3="1"/>
      <ApplyToResidue name="1:CYS"/>
      <ApplyToResidue name="2:CYS"/>
    </Patch>`

**Comment by peastman** [comment]
I converted the patch by hand, but it doesn't work.  The problem is in the handling of the lone pairs.  The way ForceField implements virtual sites assumes they're defined entirely within a single residue.  DISU has a virtual site in one residue depending on an atom in another residue, and the current code can't handle that.  Fixing it will take extensive code changes.  I think we need to put that off until after 7.5.  I don't feel safe making such major changes this close to the release.

Here's my version of the patch (obviously not tested!).

```xml
    <Patch name="DISU" residues="2">
      <RemoveAtom name="1:HG1"/>
      <RemoveAtom name="2:HG1"/>
      <RemoveAtom name="1:LPGA"/>
      <RemoveAtom name="2:LPGA"/>
      <RemoveAtom name="1:LPGB"/>
      <RemoveAtom name="2:LPGB"/>
      <ChangeAtom charge="-0.07" name="1:CB" type="DISU-1CB"/>
      <ChangeAtom charge="-0.07" name="2:CB" type="DISU-2CB"/>
      <ChangeAtom charge="0.087" name="1:HB1" type="DISU-1HB1"/>
      <ChangeAtom charge="0.087" name="2:HB1" type="DISU-2HB1"/>
      <ChangeAtom charge="0.087" name="1:HB2" type="DISU-1HB2"/>
      <ChangeAtom charge="0.087" name="2:HB2" type="DISU-2HB2"/>
      <ChangeAtom charge="0.0" name="1:SG" type="DISU-1SG"/>
      <ChangeAtom charge="0.0" name="2:SG" type="DISU-2SG"/>
      <AddAtom charge="-0.052" name="1:LPSA" type="DISU-1LPSA"/>
      <AddAtom charge="-0.052" name="2:LPSA" type="DISU-2LPSA"/>
      <AddAtom charge="-0.052" name="1:LPSB" type="DISU-1LPSB"/>
      <AddAtom charge="-0.052" name="2:LPSB" type="DISU-2LPSB"/>
      <AddBond atomName1="1:SG" atomName2="2:SG"/>
      <VirtualSite atomName1="1:SG" atomName2="1:CB" atomName3="2:SG" p1="-0.030781812899310187" p2="0.0" p3="0.08457233587073176" siteName="1:LPSA" type="localCoords" wo1="1" wo2="0" wo3="0" wx1="-1.0" wx2="0.5" wx3="0.5" wy1="0" wy2="-1" wy3="1"/>
      <VirtualSite atomName1="2:SG" atomName2="2:CB" atomName3="1:SG" p1="-0.030781812899310187" p2="0.0" p3="0.08457233587073176" siteName="2:LPSA" type="localCoords" wo1="1" wo2="0" wo3="0" wx1="-1.0" wx2="0.5" wx3="0.5" wy1="0" wy2="-1" wy3="1"/>
      <VirtualSite atomName1="1:SG" atomName2="2:SG" atomName3="1:CB" p1="-0.030781812899310187" p2="0.0" p3="0.08457233587073176" siteName="1:LPSB" type="localCoords" wo1="1" wo2="0" wo3="0" wx1="-1.0" wx2="0.5" wx3="0.5" wy1="0" wy2="-1" wy3="1"/>
      <VirtualSite atomName1="2:SG" atomName2="1:SG" atomName3="2:CB" p1="-0.030781812899310187" p2="0.0" p3="0.08457233587073176" siteName="2:LPSB" type="localCoords" wo1="1" wo2="0" wo3="0" wx1="-1.0" wx2="0.5" wx3="0.5" wy1="0" wy2="-1" wy3="1"/>
      <ApplyToResidue name="1:CYS"/>
      <ApplyToResidue name="2:CYS"/>
    </Patch>
```

**Comment by arcaian** [comment]
Thanks for converting it over - it does make sense to avoid delaying 7.5 for this fix. This does explain why I couldn't get the patch working. Fingers are crossed that the code changes aren't too complicated - if there's work that's appropriate for someone unfamiliar with the details of OpenMM but with a passable knowledge of Python, I'm happy to try and contribute.
