### ISSUE TITLE
"Exception: Particle coordinate is nan" immediately after successful minimization

### ISSUE THREAD

**Issue by corinwagen** [openmm/openmm#2937]
Hello,

I'm trying to run MD using openforcefield/openmm to study the association between a few small molecules, but I'm having some trouble getting the code to work.

My Python script (``run_md.py``) is here (I'm sure this is offensively bad to trained eyes, sorry, I'm trying to learn how to use this):

```
import yaml, sys, os, time, logging
import matplotlib.pyplot as plt
from openforcefield.topology import Molecule, Topology
from openforcefield.typing.engines.smirnoff import ForceField, NonbondedMethod
from openforcefield.utils.toolkits import RDKitToolkitWrapper, AmberToolsToolkitWrapper
from simtk import openmm, unit
from rdkit import Chem
import mdtraj as mdt

#### packmol needs to be in PATH so distutils.spawn.find_executable can locate it
os.environ["PATH"] += os.pathsep + os.path.expanduser("~") + "/sw/packmol"
from openmoltools.packmol import pack_box

logging.basicConfig(level=logging.INFO, filename="log.log", format='%(asctime)s %(name)-12s  %(message)s', datefmt='%m-%d %H:%M', filemode="w")
logger = logging.getLogger(__name__)

#### This script uses OpenMM to run molecular dynamics on a solute in a cube of solvent.

#### USAGE:
#### python run_md.py structure.sdf

#### Expects ``config.yml`` in the same directory.

def run_md(molecule, components, confId=0):
    """
    Uses the PARSLEY forcefield to compute molecule ``molecule`` in a cubic box of solvent at STP.

    Details:
        - Particle mesh Ewald summation is used (1 nm cutoff)
        - Periodic boundary conditions are employed
        - Langevin thermostat is employed to regulate temperature
        - Box size is automatically scaled to the desired number of solvent molecules

    Args:
        molecule (openforcefield.topology.Molecule): desired molecule
        components (list of openforcefield.topology.Molecule): all connected components

    Returns:
        Nothing, but ``.csv``, ``.hdf5``, and ``.pdb`` files are generated in the current directory.
    """

    #### Load in the appropriate Molecule object
    off_solute = molecule.to_topology()
    omm_solute = off_solute.to_openmm()
    mdt_solute = mdt.Topology.from_openmm(omm_solute)

    solvent = Molecule.from_smiles(config["solvent_smiles"])
    density = config["solvent_density"]
    mw = config["solvent_mw"]

    solvent.generate_conformers()
    off_solvent = solvent.to_topology()
    omm_solvent = off_solvent.to_openmm()
    mdt_solvent = mdt.Topology.from_openmm(omm_solvent)

    #### Calculate box side length
    num, length = None, None
    if "num" in config:
        num = config["num"]
        assert isinstance(num, int), "Need an integer number of solvent molecules."
        assert num > 0, "Need a positive number of solvent molecules."
        length = (1.6606 * num * mw / density) ** (1/3) # 1.6606 = 10^24 (Å**3 per mL) divided by Avogadro's number
    elif "length" in config:
        length = config["length"]
        assert isinstance(length, (int, float)), "Need a numeric side length."
        assert length > 0, "Need a positive length."
        num = (length ** 3) * density / (mw * 1.6606)
        num = int(num)
    else:
        raise ValueError("Need ``length`` or ``num`` in config file!")

    logger.info(f"{num} solvent molecules in a cube with {length:.2f} Å sides.")

    #### Write solvent and solute to ``.pdb`` files for PACKMOL
    solute_pdb = "solute.pdb"
    with open(solute_pdb, "w+") as f:
        openmm.app.pdbfile.PDBFile.writeFile(omm_solute, molecule.conformers[confId], f)

    solvent_pdb = "solvent.pdb"
    with open(solvent_pdb, "w+") as f:
        openmm.app.pdbfile.PDBFile.writeFile(omm_solvent, solvent.conformers[0], f)

    #### Use ``openmoltools`` Python wrapper for PACKMOL to fill the box appropriately
    mdt_trajectory = pack_box([solute_pdb, solvent_pdb], [1, num], box_size=length)

    #### Convert back to ``openforcefield``
    omm_topology = mdt_trajectory.top.to_openmm()
    length = length / 10 # OpenMM uses nanometers for some reason
    omm_topology.setPeriodicBoxVectors(((length, 0, 0), (0, length, 0), (0, 0, length)))
    off_topology = Topology.from_openmm(omm_topology, [solvent, *components])

    logger.info(f"BOX VECTORS: {off_topology.box_vectors}")

    #### Set up the OpenMM system
    forcefield.get_parameter_handler('Electrostatics').method = 'PME'
    system = forcefield.create_openmm_system(off_topology, allow_nonintegral_charges=True) # the charges keep getting a little off, hope it's not a big deal. large molecule at AM1.
    time_step = config["time_step"] * unit.femtoseconds
    temperature = config["temperature"] * unit.kelvin
    friction = 1 / unit.picosecond
    integrator = openmm.LangevinIntegrator(temperature, friction, time_step)

    #### Set up the simulation
    simulation = openmm.app.Simulation(omm_topology, system, integrator)
    logger.info(f"Simulation object created.")
    simulation.context.setPositions(mdt_trajectory.openmm_positions(0))
    logger.info(f"Positions loaded.")

    pdb_reporter = openmm.app.PDBReporter('trj.pdb', config["pdb_freq"])
    hdf5_reporter = mdt.reporters.HDF5Reporter('trj.hdf5', config["hdf5_freq"])
    state_data_reporter = openmm.app.StateDataReporter(
        "data.csv",
        config["data_freq"],
        step=True,
        potentialEnergy=True,
        temperature=True,
        density=True
    )

    simulation.reporters.append(pdb_reporter)
    simulation.reporters.append(hdf5_reporter)
    simulation.reporters.append(state_data_reporter)

    logger.info("Using Platform: " + simulation.context.getPlatform().getName())
    logger.info("Saving state to initial.xml and checkpoint to initial.chk")
    simulation.saveState("initial.xml")
    simulation.saveCheckpoint("initial.chk")

    #### Clean up ``.pdb`` files
    os.remove(solute_pdb)
    os.remove(solvent_pdb)

    logger.info("Minimizing...")
    simulation.minimizeEnergy(maxIterations=25)

    logger.info("Running...")
    w_start = time.time()
    p_start = time.process_time()
    simulation.step(config["num_steps"])
    w_end = time.time()
    p_end = time.process_time()
    logger.info(f"Elapsed time {w_end-w_start:.2f} s (CPU: {p_end-p_start:.2f} s)")
    logger.info("Done")

if __name__=="__main__":
    forcefield = ForceField("openff_unconstrained-1.2.0.offxml")
    config = yaml.load(open("config.yml", "r"), yaml.Loader)
    molecule = Molecule.from_file(sys.argv[1], allow_undefined_stereo=True)

    components = []
    for filename in sys.argv[2:]:
        components.append(Molecule.from_file(filename, allow_undefined_stereo=True))

    run_md(molecule, components)
```

The contents of ``config.yaml`` are here:

```
#### CONFIG FILE

time_step: 1 # 1 fs
temperature: 300
friction: 1
length: 30 # box side length (Å)

pdb_freq: 1000 # 1 ps
hdf5_freq: 1000 # 1 ps
data_freq: 1000 # 1 ps
num_steps: 1000000000 # 1 µs

solvent_smiles: CC(C)OC(C)C
solvent_mw: 102.18
solvent_density: 0.725
```

When I run the script with ``python run_md.py full_13_pre_Pbond.sdf sug1P.sdf sug2.sdf cat.sdf``
(where ``full_13_prePbond`` is my full system and ``sug1P``, ``sug2``, and ``cat`` are the individual components), I get the following error:

```
Traceback (most recent call last):
  File "run_md.py", line 153, in <module>
    run_md(molecule, components)
  File "run_md.py", line 138, in run_md
    simulation.step(config["num_steps"])
  File "<condapath>/python3.7/site-packages/simtk/openmm/app/simulation.py", line 132, in step
    self._simulate(endStep=self.currentStep+steps)
  File "<condapath>/python3.7/site-packages/simtk/openmm/app/simulation.py", line 197, in _simulate
    self.integrator.step(10) # Only take 10 steps at a time, to give Python more chances to respond to a control-c.
  File "<condapath>/python3.7/site-packages/simtk/openmm/openmm.py", line 19017, in step
    return _openmm.LangevinIntegrator_step(self, steps)
Exception: Particle coordinate is nan
Closing remaining open files:trj.hdf5...done
```

I tried to figure out what this error means: [this issue](https://github.com/openmm/openmm/issues/2308) suggests that the simulation is exploding somehow, but I don't think a 1 fs timestep is unreasonable, and the initial minimization works ok! I tried printing the initial ``System`` state and the ``.xml`` looks reasonable on the surface, but I can't figure out how to view it as ``.xyz``/``.pdb``for visual inspection. If the simulation were rapidly blowing up [as in this issue](https://github.com/openmm/openmm/issues/2026), I'd expect more than a single frame to finish? But I guess I'm not sure how to tell how far it's progressed; all I know is that it dies before it reports anything. Is there some way I can view the energy or position when it dies?

The ``logging`` log (``log.log``) is here, indicating that minimization goes ok:

```
11-25 05:17 openforcefield.utils.toolkits  Warning (not error because allow_undefined_stereo=True):
11-25 05:17 __main__      115 solvent molecules in a cube with 30.00 Å sides.
11-25 05:17 __main__      BOX VECTORS: ((3.0, 0, 0), (0, 3.0, 0), (0, 0, 3.0)) nm
11-25 05:17 openforcefield.typing.engines.smirnoff.parameters  4697 angles added (0 skipped due to constraints)
11-25 05:17 openforcefield.typing.engines.smirnoff.parameters  2538 bonds added (0 skipped due to constraints)
11-25 05:18 openforcefield.utils.toolkits  Warning: In AmberToolsToolkitwrapper.compute_partial_charges_am1bcc: Molecule 'dimer_c00358_freq.out' has more than one conformer, but this function will only generate charges for the first one.
11-25 07:22 openforcefield.utils.toolkits  Warning: In AmberToolsToolkitwrapper.compute_partial_charges_am1bcc: Molecule '6tBu_bGalOMe.out' has more than one conformer, but this function will only generate charges for the first one.
11-25 07:22 openforcefield.utils.toolkits  Warning: In AmberToolsToolkitwrapper.compute_partial_charges_am1bcc: Molecule 'Me4_aGalOPO3PH2.out' has more than one conformer, but this function will only generate charges for the first one.
11-25 07:31 openforcefield.utils.toolkits  Warning: In AmberToolsToolkitwrapper.compute_partial_charges_am1bcc: Molecule '' has more than one conformer, but this function will only generate charges for the first one.
11-25 07:31 openforcefield.typing.engines.smirnoff.parameters  51 impropers added, each applied in a six-fold trefoil
11-25 07:31 openforcefield.typing.engines.smirnoff.parameters  5456 torsions added
11-25 07:31 __main__      Simulation object created.
11-25 07:31 __main__      Positions loaded.
11-25 07:31 numexpr.utils  Note: NumExpr detected 36 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.
11-25 07:31 __main__      Using Platform: CPU
11-25 07:31 __main__      Saving state to initial.xml and checkpoint to initial.chk
11-25 07:31 __main__      Minimizing...
11-25 07:31 __main__      Running...
```

I'm not sure how to proceed; it's likely that I'm screwing something up, but I'm really not sure what this error implies. I've done my best to attach all the relevant files?

My package info is here (excerpted from ``conda list``):
 
```
ambertools                19                   h0d7ec52_0    conda-forge
openforcefield            0.6.0                    py37_1    omnia
openforcefields           1.2.0                    py37_0    omnia
openmm                    7.4.2           py37_cuda101_rc_1    omnia
openmmtools               0.20.0                   py37_0    omnia
openmoltools              0.8.7                    py37_0    omnia
mdtraj                    1.9.4            py37h4112681_0    conda-forge
parmed                    3.2.0            py37he1b5a44_2    conda-forge
rdkit                     2020.03.2        py37hdd87690_0    conda-forge
smirnoff99frosst          1.1.0                    py37_1    omnia
````

Please advise, and thanks in advance!

Corin

*files*:
[broken_openmm.zip](https://github.com/openmm/openmm/files/5599047/broken_openmm.zip)

**Comment by peastman** [comment]
Have you looked at https://github.com/openmm/openmm/wiki/Frequently-Asked-Questions#nan?  It provides a good starting point for debugging errors of this sort.

I'm not familiar with the openforcefield classes, so I can't comment on your script.  Perhaps someone else can help.

**Comment by corinwagen** [comment]
Ah, that's a very helpful link! Let me check that first before I waste anyone's time on something trivial. Sorry. 

Corin

**Comment by peastman** [comment]
Were you able to resolve this?

**Comment by corinwagen** [comment]
In progress, trying to wrap my head around ``openmm`` object structure more fully. Let me just close this for now.
