### ISSUE TITLE
Issue with units in np.log()

### ISSUE THREAD

**Issue by marleysamways** [openmm/openmm#2977]
Hi,

I've noticed some odd behaviour when running `np.log()` on `Quantity` objects. Normally, when I run this on a dimensioned value, I get an error, but I've noticed that if the `Quantity._value` is of a NumPy type, such as `numpy.float64`, then the units seem to be ignored and the log function treats the `Quantity` as just a normal dimensionless value.

Obviously this can be avoided by just being careful with the units that you're using, but I just thought I'd raise the issue - though this may be more of a NumPy issue, I'm not sure.

Apologies if this has already been raised/resolved elsewhere.

Thanks in advance.

Example (using OpenMM 7.4.2 and NumPy 1.16.4):
```
>>> x1 = 5.0
>>> print(x1)
5.0
>>> np.log(x1)
1.6094379124341003
>>> 
>>> 
>>> x2 = 5.0 * angstroms
>>> print(x2)
5.0 A
>>> type(x2._value)
<class 'float'>
>>> np.log(x2)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/mls2g13/miniconda2/envs/py36/lib/python3.6/site-packages/simtk/unit/quantity.py", line 202, in __getattr__
    ret_val = getattr(self._value, attribute)
AttributeError: 'float' object has no attribute 'log'
>>> 
>>> 
>>> x3 = np.sqrt(25.0) * angstroms
>>> print(x3)
5.0 A
>>> type(x3._value)
<class 'numpy.float64'>
>>> np.log(x3)
1.6094379124341003
```

**Comment by marleysamways** [comment]
I've just noticed that this doesn't seem to be an issue when using `math.log()` instead of `np.log()`, so perhaps it is more of a NumPy thing?
```
>>> x4 = np.sqrt(25.0) * angstroms
>>> print(x4)
5.0 A
>>> type(x4._value)
<class 'numpy.float64'>
>>> math.log(x4)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: Quantity.__float__ returned non-float (type Quantity)

```

**Comment by peastman** [comment]
I don't think taking the log of a quantity with units is well defined.  Changing to a different set of units would add a constant to the result instead of scaling the result.  There's no way to capture that with units on the result.

**Comment by marleysamways** [comment]
Hi,

Many thanks for your reply.

I agree that logs should be taken of dimensionless values. Most of the time (as per my examples above) you get an error when you give it a value with units - which is correct. I was more commenting that for some reason, this doesn't happen when the `Quantity` has a NumPy value (the `x3` case above), if it's possible I think it would be better for this to also return an error?

In the same way that `simtk.unit` has safeguards against combining incompatible units (i.e. you can't add 1 metre to 1 second), maybe it would be good if there were also safeguards against taking logarithms and exponentials of quantities?

**Comment by peastman** [comment]
It isn't clear to me how numpy is coming up with that value.  Suppose we use a standard Python value wrapped in a Quantity:

```
>>> np.log(5.0*angstroms)
Traceback (most recent call last):
  File "/Users/peastman/miniconda3/lib/python3.7/site-packages/simtk/unit/quantity.py", line 202, in __getattr__
    ret_val = getattr(self._value, attribute)
AttributeError: 'float' object has no attribute 'log'
```

In this case it appears `np.log()` tries to invoke a `log()` method on the object you pass.  Since Quantity doesn't have a `log()` method, it tries to delegate it to the value it contains.  That doesn't have one either, so it throws an exception.

But numpy values also don't have a `log()` method:

```
>>> np.sqrt(25).log()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'numpy.float64' object has no attribute 'log'
```

So how does it manage to evaluate it?  What steps does it follow to come up with the output value?

**Comment by marleysamways** [comment]
I'm not sure, to be honest. Somehow it seems to manage to just run `np.log(5)`, but I have no idea how it gets there.

For a `Quantity` with a NumPy value, the `AttributeError` is somehow not raised, even though running that same line in isolation does give an error:
```
>>> x = np.sqrt(25) * angstroms
>>> getattr(x._value, 'log')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'numpy.float64' object has no attribute 'log'
```
