### ISSUE TITLE
nvlink error with CustomCVForce

### ISSUE THREAD

**Issue by scychon** [openmm/openmm#3011]
I'm trying to use two GPUs linked with nvlink bridge. While normal simulations with common forces runs fine with great performance gain, CudaContext throws 'CUDA_ERROR_PEER_ACCESS_ALREADY_ENABLED' error while creating context if the system contains CustomCVForce.

I tried to debug this, and it looks like the innercontext created for CustomCVForce tried to enable peer access which is already enabled by the normal context.
Is there any easy fix for it? I'm using 7.4_branch with custom edit on the code...

Thanks !

Traceback (most recent call last):
  File "run_sphere_5nm_pbc.py", line 307, in <module>
    simmd = Simulation(newTopology, system, integ_md, platform, properties)
  File "/home/cson/program/anaconda3/lib/python3.7/site-packages/simtk/openmm/app/simulation.py", line 105, in __init__
    self.context = mm.Context(self.system, self.integrator, platform, platformProperties)
  File "/home/cson/program/anaconda3/lib/python3.7/site-packages/simtk/openmm/openmm.py", line 3329, in __init__
    this = _openmm.new_Context(*args)
Exception: Error initializing Context: CUDA_ERROR_PEER_ACCESS_ALREADY_ENABLED (704) at /home/cson/program/openmm_src_7.4/platforms/cuda/src/CudaContext.cpp:249

**Comment by peastman** [comment]
Here is where it enables peer to peer access:

https://github.com/openmm/openmm/blob/84a93cf857e26f732161550a78f217281e6d5d29/platforms/cuda/src/CudaContext.cpp#L235-L244

I think the correct fix is to change the first line to

```c++
if (contextIndex > 0 && originalContext == NULL) {
```

Could you try that and see if it works?

**Comment by scychon** [comment]
Skipping those lines for innercontext changes the error as following.

terminate called after throwing an instance of 'OpenMM::OpenMMException'
  what():  Error invoking kernel: CUDA_ERROR_INVALID_HANDLE (400)

**Comment by scychon** [comment]
It passed the initialization routine (I've checked by printing message at the end of CudaContext::CudaContext), and it was not easy to find where the error is occurring after this... The code runs without any issue if the devices are not linked or if I request to use only single GPU.

**Comment by scychon** [comment]
I've done some debugging and looks like the error is occurring when the CudaCalcForcesAndEnergyKernel::beginComputation is calling " cu.clearAutoclearBuffers();" function. 

 > https://github.com/openmm/openmm/blob/473069f07ecbf6267db2fc558dc8443a8d01d4e8/platforms/cuda/src/CudaKernels.cpp#L59-L65

The first call for the originalContext works fine, but the second call for the linkedContext w/ cu.getContextIndex()==1 generates CUDA_ERROR.
I assume the threaded clearing of the buffers generate some conflict in the buffer memory, but I'm not confident enough to make changes in the context. Any advice on this ?

**Comment by scychon** [comment]
I found two places generating exception on the CudaKernels.cpp. 
First is the above clearAutoclearBuffers(); command, and the second is "cu.reduceEnergy();" in CudaCalcForcesAndEnergyKernel::finishComputation

> https://github.com/openmm/openmm/blob/473069f07ecbf6267db2fc558dc8443a8d01d4e8/platforms/cuda/src/CudaKernels.cpp#L73-L84

Adding two sets of clauses in CudaContext.cpp to ignore above functions when the contextIndex > 0 for linked context as following passes all the tests and is able to run the simulation, but need to be validated whether the forces and energies are calculated as intended to be. I'll update after further tests.

> https://github.com/openmm/openmm/blob/473069f07ecbf6267db2fc558dc8443a8d01d4e8/platforms/cuda/src/CudaContext.cpp#L757-L760

```ruby
void CudaContext::clearAutoclearBuffers() { 
    int base = 0;
    int total = autoclearBufferSizes.size();
    if (this->deviceIndex > 0 and isLinkedContext)
        return;
    while (total-base >= 6) {
```


> https://github.com/openmm/openmm/blob/473069f07ecbf6267db2fc558dc8443a8d01d4e8/platforms/cuda/src/CudaContext.cpp#L801-L804

```ruby
    int workGroupSize  = 512;
    if (this->deviceIndex > 0 and isLinkedContext)
        return 0.0;
    void* args[] = {&energyBuffer.getDevicePointer(), &energySum.getDevicePointer(), &bufferSize, &workGroupSize};
```

**Comment by peastman** [comment]
No idea why those functions would cause errors.  Skipping them will not produce correct results.  The only thing that gets shared between linked contexts is the `CUcontext`.  They still have their own separate versions of all the arrays, such as the energy buffer.

https://github.com/openmm/openmm/blob/473069f07ecbf6267db2fc558dc8443a8d01d4e8/platforms/cuda/src/CudaContext.cpp#L203-L208

That's pretty much the only thing that's done differently for linked contexts.

**Comment by scychon** [comment]
It looks like the later error is general to multi-GPU simulation without NVLink. If I try to use two unlinked GPUs, the error message changes as following.

```ruby
  File "il_ua.py", line 78, in <module>
    print(type(f), str(simeq.context.getState(getEnergy=True, groups=2**i).getPotentialEnergy()))
  File "/home/cson/program/anaconda3/lib/python3.8/site-packages/simtk/openmm/openmm.py", line 16188, in getState
    state = _openmm.Context_getState(self, types, enforcePeriodicBox, groups_mask)
SystemError: <built-in function Context_getState> returned NULL without setting an error
terminate called after throwing an instance of 'OpenMM::OpenMMException'
  what():  Error deleting array bondParams: CUDA_ERROR_ILLEGAL_ADDRESS (700)
```

Again, running in single GPU does not have any problem. The problem happens only when CustomCVForce is added to the system, and trying to get the energy of this force object.
 
Doesn't the CustomCVForce rely on the energy terms in the innercontext? If so, wouldn't there be a problem when clearing buffers and energy params in a threaded fashion?

**Comment by babaid** [comment]
What is the current state on this issue, any progress?
I encountered similar problems.
