### ISSUE TITLE
How to add a protein floating above a lipid membrane

### ISSUE THREAD

**Issue by nataliaszulc** [openmm/openmm#3110]
Hello,
I've a protein positioned in Charmm-GUI to be above a lipid membrane. I try to make a similar system in your OpenMM software. Nevertheless, it fails to run with fallowing error:

```
Traceback (most recent call last):
  File "/home/ebam/niedziel1p/Desktop/insert_openmm/openmm_run.py", line 42, in <module>
    membraneCenterZ=-5*nanometer, neutralize=True)
  File "/home/ebam/niedziel1p/miniconda3/envs/openmm/lib/python3.6/site-packages/simtk/openmm/app/modeller.py", line 1454, in addMembrane
    integrator.step(20)
  File "/home/ebam/niedziel1p/miniconda3/envs/openmm/lib/python3.6/site-packages/simtk/openmm/openmm.py", line 11862, in step
    return _openmm.LangevinIntegrator_step(self, steps)
simtk.openmm.OpenMMException: Particle coordinate is nan
```
How to setup lipid membrane ?
Here is my code:
The error happens at the line below : "# HERE IS THE ERROR"
```
from simtk.openmm.app import *
from simtk.openmm import *
from simtk.unit import *
from simtk.openmm.app import DCDFile
import numpy as np
import random
import time
import shutil
from pprint import pprint
import matplotlib.pyplot as plt 
import seaborn as sns 
import os
import logging

dirName = 'simulation_2us'

# change it 
cuda = True
sim_time = 20000 # ps, so 5.0 us
#sim_time = 2500 # ps, so 2.5 ns
timestep = 0.004 # ps
steps = int(sim_time/0.004)
saving_frequency = 2000 # every 5000 steps, for timestep 0.004 it's every 20ps
cwd = os.getcwd()

os.mkdir(dirName)
logging.basicConfig(filename=dirName+'/file.log',level=logging.INFO)

if cuda:
    platform = Platform.getPlatformByName('CUDA')
else:
    platform = Platform.getPlatformByName('CPU')

forcefield = ForceField('amber14-all.xml', 'amber14/tip3pfb.xml')
pdb = PDBFile('step5_input.pdb')
modeller = Modeller(pdb.topology, pdb.positions)
# HERE IS THE ERROR
modeller.addMembrane(forcefield, lipidType='POPC', minimumPadding=1*nanometer, ionicStrength=0.05*molar,
                     membraneCenterZ=-5*nanometer, neutralize=True)
system = forcefield.createSystem(modeller.topology, nonbondedMethod=PME, constraints=HBonds, 
                                 nonbondedCutoff=1.2*nanometer, switchDistance=0.9*nanometer, 
                                 hydrogenMass=4*amu)
integrator = LangevinMiddleIntegrator(300*kelvin, 1/picosecond, timestep*picosecond)
topology = modeller.topology
positions = modeller.positions

from simtk.openmm.app import PDBFile, PDBxFile
filehandle = open('positions.pdb', 'w')
PDBFile.writeHeader(topology, filehandle)
PDBFile.writeModel(topology, positions, filehandle, 0)
PDBFile.writeFooter(topology, filehandle)
filehandle.close()
properties = {'Precision': 'mixed', 'DeviceIndex': '0, 1, 2, 3'}
simulation = Simulation(topology, system, integrator, platform, properties)
dcdreporter = DCDReporter(dirName+'/traj'+'.dcd', saving_frequency)
simulation.reporters.append(dcdreporter)
simulation.reporters.append(StateDataReporter(dirName+'/scalars'+'.csv', saving_frequency, time=True,
                                              potentialEnergy=True, totalEnergy=True, temperature=True))
simulation.context.setPositions(positions)
simulation.minimizeEnergy()

logging.info('start simulation, time is {0} ns'.format(sim_time/1000))
logging.info('Using GPU ?: {0}'.format(cuda))
logging.info('timestep {0} ps'.format(timestep))
logging.info('temperature {0} K'.format(300))
start_time = time.time()
simulation.step(steps)
end_time = time.time()
logging.info('Simulation ended, time spent {0} h for {1} ns'.format((-start_time+end_time)/3600, sim_time/1000))

```

**Comment by peastman** [comment]
Could you post your input file so we can try to reproduce it?

**Comment by nataliaszulc** [comment]
The input .pdb  file, packed in zip:
[step5_input.zip](https://github.com/openmm/openmm/files/6453926/step5_input.zip)

**Comment by peastman** [comment]
This seems to be related to periodic boundary conditions.  Looking at your PDB file, I see the protein is actually centered at about z = +10 nm.  You tell it to center the membrane at z = -5 nm.  It normally removes any lipids that overlap the protein, but since they're so far apart, it doesn't remove any.

But the total box size in the z direction is about 7.3 nm.  So after applying periodic boundary conditions, the protein actually comes down right on top of the membrane!

When you specify a padding distance, it chooses the box height as max(proteinHeight, membraneHeight)+2*padding.  Arguably it should also take into account the distance between the protein and the membrane.  But of course, this is a very unusual situation.  Normally they overlap each other.
