### ISSUE TITLE
CHARMM-GUI Systems in OpenMM: Interoperability and Documentation

### ISSUE THREAD

**Issue by apayne97** [openmm/openmm#3152]
It has become standard practice in the membrane protein simulation world to set up membrane systems using CHARMM-GUI. However, it is not yet common for such labs to then simulate their systems using OpenMM (GROMACS or NAMD/CHARMM are often used instead).

In the interest of including these potential users in the OpenMM world, it would be useful to have a more comprehensive tutorial for simulating systems set up in CHARMM-GUI. This point is further made by the issue here: https://github.com/openmm/openmm/issues/3114 in which several errors with the existing membrane protein simulation tutorial are notated. 

Both OpenMM and CHARMM-GUI boast simplicity and interoperability, but the documentation describing the various options for connecting the two is still rather limited. I would be happy to help set up a bit of a guide and work through some of the potential problems making the transition from CHARMM-GUI to OpenMM.

**Comment by apayne97** [comment]
Is it possible to set up tests to make sure the tutorial examples still work?

**Comment by peastman** [comment]
If you want to create a tutorial on this, that would be fantastic!  If you write it as a Jupyter notebook, we can add it to the tutorials section on the website.

> Is it possible to set up tests to make sure the tutorial examples still work?

We don't currently have that, but it would be a useful thing to add.

**Comment by apayne97** [comment]
I would love to write a tutorial, but unfortunately since the existing tutorial doesn't work I don't actually know how to set the system up. 

Here's the code I ran `b2ar-tutorial-sim.py` with the input files:
[tutorial-test.tar.gz](https://github.com/openmm/openmm/files/6689658/tutorial-test.tar.gz)

when I ran it on OpenMM version 7.4.2 it minimized:
```
The output (if any) follows:

  initial : -61533.890 kcal/mol
  final : -54091.681 kcal/mol
```
but didn't simulate very long before I got this error:
```
Traceback (most recent call last):
  File "b2ar-tutorial-sim.py", line 50, in <module>
    simulation.step(10000)
  File "/home/paynea/miniconda3/envs/omm742/lib/python3.7/site-packages/simtk/openmm/app/simulation.py", line 132, in step
    self._simulate(endStep=self.currentStep+steps)
  File "/home/paynea/miniconda3/envs/omm742/lib/python3.7/site-packages/simtk/openmm/app/simulation.py", line 238, in _simulate
    self._generate_reports(unwrapped, False)
  File "/home/paynea/miniconda3/envs/omm742/lib/python3.7/site-packages/simtk/openmm/app/simulation.py", line 257, in _generate_reports
    reporter.report(self, state)
  File "/home/paynea/miniconda3/envs/omm742/lib/python3.7/site-packages/simtk/openmm/app/pdbreporter.py", line 99, in report
    PDBFile.writeModel(simulation.topology, state.getPositions(), self._out, self._nextModel)
  File "/home/paynea/miniconda3/envs/omm742/lib/python3.7/site-packages/simtk/openmm/app/pdbfile.py", line 333, in writeModel
    raise ValueError('Particle position is NaN')
ValueError: Particle position is NaN
```
The PDB output file contains only CONECT records, but if I run pdb.getPositions() before simulating I get vectors, so I'm not sure what is happening.

**Comment by jchodera** [comment]
@peastman : The thought was that @apayne97 could work with you and @Yoshanuikabundi to identify the MVP content for the tutorial or cookbook entry here, but since none of us actually know how to properly take a membrane protein system from CHARMM-GUI into OpenMM to simulate it faithfully, he'll need to lean on you and I to help sort that out. As he points out, we'll need to update the existing B2AR tutorial as well (#3114).

**Comment by peastman** [comment]
I'll be happy to help how I can.  This isn't something I have experience with either.

**Comment by jchodera** [comment]
Together, we should be able to puzzle it out! If we need changes on the CHARMM-GUI side, this will be a way to collect our requests into a minimal, coherent request to improve interoperability.

**Comment by apayne97** [comment]
Any suggestions for troubleshooting directions? basic tests to run to see why this is failing?

**Comment by peastman** [comment]
The [FAQ](https://github.com/openmm/openmm/wiki/Frequently-Asked-Questions#nan) has advice on how to debug errors involves NaNs.

**Comment by ljmartin** [comment]
One suggestion might be changing the line: 
`simulation.topology.setUnitCellDimensions([70.4188763, 70.4188763, 100.589642])`
The units here are in nanometers so the images are a long way away. The max atom coordinates after translating the minimum coordinate to (0,0,0) are:
```
array([Quantity(value=7.9916, unit=nanometer),
       Quantity(value=7.8518, unit=nanometer),
       Quantity(value=10.1652, unit=nanometer)], dtype=object)
``` 

Maybe this could be changed to 
`simulation.topology.setUnitCellDimensions([8.1, 8.1, 10.3])`

It's possible it's an already equilibrated cell, but the PDB file is missing the cell information so it would require a barostat to equilibrate.

**Comment by jchodera** [comment]
One way in which this can be improved is to have a path to automatically moving the unit cell dimensions into OpenMM. For example, CHARMM-GUI could add the `CRYST` header to the PDB file, or write the box vectors to another auxiliary file.

**Comment by peastman** [comment]
Including the `CRYST1` record in the PDB file would definitely be good!

**Comment by jchodera** [comment]
@peastman : We should refine this as much as possible on our end into a useful tutorial, then collect our suggestions for the CHARMM-GUI team on how to make this process simpler and easier. That could be one of our suggestions.

**Comment by apayne97** [comment]
Ok I found a new error. Not sure how to dig through the files but the CHARMM PSF file created by CHARMM-GUI includes explicit bonds between H1 and H2 of water molecules.

(as explained at the bottom here)
[https://www.ks.uiuc.edu/Training/Tutorials/namd/namd-tutorial-unix-html/node24.html](https://www.ks.uiuc.edu/Training/Tutorials/namd/namd-tutorial-unix-html/node24.html)

Thus, if you create a Modeller object from a charmm psf file, HOH will have an extra bond:
```
[Bond(<Atom 19085 (O) of chain 2 residue 379 (HOH)>, <Atom 19086 (H1) of chain 2 residue 379 (HOH)>),
 Bond(<Atom 19085 (O) of chain 2 residue 379 (HOH)>, <Atom 19087 (H2) of chain 2 residue 379 (HOH)>),
 Bond(<Atom 19086 (H1) of chain 2 residue 379 (HOH)>, <Atom 19087 (H2) of chain 2 residue 379 (HOH)>)]
```
and when attempting to create a system from the forcefield you will get this error:

"No template found for residue 379 (HOH).  The set of atoms matches TIP3, but the bonds are different.  Perhaps the chain is missing a terminal group?"

I'm not sure but I think it might have to do with the fact that the bond is missing in this definition for TIP3P?

https://github.com/openmm/openmmforcefields/blob/master/charmm/ffxml/waters_ions_default.xml

**Comment by zhang-ivy** [comment]
Based on [the tutorial you sent](https://www.ks.uiuc.edu/Training/Tutorials/namd/namd-tutorial-unix-html/node24.html), it seems that the H1-H2 bond in HOH is only necessary for setting up CHARMM simulations. I would write a function that iterates over the bonds and deletes H1-H2 bonds from HOH, as they aren't necessary for OpenMM simulations.

**Comment by apayne97** [comment]
So far I've had success by deleting and re-adding waters within openmm, and then deleting the waters that .addSolvent() adds to inside the membrane using MDTraj. But I can try deleting the extra bonds instead, since that will save a few steps!

**Comment by peastman** [comment]
The extra bond is supposed to get removed automatically:

https://github.com/openmm/openmm/blob/71bc7c8c70ffbccd82891dec7fd4f4deb99af64d/wrappers/python/openmm/app/charmmpsffile.py#L275-L277

What are the atom and residue names?  We may just need to add some extra alternates if they're ones we haven't encountered before.

**Comment by apayne97** [comment]
> What are the atom and residue names? We may just need to add some extra alternates if they're ones we haven't encountered before.

```
# Load CHARMM files
filePath = 'b2ar-tutorial-param-files'

psf = CharmmPsfFile(os.path.join(filePath, 'step5_input.psf'))
pdb = PDBFile(os.path.join(filePath, 'step5_input_TP3.pdb')) ## new file here

param_filenames = ['par_all36_prot.prm', 'top_all36_prot.rtf',
                       'par_all36_lipid.prm', 'top_all36_lipid.rtf',
                       'toppar_water_ions.str']
param_paths = [os.path.join(filePath, file) for file in param_filenames]
params = CharmmParameterSet(*param_paths)

modeller = app.Modeller(psf.topology, pdb.positions)
allResidues = [everyResidue for everyResidue in modeller.topology.residues()]
myResidue = allResidues[379]
myAtoms = [everyAtom for everyAtom in myResidue.atoms()]
myBonds = [myBond for myBond in myResidue.bonds()]
myBonds
```
"[Bond(<Atom 19085 (O) of chain 2 residue 379 (HOH)>, <Atom 19086 (H1) of chain 2 residue 379 (HOH)>),
 Bond(<Atom 19085 (O) of chain 2 residue 379 (HOH)>, <Atom 19087 (H2) of chain 2 residue 379 (HOH)>),
 Bond(<Atom 19086 (H1) of chain 2 residue 379 (HOH)>, <Atom 19087 (H2) of chain 2 residue 379 (HOH)>)]"

So I think the Atom names are H1 and H2 and the residue name is HOH.

**Comment by peastman** [comment]
I don't understand why it isn't removing the bond.  The residue name is "TIP3" which is included in WATNAMES:

https://github.com/openmm/openmm/blob/71bc7c8c70ffbccd82891dec7fd4f4deb99af64d/wrappers/python/openmm/app/charmmpsffile.py#L60

And both hydrogens have names starting with "H".  So it should be removing the bond.

Can you send me the PSF and PDB files?

**Comment by apayne97** [comment]
They are included in the zip file I sent before! https://github.com/openmm/openmm/issues/3152#issuecomment-865366739

**Comment by peastman** [comment]
I'm not seeing the error when I run it with the OpenMM 7.6 beta:

```python
filePath = 'b2ar-tutorial-param-files'
psf = CharmmPsfFile(os.path.join(filePath, 'step5_input.psf'))
for a1, a2 in psf.topology.bonds():
    if a1.residue.index == 379:
        print(a1, a2)
```

That produces the output

```
<Atom 19085 (O) of chain 2 residue 379 (HOH)> <Atom 19086 (H1) of chain 2 residue 379 (HOH)>
<Atom 19085 (O) of chain 2 residue 379 (HOH)> <Atom 19087 (H2) of chain 2 residue 379 (HOH)>
```

Just the two expected bonds, none between the hydrogens.  What version of OpenMM are you using?

**Comment by apayne97** [comment]
I used 7.4.2! I will update and test.

**Comment by apayne97** [comment]
I updated to version 7.5.1 using conda, which fixed the bonding issue as you have shown! yay!

however, I got this same loading error https://github.com/openmm/openmmforcefields/issues/164 I got previously. loading the forcefields using openmmforcefield fails, it just never stops consuming memory (up to 32Gb on the cluster) and never finishes loading. Does this happen with 7.6 beta? how can I install 7.6 beta?
```
ffxml_filenames = ['charmm/charmm36_nowaters.xml', 'charmm/toppar_all36_lipid_model.xml', 'charmm/waters_ions_default.xml']
print("Loading forcefield: %s" % ffxml_filenames)
forcefield = app.ForceField(*ffxml_filenames)
```

that said, this code works with 7.5.1:
```
# Load CHARMM files
filePath = '../b2ar-tutorial-param-files'

psf = CharmmPsfFile(os.path.join(filePath, 'step5_input.psf'))
pdb = PDBFile(os.path.join(filePath, 'step5_input.pdb'))

param_filenames = ['par_all36_prot.prm', 'top_all36_prot.rtf',
                       'par_all36_lipid.prm', 'top_all36_lipid.rtf',
                       'toppar_water_ions.str']
param_paths = [os.path.join(filePath, file) for file in param_filenames]
params = CharmmParameterSet(*param_paths)

# X Y and Z values retrieved from the CHARMM-GUI interface
psf.setBox(7.04, 7.04, 10.05)

## Setting up the system using the psf file
system = psf.createSystem(params, 
                          nonbondedMethod=app.PME, 
                          constraints=app.HBonds,
                         removeCMMotion=False,
                         hydrogenMass=4.0 * unit.amu)
integrator = LangevinIntegrator(300*unit.kelvin,   # Temperature of head bath
                                1/unit.picosecond, # Friction coefficient
                                0.002*unit.picoseconds) # Time step

simulation = app.Simulation(psf.topology, system, integrator)
simulation.context.setPositions(pdb.positions)
```
...then minimization, simulation with PBC, etc. 

Since the parameters are loaded from locally downloaded files from CHARMM-GUI, I think this means that CHARMM36m will run even though it isn't in openmmforcefields yet. 

So progress! Thanks for the help!

**Comment by peastman** [comment]
> how can I install 7.6 beta?

Use this command:

```
conda install -c conda-forge/label/openmm_rc -c conda-forge openmm
```
