### ISSUE TITLE
When residue template cannot be matched, show set difference between missing atoms or bonds?

### ISSUE THREAD

**Issue by jchodera** [openmm/openmm#3181]
`openmm.app.ForceField` will sometimes fail to match a residue with messages like this:
```
ValueError: No template found for residue 608 (PHE).  The set of atoms matches CPHE, but the bonds are different.  Perhaps the chain is missing a terminal group?
```
In these cases, it's generally difficult to figure out exactly what the issue is. If we are missing atoms are bonds, could we show the set differences between what is expected and what is found? This might help debug problematic PDB files.

**Comment by jchodera** [comment]
Here's an example where this error is issued when trying to parameterize the PDB file because it contains `UNK` residues:
```
(perses-dev) lski2838:Desktop choderaj$ python
Python 3.8.10 | packaged by conda-forge | (default, May 10 2021, 22:58:09) 
[Clang 11.1.0 ] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from simtk.openmm import app
>>> pdbfile = app.PDBFile('fixed_receptor.pdb')
>>> forcefield = app.ForceField('amber14-all.xml')
>>> system = forcefield.createSystem(pdbfile.topology)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/choderaj/miniconda/envs/perses-dev/lib/python3.8/site-packages/simtk/openmm/app/forcefield.py", line 1179, in createSystem
    templateForResidue = self._matchAllResiduesToTemplates(data, topology, residueTemplates, ignoreExternalBonds)
  File "/Users/choderaj/miniconda/envs/perses-dev/lib/python3.8/site-packages/simtk/openmm/app/forcefield.py", line 1393, in _matchAllResiduesToTemplates
    raise ValueError('No template found for residue %d (%s).  %s' % (res.index+1, res.name, _findMatchErrors(self, res)))
ValueError: No template found for residue 343 (UNK).  The set of atoms matches HID, but the bonds are different.
```
[fixed_receptor.pdb.zip](https://github.com/openmm/openmm/files/6833613/fixed_receptor.pdb.zip)

**Comment by peastman** [comment]
Good idea.

**Comment by epretti** [comment]
This has been addressed by #5020.
