### ISSUE TITLE
How to use ML Potentials with openmm?

### ISSUE THREAD

**Issue by siddharth-ncl-work** [openmm/openmm#3215]
Hi,

I want to use a trained SchNet model to carry out NPT simulation. Unfortunately, SchNetPack and torchmd don't natively support NPT simulation (let me know if I am wrong about this). 

I stumbled upon issue #2991, looks like there are on going efforts for the incorporation of ML potentials in openmm. I have a few questions related to this:
1. Are ML potentials part of the latest version of openmm or separate repository (i.e., [openmm-ml](https://github.com/openmm/openmm-ml) )?
2. How should I get started with ML potentials using openmm? Is there documentation/examples for it?

Thank you

**Comment by peastman** [comment]
You can use the [openmm-torch](https://github.com/openmm/openmm-torch) plugin.  It lets you use any PyTorch model as a force.  You'll probably need to write a simple model as an adapter to convert between the inputs and outputs of the SchNetPack model and those expected by OpenMM.  That should only be a few lines.

Note that for periodic boundary conditions, one of the inputs to the model is the box vectors.  With NPT, those will change from step to step.  Is that compatible with how SchNetPack defines periodic boundary conditions?

**Comment by siddharth-ncl-work** [comment]
I will check out the openmm-torch plugin and the required transformations between input and output. 

Regarding periodic boundary conditions, I think SchNet supports PBC but currently, I am working with the model trained on DFT data so only input to the model is coordinates and atomic numbers. If openmm provides box vectors as one of the inputs at each step......I think I will have to ignore it.

Thank you for the response.

**Comment by siddharth-ncl-work** [comment]
@peastman, I tried openmm-torch plugin. Unfortunately, I couldn't make it work. I am getting the following error. Could you please help me with it.

**Input**
```
import torch
import schnetpack
from schnetpack.md import System
from schnetpack.md.utils import MDUnits
from schnetpack.md.calculators import SchnetPackCalculator
from schnetpack import Properties

# create system
system = System(1, device='cuda')
system.load_molecules_from_xyz('input_data/ethanol_from_pubchem.xyz')

# import schnetpack model
model=schnetpack.utils.load_model('schnetpack_model',map_location='cuda')

# create calculator object for calculating energy
calculator = SchnetPackCalculator(
    model,
    required_properties=[Properties.energy, Properties.forces],
    force_handle=Properties.forces,
    position_conversion='A',
    force_conversion='kcal/mol/A',
)

# factor to convert nm to schnetpack internal units
scale=10*MDUnits.angs2internal

class ForceModule(torch.nn.Module):
    
    def forward(self, positions,scale):
        """The forward method returns the energy computed from positions.

        Parameters
        ----------
        positions : torch.Tensor with shape (nparticles,3)
           positions[i,k] is the position (in nanometers) of spatial dimension k of particle i

        Returns
        -------
        potential : torch.Scalar
           The potential energy (in kJ/mol)
        """
        # convert positions units from nm to schnetpack internal units
        positions=positions*scale
        
        # reshape, change dtype and move to device
        positions=positions.reshape(system.positions.shape)
        positions=positions.to(system.device,dtype=system.positions.dtype)
        
        # update system coordinates with positions
        system.positions=positions
        
        # calculate energy
        calculator.calculate(system)
        energy=calculator.results['energy']
        energy=energy*MDUnits.unit2unit('kcal/mol', 'kJ/mol')
        return energy

# Render the compute graph to a TorchScript module
module = torch.jit.script(ForceModule())

# Serialize the compute graph to a file
module.save('model.pt')
```

**Error**
```
RuntimeError                              Traceback (most recent call last)
/tmp/ipykernel_172320/2672050112.py in <module>
     57 
     58 # Render the compute graph to a TorchScript module
---> 59 module = torch.jit.script(ForceModule())
     60 
     61 # Serialize the compute graph to a file

~/anaconda3/envs/schnetpack/lib/python3.8/site-packages/torch/jit/_script.py in script(obj, optimize, _frames_up, _rcb)
    895 
    896     if isinstance(obj, torch.nn.Module):
--> 897         return torch.jit._recursive.create_script_module(
    898             obj, torch.jit._recursive.infer_methods_to_compile
    899         )

~/anaconda3/envs/schnetpack/lib/python3.8/site-packages/torch/jit/_recursive.py in create_script_module(nn_module, stubs_fn, share_types)
    350     check_module_initialized(nn_module)
    351     concrete_type = get_module_concrete_type(nn_module, share_types)
--> 352     return create_script_module_impl(nn_module, concrete_type, stubs_fn)
    353 
    354 def create_script_module_impl(nn_module, concrete_type, stubs_fn):

~/anaconda3/envs/schnetpack/lib/python3.8/site-packages/torch/jit/_recursive.py in create_script_module_impl(nn_module, concrete_type, stubs_fn)
    408     # Compile methods if necessary
    409     if concrete_type not in concrete_type_store.methods_compiled:
--> 410         create_methods_and_properties_from_stubs(concrete_type, method_stubs, property_stubs)
    411         torch._C._run_emit_module_hook(cpp_module)
    412         concrete_type_store.methods_compiled.add(concrete_type)

~/anaconda3/envs/schnetpack/lib/python3.8/site-packages/torch/jit/_recursive.py in create_methods_and_properties_from_stubs(concrete_type, method_stubs, property_stubs)
    302     property_rcbs = [p.resolution_callback for p in property_stubs]
    303 
--> 304     concrete_type._create_methods_and_properties(property_defs, property_rcbs, method_defs, method_rcbs, method_defaults)
    305 
    306 

RuntimeError: 
attribute lookup is not defined on python value of type 'System':
  File "/tmp/ipykernel_172320/2672050112.py", line 46
        
        # reshape, change dtype and move to device
        positions=positions.reshape(system.positions.shape)
                                    ~~~~~~~~~~~~~~~~ <--- HERE
        positions=positions.to(system.device,dtype=system.positions.dtype)
```

**Comment by raimis** [comment]
`system` should be created in the `ForceModule` constructor, i.e. __init__.

**Comment by peastman** [comment]
To elaborate slightly, you're asking it to compile the Python code in ForceModule to TorchScript.  It can only do that if the code is completely self contained.  `forward()` can only reference values that were passed as arguments (including `this`).  It can't reference values defined in an external scope.

**Comment by siddharth-ncl-work** [comment]
@raimis @peastman, thank you for the suggestions. I have incorporated them into the script. It looks like the previous issue has been resolved but now I am stuck with the new error. Here, I have shown only first and last portion of the error as it was quite long. You can access the whole error log from [here.](https://gist.github.com/siddharth-ncl-work/68983bd8f74944f24d9a0e02523367aa)

**Input**
```
import torch
import schnetpack
from schnetpack.md import System
from schnetpack.md.utils import MDUnits
from schnetpack.md.calculators import SchnetPackCalculator
from schnetpack import Properties


class ForceModule(torch.nn.Module):
    
    def __init__(self):
        
        super(ForceModule, self).__init__()
        
        # create system
        self.system = System(1, device='cuda')
        self.system.load_molecules_from_xyz('input_data/ethanol_from_pubchem.xyz')

        # import schnetpack model
        self.model=schnetpack.utils.load_model('schnetpack_model',map_location='cuda')
    
        # create calculator object for calculating energy
        self.calculator = SchnetPackCalculator(
            self.model,
            required_properties=[Properties.energy, Properties.forces],
            force_handle=Properties.forces,
            position_conversion='A',
            force_conversion='kcal/mol/A',
        )
        
        # factor to convert nm to schnetpack internal units
        self.scale_length=10*MDUnits.angs2internal
        self.scale_energy=MDUnits.unit2unit('kcal/mol', 'kJ/mol')
        
    def forward(self, positions):
        """The forward method returns the energy computed from positions.

        Parameters
        ----------
        positions : torch.Tensor with shape (nparticles,3)
           positions[i,k] is the position (in nanometers) of spatial dimension k of particle i

        Returns
        -------
        potential : torch.Scalar
           The potential energy (in kJ/mol)
        """

        # convert positions units from nm to schnetpack internal units
        positions=positions*self.scale_length
        
        # reshape, change dtype and move to device
        positions=positions.reshape(self.system.positions.shape)
        positions=positions.to(self.system.device,dtype=self.system.positions.dtype)
        
        # update system coordinates with positions
        self.system.positions=positions
        
        # calculate energy
        self.calculator.calculate(self.system)
        energy=self.calculator.results['energy']
        energy=energy*scale_energy
        return energy

# Render the compute graph to a TorchScript module
module = torch.jit.script(ForceModule())

# Serialize the compute graph to a file
module.save('model.pt')
```

**Error**
```
RuntimeError                              Traceback (most recent call last)
/tmp/ipykernel_182453/2971404541.py in <module>
     64 
     65 # Render the compute graph to a TorchScript module
---> 66 module = torch.jit.script(ForceModule())
     67 
     68 # Serialize the compute graph to a file

~/anaconda3/envs/schnetpack/lib/python3.8/site-packages/torch/jit/_script.py in script(obj, optimize, _frames_up, _rcb)
    895 
    896     if isinstance(obj, torch.nn.Module):
--> 897         return torch.jit._recursive.create_script_module(
    898             obj, torch.jit._recursive.infer_methods_to_compile
    899         )

.
.
.

~/anaconda3/envs/schnetpack/lib/python3.8/site-packages/torch/jit/_script.py in script(obj, optimize, _frames_up, _rcb)
    937         if _rcb is None:
    938             _rcb = _jit_internal.createResolutionCallbackFromClosure(obj)
--> 939         fn = torch._C._jit_script_compile(
    940             qualified_name, ast, _rcb, get_default_args(obj)
    941         )

RuntimeError: 
Previous return statement returned a value of type Tuple[Tensor, Tensor] but this return statement returns a value of type Tensor:
  File "/home/vanka/anaconda3/envs/schnetpack/lib/python3.8/site-packages/schnetpack/nn/neighbors.py", line 82
            dist_vec = dist_vec / tmp_distances[:, :, :, None]
        return distances, dist_vec
    return distances
    ~~~~~~~~~~~~~~~~ <--- HERE
'atom_distances' is being compiled since it was called from 'AtomDistances.forward'
  File "/home/vanka/anaconda3/envs/schnetpack/lib/python3.8/site-packages/schnetpack/nn/neighbors.py", line 119

        """
        return atom_distances(
               ~~~~~~~~~~~~~~~
            positions,
            ~~~~~~~~~~
            neighbors,
            ~~~~~~~~~~
            cell,
            ~~~~~
            cell_offsets,
            ~~~~~~~~~~~~~
            return_vecs=self.return_directions,
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
            normalize_vecs=True,
            ~~~~~~~~~~~~~~~~~~~~
            neighbor_mask=neighbor_mask,
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~ <--- HERE
        )
```

**Comment by raimis** [comment]
```
RuntimeError: 
Previous return statement returned a value of type Tuple[Tensor, Tensor] but this return statement returns a value of type Tensor:
  File "/home/vanka/anaconda3/envs/schnetpack/lib/python3.8/site-packages/schnetpack/nn/neighbors.py", line 82
            dist_vec = dist_vec / tmp_distances[:, :, :, None]
        return distances, dist_vec
    return distances
    ~~~~~~~~~~~~~~~~ <--- HERE
```
TorchScript does not support dynamic function return types, i.e. the function has to return `Tuple[Tensor, Tensor]` or `Tensor` only and the type cannot depend on the function argument values.

In general, is SchNetPack compatible with TorchScript? Do they mention that somewhere in the docs?

**Comment by raimis** [comment]
PyTorch-Geometric has a SchNet implementation (https://pytorch-geometric.readthedocs.io/en/latest/modules/nn.html?highlight=SchNet#torch_geometric.nn.models.SchNet) compatible with TorchScript.

Unfortunately, there are no compatible Conda packages (https://github.com/rusty1s/pytorch_geometric/issues/2790) with OpenMM-Torch.

**Comment by siddharth-ncl-work** [comment]
No, they don't mention about TorchScript compatibility in the docs. However I found these two pull requests ([PR1](https://github.com/atomistic-machine-learning/schnetpack/pull/296), [PR2](https://github.com/atomistic-machine-learning/schnetpack/pull/285)) containing 'torchscript' keyword.

Thanks for sharing PyTorch-Geometric, I will check it out

**Comment by peastman** [comment]
Closing this since I think all questions have been answered.  Feel free to reopen it if I missed something.
