### ISSUE TITLE
Alchemical free energy calculations example on CPU & GPU

### ISSUE THREAD

**Issue by synjon-symthe** [openmm/openmm#3288]
I was trying to run the Alchemical free energy calculations example as is on a CPU and a gpu - both cases don't run to completion.
but the errors are different.

On the cpu I get
Minimizing energy...
state     0 iteration     0 /    50
state     0 iteration     1 /    50
state     0 iteration     2 /    50
state     0 iteration     3 /    50
state     0 iteration     4 /    50
state     0 iteration     5 /    50
Traceback (most recent call last):
  File "/openmm/alchemical-example.py", line 62, in <module
>
    integrator.step(nsteps)
  File "/miniconda3/lib/python3.9/site-packages/openmm/openmm.py", line 8405, in step
    return _openmm.LangevinIntegrator_step(self, steps)
openmm.OpenMMException: Particle coordinate is nan

on the gpu - it runs for 9 iterations ...

state     9 iteration    47 /    50
state     9 iteration    48 /    50
state     9 iteration    49 /    50
Traceback (most recent call last):

  File "/openmm/alchemical-example.py", line 79, in <module
>
    [DeltaF_ij, dDeltaF_ij, Theta_ij] = mbar.getFreeEnergyDifferences()
  File "/miniconda3/lib/python3.9/site-packages/pymbar/mbar.py", line 541, in getFreeEnergyDifferences
    Theta_ij = self._computeAsymptoticCovarianceMatrix(
  File "miniconda3/lib/python3.9/site-packages/pymbar/mbar.py", line 1679, in _computeAsymptoticCovarianceMatrix
    check_w_normalized(W, N_k)
  File "miniconda3/lib/python3.9/site-packages/pymbar/utils.py", line 358, in check_w_normalized
    raise ParameterError(
pymbar.utils.ParameterError: Warning: Should have \sum_n W_nk = 1.  Actual column sum for state 0 was 1.000564. 10 other columns have similar problems

Has anyone seen this before?

**Comment by aizvorski** [comment]
@peastman Nice!  I didn't know there even are tutorials :) How do you feel about getting these into this repo?

**Comment by z-gong** [comment]
I've encountered this problem recently. It seems to stem from the latest pymbar.
Downgrading pymbar to 3.0.3 eliminates this error.
See also https://github.com/choderalab/pymbar/issues/419

**Comment by GasparPinto** [comment]
I am getting the same error when following the tutorial? Was this deprecated?
https://openmm.github.io/openmm-cookbook/latest/notebooks/tutorials/Alchemical_free_energy_calculations.html

**Comment by sef43** [comment]
> I am getting the same error when following the tutorial? Was this deprecated? https://openmm.github.io/openmm-cookbook/latest/notebooks/tutorials/Alchemical_free_energy_calculations.html

Are you referring to the error from pymbar (https://github.com/choderalab/pymbar/issues/419) ? The error comes only when calculating the uncertainties, if you don't calculate them it should work: mbar.getFreeEnergyDifferences(compute_uncertainty=False)`

**Comment by sef43** [comment]
ah ok I think this is an API change of pymbar version 4 from version 3.x https://pymbar.readthedocs.io/en/master/moving_from_pymbar3.html thanks for highlighting it! 

the tutorials were written for pymbar version 3.x 

I will see about updating the tutorial or making a note about the pymbar version. 

(the better place for this issue would now be the cookbook repo:  https://github.com/openmm/openmm-cookbook)

**Comment by GasparPinto** [comment]
Oh, thank you for this. I was a bit lost with all the tutorials I found online. 

For me this ticket can be closed...

Cheers

**Comment by sef43** [comment]
Great, for future reference for other people stumbling on this issue the most up to date OpenMM tutorials will be found here: https://openmm.github.io/openmm-cookbook/latest/tutorials.html
