### ISSUE TITLE
OpenMM+CUDA on docker

### ISSUE THREAD

**Issue by mkadlof** [openmm/openmm#3344]
I struggle with building docker container with OpenMM. When I try to run the container with:

```bash
docker run -it --rm --name md-soft \
           --runtime nvidia \
           --gpus all \
           --device /dev/nvidia0 \
           --device /dev/nvidiactl \
           --device /dev/nvidia-modeset \
            md-soft:build \
            /bin/bash
```

I receive following error:

```
Traceback (most recent call last):
  File "./run.py", line 403, in <module>
    main()
  File "./run.py", line 395, in main
    pdb, random_seed, simulation = setup(args)
  File "./run.py", line 314, in setup
    simulation = Simulation(pdb.topology, system, integrator, platform)
  File "/opt/venv/lib/python3.8/site-packages/openmm/app/simulation.py", line 103, in __init__
    self.context = mm.Context(self.system, self.integrator, platform)
  File "/opt/venv/lib/python3.8/site-packages/openmm/openmm.py", line 18718, in __init__
    _openmm.Context_swiginit(self, _openmm.new_Context(*args))
openmm.OpenMMException: Error initializing CUDA: CUDA_ERROR_UNKNOWN (999) at /home/mdsoft/openmm/platforms/cuda/src/CudaContext.cpp:138
```
The same code works fine on host machine.

### Here are debug info:
OpenMM version: 7.6 (commit: ad113a0)
Host OS: Debian 11 bullseye
Kernel: 5.10.0-9-amd64
Platform: ThinkPad T15p Gen 1
GPU: GeForce GTX 1050 3 GB Max-Q
Docker Version: 20.10.10
Docker base image: nvidia/cuda:11.4.2-devel-ubuntu20.04
Here is my Dockerfile: https://pastebin.com/FGuSn0xJ

nvidia-smi inside container returns correct output.

### Steps to reproduce:
0. install [nvidia-docker](https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/install-guide.html#docker)
1. Build container with: `docker build -t md-soft .`
2. Enter docker (exact command above)
3. Execute test simulation: `./run.py -c config.ini --platform CUDA`

I'm aware that it might be a problem with my docker setup - not necessarily something with OpenMM. But i hope that maybe someone already had similar issue, and know the answer?

**Comment by mkadlof** [comment]
I forgot about to additional devices in docker run command:

           --device /dev/nvidia-uvm \
           --device /dev/nvidia-uvm-tools \

Now it's working fine. Sorry for spamming.
