### ISSUE TITLE
simtk.openmm.OpenMMException: Particle coordinate is nan

### ISSUE THREAD

**Issue by gugy89** [openmm/openmm#3359]
Dear OpenMM experts,

I am trying to run a simple simulation followed by a binding free energy calculation of the docked ligand (NADPH).
To do this, I am first building the forcefield for NADPH and then running a min, eq, prod (shortened for demonstration purposes in the attached code example), and then defining the alchemical system and running the lambda calculations.
As you can see from the code-comments, I come from gromacs and am new to openMM.

When running this code, I **sometimes** get an "Particle coordinate is nan" exception, which crashes the simulation:

```
Collecting data started at 13:48:59...
state     0 iteration     0 /    10
state     0 iteration     1 /    10
state     0 iteration     2 /    10
Traceback (most recent call last):
  File "/media/gug/9de566b5-6f65-4421-b224-dfbd67df027c/openMM/test_GG1/ALLINONE.py", line 417, in <module>
    integrator.step(nsteps)
  File "/home/gug/anaconda3/envs/openMM/lib/python3.9/site-packages/simtk/openmm/openmm.py", line 12771, in step
    return _openmm.VerletIntegrator_step(self, steps)
simtk.openmm.OpenMMException: Particle coordinate is nan
```

Is this reproducible on your machines? The example.zip attached should contain all you need to run the system.

Can this be overcome somehow? (naive thought: catch the error, relaunch the iteration step that crashed, but I do not know ho to do that...)

I am running on an ubuntu 18.04 with openmm 7.5.1. Happy to provide further sys details if needed.

[Example.zip](https://github.com/openmm/openmm/files/7642252/Example.zip)

**Comment by peastman** [comment]
The FAQ has a [discussion of this error](https://github.com/openmm/openmm/wiki/Frequently-Asked-Questions#nan) and how to figure out the cause.  That would be a good place to start.  I'll try to take a look at your code a bit later when I have time.

**Comment by gugy89** [comment]
Ah I see - thanks for the hint, I missed it in the FAQ.
I have increased the equilibration and simulation time to 1ns and am now running the code again.

I am wondering whether I understand correctly what is happening:
Is the "complex" object (which contains my simulated system with Protein and Ligand) updated as the simulation progresses, meaning if I call the "complex" after the simulation and for the alchemical free energy calculation, is "complex" the state of the system after the simulation?

Also, does anyone have experience with storing simulation parameters or "simulated systems" as pickles, to pass them on from one script to another? 
Or is this not recommended?

**Comment by peastman** [comment]
In your script, `complex` is a Modeller.  That's a tool for manipulating topologies prior to simulating them.  It has `topology` and `positions` fields.  Each time you call a method on it to perform some modification (such as `addSolvent()`), it replaces them with new values.  Running a simulation doesn't change them though.

When you call `createSystem()`, that creates a System object.  It's created based on the Topology, but it doesn't remain connected to it.  If you modify either the System or the Topology, that won't change the other.

A System is a static object.  It doesn't change while you run a simulation.  Everything that changes is in the Context.

> Also, does anyone have experience with storing simulation parameters or "simulated systems" as pickles, to pass them on from one script to another?

The best way to save a System is by writing it to an XML file.

```python
with open('system.xml', 'w') as output:
  output.write(XmlSerializer.serialize(system)
```

Then you can reload it with

```python
with open('system.xml') as input:
  system = XmlSerializer.deserialize(input.read())
```

**Comment by gugy89** [comment]
Ah, then I guess the problem is that I was not loading the "simulated" system in the alchemical calculation, but the "non-minimized, non-equilibrated" system, and of course that one explodes...
Will test the xml code and update as I make progress.

**Comment by gugy89** [comment]
@peastman  Thanks for the help so far.

Unfortunately, I am still having problems...

So I have split up the code that was previously in one script into two scripts and I am passing on the system as an xml file, so far so good.

BUT: At the moment, I need the topology of the system to use mdtraj to select residues and atoms that I then use as "alchemical region".
I get an error on line 103 when running alchemy.only.py:
`mdtraj_complex = md.Topology.from_openmm(system.topology)`
Error:
```
    mdtraj_complex = md.Topology.from_openmm(system.topology)
AttributeError: 'System' object has no attribute 'topology'

```

So my question now is:
What is the recommended way of storing a topology with openMM?
I wan tto avoid conversions to Gromacs/AMBEr or other formats, and I guess there is an XML export, but I cannot find Info on this.
I think it would be nice to add such info to the Docs, e.g. here: 
http://docs.openmm.org/7.0.0/api-python/generated/simtk.openmm.app.topology.Topology.html

To me this is still linked to my problem with the system blowing up, because in the original version of the code, I was loading the topology fr
[211209_code.zip](https://github.com/openmm/openmm/files/7685783/211209_code.zip)
om my modeller object called complex...
But I can open a new question if this is too far off topic.
