### ISSUE TITLE
`KeyError` throw because of patch in the force field xml file

### ISSUE THREAD

**Issue by yihengwuKP** [openmm/openmm#3360]
**Summary**
when I tried to use the patch syntax for creating a coarse-grained forcefield xml file, the `KeyError` is thrown in line 1559 of the `forcefield.py`, because the `forcefield._patches` is an empty list.

**OpenMM Version and Platform**
I am using `openmm 7.6.0` in manjaro, installed from `conda-forge`

**Expected behaviour**
As described in the [documentation](http://docs.openmm.org/latest/userguide/application/05_creating_ffs.html#patches), patches should modify the existing residues and parse them, but it seems to fail.

**Minimum Reproducing Example**
file `test_patch.xml`:
```xml
<Forcefield>     
        <AtomTypes>         
                <Type name="P" class="Phosphate" element= "P"  mass = "94.97"/>         
                <Type name="S" class="Sugar"  element="C" mass = "97.054"/>         
                <Type name="N6" class="Base"  element="N" mass = "42.030"/>              
                <Type name="O2" class="Base"  element="H" mass = "42.006"/>         
                <Type name="CU" class="Base"  element="C" mass = "26.016"/>         
        </AtomTypes>     
        <Residues>         
                <Residue name="C">             
                <AllowPatch name="single_nt"/>             
                <ExternalBond atomName="P"/>             
                <Atom name="P" type="P"/>             
                <Atom name="S" type="S"/>             
                <Atom name="CU" type="CU"/>             
                <Atom name="N6" type="N6"/>             
                <Atom name="O2" type="O2"/>             
                <Bond atomName1="P" atomName2="S"/>             
                <Bond atomName1="S" atomName2="CU"/>             
                <Bond atomName1="CU" atomName2="N6"/>             
                <Bond atomName1="CU" atomName2="O2"/>             
                <Bond atomName1="N6" atomName2="O2"/>             
                <ExternalBond atomName="S"/>         
                </Residue>         
                <Patch name="single_nt">            
                <RemoveExternalBond atomName="P"/>             
                <RemoveAtom name="P"/>             
                <RemoveBond atomName1="P" atomName2="S"/>             
                <RemoveExternalBond atomName="S"/>         
                </Patch>     
        </Residues> 
</Forcefield>
```

file `1ntC_cg_box.pdb`:
```
CRYST1  100.000  100.000  100.000  90.00  90.00  90.00 P 1           1
ATOM      1  S     C A   1      46.738  44.489  63.724  1.00  0.00           C  
ATOM      2  CU    C A   1      44.251  46.691  63.026  1.00  0.00           C  
ATOM      3  N6    C A   1      41.659  48.678  61.510  1.00  0.00           N  
ATOM      4  O2    C A   1      42.040  44.171  61.971  1.00  0.00           H  
CONECT    1    2 
CONECT    2    1    3    4    
CONECT    3    2    4
CONECT    4    2    3
```
This is coarse-grained starting nucleotide cytosine.

and file `test_1ntC_xml.py`:
```python
#!/usr/bin/env python

import openmm.app as app # contains functions for I/O

pdb = app.PDBFile("1ntC_cg_box.pdb")
forcefield = app.ForceField("test_patch.xml")
top = pdb.topology

system = forcefield.createSystem(top)
print(system)
```
And the full error message is:
```
Traceback (most recent call last):
  File "./test_1ntC_xml.py", line 9, in <module>
    system = forcefield.createSystem(top)
  File "/pathto/openmm/lib/python3.7/site-packages/openmm/app/forcefield.py", line 1206, in createSystem
    templateForResidue = self._matchAllResiduesToTemplates(data, topology, residueTemplates, ignoreExternalBonds)
  File "/pathto/openmm/lib/python3.7/site-packages/openmm/app/forcefield.py", line 1399, in _matchAllResiduesToTemplates
    unmatchedResidues = _applyPatchesToMatchResidues(self, data, unmatchedResidues, templateForResidue, data.bondedToAtom, ignoreExternalBonds, ignoreExtraParticles)
  File "/pathto/openmm/lib/python3.7/site-packages/openmm/app/forcefield.py", line 1559, in _applyPatchesToMatchResidues
    patches = [forcefield._patches[patchName] for patchName, patchResidueIndex in forcefield._templatePatches[name] if forcefield._patches[patchName].numResidues == 1]
  File "/pathto/openmm/lib/python3.7/site-packages/openmm/app/forcefield.py", line 1559, in <listcomp>
    patches = [forcefield._patches[patchName] for patchName, patchResidueIndex in forcefield._templatePatches[name] if forcefield._patches[patchName].numResidues == 1]
KeyError: 'single_nt'
```

I tried to look into the `forcefield.py`, and found that somehow the `forcefield._patch` is an empty list during the running, but I don't know why or how to proceed debugging. I also found if I delete the line `<AllowPatch name="single_nt"/>` and add `<ApplyToResidue name="C"/>` to the patch, then it will thrown the error: No template found for residue 1 (C). All files are zipped and attached!
[1ntC_xml.zip](https://github.com/openmm/openmm/files/7644028/1ntC_xml.zip)

**Comment by peastman** [comment]
`<Patch>` tags need to go inside the `<Patches>` category.  You put yours inside the `<Residues>` category.

**Comment by yihengwuKP** [comment]
ah, ok it works! thanks for helping me out, it really bugs me for a while! I would appreciate it if this can more explicit in the documentation though

**Comment by peastman** [comment]
I'll reopen this issue and mark it as documentation.  I think we can make it a bit clearer.  Thanks!
