### ISSUE TITLE
Applying barostat to an openff forcefield: A barostat cannot be used with a non-periodic system

### ISSUE THREAD

**Issue by snyga** [openmm/openmm#3374]
When applying the MonteCarloBarostat to a system and running the simulation it returns: 
`openmm.OpenMMException: A barostat cannot be used with a non-periodic system`

I find it weird as when looking  through the documentation it seems that most simple systems are periodic by default.

Edit: Added the pdb and sdf files used for the simulations:
https://drive.google.com/file/d/1-XMaMVsC6s9SJJx7nsW6dQqbvmtz05wi/view?usp=sharing
https://drive.google.com/file/d/19r2xrri3ipzJ_nsW5v3WkIJCCy6tOHrq/view?usp=sharing
https://drive.google.com/file/d/1ueuy3_ILcVrA5cOu7Ts25PpTdEGv_hzf/view?usp=sharing
```
from openmm.app import ForceField
from openmm.app import Modeller
from openmm.app import PDBFile
from openmm.app import Simulation

from openmm.vec3 import Vec3

from openmm.openmm import unit
from openmm.openmm import LangevinMiddleIntegrator
from openmm.openmm import MonteCarloBarostat

from openmmforcefields.generators import SMIRNOFFTemplateGenerator
# version openmmforcefields         0.9.0+29.g73a0707          pypi_0    pypi
# Pulled 
from openff.toolkit.topology import Molecule

smirnoff = SMIRNOFFTemplateGenerator(forcefield='openff-2.0.0.offxml')
    
offmol_sdf = sdf_files = ['aspirin.sdf', 'bcd_gly.sdf']
for i in range(2):
    offmol = Molecule.from_file(offmol_sdf[i])
    smirnoff.add_molecules(offmol)
force_field = ForceField('amber14-all.xml', 'tip3p.xml', 'amber/GLYCAM_06j-1.xml')
force_field.registerTemplateGenerator(smirnoff.generator)

pdb = PDBFile('bcd_gly_aspirin.pdb')

a_vec = Vec3(5, 0, 0)
b_vec = Vec3(0, 5, 0)
c_vec = Vec3(0, 0, 5)
        
modeller = Modeller(pdb.topology, pdb.positions)
modeller.addSolvent(force_field, model='tip3p', boxVectors=(a_vec, b_vec, c_vec))

temp =      298.15 * unit.kelvin
step_size = 1 * unit.picoseconds
fric_coef = 1 / unit.picoseconds

integrator = LangevinMiddleIntegrator(temp, fric_coef, step_size)
system = force_field.createSystem(modeller.topology)

pressure =  1 * unit.atmospheres
barostat = MonteCarloBarostat(pressure, temp, 25)
system.addForce(barostat)

simulation = Simulation(modeller.topology, system, integrator)from openmm.app import ForceField
```

The above simulation returns the following error:

```
Traceback (most recent call last):
  File "/mnt/g/My Drive/test10/test50.py", line 53, in <module>
    simulation = Simulation(modeller.topology, system, integrator)
  File "/home/snyga17/miniconda3/envs/pyth39/lib/python3.9/site-packages/openmm/app/simulation.py", line 101, in __init__
    self.context = mm.Context(self.system, self.integrator)
  File "/home/snyga17/miniconda3/envs/pyth39/lib/python3.9/site-packages/openmm/openmm.py", line 3951, in __init__
    _openmm.Context_swiginit(self, _openmm.new_Context(*args))
openmm.OpenMMException: A barostat cannot be used with a non-periodic system
```

**Comment by peastman** [comment]
Whether the system is periodic is determined by the `nonbondedMethod` argument to `createSystem()`.  Since you didn't specify it, you're getting the default value of `NoCutoff`, which corresponds to a non-periodic system.  If you instead set it to `CutoffPeriodic` or `PME`, you'll get a periodic system.

**Comment by snyga** [comment]
Thank you very much, that solved my problem.
