### ISSUE TITLE
I get an error in OpenMM 7.7 when I use "updateParametersInContext" after Nonbonded force modified. 

### ISSUE THREAD

**Issue by Bio-Otto** [openmm/openmm#3471]
The script that I use is below.

```python
 # --------------------------------------------- NOBONDED FORCE ----------------------------------------------- #
        if simulation.context.getPlatform().getName() in ['OpenCL', 'CUDA']:
            for index in range(Nonbonded_F.getNumParticles()):
                charge, sigma, epsilon = NonBonded_Parameters[index]
                exclude = (index not in by_pass_atoms_index)
                Nonbonded_F.setParticleParameters(index, 0 * charge if exclude else charge, sigma,
                                                  0 * epsilon if exclude else epsilon)

            for index in range(Nonbonded_F.getNumExceptions()):
                exclude = (index not in by_pass_atoms_index)
                particle1, particle2, chargeProd, sigma, epsilon = NonBonded_Exception_Parameters[index]
                Nonbonded_F.setExceptionParameters(index, particle1, particle2,
                                                   0 * chargeProd if exclude else chargeProd,
                                                   sigma, 0 * epsilon if exclude else epsilon)

            Nonbonded_F.updateParametersInContext(simulation.context)
```

And the error that I get is below.

```
Traceback (most recent call last):
  File "/home/bio-otto/anaconda3/envs/mdpertool/lib/python3.9/threading.py", line 973, in _bootstrap_inner
    self.run()
  File "/home/bio-otto/anaconda3/envs/mdpertool/lib/python3.9/threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
  File "/home/bio-otto/Desktop/MDPerTool_GUI/mdpertool/src/omm_runner.py", line 144, in run_openmm_script
    exec(code, {'__queue': queue, '__queue_reporter_factory': queue_reporter_factory})
  File "<string>", line 424, in <module>
  File "/home/bio-otto/Desktop/MDPerTool_GUI/mdpertool/no_gui/energy_decomposition_from_trajectory.py", line 278, in residue_based_decomposition
    Nonbonded_F.updateParametersInContext(simulation.context)
  File "/home/bio-otto/anaconda3/envs/mdpertool/lib/python3.9/site-packages/openmm/openmm.py", line 10802, in updateParametersInContext
    return _openmm.NonbondedForce_updateParametersInContext(self, context)
openmm.OpenMMException: updateParametersInContext: The set of non-excluded exceptions has changed
```

**Comment by Bio-Otto** [comment]
Thank you for your quick response @peastman . Actually, it was working well like this with OpenMM 7.5. I thought there might be another reason for this.  Have you made any changes regarding this issue in the latest release?

**Comment by Bio-Otto** [comment]
It's good to know that. Thank you for clarifying.
