### ISSUE TITLE
CUDA_ERROR_ILLEGAL_ADRESS (700) with CustomNonbondedForce

### ISSUE THREAD

**Issue by kolotinsky1998** [openmm/openmm#3511]
Hi dear community!

I use `mm.CustomNonbondedForce` class object for defining interactions between particles in a simulation. When the simulation is launched for  2^19  particles or more on NVIDIA TESLA A100 80 GB NVLink I get the Cuda error message "CUDA_ERROR_ILLEGAL_ADRESS (700)". OpenMM version 7.7.0 is installed via Conda with cudatoolkit version 11.4. Custom Integrator is used. 

Searching through issues I have found #3414 with the similar problem and #3428 with some correcting commit. Is I understand correctly that  #3428 fixes the problem I have faced and the updated version will be available in the next OpenMM release ?

Sincerely,
Daniil Kolotinskii

**Comment by peastman** [comment]
Hopefully.  Try installing the latest nightly build and see if it works.

```
conda install -c omnia-dev openmm 
```

(Nightly builds should not be used for production work, since they may contain bugs.  This is just to confirm whether this particular problem is fixed.)

**Comment by kolotinsky1998** [comment]
Unfortunately, the same problem:
openmm.OpenMMException: Error synchronizing CUDA context: CUDA_ERROR_ILLEGAL_ADDRESS (700) at /home/conda/build_artifacts/openmm_1646976083845/work/platforms/cuda/src/CudaParallelKernels.cpp:111
terminate called after throwing an instance of 'OpenMM::OpenMMException'
Error deleting array customExternalGlobals: CUDA_ERROR_ILLEGAL_ADDRESS (700)

**Comment by peastman** [comment]
Can you provide a test case to reproduce the problem?

I notice you're parallelizing the simulation across multiple GPUs.  Does it also happen if you only use a single GPU?

**Comment by kolotinsky1998** [comment]
The test openmm program

```
import numpy as np
from numpy import random
import openmm as mm



N = int(2**19)

position = []
velocity = []
for i in range(N):
    x = random.uniform(-10, 10)
    y = random.uniform(-10, 10)
    z = random.uniform(-10, 10)
    position.append((x, y, z))
v_x = np.random.normal(0, 1, N)
v_y = np.random.normal(0, 1, N)
v_z = np.random.normal(0, 1, N)
for i in range(N):
    velocity.append((v_x[i], v_y[i], v_z[i]))
system = mm.System()
ionIonForceLine = "exp(-r)/(r+r_0)"
ionIonForce = mm.CustomNonbondedForce(ionIonForceLine)
ionIonForce.addGlobalParameter("r_0", 0.1)
trapIonForceLine = "-r^2; r = sqrt(x^2+y^2+z^2)"
trapIonForce = mm.CustomExternalForce(trapIonForceLine)
for i in range(N):
    system.addParticle(1)

for i in range(N):
    ionIonForce.addParticle([])
    trapIonForce.addParticle(i, [])


system.addForce(ionIonForce)
system.addForce(trapIonForce)

integrator = mm.CustomIntegrator(1e-10)
integrator.addUpdateContextState()
integrator.addComputePerDof("v", "v+0.5*dt*f/m")
integrator.addComputePerDof("x", "x+dt*v")
integrator.addComputePerDof("v", "v+0.5*dt*f/m")

platform = mm.Platform.getPlatformByName("CUDA")
properties = {'Precision': 'single'}
context = mm.Context(system, integrator, platform, properties)
context.setPositions(position)
context.setVelocities(velocity)

integrator.step(1000)
```

The batch script
``` 
#!/bin/bash
#SBATCH --job-name=opendustPerformanceTest     
#SBATCH --error=errPerformanceTest
#SBATCH --output=outputPerformanceTest
#SBATCH --time=05:00:00            
#SBATCH --ntasks=1                
#SBATCH --nodes=1                  
#SBATCH --gpus=1        
#SBATCH --cpus-per-task=1         
#SBATCH  --constraint="type_e"

touch time.txt


time python test.py 
```

Error I get

```
Traceback (most recent call last):
  File "/home/avtimofeev/opendust/test/BigSystem/test.py", line 50, in <module>
    integrator.step(1000)
  File "/home/avtimofeev/kolotinskii/programs/miniconda3/lib/python3.9/site-packages/openmm/openmm.py", line 6011, in step
    return _openmm.CustomIntegrator_step(self, steps)
openmm.OpenMMException: Error invoking kernel: CUDA_ERROR_ILLEGAL_ADDRESS (700)
terminate called after throwing an instance of 'OpenMM::OpenMMException'
  what():  Error deleting array customNonbondedGlobals: CUDA_ERROR_ILLEGAL_ADDRESS (700)
/var/spool/slurm/d/job512376/slurm_script: line 15: 24944 Aborted                 python test.py
```

**Comment by peastman** [comment]
The error only happens when running with no cutoff on nonbonded interactions.  It comes from roundoff error in the calculation that maps from tile indices to atom block indices:

https://github.com/openmm/openmm/blob/a6cd8c226313161296882e1eb50d5f3aef82e85b/platforms/cuda/src/kernels/nonbonded.cu#L368-L369

It requires performing floating point operations on the integer indices.  When they get too large, there isn't enough precision to do them accurately.  Do you really intend to be running without a cutoff?  With half a million particles, that would be incredibly slow in any case.  Adding this line makes the error go away:

```python
ionIonForce.setNonbondedMethod(mm.CustomNonbondedForce.CutoffNonPeriodic)
```

**Comment by kolotinsky1998** [comment]
Peter, thank you for the answer!

For describing the interactions between particles I use Yukawa potential. In my case, the number of particles, interactions between which can not be truncated, may reach from several hundred to one million of atoms due to large particle density. In my calculations, I use `CutoffNonPeriodic` option when the volume of the system is big and the number of "non-interacted" particles is large enough. Otherwise, for small volume system with high number of particles I carry out simulation without cutoff distance, because I have noticed that using `CutoffNonPeriodic` significantly reduce the speedup for multi GPU simulations. 

Anyway, I have realised that the test example presented in my previous message not completely demonstrates the problem.  I use `CustomIntegrator` for simulations. With custom integrator I change some particle coordinate positions to uniform random values. I that causes another CUDA error. That can be demonstrated with the example from my previous message if on adds the string `integrator.addComputePerDof("x","uniform")` to it. This causes the following error:

```
Traceback (most recent call last):
  File "/home/avtimofeev/opendust/test/BigSystem/test.py", line 53, in <module>
    integrator.step(1000)
  File "/home/avtimofeev/kolotinskii/programs/miniconda3/lib/python3.9/site-packages/openmm/openmm.py", line 6011, in step
    return _openmm.CustomIntegrator_step(self, steps)
openmm.OpenMMException: Error creating array interactingAtoms: CUDA_ERROR_OUT_OF_MEMORY (2)
```

**Comment by peastman** [comment]
If you move all the atoms to random positions, that will produce massive forces and the simulation will instantly blow up.

**Comment by kolotinsky1998** [comment]
In the simulation I use this 
```
integrator.addComputePerDof(
            "x",
            "select(_x(ions_to_sides),x_axis*R*sqrt(_x(uniform))*cos(2*pi*_y(uniform))+y_axis*R*sqrt(_x(uniform))*sin(2*pi*_y(uniform))+z_axis*(-H/2), x)",)
```

**Comment by peastman** [comment]
Even moving just a few atoms could easily cause the simulation to blow up.  All that's necessary is that the force on a single atom becomes larger than what you can stably integrate.  What happens if you remove that step to randomize positions (and also use a cutoff)?

**Comment by kolotinsky1998** [comment]
For the interaction potential I use Debye potential
<img src="https://latex.codecogs.com/svg.latex?\Large&space;\varphi=\frac{1}{r}\exp{(-\frac{r}{r_{De}}\)}" title="Debye" />
The inherent singularity of this potential at short distance is avoided by softening the potential
<img src="https://latex.codecogs.com/svg.latex?\Large&space;\varphi=\frac{1}{r+r_0}\exp{(-\frac{r}{r_{De}}\)}" title="Debye" />

That approach allows to prevent force on a single atom becoming larger than what I can stably integrate for any position of moved atom. 

I have found out that the randomisation step somehow force CUDA to print error message but not a direct reason for it. Without randomisation step  there is overflowing in some arrays but error message is not printed. The problem removes only for very small (for my task) values of cutoff distance.
