### ISSUE TITLE
AddMembrane() fails

### ISSUE THREAD

**Issue by jacopomoi** [openmm/openmm#3584]
I'm doing simulation of membrane protein with amber14-all.
All of my proteins are correctly oriented from OPM.
When i call the Modeller.addMembrane() method, sometimes it works and sometimes it fails. Most of the time fails with this error: 
```
Loading... V795I.pdb
Done
<Topology; 3 chains, 1111 residues, 18063 atoms, 18278 bonds>
Traceback (most recent call last):
  File "/g100/home/userexternal/jmoi0000/FGMD-noTm/FGMD_func.py", line 380, in <module>
    run(sys.argv[1],int(sys.argv[2]))
  File "/g100/home/userexternal/jmoi0000/FGMD-noTm/FGMD_func.py", line 114, in run
    model.addMembrane(forcefield, lipidType="POPC",minimumPadding=1*un.nanometer,ionicStrength=0.15*un.molar,neutralize=True,positiveIon='Na+')
  File "/g100/home/userexternal/jmoi0000/miniconda3/lib/python3.9/site-packages/openmm/app/modeller.py", line 1490, in addMembrane
    modeller.addSolvent(forcefield, neutralize=False)
  File "/g100/home/userexternal/jmoi0000/miniconda3/lib/python3.9/site-packages/openmm/app/modeller.py", line 524, in addSolvent
    cells = _CellList(positions, maxCutoff, vectors, True)
  File "/g100/home/userexternal/jmoi0000/miniconda3/lib/python3.9/site-packages/openmm/app/modeller.py", line 1572, in __init__
    pos = pos - floor(pos[2]*invBox[2])*vectors[2]
ValueError: cannot convert float NaN to integer
```

Any hints on what could be missing or wrong? Thanks!

**Comment by jacopomoi** [comment]
I think it's related to the unitCellDimension. I've changed it to more larger values and now it seem to work.

**Comment by peastman** [comment]
I'm not sure exactly.  To insert the protein into the membrane, it runs dynamics to let the membrane relax around it.  I think that dynamics was blowing up.

> I think it's related to the unitCellDimension. I've changed it to more larger values and now it seem to work.

`addMembrane()` doesn't have a `unitCellDimension` option?

**Comment by jacopomoi** [comment]
Yes it hasn't. But  before adding a membrane i've defined Modeller.unitCellDimensions()
Here the code:

```
model.topology.setUnitCellDimensions((12,12,12))
model.addMembrane(forcefield,lipidType="POPC",minimumPadding=1*
[wtm.zip](https://github.com/openmm/openmm/files/8571228/wtm.zip)
nanometer,ionicStrength=0.15*un.molar,neutralize=True,positiveIon='Na+')
```

I attached the file if you want to try this function on it.

**Comment by jacopomoi** [comment]
[wtm.zip](https://github.com/openmm/openmm/files/8571231/wtm.zip)

**Comment by thepoole** [comment]
From the code..
`        proteinPos = self.positions.value_in_unit(nanometer)
        proteinMinPos = Vec3(*[min((p[i] for p in proteinPos)) for i in range(3)])
        proteinMaxPos = Vec3(*[max((p[i] for p in proteinPos)) for i in range(3)])
        proteinSize = proteinMaxPos-proteinMinPos
        proteinCenterPos = (proteinMinPos+proteinMaxPos)/2
        proteinCenterPos = Vec3(proteinCenterPos[0], proteinCenterPos[1], membraneCenterZ)
        patchPos = patch.positions.value_in_unit(nanometer)
        patchSize = patch.topology.getUnitCellDimensions().value_in_unit(nanometer)
        patchMinPos = Vec3(*[min((p[i] for p in patchPos)) for i in range(3)])
        patchMaxPos = Vec3(*[max((p[i] for p in patchPos)) for i in range(3)])
        patchCenterPos = (patchMinPos+patchMaxPos)/2
        nx = int(ceil((proteinSize[0]+2*minimumPadding)/patchSize[0]))
        ny = int(ceil((proteinSize[1]+2*minimumPadding)/patchSize[1]))
`

So if the UnitCellDimensions are not defined is the patch size zero? It might be better to define patch sizes by another method or allow users to specify?

**Comment by peastman** [comment]
The patch size isn't something you can set.  That variable is the size of the pre-equilibrated patch it tiles to build the membrane.  It is what it is.  To get a different patch size, you would need to provide your own membrane patch for it to tile.

**Comment by thepoole** [comment]
Yes, the unitcell parameters seems to create a buffer zone around the protein or something.. it’s not super clear but I am just tired from teaching and debugging the examples for my class where I am using openmm as a teaching tool. It is especially vexing because I am using two homologous proteins (GPCRs) with the same alignment, and for one addMembrane works while the other does not. Whats just clear is this method lacks robustness and doesn’t produce information enough on failure conditions in a way that enable the user to investigate their cause so it cannot be used as widely as desired.

**Comment by peastman** [comment]
Can you open a new issue and describe exactly what problem you're experiencing?  Show what you're doing (preferably with all input files needed to reproduce it), what you expect to happen, and what happens instead.

**Comment by ndnng** [comment]
@jacopomoi do you have a paper coming out or codes? I'm interested to see how simulate membrane proteins in openmm. I can email via ndtrvlmind@gmail.com

**Comment by b-rousse** [comment]
Was there any resolution to this issue? I'm encountering similar issues for proteins with long molecular axes.
