### ISSUE TITLE
How do I disable the pme stream to prevent 'Error invoking kernel: CUDA_ERROR_ILLEGAL_ADDRESS (700)'

### ISSUE THREAD

**Issue by Maxim-93** [openmm/openmm#3589]
know you solved this issue several years ago, but I'm unsure how to actually implement it within the submission python script. Could you perhaps provide an example of how this ought to look?

Initial solution:
"Disabling the PME stream actually does eliminate the problem.  I hadn't noticed the script was creating two different Contexts, so I had to modify both of them.  I still don't know what the cause is, but if you need a workaround, just add the following as a fourth argument to the Context constructor: `{'DisablePmeStream':'true'}`."

_Originally posted by @peastman in https://github.com/openmm/openmm/issues/1728#issuecomment-279820605_

**Comment by Maxim-93** [comment]
Switching the integrator from MTS to Langevin solves the issue, however I'd prefer not to use that particular integrator in this case...

**Comment by peastman** [comment]
Change this line:

```python
simulation = Simulation(pdb.topology, sys, integrator,platform)
```

to this:

```python
simulation = Simulation(pdb.topology, sys, integrator, platform, {'DisablePmeStream':'true'})
```

**Comment by Maxim-93** [comment]
Thanks! That's fixed it however I'm now running into a new issue where:

'''
Traceback (most recent call last):
  File "eq-v5-2.py", line 68, in <module>
    simulation.step(1000000)
  File "/grid/it/data/elzar/easybuild/software/OpenMM/7.5.1-fosscuda-2020b/lib/python3.8/site-packages/simtk/openmm/app/simulation.py", line 132, in step
    self._simulate(endStep=self.currentStep+steps)
  File "/grid/it/data/elzar/easybuild/software/OpenMM/7.5.1-fosscuda-2020b/lib/python3.8/site-packages/simtk/openmm/app/simulation.py", line 234, in _simulate
    self._generate_reports(wrapped, True)
  File "/grid/it/data/elzar/easybuild/software/OpenMM/7.5.1-fosscuda-2020b/lib/python3.8/site-packages/simtk/openmm/app/simulation.py", line 256, in _generate_reports
    reporter.report(self, state)
  File "/grid/it/data/elzar/easybuild/software/OpenMM/7.5.1-fosscuda-2020b/lib/python3.8/site-packages/simtk/openmm/app/pdbreporter.py", line 99, in report
    PDBFile.writeModel(simulation.topology, state.getPositions(), self._out, self._nextModel)
  File "/grid/it/data/elzar/easybuild/software/OpenMM/7.5.1-fosscuda-2020b/lib/python3.8/site-packages/simtk/openmm/app/pdbfile.py", line 380, in writeModel
    recordName, atomIndex%100000, atomName, resName, chainName, resId, resIC, _format_83(coords[0]),
  File "/grid/it/data/elzar/easybuild/software/OpenMM/7.5.1-fosscuda-2020b/lib/python3.8/site-packages/simtk/openmm/app/pdbfile.py", line 463, in _format_83
    raise ValueError('coordinate "%s" could not be represented '
ValueError: coordinate "-112374104.69244537" could not be represented in a width-8 field
'''

This error occurred after 1370 ps, which is pretty weird for a simulation to be inexplicably blowing up at that point. At least that's what it looks like given the error. Despite that- after restarting from a checkpoint file, the simulation can continue smoothly. This suggests to me that it's got something to do with the how the calculation is being processed on the GPU maybe? 

What do you reckon?

**Comment by peastman** [comment]
See [this FAQ entry](https://github.com/openmm/openmm/wiki/Frequently-Asked-Questions#nan) for advice on debugging simulations blowing up.  Here are a few things that occur to me from looking at your script.

- Is there a reason you're using AndersenThermostat plus MTSIntegrator rather than MTSLangevinIntegrator?  The latter tends to be slightly more stable.
- Try adding a bit of hydrogen mass repartitioning.  That can sometime improve stability.  Add the argument `hydrogenMass=1.5*amu` to the call to `createSystem()`.
- The way you're running the simulation, it isn't deterministic.  If you ask it to compute forces several times for the same conformation, they'll be slightly different (just in the last few bits) each time.  That explains why it blew up once, but didn't when you restarted from a checkpoint.  You can force it to be deterministic by adding `'DeterministicForces':'true'` to the dict of properties you pass to the Simulation constructor.  It will make the simulation run very slightly slower, but it could be helpful in debugging.

**Comment by Maxim-93** [comment]
OK, thank's so much for that! I'll give it a go now.

**Comment by yongyouhe** [comment]
I encountered the same issue when I used the MTSLangevin integrator to simulate a large system. The OpenMM version is 7.7.0, GPU is RTX 4090, nvcc is 11.8. The issue was solved after I disabled the PME stream.
However, I can run the simulation successfully on an RTX 2070 with nvcc 10.2 (OpenMM 7.7.0).  
I would like know how the PME stream causes the issue.

**Comment by peastman** [comment]
Could you test with the latest release (8.1.1)?  If it still has the problem, open a new issue and attach all the files needed to reproduce it.

**Comment by yongyouhe** [comment]
> Could you test with the latest release (8.1.1)? If it still has the problem, open a new issue and attach all the files needed to reproduce it.

I have tested this with the OpenMM 8.1.1. The 

> Could you test with the latest release (8.1.1)? If it still has the problem, open a new issue and attach all the files needed to reproduce it.

I have tested with OpenMM 8.1.1 (cuda 11.8) on RTX 3090, the error became "openmm.OpenMMException: Particle coordinate is NaN" instead of "CUDA_ERROR_ILLEGAL_ADDRESS (700)". However, the simulation ran successfully with double precision. 
I also tested with OpenMM 7.7.0 (cuda 10.2) on the same GPU with mixed precision, and the simulation ran successfully. 
I guess there may be some incompatibility issues with CUDA when simulating with AMOEBA force field. 
If necessary, I will open a new issue after some time.
