### ISSUE TITLE
Multiple non-identical matching templates with GLYCAM

### ISSUE THREAD

**Issue by rosemary-cresset** [openmm/openmm#3651]
Running this snippet on 1AGM from the PDB: 
```
pdb_file = app.PDBFile('input.pdb')
force_field = app.ForceField('amber/protein.ff14SB.xml', 'amber/GLYCAM_06j-1.xml')
unmatched_residues = force_field.getUnmatchedResidues(pdb_file.topology)
```
I get the following error: 
```
Traceback (most recent call last):
  File "/tmp/FieldEngine-rosemary/OpenMM_Force_Fields_25350_1/test.py", line 6, in <module>
    unmatched_residues = force_field.getUnmatchedResidues(pdb_file.topology)
  File "/home/rosemary/.conan/data/OpenMM/7.7.0/cresset/stable/package/a023319b593d272450ee34ad9f9daf11b47e98c4/python/openmm/app/forcefield.py", line 1060, in getUnmatchedResidues
    [template, matches] = self._getResidueTemplateMatches(res, bondedToAtom)
  File "/home/rosemary/.conan/data/OpenMM/7.7.0/cresset/stable/package/a023319b593d272450ee34ad9f9daf11b47e98c4/python/openmm/app/forcefield.py", line 1011, in _getResidueTemplateMatches
    raise Exception('Multiple non-identical matching templates found for residue %d (%s): %s.' % (res.index+1, res.name, ', '.join(match[0].name for match in allMatches)))
Exception: Multiple non-identical matching templates found for residue 471 (MAN): 0EA, 0EB, 0GA, 0GB, 0KA, 0KB, 0LA, 0LB, 0MA, 0MB, 0NA, 0NB, 0TA, 0TB, 0eA, 0eB, 0gA, 0gB, 0kA, 0kB, 0lA, 0lB, 0mA, 0mB, 0nA, 0nB, 0tA, 0tB.
```

Does this look like a bug to you or is there something I'm doing wrong? Thank you.

**Comment by peastman** [comment]
See the note about GLYCAM at http://docs.openmm.org/latest/userguide/application/02_running_sims.html#amber14.  It's a kind of strange force field that requires you to follow a particular nonstandard naming convention.  If I recall correctly, that's because it assigns different parameters to molecules that are identical except for chirality.  Since their elements and bonds are identical, they can't be distinguished by matching templates in the usual way.

**Comment by rosemary-cresset** [comment]
Thanks very much for your help!
