### ISSUE TITLE
Failure building openmm from scratch on M1 Mac

### ISSUE THREAD

**Issue by ziyuanzhao2000** [openmm/openmm#3666]
Hi, so I was modifying some code inside the modeller class and then tried to rebuild the whole source code. I've proceeded through the installation and installing Python API steps. But I couldn't pass the test for the Python API. There's this cryptic message:
```
(openmm) XXX@dhcp-10-250-144-93 build % python -m openmm.testInstallation

Traceback (most recent call last):
  File "/Users/XXX/opt/anaconda3/envs/openmm/lib/python3.7/runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/Users/XXX/opt/anaconda3/envs/openmm/lib/python3.7/runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "/Users/XXX/opt/anaconda3/envs/openmm/lib/python3.7/site-packages/openmm/__init__.py", line 24, in <module>
    from openmm.openmm import *
  File "/Users/XXX/opt/anaconda3/envs/openmm/lib/python3.7/site-packages/openmm/openmm.py", line 13, in <module>
    from . import _openmm
ImportError: dlopen(/Users/XXX/opt/anaconda3/envs/openmm/lib/python3.7/site-packages/openmm/_openmm.cpython-37m-darwin.so, 0x0002): symbol not found in flat namespace '__ZTIN6OpenMM10DrudeForceE'
(openmm) XXX@dhcp-10-250-144-93 build % 

```

I'm not sure what caused that "symbol not found in flat namespace," but upon inspecting the source code I suspect it has to do with importing the low level C/C++ libraries into python. I appreciate any help or suggestion to resolve this problem. Thanks!

**Comment by peastman** [comment]
Can you describe the exact steps you went through to build, including setting up your Python environment, configuring CMake, etc.?  I have no trouble building on a M1.  Something is clearly different in your environment.  It's hard to guess what.

Also try executing this command:

```
otool -L /Users/XXX/opt/anaconda3/envs/openmm/lib/python3.7/site-packages/openmm/_openmm.cpython-37m-darwin.so
```

What is the output?

**Comment by ziyuanzhao2000** [comment]
Hi Peter, thanks for trying to help! I followed the tutorial [here](http://docs.openmm.org/latest/userguide/library/02_compiling.html) on OpenMM website as faithfully as I could, but I will go back and try one more time.

Here's my output with your command:
```
(openmm) ziyuanzhao@dhcp-10-250-144-93 build % otool -L /Users/ziyuanzhao/opt/anaconda3/envs/openmm/lib/python3.7/site-packages/openmm/_openmm.cpython-37m-darwin.so
/Users/ziyuanzhao/opt/anaconda3/envs/openmm/lib/python3.7/site-packages/openmm/_openmm.cpython-37m-darwin.so:
        @rpath/libc++.1.dylib (compatibility version 1.0.0, current version 1.0.0)
        /usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1311.0.0)

```

I hope it provides useful clues for solving my case. Thanks again!

**Comment by ziyuanzhao2000** [comment]
Here's my log from ccmake when initially configuring the makefile:
```
 Found PythonInterp:
 /Users/ziyuanzhao/opt/anaconda3/envs/openmm_latest/bin/python (found version
 "3.10.5")
 The C compiler identification is AppleClang 13.0.0.13000029
 The CXX compiler identification is AppleClang 13.0.0.13000029
 Detecting C compiler ABI info
 Detecting C compiler ABI info - done
 Check for working C compiler: /Library/Developer/CommandLineTools/usr/bin/cc
 - skipped
 Detecting C compile features
 Detecting C compile features - done
 Detecting CXX compiler ABI info
 Detecting CXX compiler ABI info - done
 Check for working CXX compiler:
 /Library/Developer/CommandLineTools/usr/bin/c++ - skipped
 Detecting CXX compile features
 Detecting CXX compile features - done
 CMake Deprecation Warning at CMakeLists.txt:25 (CMAKE_POLICY):
   The OLD behavior for policy CMP0042 will be removed from a future version
   of CMake.

   The cmake-policies(7) manual explains that the OLD behaviors of all
   policies are deprecated and that a policy should be set to OLD only under
   specific short-term circumstances.  Projects should be ported to the NEW
   behavior and not rely on setting a policy to OLD.

 Found Doxygen: /Users/ziyuanzhao/opt/anaconda3/envs/openmm_latest/bin/doxygen
 (found version "1.9.3") found components: doxygen missing components: dot
 CMake Warning (dev) at
 /Users/ziyuanzhao/opt/anaconda3/envs/openmm_latest/share/cmake-3.23/Modules/Fi
 ndPackageHandleStandardArgs.cmake:438 (message):
   The package name passed to `find_package_handle_standard_args` (OPENCL)
   does not match the name of the calling package (OpenCL).  This can lead to
   problems in calling code that expects `find_package` result variables
   (e.g., `_FOUND`) to follow a certain pattern.
 Call Stack (most recent call first):
   cmake_modules/FindOpenCL.cmake:86 (find_package_handle_standard_args)
   CMakeLists.txt:343 (FIND_PACKAGE)
 This warning is for project developers.  Use -Wno-dev to suppress it.
 Found OPENCL:
 /Library/Developer/CommandLineTools/SDKs/MacOSX12.1.sdk/System/Library/Framewo
 rks/OpenCL.framework
 Configuring done
```

**Comment by peastman** [comment]
It's missing all the OpenMM libraries.  Here's what I get running that command on my computer:

```
	@rpath/libOpenMM.7.7.dylib (compatibility version 7.7.0, current version 0.0.0)
	@rpath/libOpenMMAmoeba.dylib (compatibility version 0.0.0, current version 0.0.0)
	@rpath/libOpenMMRPMD.dylib (compatibility version 0.0.0, current version 0.0.0)
	@rpath/libOpenMMDrude.dylib (compatibility version 0.0.0, current version 0.0.0)
	@rpath/libc++.1.dylib (compatibility version 1.0.0, current version 1.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1311.100.3)
```

First let's verify that the libraries got built correctly.  Try running a few test cases from the build directory:

```
./TestReferenceHarmonicBondForce
./TestReferenceDrudeForce
```

Do they run correctly?

If that's ok, try rebuilding and reinstalling the Python module from scratch.  Inside the build directory type these commands:

```
rm -rf wrappers
rm -rf python
make install
make PythonInstall
```

Does that fix the problem?  Do any errors get reported?

**Comment by ziyuanzhao2000** [comment]
Dear Peter,

I apologize for my very late reply! Has been traveling but was finally back at work. I'm currently trying again to install the suite, and I will let you know what result I get this time. Hopefully, the problem will go away.
