### ISSUE TITLE
"Particle coordinate is nan" during minimization, 

### ISSUE THREAD

**Issue by razvanmarinescu** [openmm/openmm#3713]
I have a dimer system with ~4600 atoms, in implicit solvent (GBn2), running with CHARMM 3.6m force field. I get the following error when I try to minimize it (before equilibration and MD steps): 

```
Traceback (most recent call last):
  File "/home/bizon/research/md/hbv/2g33_AB_GB/run_md.py", line 62, in <module>
    simulation.minimizeEnergy()#tolerance=10*kilojoule/mole)
  File "/home/bizon/anaconda3/envs/westpa-dev/lib/python3.10/site-packages/openmm/app/simulation.py", line 137, in minimizeEnergy
    mm.LocalEnergyMinimizer.minimize(self.context, tolerance, maxIterations)
  File "/home/bizon/anaconda3/envs/westpa-dev/lib/python3.10/site-packages/openmm/openmm.py", line 11150, in minimize
    return _openmm.LocalEnergyMinimizer_minimize(context, tolerance, maxIterations)
openmm.OpenMMException: Particle coordinate is nan
```

I read the [FAQ](https://github.com/openmm/openmm/wiki/Frequently-Asked-Questions#nan) here, and followed the recommendations: 
1) I lowered the integration step to 1fs 
2) removed all constraints (to ensure no clashing)
3) periodic boundary conditions are not relevant, as I'm doing Generalized Born solvent

but this didn't help at all. Any ideas how to fix it? Here's my code

```
pdb = PDBFile('psfgen_out.pdb')
psf = CharmmPsfFile('psfgen_out.psf')
params = CharmmParameterSet('toppar_c36_jul21/top_all36_prot.rtf', 'toppar_c36_jul21/par_all36m_prot.prm')

dt = 0.001*picoseconds
constraints = None
hydrogenMass = 1.5*amu


system = psf.createSystem(params, nonbondedMethod=CutoffNonPeriodic, nonbondedCutoff=2*nanometer, constraints=constraints, implicitSolvent=GBn2)

integrator = LangevinMiddleIntegrator(300*kelvin, 1/picosecond, dt)

platform = Platform.getPlatformByName('CUDA')
properties = {'DeviceIndex': '%s' % 1} # implicit solvent doesn't support more than 1 GPU
simulation = Simulation(psf.topology, system, integrator, platform, properties)
simulation.context.setPositions(pdb.positions)

# run minimization

simulation.minimizeEnergy()
```

Attaching a zip with a minimal system and code, reproducing the error.

Thanks!

[2g33_AB_GB.zip](https://github.com/openmm/openmm/files/9187045/2g33_AB_GB.zip)

**Comment by razvanmarinescu** [comment]
Never mind, I just realized it was due to a mistake in how I built the system. It works now
