### ISSUE TITLE
unrecognized atom types in CHARMM file

### ISSUE THREAD

**Issue by OkKakao** [openmm/openmm#3785]
Hi

I'm trying CB7 smulation with CHARMM input files.

I got CHARMM parameter files, but it was not recognized by openmm.

The following error was occured.

```
Traceback (most recent call last):
  File "/home/compu/anaconda3/envs/openmmvenv/lib/python3.7/site-packages/openmm/app/charmmpsffile.py", line 621, in loadParameters
    atype = parmset.atom_types_str[atom.attype]
KeyError: 'CG3RC1'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/compu/temp/droplet/droplet_generator_CHARMM.py", line 22, in <module>
    system = psf.createSystem(params, nonbondedMethod=NoCutoff, nonbondedCutoff=2*nanometer, constraints=HBonds)
  File "/home/compu/anaconda3/envs/openmmvenv/lib/python3.7/site-packages/openmm/app/charmmpsffile.py", line 876, in createSystem
    self.loadParameters(params)
  File "/home/compu/anaconda3/envs/openmmvenv/lib/python3.7/site-packages/openmm/app/charmmpsffile.py", line 624, in loadParameters
    atom.attype)
openmm.app.internal.charmm.exceptions.MissingParameter: Could not find atom type for CG3RC1
```

How can I operate with those files?

The following is my and the files.

```
from openmm.app import *
from openmm import *
from openmm.unit import *
from sys import stdout

forcefield = ForceField('amber14/tip3p.xml')

name = '../parameters/cb7'

params = CharmmParameterSet('../parameters/cb1.str')
psf = CharmmPsfFile('../parameters/cb7.psf')
pdb = PDBFile(f'{name}.pdb')

platform = Platform.getPlatformByName('CUDA')
system = psf.createSystem(params, nonbondedMethod=NoCutoff, nonbondedCutoff=2*nanometer, constraints=HBonds)
integrator = LangevinMiddleIntegrator(300*kelvin, 1/picosecond, 0.004*picoseconds)
simulation = Simulation(psf.topology, system, integrator, platform)
simulation.context.setPositions(pdb.positions)
simulation.minimizeEnergy()
simulation.reporters.append(PDBReporter(f'CB7_1.pdb', 10000))
simulation.reporters.append(StateDataReporter(stdout, 1000, step=True, potentialEnergy=True, temperature=True))

simulation.step(10000)
```
[Desktop.zip](https://github.com/openmm/openmm/files/9598521/Desktop.zip)

**Comment by peastman** [comment]
That means the CharmmParameterSet is missing the file in which that atom type is defined.  I believe it's a CGenFF type, which would be defined in the file `par_all36_cgenff.prm`.  CHARMM tends to define parameters in a modular way, where you end up combining several files to get the parameters you need for a simulation.

**Comment by OkKakao** [comment]
Is this the file that you've mentioned?

[https://charmm-gui.org/?doc=open_toppar&filename=par_all36_cgenff.prm](url)

I searched it on the browser but i'm not sure that this one is right or not

**Comment by OkKakao** [comment]
That was the right file.
Thanks!
