### ISSUE TITLE
`conda env create mmh/openmm-8-beta-linux` yields segfaults when running ` pytest github/openmm-ml/test/TestMLPotential.py`

### ISSUE THREAD

**Issue by dominicrufa** [openmm/openmm#3845]
@peastman @jchodera , I am having trouble simply running energy tests in `openmm-ml` on GPU with the above `conda` installation.
Is there a known procedure to build `openmm8` (via `conda install -c conda-forge/label/openmm_rc -c conda-forge openmm`) with the necessary dependencies to run this test?

The segfault is 
```
(openmm-8-beta-linux) pytest TestMLPotential.py
============================================================================================================ test session starts ============================================================================================================
platform linux -- Python 3.10.6, pytest-7.2.0, pluggy-1.0.0
rootdir: /lila/home/rufad/github/openmm-ml
collected 8 items

TestMLPotential.py FFatal Python error: Segmentation fault

Current thread 0x00002ae014942f00 (most recent call first):
  File "<frozen importlib._bootstrap>", line 241 in _call_with_frames_removed
  File "<frozen importlib._bootstrap_external>", line 1176 in create_module
  File "<frozen importlib._bootstrap>", line 571 in module_from_spec
  File "<frozen importlib._bootstrap>", line 674 in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1006 in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1027 in _find_and_load
  File "<frozen importlib._bootstrap>", line 241 in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1078 in _handle_fromlist
  File "/home/rufad/miniconda3/envs/openmm-8-beta-linux/lib/python3.10/site-packages/torchani/aev.py", line 14 in <module>
  File "<frozen importlib._bootstrap>", line 241 in _call_with_frames_removed
  File "<frozen importlib._bootstrap_external>", line 883 in exec_module
  File "<frozen importlib._bootstrap>", line 688 in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1006 in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1027 in _find_and_load
  File "/home/rufad/miniconda3/envs/openmm-8-beta-linux/lib/python3.10/site-packages/torchani/__init__.py", line 34 in <module>
  File "<frozen importlib._bootstrap>", line 241 in _call_with_frames_removed
  File "<frozen importlib._bootstrap_external>", line 883 in exec_module
  File "<frozen importlib._bootstrap>", line 688 in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1006 in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1027 in _find_and_load
  File "/home/rufad/miniconda3/envs/openmm-8-beta-linux/lib/python3.10/site-packages/openmmml/models/anipotential.py", line 71 in addForces
  File "/home/rufad/miniconda3/envs/openmm-8-beta-linux/lib/python3.10/site-packages/openmmml/mlpotential.py", line 267 in createMixedSystem
  File "/lila/home/rufad/github/openmm-ml/test/TestMLPotential.py", line 21 in testCreateMixedSystem
  File "/home/rufad/miniconda3/envs/openmm-8-beta-linux/lib/python3.10/site-packages/_pytest/python.py", line 195 in pytest_pyfunc_call
  File "/home/rufad/miniconda3/envs/openmm-8-beta-linux/lib/python3.10/site-packages/pluggy/_callers.py", line 39 in _multicall
  File "/home/rufad/miniconda3/envs/openmm-8-beta-linux/lib/python3.10/site-packages/pluggy/_manager.py", line 80 in _hookexec
  File "/home/rufad/miniconda3/envs/openmm-8-beta-linux/lib/python3.10/site-packages/pluggy/_hooks.py", line 265 in __call__
  File "/home/rufad/miniconda3/envs/openmm-8-beta-linux/lib/python3.10/site-packages/_pytest/python.py", line 1789 in runtest
  File "/home/rufad/miniconda3/envs/openmm-8-beta-linux/lib/python3.10/site-packages/_pytest/runner.py", line 167 in pytest_runtest_call
  File "/home/rufad/miniconda3/envs/openmm-8-beta-linux/lib/python3.10/site-packages/pluggy/_callers.py", line 39 in _multicall
  File "/home/rufad/miniconda3/envs/openmm-8-beta-linux/lib/python3.10/site-packages/pluggy/_manager.py", line 80 in _hookexec
  File "/home/rufad/miniconda3/envs/openmm-8-beta-linux/lib/python3.10/site-packages/pluggy/_hooks.py", line 265 in __call__
  File "/home/rufad/miniconda3/envs/openmm-8-beta-linux/lib/python3.10/site-packages/_pytest/runner.py", line 260 in <lambda>
  File "/home/rufad/miniconda3/envs/openmm-8-beta-linux/lib/python3.10/site-packages/_pytest/runner.py", line 339 in from_call
  File "/home/rufad/miniconda3/envs/openmm-8-beta-linux/lib/python3.10/site-packages/_pytest/runner.py", line 259 in call_runtest_hook
  File "/home/rufad/miniconda3/envs/openmm-8-beta-linux/lib/python3.10/site-packages/_pytest/runner.py", line 220 in call_and_report
  File "/home/rufad/miniconda3/envs/openmm-8-beta-linux/lib/python3.10/site-packages/_pytest/runner.py", line 131 in runtestprotocol
  File "/home/rufad/miniconda3/envs/openmm-8-beta-linux/lib/python3.10/site-packages/_pytest/runner.py", line 112 in pytest_runtest_protocol
  File "/home/rufad/miniconda3/envs/openmm-8-beta-linux/lib/python3.10/site-packages/pluggy/_callers.py", line 39 in _multicall
  File "/home/rufad/miniconda3/envs/openmm-8-beta-linux/lib/python3.10/site-packages/pluggy/_manager.py", line 80 in _hookexec
  File "/home/rufad/miniconda3/envs/openmm-8-beta-linux/lib/python3.10/site-packages/pluggy/_hooks.py", line 265 in __call__
  File "/home/rufad/miniconda3/envs/openmm-8-beta-linux/lib/python3.10/site-packages/_pytest/main.py", line 349 in pytest_runtestloop
  File "/home/rufad/miniconda3/envs/openmm-8-beta-linux/lib/python3.10/site-packages/pluggy/_callers.py", line 39 in _multicall
  File "/home/rufad/miniconda3/envs/openmm-8-beta-linux/lib/python3.10/site-packages/pluggy/_manager.py", line 80 in _hookexec
  File "/home/rufad/miniconda3/envs/openmm-8-beta-linux/lib/python3.10/site-packages/pluggy/_hooks.py", line 265 in __call__
  File "/home/rufad/miniconda3/envs/openmm-8-beta-linux/lib/python3.10/site-packages/_pytest/main.py", line 324 in _main
  File "/home/rufad/miniconda3/envs/openmm-8-beta-linux/lib/python3.10/site-packages/_pytest/main.py", line 270 in wrap_session
  File "/home/rufad/miniconda3/envs/openmm-8-beta-linux/lib/python3.10/site-packages/_pytest/main.py", line 317 in pytest_cmdline_main
  File "/home/rufad/miniconda3/envs/openmm-8-beta-linux/lib/python3.10/site-packages/pluggy/_callers.py", line 39 in _multicall
  File "/home/rufad/miniconda3/envs/openmm-8-beta-linux/lib/python3.10/site-packages/pluggy/_manager.py", line 80 in _hookexec
  File "/home/rufad/miniconda3/envs/openmm-8-beta-linux/lib/python3.10/site-packages/pluggy/_hooks.py", line 265 in __call__
  File "/home/rufad/miniconda3/envs/openmm-8-beta-linux/lib/python3.10/site-packages/_pytest/config/__init__.py", line 167 in main
  File "/home/rufad/miniconda3/envs/openmm-8-beta-linux/lib/python3.10/site-packages/_pytest/config/__init__.py", line 190 in console_main
  File "/home/rufad/miniconda3/envs/openmm-8-beta-linux/bin/pytest", line 10 in <module>

Extension modules: openmm._openmm, numpy.core._multiarray_umath, numpy.core._multiarray_tests, numpy.linalg._umath_linalg, numpy.fft._pocketfft_internal, numpy.random._common, numpy.random.bit_generator, numpy.random._bounded_integers, numpy.random._mt19937, numpy.random.mtrand, numpy.random._philox, numpy.random._pcg64, numpy.random._sfc64, numpy.random._generator, openmm.app.internal.compiled, torch._C, torch._C._fft, torch._C._linalg, torch._C._nn, torch._C._sparse, torch._C._special (total: 21)
Segmentation fault (core dumped)
```

**Comment by dominicrufa** [comment]
alright, after realizing that I can't run tests with the above conda install, I tried to use `conda install -c conda-forge/label/openmm_rc -c conda-forge openmm` as explained here: https://simtk.org/plugins/phpBB/viewtopicPhpbb.php?f=161&t=15133&p=0&start=0&view=, but with `conda 22.9.0`, conda install fails with:
```
failed

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/home/rufad/miniconda3/lib/python3.9/site-packages/urllib3/connectionpool.py", line 449, in _make_request
        six.raise_from(e, None)
      File "<string>", line 3, in raise_from
      File "/home/rufad/miniconda3/lib/python3.9/site-packages/urllib3/connectionpool.py", line 444, in _make_request
        httplib_response = conn.getresponse()
      File "/home/rufad/miniconda3/lib/python3.9/http/client.py", line 1371, in getresponse
        response.begin()
      File "/home/rufad/miniconda3/lib/python3.9/http/client.py", line 319, in begin
        version, status, reason = self._read_status()
      File "/home/rufad/miniconda3/lib/python3.9/http/client.py", line 280, in _read_status
        line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
      File "/home/rufad/miniconda3/lib/python3.9/socket.py", line 704, in readinto
        return self._sock.recv_into(b)
      File "/home/rufad/miniconda3/lib/python3.9/ssl.py", line 1241, in recv_into
        return self.read(nbytes, buffer)
      File "/home/rufad/miniconda3/lib/python3.9/ssl.py", line 1099, in read
        return self._sslobj.read(len, buffer)
    socket.timeout: The read operation timed out

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/home/rufad/miniconda3/lib/python3.9/site-packages/urllib3/connectionpool.py", line 703, in urlopen
        httplib_response = self._make_request(
      File "/home/rufad/miniconda3/lib/python3.9/site-packages/urllib3/connectionpool.py", line 451, in _make_request
        self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
      File "/home/rufad/miniconda3/lib/python3.9/site-packages/urllib3/connectionpool.py", line 340, in _raise_timeout
        raise ReadTimeoutError(
    urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='conda.anaconda.org', port=443): Read timed out. (read timeout=5)

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/home/rufad/miniconda3/lib/python3.9/site-packages/requests/adapters.py", line 489, in send
        resp = conn.urlopen(
      File "/home/rufad/miniconda3/lib/python3.9/site-packages/urllib3/connectionpool.py", line 815, in urlopen
        return self.urlopen(
      File "/home/rufad/miniconda3/lib/python3.9/site-packages/urllib3/connectionpool.py", line 815, in urlopen
        return self.urlopen(
      File "/home/rufad/miniconda3/lib/python3.9/site-packages/urllib3/connectionpool.py", line 815, in urlopen
        return self.urlopen(
      File "/home/rufad/miniconda3/lib/python3.9/site-packages/urllib3/connectionpool.py", line 787, in urlopen
        retries = retries.increment(
      File "/home/rufad/miniconda3/lib/python3.9/site-packages/urllib3/util/retry.py", line 592, in increment
        raise MaxRetryError(_pool, url, error or ResponseError(cause))
    urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='conda.anaconda.org', port=443): Max retries exceeded with url: /conda-forge/label/openmm_rc/notices.json (Caused by ReadTimeoutError("HTTPSConnectionPool(host='conda.anaconda.org', port=443): Read timed out. (read timeout=5)"))

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/home/rufad/miniconda3/lib/python3.9/site-packages/conda/exceptions.py", line 1129, in __call__
        return func(*args, **kwargs)
      File "/home/rufad/miniconda3/lib/python3.9/site-packages/conda/cli/main.py", line 86, in main_subshell
        exit_code = do_call(args, p)
      File "/home/rufad/miniconda3/lib/python3.9/site-packages/conda/cli/conda_argparse.py", line 93, in do_call
        return getattr(module, func_name)(args, parser)
      File "/home/rufad/miniconda3/lib/python3.9/site-packages/conda/notices/core.py", line 75, in wrapper
        display_notices(
      File "/home/rufad/miniconda3/lib/python3.9/site-packages/conda/notices/core.py", line 39, in display_notices
        channel_notice_responses = http.get_notice_responses(channel_name_urls, silent=silent)
      File "/home/rufad/miniconda3/lib/python3.9/site-packages/conda/notices/http.py", line 36, in get_notice_responses
        return tuple(
      File "/home/rufad/miniconda3/lib/python3.9/site-packages/conda/notices/http.py", line 39, in <genexpr>
        (
      File "/home/rufad/miniconda3/lib/python3.9/concurrent/futures/_base.py", line 608, in result_iterator
        yield fs.pop().result()
      File "/home/rufad/miniconda3/lib/python3.9/concurrent/futures/_base.py", line 445, in result
        return self.__get_result()
      File "/home/rufad/miniconda3/lib/python3.9/concurrent/futures/_base.py", line 390, in __get_result
        raise self._exception
      File "/home/rufad/miniconda3/lib/python3.9/concurrent/futures/thread.py", line 52, in run
        result = self.fn(*self.args, **self.kwargs)
      File "/home/rufad/miniconda3/lib/python3.9/site-packages/conda/notices/http.py", line 42, in <lambda>
        lambda args: get_channel_notice_response(*args), url_and_names
      File "/home/rufad/miniconda3/lib/python3.9/site-packages/conda/notices/cache.py", line 37, in wrapper
        return_value = func(url, name)
      File "/home/rufad/miniconda3/lib/python3.9/site-packages/conda/notices/http.py", line 58, in get_channel_notice_response
        resp = session.get(url, allow_redirects=False, timeout=5)  # timeout: connect, read
      File "/home/rufad/miniconda3/lib/python3.9/site-packages/requests/sessions.py", line 600, in get
        return self.request("GET", url, **kwargs)
      File "/home/rufad/miniconda3/lib/python3.9/site-packages/requests/sessions.py", line 587, in request
        resp = self.send(prep, **send_kwargs)
      File "/home/rufad/miniconda3/lib/python3.9/site-packages/requests/sessions.py", line 701, in send
        r = adapter.send(request, **kwargs)
      File "/home/rufad/miniconda3/lib/python3.9/site-packages/requests/adapters.py", line 565, in send
        raise ConnectionError(e, request=request)
    requests.exceptions.ConnectionError: HTTPSConnectionPool(host='conda.anaconda.org', port=443): Max retries exceeded with url: /conda-forge/label/openmm_rc/notices.json (Caused by ReadTimeoutError("HTTPSConnectionPool(host='conda.anaconda.org', port=443): Read timed out. (read timeout=5)"))

`$ /home/rufad/miniconda3/bin/conda install -c conda-forge/label/openmm_rc -c conda-forge openmm`

  environment variables:
                 CIO_TEST=<not set>
        CONDA_DEFAULT_ENV=openmm-8
                CONDA_EXE=/home/rufad/miniconda3/bin/conda
             CONDA_PREFIX=/home/rufad/miniconda3/envs/openmm-8
           CONDA_PREFIX_1=/home/rufad/miniconda3
          CONDA_PREFIX_10=/home/rufad/miniconda3/envs/openmm-8
          CONDA_PREFIX_11=/home/rufad/miniconda3
           CONDA_PREFIX_2=/home/rufad/miniconda3/envs/perses
           CONDA_PREFIX_3=/home/rufad/miniconda3/envs/aludel
           CONDA_PREFIX_4=/home/rufad/miniconda3/envs/openmm-8-beta-linux
           CONDA_PREFIX_5=/home/rufad/miniconda3
           CONDA_PREFIX_6=/home/rufad/miniconda3/envs/openmm-8-beta-linux
           CONDA_PREFIX_7=/home/rufad/miniconda3
           CONDA_PREFIX_8=/home/rufad/miniconda3/envs/openmm-8-beta-linux
           CONDA_PREFIX_9=/home/rufad/miniconda3
    CONDA_PROMPT_MODIFIER=(openmm-8)
         CONDA_PYTHON_EXE=/home/rufad/miniconda3/bin/python
               CONDA_ROOT=/home/rufad/miniconda3
              CONDA_SHLVL=12
           CURL_CA_BUNDLE=<not set>
          LD_LIBRARY_PATH=/usr/local/cuda-11.3/lib64:/usr/local/cuda-11.3/lib:/usr/local/cuda-11
                          .3/targets/x86_64-linux/lib/:/admin/lsflilac/lsf/10.1/linux3.10-glibc2
                          .17-x86_64/lib
                  MANPATH=/admin/lsflilac/lsf/10.1/man:
               MODULEPATH=/usr/share/Modules/modulefiles:/etc/modulefiles:/opt/common/modulefile
                          s
                     PATH=/usr/local/cuda-11.3/bin:/admin/lsflilac/lsf/10.1/linux3.10-glibc2.17-
                          x86_64/bin:/home/rufad/miniconda3/envs/openmm-8/bin:/home/rufad/minico
                          nda3/condabin:/admin/lsflilac/lsf/10.1/linux3.10-glibc2.17-x86_64/etc:
                          /usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/usr/lpp/mmfs/bin:/o
                          pt/puppetlabs/bin
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>

     active environment : openmm-8
    active env location : /home/rufad/miniconda3/envs/openmm-8
            shell level : 12
       user config file : /home/rufad/.condarc
 populated config files : /home/rufad/.condarc
          conda version : 22.9.0
    conda-build version : not installed
         python version : 3.9.7.final.0
       virtual packages : __cuda=11.7=0
                          __linux=3.10.0=0
                          __glibc=2.17=0
                          __unix=0=0
                          __archspec=1=x86_64
       base environment : /home/rufad/miniconda3  (writable)
      conda av data dir : /home/rufad/miniconda3/etc/conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/conda-forge/label/openmm_rc/linux-64
                          https://conda.anaconda.org/conda-forge/label/openmm_rc/noarch
                          https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://conda.anaconda.org/omnia/linux-64
                          https://conda.anaconda.org/omnia/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /home/rufad/miniconda3/pkgs
                          /home/rufad/.conda/pkgs
       envs directories : /home/rufad/miniconda3/envs
                          /home/rufad/.conda/envs
               platform : linux-64
             user-agent : conda/22.9.0 requests/2.28.1 CPython/3.9.7 Linux/3.10.0-1160.45.1.el7.x86_64 centos/7.9.2009 glibc/2.17
                UID:GID : 1619:3008
             netrc file : None
           offline mode : False


An unexpected error has occurred. Conda has prepared the above report.

If submitted, this report will be used by core maintainers to improve
future releases of conda.
Would you like conda to send this report to the core maintainers? [y/N]:
No report sent. To permanently opt-out, use

    $ conda config --set report_errors false

(openmm-8)
```
any way to solve this?

**Comment by peastman** [comment]
That looks like a network problem retrieving conda packages.  It might just be a transient issue.  See if it fixes itself after a few minutes?

With your original error, try installing with mamba instead of conda.  They install different versions of a lot of packages, and we've found a number of cases where the mamba install works but the conda install fails.

**Comment by dominicrufa** [comment]
yes, `mamba` seems to be the fix. thanks, @peastman
