### ISSUE TITLE
problem big system

### ISSUE THREAD

**Issue by anicoli** [openmm/openmm#3859]
Dear openmm developers,

Recently, we wrote a protcol to run membrane protein using openmm and CHARMM as force fiels. We generally, build and obtain topology, and psf,/pdb using a combination of htmd and vmd. We tested the protocol with a system of 71K atoms (POPC, proteinx1, ligandx1, water and ions), and everything was working fine. Then, we moved to test the same protocol to a bigger system that is around 317K atoms. Now, the same protocol arise some problems (please read below). We import parameters, psf and pdb files, but this time during the parsing of the pdb file, appear the following Warnings:

```
[...]
lib/python3.9/site-packages/openmm/app/internal/pdbstructure.py:538: UserWarning: WARNING: duplicate atom (ATOM  116123 H16Y POPCL   1      62.995  67.348   4.562  1.00  0.00      L216 H  , ATOM  115989 H16Y POPCL   1      71.226  64.435   1.048  1.00  0.00      L116 H  )
  warnings.warn("WARNING: duplicate atom (%s, %s)" % (atom, old_atom._pdb_string(old_atom.serial_number, atom.alternate_location_indicator)))
lib/python3.9/site-packages/openmm/app/internal/pdbstructure.py:538: UserWarning: WARNING: duplicate atom (ATOM  116124 H16Z POPCL   1      64.220  66.316   3.769  1.00  0.00      L216 H  , ATOM  115990 H16Z POPCL   1      70.186  63.123   1.932  1.00  0.00      L116 H  )
  warnings.warn("WARNING: duplicate atom (%s, %s)" % (atom, old_atom._pdb_string(old_atom.serial_number, atom.alternate_location_indicator)))
[...]
```
Then, we set the dimension box on the psf, we set constraint, diffrent settings and create the system and till here no problems. But when tried to minimize the system arised the following error:

```
OpenMMException                           Traceback (most recent call last)
Input In [28], in <cell line: 13>()
     11 integrator.setConstraintTolerance(constraintTolerance)
     12 simulation = Simulation(topology, system, integrator, platform, platformProperties)
---> 13 simulation.context.setPositions(coords)
     15 # Minimize 
     16 print('Performing energy minimization...')

File python3.9/site-packages/openmm/openmm.py:12108, in Context.setPositions(self, positions)
  12104 if unit.is_quantity(positions):
  12105     positions = positions.value_in_unit(unit.nanometer)
> 12108 return _openmm.Context_setPositions(self, positions)

OpenMMException: Called setPositions() on a Context with the wrong number of positions
```

from the following code:

```
coords = pdb.positions
[...]
### Minimize
system.addForce(MonteCarloMembraneBarostat(pressure, surface_tension,
                                           temperature,
                                           MonteCarloMembraneBarostat.XYIsotropic,
                                           MonteCarloMembraneBarostat.ZFree,
                                           barostatInterval))
integrator = LangevinIntegrator(temperature, friction, dt)
integrator.setConstraintTolerance(constraintTolerance)
simulation = Simulation(topology, system, integrator, platform, platformProperties)
simulation.context.setPositions(coords)

state = simulation.context.getState(getEnergy=True, getForces=True)    # getinfo initial state pot e
print('Starting pot energy:', state.getPotentialEnergy())              # Print initial energies
simulation.minimizeEnergy(minimization_steps)
state = simulation.context.getState(getPositions=True, getEnergy=True, getForces=True) # getinfo final pot e
print('\tEnding pot energy:', state.getPotentialEnergy())
```
Then, I checked the length of the variable coords (pdb.positions), and it is 317581, instead the total number of atoms in the system are 317715. The difference is about 134 coordinates, atoms. Is this the error? During the parsing of the pdb file, the function PDBFile drop the duplicate atoms? if yes, how can I avoid it, or be able to run the protocol?

Kind regards,
Alessandro

**Comment by peastman** [comment]
> lib/python3.9/site-packages/openmm/app/internal/pdbstructure.py:538: UserWarning: WARNING: duplicate atom (ATOM  116123 H16Y POPCL   1      62.995  67.348   4.562  1.00  0.00      L216 H  , ATOM  115989 H16Y POPCL   1      71.226  64.435   1.048  1.00  0.00      L116 H  )

This warning is telling you there are two atoms called `H16Y` within a single residue.  That indicates some sort of a problem with your PDB file, though I can't say exactly what without seeing it.

The PDB format is inherently limited to only 99,999 atoms and only 9999 residues in a single file.  Different programs use a variety of hacks to work around those limits, but they're all nonstandard and not guaranteed to work in other programs.  Can you use PDBx/mmCIF format instead?  It doesn't have those limits.

> Then, I checked the length of the variable coords (pdb.positions), and it is 317581, instead the total number of atoms in the system are 317715.

Can you show the code for how you created the System?

**Comment by anicoli** [comment]
Dear @peastman,

Thank for your kind reply. I noticed that there was already a similar problem here #1064.  
 
> > Then, I checked the length of the variable coords (pdb.positions), and it is 317581, instead the total number of atoms in the system are 317715.
> 
I have counted the number of WARNINGS after the import of the PDB with PDBFile, and they are exactly 134, basically the difference between the exact total number of atoms in the PDB, and the ones "parsed" by the  PDBFile functions (len(pdb.coords)). The error arises at the moment of the parsing of the pdb file. The problem regards, apparently some hydrogens bound to the POPC. 

Take as an example, the warning mentioned before. I extracted the two POPC residue, that apparently caused the warnings in the PDBFile. Please find in zip file here: [POPC.zip](https://github.com/openmm/openmm/files/10121995/POPC.zip). My doubt now, is why it is not able just to parse those 134 atoms but the rest yes? It is also true that the two residue POPC have the same resname, but they have different atom index and segname. Sorry, for the question but it is the first time that this happen, especially since it was working fine with smaller system.

> > lib/python3.9/site-packages/openmm/app/internal/pdbstructure.py:538: UserWarning: WARNING: duplicate atom (ATOM 116123 H16Y POPCL 1 62.995 67.348 4.562 1.00 0.00 L216 H , ATOM 115989 H16Y POPCL 1 71.226 64.435 1.048 1.00 0.00 L116 H )

> This warning is telling you there are two atoms called H16Y within a single residue. That indicates some sort of a problem with your PDB file, though I can't say exactly what without seeing it.

Here, how the two atoms looks like in the pdb:
```
grep "H16Y" final_sys.pdb
output:
ATOM  1c51e H16Y POPCL   1      71.226  64.435   1.048  1.00  0.00      L116 H
ATOM  1c5a4 H16Y POPCL   1      62.995  67.348   4.562  1.00  0.00      L216 H
```
I would like to add that I tried to visualize with VMD, and I obtained the correct number of atoms (317715) with no errors. I tried to parse the pdb and psf, also using mdanalysis or parmed, and also with them the number of atoms was correct. Then, I tried to use ACEMD3 performing a minimizazion and small equilibration, and it was working fine.


>>The PDB format is inherently limited to only 99,999 atoms and only 9999 residues in a single file. Different programs use a variety of hacks to work around those limits, but they're all nonstandard and not guaranteed to work in other programs. Can you use PDBx/mmCIF format instead? It doesn't have those limits.

I had a look if it is possible to convert a PDB (charmm format) to PDBx/mmCIF format on parmed webpage [https://parmed.github.io/ParmEd/html/readwrite.html](url). Apparently the use of the flag charmm ( (charmm – If True, the SEGID will be printed in columns 73 to 76 of the PDB file (default is False))) while writing is only available for PDB format, at least for my understanding. Then, I tried with these simple lines, since I am beginner with parmed package to try to convert the pdb in PDBx/mmCIF.

```
import parmed as pmd

input_file_pdb = pmd.load_file('final_sys.pdb')
len(input_file_pdb.atoms) -> out: 317715
input_file_pdb.save(test.cif)
input_file_pdb.save(test.cif)
```
Load it into vmd, using the same psf file and the result is not great at all. Do you have any suggestions?

![image](https://user-images.githubusercontent.com/87415853/204783421-09aa0323-7c23-4e66-b662-de5ecea4a8ba.png)


Best,
Alessandro

**Comment by peastman** [comment]
You posted two different PDB files, each containing only a single residue.  Are those extracted from a larger file?  Can you post the full file?

**Comment by anicoli** [comment]
Dear @peastman,

Yes, in the two pdb file there is two POPC, take as an example that cause some of the warnings.

> You posted two different PDB files, each containing only a single residue. Are those extracted from a larger file? Can you post the full file?

Please find here the system: [sys_final.zip](https://github.com/openmm/openmm/files/10127459/sys_final.zip).

**Comment by anicoli** [comment]
Dear @peastman,

Yes, in the two pdb file there is two POPC, take as an example that causes some of the warnings.

> You posted two different PDB files, each containing only a single residue. Are those extracted from a larger file? Can you post the full file?

Please find here the system: [sys_final.zip](https://github.com/openmm/openmm/files/10127459/sys_final.zip).

**Comment by peastman** [comment]
This is a really messed up file.  It's nonstandard in a lot of different ways.  Regarding the particular problem you asked about, it looks like you intended a new residue to start at atom 1c520, but nothing in the file indicates that:

```
ATOM  1c51e H16Y POPCL   1      71.226  64.435   1.048  1.00  0.00      L116 H
ATOM  1c51f H16Z POPCL   1      70.186  63.123   1.932  1.00  0.00      L116 H
ATOM  1c520  N   POPCL   1      66.233  67.824 -18.536  1.00  0.00      L216 N
ATOM  1c521  C12 POPCL   1      65.178  66.688 -18.282  1.00  0.00      L216 C
```

Same chain ID (L), same residue sequence number (1), so it's all one residue.  That's why the reader correctly reports that you have multiple atoms with the same name in a single residue.

Another serious problem is that it misuses the chain ID (column 22).  This is supposed to be a unique letter for every chain.  Instead the file contains what appears to be an indicator for what type of molecule each residue is part of: P for protein, L for lipid, W for water, and I for ions.  This will lead to the file being interpreted incorrectly.  For example, at this point there is clearly meant to be a break between chains:

```
ATOM  10342  HT2 ASN P 340      -3.668  36.732 -29.311  1.00  0.00      P1   H
ATOM  10343  HT3 ASN P 340      -3.417  35.466 -28.302  1.00  0.00      P1   H
ATOM  10344  CAY THR P   6       7.624  10.642 -81.733  1.00  0.00      P2   C
ATOM  10345  HY1 THR P   6       7.297   9.712 -81.901  1.00  0.00      P2   H
```

The residue sequence number goes down from 340 to 6 and there's an abrupt jump in the coordinates.  But the chain ID doesn't change and there's no TER record, so they'll be interpreted as a single chain and it will try to put a bond between those residues.

Here are some other problems I noticed in the file.

- It often uses four characters for residue names.  The PDB format only provides three columns (18-20) for residue names.  Many readers will ignore the fourth character.
- Notice the hex atom numbers above.  That's a hack some programs use for storing more than 99,999 atoms.  There are multiple systems used by different programs for representing atom numbers with hex.  Don't be surprised if some programs don't interpret them the way you intended.
- Notice the second to last column in the parts quoted above, containing things like L116 and P1.  That's meaningless.  The spec doesn't define any role for columns 67-76.  Any data in those columns will at best be ignored, and may break parsers.

You might want to look at [the spec](http://www.wwpdb.org/documentation/file-format-content/format33/sect9.html#ATOM) for more information.

Those are the problems I noticed on a quick scan, but there may be others.  The broken visualization you showed above looks like some atom coordinates are messed up.

**Comment by tristanic** [comment]
This looks like the CHARMM PDB format (see http://www.mmtsb.org/software/tutorial/allatom-pdbfiles.html), most commonly used these days by VMD/NAMD. Its most important distinguishing feature is that the chain ID is essentially ignored in favour of using the segid. It looks like ParmEd _should_ be able to read it and write out to mmCIF (see https://parmed.github.io/ParmEd/html/readwrite.html).

**Comment by anicoli** [comment]
Dear @peastman,

**Comment by anicoli** [comment]
Thank you @peastman and @tristanic for your explenation and suggestions. I then tried to fix and modify the PDB file, for example by renumbering the POPC chain (that was causing the problems of duplicate atoms) before the embedding (please see the small script below), and now the parser is able to read the pdb file,  the minimization and simulation have started . 
```
membrane_popc = Molecule('membrane.pdb') 
membrane_popc.filter("resname POPC")  
mapping = membrane_popc.renumberResidues(returnMapping=True) 
print(mapping)
membrane_popc.set('chain','M','resname POPC') # set chain M, since L for the ligand
membrane_popc.write('popc_TEMP_renum.pdb')
```



####
The broken visualization of the image, was due to the mmcif conversation after the parmed (script above). But I will try to have a deep look on parmed documentation as suggested from @tristanic.

P.s. As @tristanic also pointed the PDB file is in a CHARMM PDB format, since has been created with a combination of HTMD and also VMD passages.

**Comment by anicoli** [comment]
I have last questions regarding the setting of the MD simulations (equilibration stage). The simulation with the system described above of 120ns has stopped at the 83% (99.6ns) with the following error.
```
83.7%	50200000	33.1	14:12:35
83.8%	50250000	33.1	14:08:15
Traceback (most recent call last):
  File "/home/nicoli/Desktop/MD_PhD/5ht7r_zeenat/MD/ACTIVE/CHARMM_equil_complex_v006.py", line 879, in <module>
    main()
  File "/home/nicoli/Desktop/MD_PhD/5ht7r_zeenat/MD/ACTIVE/CHARMM_equil_complex_v006.py", line 874, in main
    gradek1, gradek2, gradek3, gradek4, simulation, final_state, positions, last_frame = sys_equilibration(eq_folder,trajectory_freq,system,simulation,log_freq,save_checkpoint,nsteps,t1,t2,t3,t4,t5_free,delta1,delta2,delta3,delta4,temperature,
  File "/home/nicoli/Desktop/MD_PhD/5ht7r_zeenat/MD/ACTIVE/CHARMM_equil_complex_v006.py", line 729, in sys_equilibration
    simulation.step(1)            #simulate 1 step for each for cyclee
  File "/home/nicoli/anaconda2/envs/gpcrmd_run/lib/python3.9/site-packages/openmm/app/simulation.py", line 141, in step
    self._simulate(endStep=self.currentStep+steps)
  File "/home/nicoli/anaconda2/envs/gpcrmd_run/lib/python3.9/site-packages/openmm/app/simulation.py", line 210, in _simulate
    self.integrator.step(stepsToGo)
  File "/home/nicoli/anaconda2/envs/gpcrmd_run/lib/python3.9/site-packages/openmm/openmm.py", line 14726, in step
    return _openmm.LangevinIntegrator_step(self, steps)
openmm.OpenMMException: Particle coordinate is nan
```
Please find here the plots of Box Volume, Temperature and water density till the error ([eq_system_features.pdf](https://github.com/openmm/openmm/files/10168270/eq_system_features.pdf)). The mean value are:
```
Mean Box Volume (nm^3): 2674.395018925665
Mean Temperature (K): 310.02084228613035
Mean Density (g/mL): 1.0247486313862408
```
The settings used are the follow:

```
FF = CHARMM36
Box Dimension   13.7973 nm  13.846400000000001 nm   16.5788 nm
dt = 0.002*picoseconds
Constraint tolerance = 1e-06
platform = Platform.getPlatformByName('CUDA')
platformProperties = {'Precision': 'mixed'}
nsteps =  60000000.0

nonbondedMethod = PME
nonbondedCutoff = 9*angstroms
switchDistance=7.5*angstroms
ewaldErrorTolerance = 0.0005
hydrogenMass=None
constraints = HBonds
rigidWater = True
constraintTolerance = 0.000001
temperature = 310*kelvin
friction = 1.0/picosecond
pressure = 1.0132*bar
XYmode = MonteCarloMembraneBarostat.XYIsotropic
Zmode = MonteCarloMembraneBarostat.ZFree
barostatInterval = 25
fc = 200*kilojoules_per_mole/nanometer**2

####

topology = psf.topology
positions = pdb.positions
system = psf.createSystem(params, nonbondedMethod=nonbondedMethod, nonbondedCutoff=nonbondedCutoff,
constraints=constraints, rigidWater=rigidWater, ewaldErrorTolerance=ewaldErrorTolerance, hydrogenMass=hydrogenMass)

system.addForce(MonteCarloMembraneBarostat(pressure, surface_tension,temperature,
                                           MonteCarloMembraneBarostat.XYIsotropic,
                                           MonteCarloMembraneBarostat.ZFree,
                                           barostatInterval))
integrator = LangevinIntegrator(temperature, friction, dt)
integrator.setConstraintTolerance(constraintTolerance)
simulation = Simulation(topology, system, integrator, platform, platformProperties)
```
We also set the restraint for example on the carbon alpha following @peastman previous useful suggestion (#3817). In your opinion which might be the problem? for CHARMM and membrane protein MD simulation with OpenMM, which are the settings that you recommended? Do you suggest to increase the nonbondedCutoff (default=1.0nm) and the switchDistance? 

Thanks again for your time.

**Comment by peastman** [comment]
CHARMM has created their own "PDB" format that looks like PDB and uses the .pdb extension but isn't really PDB?  Sersiously???  That is such a terrible idea in so many ways.  PDB is a standard format defined by a spec.  If they're going to throw out the spec, they need to call their new format something different.  It isn't PDB.

**Comment by tristanic** [comment]
An unfortunate decision, I agree. Sadly, it's one that was made 30 or more years ago... no putting that genie back in the bottle (other than letting it die along with the PDB format itself as mmCIF takes over).
