### ISSUE TITLE
Using Gromacs topology to create a dcd file

### ISSUE THREAD

**Issue by xiki-tempula** [openmm/openmm#3861]
So I'm interested in using Gromacs topology to run a simulation and then save the result into the DCD file.

```python
    gro = app.GromacsGroFile(f"ethanol.gro")
    top = app.GromacsTopFile(
        f"ethanol.top",
        periodicBoxVectors=gro.getPeriodicBoxVectors(),
    )
    integrator = integrators.LangevinIntegrator(
        collision_rate=1.0 / unit.picoseconds,
        timestep=2.0 * unit.femtoseconds,
        temperature=298.0 * unit.kelvin,
    )
    dcd = app.DCDFile(
        open(f"run.dcd", "wb"),
        top,
        integrator.getStepSize(),
        0,
        200,
        False,
    )
```
However, this would give me 
```
Traceback (most recent call last):
  File "/Users/zwu/bitbucket/asfe/src/exs/asfe/hello.py", line 97, in <module>
    dcd = app.DCDFile(
  File "/Users/zwu/miniconda3_x86/envs/asfe/lib/python3.8/site-packages/openmm/app/dcdfile.py", line 84, in __init__
    if topology.getUnitCellDimensions() is not None:
AttributeError: 'GromacsTopFile' object has no attribute 'getUnitCellDimensions'
```

I tried to fix this with
```python
    gro = app.GromacsGroFile(f"ethanol.gro")
    top = app.GromacsTopFile(
        f"ethanol.top",
        unitCellDimensions=gro.getUnitCellDimensions(),
    )
```
but I still cannot run `top.getUnitCellDimensions()`.

```
Traceback (most recent call last):
  File "/Users/zwu/miniconda3_x86/envs/asfe/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 3433, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-1-0eab70bfde67>", line 1, in <module>
    top.getUnitCellDimensions()
AttributeError: 'GromacsTopFile' object has no attribute 'getUnitCellDimensions'
```
[Archive.zip](https://github.com/openmm/openmm/files/10122731/Archive.zip)

**Comment by xiki-tempula** [comment]
I can see that if one use amber files, they will got the same problem.

```
    gro = app.AmberInpcrdFile(f"ethanol.rst7")
    top = app.AmberPrmtopFile(f"ethanol.prm7")
```
[Archive 2.zip](https://github.com/openmm/openmm/files/10122762/Archive.2.zip)

**Comment by sef43** [comment]
Hi, if you create the `System` and `Simulation` and then use `simulation.topology` it should work. The script below works for me. The issue in hinted in the error message, the [`GromacsTopFile`](http://docs.openmm.org/latest/api-python/generated/openmm.app.gromacstopfile.GromacsTopFile.html#openmm.app.gromacstopfile.GromacsTopFile) is not equivalent to the full OpenMM [`Topology`]( http://docs.openmm.org/latest/api-python/generated/openmm.app.topology.Topology.html#openmm.app.topology.Topology) which gets created when you setup the system and simulation. 

```
from openmm.app import *
from openmm import *
from openmm.unit import *

gro = app.GromacsGroFile(f"ethanol.gro")
top = app.GromacsTopFile(
    f"ethanol.top",
    periodicBoxVectors=gro.getPeriodicBoxVectors(),
)

system = top.createSystem(nonbondedMethod=PME, nonbondedCutoff=1*nanometer,
        constraints=HBonds)

integrator = LangevinIntegrator(
    298*kelvin,
    1.0/picosecond,
    2.0*femtosecond,
)

simulation = Simulation(top.topology, system, integrator)

dcd = DCDFile(
    open(f"run.dcd", "wb"),
    simulation.topology,
    integrator.getStepSize(),
    0,
    200,
    False,
)
```

**Comment by xiki-tempula** [comment]
I see. Thanks.

**Comment by sef43** [comment]
Yes done this way it can be slightly confusing. The simpler method for writing a dcd trajectory is using the `DCDReporter`. Here is the example, the same as in the [user guide](http://docs.openmm.org/latest/userguide/application/02_running_sims.html#using-gromacs-files), but with dcd output.

```from openmm.app import *
from openmm import *
from openmm.unit import *
from sys import stdout 

gro = app.GromacsGroFile(f"ethanol.gro")
top = app.GromacsTopFile(
    f"ethanol.top",
    periodicBoxVectors=gro.getPeriodicBoxVectors(),
)

system = top.createSystem(nonbondedMethod=PME, nonbondedCutoff=1*nanometer,
        constraints=HBonds)

integrator = LangevinIntegrator(
    298*kelvin,
    1.0/picosecond,
    2.0*femtosecond,
)

simulation = Simulation(top.topology, system, integrator)
simulation.context.setPositions(gro.positions)
simulation.minimizeEnergy()
simulation.reporters.append(DCDReporter('output.dcd', 1000))
simulation.reporters.append(StateDataReporter(stdout, 1000, step=True,
        potentialEnergy=True, temperature=True))
simulation.step(10000)
```

**Comment by xiki-tempula** [comment]
@sef43 Thanks. I noticed this as well. I'm trying to run some alchemical simulations and I was trying to use `openmmtools`, which gives context and integrator without creating the simulation object. So I kind of need to do the recording myself.
