### ISSUE TITLE
Cannot run AMBER 20 DHFR

### ISSUE THREAD

**Issue by philipturner** [openmm/openmm#3938]
OpenMM 8.0.0 release with Metal plugin installed

```
(base) philipturner@M1-Max-MacBook-Pro examples % python3 benchmark.py --platform HIP --seconds 15 --test amber20-dhfr
/bin/sh: nvidia-smi: command not found
hostname: M1-Max-MacBook-Pro.local
timestamp: 2023-01-31T23:39:24.850743
openmm_version: 8.0.0.dev-a780005
cpuinfo: Apple M1 Max
cpuarch: arm
system: Darwin
Traceback (most recent call last):
  File "/Users/philipturner/miniforge3/lib/python3.9/site-packages/openmm/app/internal/amber_file_parser.py", line 1440, in __init__
    from scipy.io import NetCDFFile
ModuleNotFoundError: No module named 'scipy.io'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/philipturner/miniforge3/lib/python3.9/site-packages/openmm/app/internal/amber_file_parser.py", line 1444, in __init__
    from scipy.io.netcdf import NetCDFFile
ModuleNotFoundError: No module named 'scipy.io'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/philipturner/miniforge3/lib/python3.9/site-packages/openmm/app/internal/amber_file_parser.py", line 1534, in readAmberCoordinates
    crdfile = AmberNetcdfRestart(filename)
  File "/Users/philipturner/miniforge3/lib/python3.9/site-packages/openmm/app/internal/amber_file_parser.py", line 1446, in __init__
    raise ImportError('scipy is necessary to parse NetCDF '
ImportError: scipy is necessary to parse NetCDF restarts

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/philipturner/miniforge3/lib/python3.9/site-packages/openmm/app/internal/amber_file_parser.py", line 1538, in readAmberCoordinates
    crdfile = AmberAsciiRestart(filename)
  File "/Users/philipturner/miniforge3/lib/python3.9/site-packages/openmm/app/internal/amber_file_parser.py", line 1258, in __init__
    lines = f.readlines()
  File "/Users/philipturner/miniforge3/lib/python3.9/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x84 in position 399: invalid start byte

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/philipturner/Documents/OpenMM/openmm/examples/benchmark.py", line 549, in <module>
    runOneTest(test, args)
  File "/Users/philipturner/Documents/OpenMM/openmm/examples/benchmark.py", line 304, in runOneTest
    system, positions, test_parameters = retrieveTestSystem(testName, pme_cutoff=options.pme_cutoff, bond_constraints=options.bond_constraints, polarization=options.polarization, epsilon=options.epsilon)
  File "/Users/philipturner/Documents/OpenMM/openmm/examples/benchmark.py", line 194, in retrieveTestSystem
    inpcrd = app.AmberInpcrdFile(os.path.join(dirname, f'PME/Coordinates/{fileName}.inpcrd'))
  File "/Users/philipturner/miniforge3/lib/python3.9/site-packages/openmm/app/amberinpcrdfile.py", line 81, in __init__
    results = amber_file_parser.readAmberCoordinates(file)
  File "/Users/philipturner/miniforge3/lib/python3.9/site-packages/openmm/app/internal/amber_file_parser.py", line 1544, in readAmberCoordinates
    raise TypeError('Could not parse Amber ASCII restart file %s' %
TypeError: Could not parse Amber ASCII restart file Amber20_Benchmark_Suite/PME/Coordinates/JAC.inpcrd
```

**Comment by peastman** [comment]
Try this:

```
conda install -c conda-forge scipy
```

**Comment by philipturner** [comment]
```
(base) philipturner@M1-Max-MacBook-Pro examples % python3 benchmark.py --platform HIP --seconds 15 --test amber20-dhfr
/bin/sh: nvidia-smi: command not found
hostname: M1-Max-MacBook-Pro.local
timestamp: 2023-02-01T01:20:36.608414
openmm_version: 8.0.0.dev-a780005
cpuinfo: Apple M1 Max
cpuarch: arm
system: Darwin
test: amber20-dhfr
cutoff: 0.9
constraints: HBonds
hydrogen_mass: 1.5
ensemble: NVT
precision: single
timestep_in_fs: 4.0
platform: HIP
platform_properties: {'DeviceIndex': '0', 'DeviceName': 'Apple M1 Max', 'MetalPlatformIndex': '0', 'MetalPlatformName': 'Apple', 'Precision': 'single', 'UseCpuPme': 'false', 'DisablePmeStream': 'false'}
steps: 9302
elapsed_time: 15.206168
ns_per_day: 211.4123163705675
```

Should we change to code to something compatible with people's default scipy installations? Or perhaps write this `conda` command into the error message.

**Comment by peastman** [comment]
Or make conda automatically install scipy.

**Comment by philipturner** [comment]
> Or make conda automatically install scipy.

I know some Conda packages have to install/update external dependencies before installing. Sounds like a good solution.

**Comment by peastman** [comment]
The 8.1 beta is now out, which adds scipy as a runtime dependency.  That means we can close this.
