### ISSUE TITLE
Forcefield template error for addMembrane

### ISSUE THREAD

**Issue by jacknicoludis** [openmm/openmm#3951]
I'm trying to use `Modeller.addMembrane()` to set up a simulation system. I am able to run `addMembrane()`, minimize the system and save to a pdb file, but if I try to reload this PDB and add to new system, I get the following error:

```
>>> system = forcefield.createSystem(new_pdb.topology, nonbondedMethod=openmm_app.PME)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<<path to environment>>/lib/python3.8/site-packages/openmm/app/forcefield.py", line 1212, in createSystem
    templateForResidue = self._matchAllResiduesToTemplates(data, topology, residueTemplates, ignoreExternalBonds)
  File "<<path to environment>>/lib/python3.8/site-packages/openmm/app/forcefield.py", line 1427, in _matchAllResiduesToTemplates
    raise ValueError('No template found for residue %d (%s).  %s' % (res.index+1, res.name, _findMatchErrors(self, res)))
ValueError: No template found for residue 184 (POP).  The set of atoms matches POPC, but the bonds are different.  Perhaps the chain is missing a terminal group?
```

The error can be reproduced using this code:
```
import openmm.app as openmm_app
import openmm.unit as unit
import os
from pathlib import Path
from openmm import VerletIntegrator

proteinforcefield = "amber14-all.xml"
solventforcefield = 'amber14/tip3p.xml'
pdbfile = "2k74.pdb" # change path to file
out_dir = "output/"  # change path to output dir

stem = Path(pdbfile).stem
out_base = os.path.join(out_dir, stem)

forcefield = openmm_app.ForceField(proteinforcefield, solventforcefield)
pdb = openmm_app.PDBFile(pdbfile)
modeller = openmm_app.Modeller(pdb.topology, pdb.positions)
modeller.addHydrogens(forcefield)
modeller.addMembrane(
    forcefield,
    lipidType="POPC",
    minimumPadding=1*unit.nanometer,
    ionicStrength=0.1*unit.molar,
    positiveIon="K+",
)
system = forcefield.createSystem(modeller.topology, nonbondedMethod=openmm_app.PME)
integrator = VerletIntegrator(0.001*unit.picoseconds)
simulation = openmm_app.Simulation(modeller.topology, system, integrator)
simulation.context.setPositions(modeller.positions)

simulation.minimizeEnergy(maxIterations=100)

positions = simulation.context.getState(getPositions=True).getPositions()
outfile =  out_base + "_system.pdb"
openmm_app.PDBFile.writeFile(simulation.topology, positions, open(outfile, "w"))


forcefield = openmm_app.ForceField(proteinforcefield, solventforcefield)
new_pdb = openmm_app.PDBFile(outfile)
system = forcefield.createSystem(new_pdb.topology, nonbondedMethod=openmm_app.PME)  # error triggered here
```

Attached is a pdb file that is an input file for testing that was downloaded (and modified to remove dummy atoms) from the [OPM](https://opm.phar.umich.edu/proteins/819):
[2k74.pdb.zip](https://github.com/openmm/openmm/files/10678824/2k74.pdb.zip)

**Comment by sef43** [comment]
Can you try using [PDBx](http://docs.openmm.org/latest/api-python/generated/openmm.app.pdbxfile.PDBxFile.html) files instead of PDB files? I think this may be an issue with PDB files not supporting more than 99,999 atoms

**Comment by jacknicoludis** [comment]
Thanks - that solved the issue. Here is the code that worked:

```
import openmm.app as openmm_app
import openmm.unit as unit
import os
from pathlib import Path
from openmm import VerletIntegrator

proteinforcefield = "amber14-all.xml"
solventforcefield = 'amber14/tip3p.xml'
pdbfile = "2k74.pdb" # change path to file
out_dir = "output/"  # change path to output dir

stem = Path(pdbfile).stem
out_base = os.path.join(out_dir, stem)

forcefield = openmm_app.ForceField(proteinforcefield, solventforcefield)
pdb = openmm_app.PDBFile(pdbfile)
modeller = openmm_app.Modeller(pdb.topology, pdb.positions)
modeller.addHydrogens(forcefield)
modeller.addMembrane(
    forcefield,
    lipidType="POPC",
    minimumPadding=1*unit.nanometer,
    ionicStrength=0.1*unit.molar,
    positiveIon="K+",
)
system = forcefield.createSystem(modeller.topology, nonbondedMethod=openmm_app.PME)
integrator = VerletIntegrator(0.001*unit.picoseconds)
simulation = openmm_app.Simulation(modeller.topology, system, integrator)
simulation.context.setPositions(modeller.positions)

simulation.minimizeEnergy(maxIterations=100)

positions = simulation.context.getState(getPositions=True).getPositions()
outfile =  out_base + "_system.pdb"
openmm_app.PDBxFile.writeFile(simulation.topology, positions, open(outfile, "w"))


forcefield = openmm_app.ForceField(proteinforcefield, solventforcefield)
new_pdb = openmm_app.PDBxFile(outfile)
system = forcefield.createSystem(new_pdb.topology, nonbondedMethod=openmm_app.PME)  # error triggered here
```
