### ISSUE TITLE
ValueError: Energy is NaN when running with GPU but works with CPU

### ISSUE THREAD

**Issue by mainguyenanhvu** [openmm/openmm#3965]
I want to run SMD with GPU after adding a custom force when running MD through this code:
```
    pdb = openmm.app.pdbfile.PDBFile(args.filename)
    spring_constant = args.spring_constant * unit.kilojoule/unit.mole/unit.nanometer**2
    velocity = args.velocity * unit.nanometer/unit.picosecond
    direction = unit.Quantity(args.direction, unit.nanometer)
    smd_force = openmm.CustomExternalForce("k*((x-x0)^2+(y-y0)^2+(z-z0)^2)^0.5 + v*(x-x0)*dir_x + v*(y-y0)*dir_y + v*(z-z0)*dir_z")
    smd_force.addGlobalParameter("k", spring_constant)
    smd_force.addGlobalParameter("v", velocity)
    smd_force.addGlobalParameter("dir_x", direction[0]/unit.nanometer)
    smd_force.addGlobalParameter("dir_y", direction[1]/unit.nanometer)
    smd_force.addGlobalParameter("dir_z", direction[2]/unit.nanometer)
    smd_force.addPerParticleParameter("x0")
    smd_force.addPerParticleParameter("y0")
    smd_force.addPerParticleParameter("z0")
    for index in range(len(pdb.positions)):
        x, y, z = pdb.positions[index]
        smd_force.addParticle(index, [x, y, z])
    system.addForce(smd_force)
```

Howerver, it threw error:
```
running 50000 equilibration steps, saving every 10000 steps
#"Temperature (K)"
695.738665325081
Traceback (most recent call last):
  File "/home/tools/run_smd.py", line 479, in <module>
    main()
  File "/home/tools/run_smd.py", line 444, in main
    simulation.step(equisteps)
  File "/home/.conda/envs/lib/python3.10/site-packages/openmm/app/simulation.py", line 141, in step
    self._simulate(endStep=self.currentStep+steps)
  File "/home/.conda/envs/lib/python3.10/site-packages/openmm/app/simulation.py", line 241, in _simulate
    self._generate_reports(wrapped, True)
  File "/home/.conda/envs/lib/python3.10/site-packages/openmm/app/simulation.py", line 263, in _generate_reports
    reporter.report(self, state)
  File "/home/.conda/envs/lib/python3.10/site-packages/mdtraj/reporters/basereporter.py", line 216, in report
    self._checkForErrors(simulation, state)
  File "/home/.conda/envs/lib/python3.10/site-packages/mdtraj/reporters/basereporter.py", line 261, in _checkForErrors
    raise ValueError('Energy is NaN')
ValueError: Energy is NaN
```

The parameters are:
```
    parser.add_argument('--spring-constant', type=float, default=100.0, help='The spring constant in kilojoules/mole/nanometer^2')
    parser.add_argument('--velocity', type=float, default=0.1, help='The constant velocity in nanometers per picosecond')
    parser.add_argument('--direction', nargs=3, type=float, default=[0.5,0.5,0.5], help='The direction vector of the pulling force in nanometers')
```

I tried this https://github.com/openmm/openmm/issues/1191 or read https://github.com/openmm/openmm/issues/1936 and change platform to CPU. It worked. However, I need to speed up SMD by using GPU. Please help me to solve it. 

Thank you very much.

**Comment by peastman** [comment]
Usually you only need to do the energy minimization with the CPU platform.  Once you have a minimized starting structure, you can run on the GPU.

**Comment by mainguyenanhvu** [comment]
I understand your solution. Please help me add code to change platform after the code:
```
   pdb = openmm.app.pdbfile.PDBFile(args.filename)
    spring_constant = args.spring_constant * unit.kilojoule/unit.mole/unit.nanometer**2
    velocity = args.velocity * unit.nanometer/unit.picosecond
    direction = unit.Quantity(args.direction, unit.nanometer)
    smd_force = openmm.CustomExternalForce("k*((x-x0)^2+(y-y0)^2+(z-z0)^2)^0.5 + v*(x-x0)*dir_x + v*(y-y0)*dir_y + v*(z-z0)*dir_z")
    smd_force.addGlobalParameter("k", spring_constant)
    smd_force.addGlobalParameter("v", velocity)
    smd_force.addGlobalParameter("dir_x", direction[0]/unit.nanometer)
    smd_force.addGlobalParameter("dir_y", direction[1]/unit.nanometer)
    smd_force.addGlobalParameter("dir_z", direction[2]/unit.nanometer)
    smd_force.addPerParticleParameter("x0")
    smd_force.addPerParticleParameter("y0")
    smd_force.addPerParticleParameter("z0")
    for index in range(len(pdb.positions)):
        x, y, z = pdb.positions[index]
        smd_force.addParticle(index, [x, y, z])
    system.addForce(smd_force)

    simulation = app.Simulation(structure_file.topology, system, integrator, platform)

    # set positions and velocities
    simulation.context.setPositions(structure_file.positions)

    if args.ministeps > 0:
        print("Performing energy minimization...")
        t1 = time.time()
        simulation.minimizeEnergy(maxIterations=args.ministeps)
        print(
            f"did {args.ministeps} steps of energy minimization in {time.time() - t1} seconds"
        )

```

**Comment by mainguyenanhvu** [comment]
Do you mean we can try this code after doing energy minimization?
```
# switch to CUDA platform
platform = openmm.Platform.getPlatformByName('CUDA')
simulation = app.Simulation(structure_file.topology, system, integrator, platform)
```

**Comment by mainguyenanhvu** [comment]
After I added the code above, it threw new error:
```_openmm.Context_swiginit(self, _openmm.new_Context(*args))
openmm.OpenMMException: This Integrator is already bound to a context
```

**Comment by mainguyenanhvu** [comment]
I found that it had a new error:
```
    return _openmm.Context_setVelocitiesToTemperature(self, *args)
openmm.OpenMMException: Particle positions have not been set
```

Is it caused by the change of simulation variable?

**Comment by peastman** [comment]
It means exactly what it says: you haven't set the particle positions on the new context.  You need to call `setPositions()` on it first.  Or you can copy over the full state from the old simulation:

```python
state = old_simulation.context.getState(getPositions=True, getVelocities=True, getParameters=True, getIntegratorParameters=True)
new_simulation.context.setState(state)
```

**Comment by peastman** [comment]
Do you have this working now?  If so, is it ok to close this issue?
