### ISSUE TITLE
DrudeNoseHooverIntegrator gives CUDA_ERROR_INVALID_VALUE (1), but DrudeLangevinIntegrator works fine.

### ISSUE THREAD

**Issue by cdeng485** [openmm/openmm#4004]
Dear OPENMM Team,

I would like to use the drude nosehoover integrator for my polarizable system, but I get this error:

Traceback (most recent call last):
  File "openmm_run.py", line 147, in <module>
    simulation.step(inputs.nstep)
  File "myprefix/lib/python3.9/site-packages/openmm/app/simulation.py", line 134, in step
    self._simulate(endStep=self.currentStep+steps)
  File "myprefix/lib/python3.9/site-packages/openmm/app/simulation.py", line 199, in _simulate
    self.integrator.step(10) # Only take 10 steps at a time, to give Python more chances to respond to a control-c.
  File "myprefix/lib/python3.9/site-packages/openmm/openmm.py", line 12320, in step
    return _openmm.NoseHooverIntegrator_step(self, steps)
openmm.OpenMMException: Error invoking kernel: CUDA_ERROR_INVALID_VALUE (1)

Replacing the DrudeNoseHooverIntegrator with DrudeLangevinIntegrator, with everything else identical, works fine:

integrator = DrudeNoseHooverIntegrator(inputs.temp*kelvin, inputs.fric_coeff/picosecond, inputs.drude_temp*kelvin, inputs.drude_fric_coeff/picosecond, inputs.dt*picoseconds)
#integrator = DrudeLangevinIntegrator(inputs.temp*kelvin, inputs.fric_coeff/picosecond, inputs.drude_temp*kelvin, inputs.drude_fric_coeff/picosecond, inputs.dt*picoseconds)

I tried openmm7.6, openmm8.0, with CUDA 10.0, CUDA11.2. It seems the version doesn't matter for my case.

**Comment by peastman** [comment]
I haven't encountered that error.  Can you post the files needed to reproduce it?
