### ISSUE TITLE
Can install 8.0 via conda-forge but can't import package in scripts

### ISSUE THREAD

**Issue by andrewsb8** [openmm/openmm#4011]
Just getting around to updating from 7.6 and I have new conda environments with python 3.10 (also tried 3.11). So different issue from #4000. 

`python -m openmm.testInstallation` leads to the following stack:

```
Traceback (most recent call last):
  File "/home/bandrews/miniconda3/envs/openMM/lib/python3.10/runpy.py", line 187, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/home/bandrews/miniconda3/envs/openMM/lib/python3.10/runpy.py", line 110, in _get_module_details
    __import__(pkg_name)
  File "/home/bandrews/miniconda3/envs/openMM/lib/python3.10/site-packages/openmm/__init__.py", line 24, in <module>
    from openmm.openmm import *
  File "/home/bandrews/miniconda3/envs/openMM/lib/python3.10/site-packages/openmm/openmm.py", line 10, in <module>
    from . import _openmm
ImportError: /home/bandrews/miniconda3/envs/openMM/lib/python3.10/site-packages/openmm/../../../libstdc++.so.6: version `GLIBCXX_3.4.30' not found (required by /home/bandrews/miniconda3/envs/openMM/lib/python3.10/site-packages/openmm/../../../libOpenMM.so.8.0)
```

If I run the following script (which worked in 7.6), I get a similar stack trace.

```
from openmm import *
from openmm.app import *
from openmm.unit import *
from sys import stdout
import sys

#inputs
protein = sys.argv[1]

#import structure and create system
try:
    pdb = PDBFile(protein)
except ZeroDivisionError:
    print("If your pdb has a line like:\nCRYST1 0 0 0...\nat the top, delete it and run this script again.")

modeller = Modeller(pdb.topology, pdb.positions)
#forcefield1 = ForceField('amber14-all.xml', 'amber14/tip3pfb.xml')
forcefield2 = ForceField('charmm_polar_2019.xml')
modeller.addExtraParticles(forcefield2)
modeller.addSolvent(forcefield2, boxSize=Vec3(5, 5, 5)*nanometers, neutralize=True, negativeIon='Cl-', positiveIon='Na+', model="swm4ndp")
#forcefield2 = ForceField('charmm_polar_2019.xml')
modeller.addExtraParticles(forcefield2)
```

```
Traceback (most recent call last):
  File "/home/bandrews/GIG_CHARMM_Drude_2019_SWM4-NDP_water_TestCorrections/openmm_setup.py", line 17, in <module>
    from openmm import *
  File "/home/bandrews/miniconda3/envs/openMM/lib/python3.11/site-packages/openmm/__init__.py", line 24, in <module>
    from openmm.openmm import *
  File "/home/bandrews/miniconda3/envs/openMM/lib/python3.11/site-packages/openmm/openmm.py", line 10, in <module>
    from . import _openmm
ImportError: /home/bandrews/miniconda3/envs/openMM/lib/python3.11/site-packages/openmm/../../../libstdc++.so.6: version `GLIBCXX_3.4.30' not found (required by /home/bandrews/miniconda3/envs/openMM/lib/python3.11/site-packages/openmm/../../../libOpenMM.so.8.0)
```

Not really sure what to do here. I didn't see anyone reporting a similar issue, but apologies if I missed the solution elsewhere.

Thanks!

**Comment by andrewsb8** [comment]
I do see openmm 8.0 in the output of conda list. Just wanted to clarify there was no error thrown when installing. Only when trying to load the package within a script.

**Comment by peastman** [comment]
I think this is a duplicate of #3943.  Do the solutions discussed there work for you?

**Comment by andrewsb8** [comment]
This update worked from #3943: `conda install -c conda-forge libstdcxx-ng`. Sorry for the duplicate. This is resolved!
