### ISSUE TITLE
CUDA_ERROR_ILLEGAL_ADDRESS (700) when trying multiple GPUs with Amoeba

### ISSUE THREAD

**Issue by andrewsb8** [openmm/openmm#4039]
Hi,

I have not had a problem with single GPU simulations in any force field from a cuda perspective. When using 7.7, whenever I would try to submit jobs allocating multiple GPUs, the simulation would just hang and I would never get an error message. But my systems are generally small so one GPU was sufficient. 

After upgrading to 8.0, I wanted to look into it to see if it was fixed as I saw some issues open about it before the release. For Amoeba, I'm using a solvated system as input (attached: [solvated.pdb.txt](https://github.com/openmm/openmm/files/11290514/solvated.pdb.txt)) so I am not missing a step where water needs to be added. The job is killed before the production simulation starts or at least before the first time step is reported. I am doing a very standard simulation, so no custom forces or anything, that works perfectly when I only specify one gpu to be used:

```
modeller = Modeller(pdb.topology, pdb.positions)
forcefield = ForceField('amoeba2018.xml')
modeller.addExtraParticles(forcefield)

system = forcefield.createSystem(modeller.topology, nonbondedMethod=PME,
        nonbondedCutoff=1*nanometer, constraints=HBonds)

#Add barostat for NPT instead of NVT simulation
system.addForce(MonteCarloBarostat(1*bar, 300*kelvin)) #this barostat is different than used in Gromacs

#Integrators assuming we want constant temperature
#Can use LangevinIntegrator and not specify a thermostat like below
integrator = LangevinIntegrator(300*kelvin, 1/picosecond, 0.001*picoseconds)

platform = Platform.getPlatformByName('CUDA')
properties = {'DeviceIndex': '0,1', 'Precision': 'double'}

simulation = Simulation(modeller.topology, system, integrator, platform, properties)
simulation.context.setPositions(modeller.positions)

#Energy minimization
simulation.minimizeEnergy(tolerance=0.0000001*kilojoule/mole, maxIterations=200000000)

#output minimized state
positions = simulation.context.getState(getPositions=True).getPositions()
PDBFile.writeFile(simulation.topology, positions, open('minimization/minimized.pdb', 'w'))

simulation.reporters = []
simulation.reporters.append(DCDReporter('md-equilibration/traj.dcd', 2000))
simulation.reporters.append(StateDataReporter(stdout, 2000, step=True,
                                              temperature=True, elapsedTime=True))
simulation.reporters.append(StateDataReporter("md-equilibration/log.csv", 2000, time=True,
                                              potentialEnergy=True, totalEnergy=True, temperature=True, elapsedTime=True)) #2 ps sampling

simulation.reporters.append(CheckpointReporter("md-equilibration/1.chk", 1000))

simulation.step(600000000)

#output minimized state to load for production simulation
simulation.saveState('md-equilibration/state1.xml')
```

I have tried removing the Precision specification which had no effect. In this case I get the error

```
Traceback (most recent call last):
  File "/ifs/groups/urba
[solvated.pdb.txt](https://github.com/openmm/openmm/files/11290508/solvated.pdb.txt)
ncMRIGrp/andrews/GGG_Amoeba2018_COO-/openmm_setup.py", line 75, in <module>
    simulation.step(600000000)
  File "/ifs/groups/urbancMRIGrp/opt/miniconda/envs/openMM-8.0/lib/python3.10/site-packages/openmm/app/simulation.py", line 141, in step
    self._simulate(endStep=self.currentStep+steps)
  File "/ifs/groups/urbancMRIGrp/opt/miniconda/envs/openMM-8.0/lib/python3.10/site-packages/openmm/app/simulation.py", line 206, in _simulate
    self.integrator.step(10) # Only take 10 steps at a time, to give Python more chances to respond to a control-c.
  File "/ifs/groups/urbancMRIGrp/opt/miniconda/envs/openMM-8.0/lib/python3.10/site-packages/openmm/openmm.py", line 4327, in step
    return _openmm.LangevinIntegrator_step(self, steps)
openmm.OpenMMException: Error invoking kernel: CUDA_ERROR_ILLEGAL_ADDRESS (700)
terminate called after throwing an instance of 'OpenMM::OpenMMException'
  what():  Error deleting array param1: CUDA_ERROR_ILLEGAL_ADDRESS (700)
/cm/local/apps/slurm/var/spool/job9082624/slurm_script: line 25: 42271 Aborted                 (core dumped) python3 openmm_setup.py common/solvated.pdb
```

nvidia-smi shows driver version 510.39.01, which was shown to not be problematic in issue #3329. The machine also uses Cuda 11.6. I tried with openmm 8.0 and cudatoolkit 10.2.89 and 11.6 with the same stack trace as above in both cases.

However, the issue did not persist when using an additive force field and I see utilization of each gpu allocated e.g.:

```
forcefield = ForceField('charmm36.xml', 'charmm36/spce.xml')
modeller.addSolvent(forcefield, boxSize=Vec3(5, 5, 5)*nanometers, neutralize=True, negativeIon='Cl-', positiveIon='Na+')
```

I tried CHARMM Drude just since it's also polarizable, although a different implementation, and it works fine also with utilization on both GPUs with both versions of cudatoolkit. 

```
forcefield = ForceField('charmm_polar_2019.xml')
modeller.addExtraParticles(forcefield)
modeller.addSolvent(forcefield, boxSize=Vec3(5, 5, 5)*nanometers, neutralize=True, negativeIon='Cl-', positiveIon='Na+', model="swm4ndp")
```

I couldn't find other issues where something similar was mentioned. My cluster uses slurm, but I have tested allocating more GPUs in the slurm bash script than defined in the OpenMM python script and everything behaves normally, as long as I don't allocate less than the python script tries to define. So I'm not quite sure how to debug further...

**Comment by peastman** [comment]
I don't think AmoebaMultipoleForce works with multiple GPUs.  In fact, I thought it would throw an exception if you tried to, but I don't see it doing that.  Computing the induced dipoles requires a complex multi-step process that's hard to parallelize efficiently over multiple GPUs, and it doesn't even try to.

**Comment by andrewsb8** [comment]
Ok, thanks for your help! I'll have to tune some conditions of the simulation, like the ewalderrortolerance, to run on one gpu. Single gpu for a couple thousand atoms is like 15 ns/day due to the complexity of the calculations!

**Comment by peastman** [comment]
A good GPU should be much faster than that with only 2000 atoms.  See the benchmarks at https://openmm.org/benchmarks.  Using AMOEBA to simulate DHFR (23,558 atoms), most GPUs are somewhere between 15 and 25 ns/day.

**Comment by andrewsb8** [comment]
Interesting, I'll try a few more runs and see if the performance I'm seeing remains consistent.

**Comment by andrewsb8** [comment]
I've circled back to this recently and I'm having issues pinning down which parameter would be slowing my simulations down this much relative to the benchmark. I'm not specifying ewald or mutual polarization tolerance so I should be using the defaults of 5*10^-5 and 10^-5. Here are my potential culprits:
- My cutoffs are slightly larger than the two defined in the benchmark but shouldn't be reducing performance by this much. Mine is 1 nm as opposed to .9 nm and .7 nm.
- The nonbonded forces are also only calculated every 2 fs and bonded every fs. If this is not default, then I'm calculating both every fs which could effect performance especially since nonbonded forces are more intensive to calculate.
- I'm using mutual polarization and the polarization method is not specified in the benchmark. If direct polarization was used in the benchmark, this would affect comparison of performance.
- I'm using default GPU precision (mixed?) and the benchmark does not specify. If default is double and benchmark uses mixed, then this could also affect performance.

I am unsure if I will be able to do a true sensitivity analysis for each of these parameters. So, I'm interested in your opinion about these different factors regarding simulation performance.

I know this is not the original topic of the issue. If appropriate, I could open a new one rather than discuss here. So let me know if that would be preferred. Thanks.

**Comment by peastman** [comment]
You can test and see what factors are most important.  The longer cutoff and the smaller time step will both have significant effects, and some of the others might too.  I suggest looking at the [benchmarking script](https://github.com/openmm/openmm/blob/master/examples/benchmark.py), copying exactly what it does, and seeing how your performance is.
