### ISSUE TITLE
Compiling openmm-8.0.0 from source

### ISSUE THREAD

**Issue by daipayans** [openmm/openmm#4041]
Hi, 
I am trying to compile openmm-8.0.0 from source. Based on the documentation ([http://docs.openmm.org/latest/userguide/library/02_compiling.html]), I am able to build into /usr/local/openmm as I have sudo priviledge on the workstation, I am trying to compile OpenMM. 

However, 8.1.6. Step3: Install the Python API is not working for me. Here, sudo make PythonInstall, complains that it cannot find module Cython. This however is not true, as simply running python3 on a terminal window followed by "from Cython.Build import cythonize", doesn't give the same error. I have made sure that ccmake is pointing to the correct PYTHON_EXECUTABLE                /usr/bin/python3. 

```
[  0%] Built target ApiWrappers
[ 44%] Built target OpenMM
[ 44%] Building OpenMM Python binary module...
OPENMM_LIB_PATH = /usr/local/openmm/lib
OPENMM_INCLUDE_PATH = /home/dsarkar/bin/openmm-8.0.0/./include/home/dsarkar/bin/openmm-8.0.0/./include/openmm/home/dsarkar/bin/openmm-8.0.0/./include/openmm/internal/home/dsarkar/bin/openmm-8.0.0/openmmapi/include/home/dsarkar/bin/openmm-8.0.0/openmmapi/include/openmm/home/dsarkar/bin/openmm-8.0.0/openmmapi/include/openmm/internal/home/dsarkar/bin/openmm-8.0.0/olla/include/home/dsarkar/bin/openmm-8.0.0/olla/include/openmm/home/dsarkar/bin/openmm-8.0.0/olla/include/openmm/internal/home/dsarkar/bin/openmm-8.0.0/serialization/include/home/dsarkar/bin/openmm-8.0.0/serialization/include/openmm/home/dsarkar/bin/openmm-8.0.0/serialization/include/openmm/internal/home/dsarkar/bin/openmm-8.0.0/plugins/amoeba/openmmapi/include/home/dsarkar/bin/openmm-8.0.0/plugins/amoeba/openmmapi/include/openmm/home/dsarkar/bin/openmm-8.0.0/plugins/amoeba/openmmapi/include/openmm/internal/home/dsarkar/bin/openmm-8.0.0/plugins/rpmd/openmmapi/include/home/dsarkar/bin/openmm-8.0.0/plugins/rpmd/openmmapi/include/openmm/home/dsarkar/bin/openmm-8.0.0/plugins/rpmd/openmmapi/include/openmm/internal/home/dsarkar/bin/openmm-8.0.0/plugins/drude/openmmapi/include/home/dsarkar/bin/openmm-8.0.0/plugins/drude/openmmapi/include/openmm/home/dsarkar/bin/openmm-8.0.0/plugins/drude/openmmapi/include/openmm/internal
/home/dsarkar/bin/openmm-8.0.0/build/python/setup.py:11: DeprecationWarning: The distutils package is deprecated and slated for removal in Python 3.12. Use setuptools or check PEP 632 for potential alternatives
  from distutils.core import setup
Traceback (most recent call last):
  File "/home/dsarkar/bin/openmm-8.0.0/build/python/setup.py", line 12, in <module>
    from Cython.Build import cythonize
ModuleNotFoundError: No module named 'Cython'
[ 44%] Installing OpenMM Python binary module...
OPENMM_LIB_PATH = /usr/local/openmm/lib
OPENMM_INCLUDE_PATH = /home/dsarkar/bin/openmm-8.0.0/./include/home/dsarkar/bin/openmm-8.0.0/./include/openmm/home/dsarkar/bin/openmm-8.0.0/./include/openmm/internal/home/dsarkar/bin/openmm-8.0.0/openmmapi/include/home/dsarkar/bin/openmm-8.0.0/openmmapi/include/openmm/home/dsarkar/bin/openmm-8.0.0/openmmapi/include/openmm/internal/home/dsarkar/bin/openmm-8.0.0/olla/include/home/dsarkar/bin/openmm-8.0.0/olla/include/openmm/home/dsarkar/bin/openmm-8.0.0/olla/include/openmm/internal/home/dsarkar/bin/openmm-8.0.0/serialization/include/home/dsarkar/bin/openmm-8.0.0/serialization/include/openmm/home/dsarkar/bin/openmm-8.0.0/serialization/include/openmm/internal/home/dsarkar/bin/openmm-8.0.0/plugins/amoeba/openmmapi/include/home/dsarkar/bin/openmm-8.0.0/plugins/amoeba/openmmapi/include/openmm/home/dsarkar/bin/openmm-8.0.0/plugins/amoeba/openmmapi/include/openmm/internal/home/dsarkar/bin/openmm-8.0.0/plugins/rpmd/openmmapi/include/home/dsarkar/bin/openmm-8.0.0/plugins/rpmd/openmmapi/include/openmm/home/dsarkar/bin/openmm-8.0.0/plugins/rpmd/openmmapi/include/openmm/internal/home/dsarkar/bin/openmm-8.0.0/plugins/drude/openmmapi/include/home/dsarkar/bin/openmm-8.0.0/plugins/drude/openmmapi/include/openmm/home/dsarkar/bin/openmm-8.0.0/plugins/drude/openmmapi/include/openmm/internal
/home/dsarkar/bin/openmm-8.0.0/build/python/setup.py:11: DeprecationWarning: The distutils package is deprecated and slated for removal in Python 3.12. Use setuptools or check PEP 632 for potential alternatives
  from distutils.core import setup
Traceback (most recent call last):
  File "/home/dsarkar/bin/openmm-8.0.0/build/python/setup.py", line 12, in <module>
    from Cython.Build import cythonize
ModuleNotFoundError: No module named 'Cython'
[100%] Built target PythonInstall
```

Next, as the prompt reports 100% built target python install, testing if openmm was installed generates the following error. 
```
python3 -m openmm.testInstallation
/usr/bin/python3: Error while finding module specification for 'openmm.testInstallation' (ModuleNotFoundError: No module named 'openmm')
```
Kindly advise on where I am going wrong. Many thanks in advance for your help. 

Best, 
Daipayan

**Comment by peastman** [comment]
I strongly recommend against using the system python.  It's much better to install a copy of miniconda inside your home directory.  That gives you complete control over what python version you use, and you don't need to use sudo, and you can create multiple environments to avoid conflicts between packages that may have incompatible requirements.

In CMake, what is `PYTHON_EXECUTABLE` set to?

**Comment by daipayans** [comment]
Thanks for your recommendation. However, as I am not very familiar with building environments within conda, I will have to look in how to compile OpenMM from source using miniconda. Can you suggest some documentation for this?

Currently, in CMake, the `PYTHON_EXECUTABLE`  is set to  `/usr/bin/python3`. The version of python is 3.10.6.

**Comment by peastman** [comment]
Just download and install it from https://docs.conda.io/en/latest/miniconda.html.  The installer can automatically configure your path so that `python` points to it.  You also can create different environments with different packages and even different python versions.  See https://conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html.

**Comment by xavgit** [comment]
Hi,
I have exactly the same problem of the previous user.
In my shell I read: 
$ python3
Python 3.10.6 (main, Mar 10 2023, 10:55:28) [GCC 11.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from Cython.Build import cythonize
>>> 
Therefore I guess that the error do not arise from python and the installed packages.
It is possible to receive another bit of help to avoid this problem?

Many thanks.

Saverio

**Comment by xavgit** [comment]
Hi,
sorry for the incomplete output of the shell.
It is:
$ python3
Python 3.10.6 (main, Mar 10 2023, 10:55:28) [GCC 11.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
\>>> from Cython.Build import cythonize
\>>>

**Comment by sef43** [comment]
So the problem is that you are using the system installed version of python. It will be much easier if you use conda, create a new conda environment, and use the conda version of python. 

See here and follow the instructions for Miniconda: https://docs.conda.io/projects/conda/en/stable/user-guide/install/linux.html#install-linux-silent

Then once you are able to use `conda`  and have created and activated a new conda environment you can follow the insructions here: http://docs.openmm.org/latest/userguide/library/02_compiling.html#compiling-on-linux-and-mac

**Comment by peastman** [comment]
Yeah, this is an annoying thing about conda.  There's no clean way to install a conda package while building one of its dependencies from source.  You'll need to install pdbfixer from source as well.  Fortunately that's very easy, since it's pure Python.

**Comment by xavgit** [comment]
Hi peastman,
thanks for your suggestion.

A last question.
I have made the compilation steps without conda even with the PYTHON_EXECUTABLE set both  to /usr/bin/python3.10
and /usr/bin/python3 receiving the same error using sudo make PythonInstall.

Traceback (most recent call last):
  File "/home/xxxx/sources/openmm-master-8.0.0/build/python/setup.py", line 11, in <module>
    from Cython.Build import cythonize
ModuleNotFoundError: No module named 'Cython'
[100%] Built target PythonInstall

But if I use make PythonInstall it seems that make is able to produce the module(s) as can be seen in the 
attached file make_PythonInstall.out.zip but with an obvious 
error: could not create '/usr/local/lib/python3.10/dist-packages/simtk': Permission denied

Do you have an idea about this?

Thanks again for your time.
Saverio

[make_PythonInstall.out.zip](https://github.com/openmm/openmm/files/11522076/make_PythonInstall.out.zip)

**Comment by peastman** [comment]
You're still using the system Python.  You should set it to the one inside your conda environment.

**Comment by xavgit** [comment]
Hi peastman,
no, no I have used your suggestions and compiled from the sources using conda first OpenMM and then pdbfixer
The "last question" was only a curiosity.
I have executed the first section of prody code for clustenmd but I receive an error:

@> PDB file is found in working directory (1tw7.pdb).
@> 1890 atoms and 1 coordinate set(s) were parsed in 0.03s.
@> Fixing the structure ...
@> 3108 atoms and 1 coordinate set(s) were parsed in 0.04s.
@> The structure was fixed in 0.92s.
@> Kirchhoff was built in 0.07s.
@> Generation 0 ...
@> Minimization & heating-up in generation 0 ...
@> WARNING OpenMM exception: Unit "kilojoule/mole" is not compatible with Unit "kilojoule/(nanometer*mole)". so the corresponding conformer will be discarded!
Traceback (most recent call last):
  File "/home/xxxx/ClustENMD/1tw7/run_simulation.py", line 11, in <module>
    clustenm.run( n_modes= 3 , n_gens = 5 , maxclust = tuple( range( 20 , 120 , 20 ) ) ,  sim = True , solvent = 'imp' , t_steps_i = 0 , t_steps_g = 0 , platform = 'CUDA' )
  File "/home/xxxx/miniconda3/envs/prody_env/lib/python3.11/site-packages/prody/dynamics/clustenm.py", line 1077, in run
    raise ValueError('Initial structure could not be minimized. Try again and/or check your structure.')
ValueError: Initial structure could not be minimized. Try again and/or check your structure.

 The pdb Id is that of prody example.

If I run the same code with the OpenMM installed with apt in Ubuntu 22.04 , without the platform='CUDA' argument  ,the execution is very slow but without errors.
 ./run_simulation.py 
@> PDB file is found in working directory (1tw7.pdb).
@> 1890 atoms and 1 coordinate set(s) were parsed in 0.02s.
@> Fixing the structure ...
@> 3108 atoms and 1 coordinate set(s) were parsed in 0.03s.
@> The structure was fixed in 2.59s.
@> Kirchhoff was built in 0.01s.
@> Generation 0 ...
@> Minimization & heating-up in generation 0 ...
@> Completed in 854.04s.
@> #-------------------/*\-------------------#
@> Generation 1 ...
@> Sampling conformers in generation 1 ...
@> Hessian was built in 0.06s.
@> 3 modes were calculated in 0.08s.
@> Parameter: rmsd = 1.00 A
@> Parameter: n_confs = 50
@> Modes are scaled by 28.092585901979998.
@> Clustering in generation 1 ...
@> Centroids were generated in 0.26s.
@> Minimization & heating-up in generation 1 ...

I'll post a question to the prody team.

Thanks.
Saverio

**Comment by peastman** [comment]
I don't understand what you were asking then.  In your previous post you said,

>  I have made the compilation steps without conda even with the PYTHON_EXECUTABLE set both to /usr/bin/python3.10 and /usr/bin/python3 receiving the same error using sudo make PythonInstall.

That's the system python, not the one in your conda environment.

>  @> WARNING OpenMM exception: Unit "kilojoule/mole" is not compatible with Unit "kilojoule/(nanometer*mole)". so the corresponding conformer will be discarded!

Something in the code is mixing up incompatible units.  kJ/mol is a unit of energy, and kJ/mol/nm is a unit of force.  That error could be caused by trying to add a force and an energy to each other, or interpret an energy as a force, or something similar.

**Comment by xavgit** [comment]
Hi,
for the PYTHON_EXECUTABLE ..... it is not important.
For the warning I have  used, in the conda environment, pip to uninstall pdbfixer and openmm compiled from sources.
Then I have reinstalled the previous packages with conda.
Now the same script works fine. 
With only cpu
@> Generation 0 ...
@> Minimization & heating-up in generation 0 ...
@> Completed in 854.04s.
With CUDA and an old RTX 2080Ti
@> Generation 0 ...
@> Minimization & heating-up in generation 0 ...
@> Completed in 2.79s.
Very^2 good.

Thanks for the helps and the packages.

Saverio

**Comment by huangjianxiangzju** [comment]
> Hi, for the PYTHON_EXECUTABLE ..... it is not important. For the warning I have used, in the conda environment, pip to uninstall pdbfixer and openmm compiled from sources. Then I have reinstalled the previous packages with conda. Now the same script works fine. With only cpu @> Generation 0 ... @> Minimization & heating-up in generation 0 ... @> Completed in 854.04s. With CUDA and an old RTX 2080Ti @> Generation 0 ... @> Minimization & heating-up in generation 0 ... @> Completed in 2.79s. Very^2 good.
> 
> Thanks for the helps and the packages.
> 
> Saverio

Hi. Just for you reference. I had the same problem with you. It occurred to me that during the authors of clustENM were developing, they were supposed to use an older version of OpenMM. So I used conda to install OpenMM7.7.0 with python3.8. It works now.
