### ISSUE TITLE
Particle positions have not been set

### ISSUE THREAD

**Issue by H-EKE** [openmm/openmm#4056]
Hi,I'm trying to write a script, where I minimize, then I apply constraints to the backbone, I perfomr gradual heating, then NPt equilibration while I decrease the constraints, and finally production.

When I run hte following script 
```
from openmm import *
from openmm.app import *
from openmm.unit import *
from sys import stdout

# Load CHARMM files
psf = CharmmPsfFile('step3_input.psf')
pdb = PDBFile('step3_input.pdb')
params = CharmmParameterSet('toppar/top_all36_prot.rtf', 'toppar/par_all36m_prot.prm','toppar/top_all36_lipid.r
tf', 'toppar/par_all36_lipid.prm','toppar/toppar_water_ions.str')

# Create an openmm system
system = psf.createSystem(params, nonbondedMethod=CutoffNonPeriodic, nonbondedCutoff=0.9 * nanometer,
                           constraints=HBonds, rigidWater=True, ewaldErrorTolerance=0.0005)

# Apply constraints to the backbone
backbone_atoms = [atom.index for atom in psf.topology.atoms() if atom.name in ('CA', 'N', 'C', 'O')]
constraint_force = HarmonicBondForce()
for i in range(len(backbone_atoms)-1):
    constraint_force.addBond(backbone_atoms[i], backbone_atoms[i+1], 0.5 * nanometer, 1.0 * kilocalorie_per_mol
e / angstrom ** 2)
system.addForce(constraint_force)

# Set up the integrator for minimization
integrator_minimization = LangevinIntegrator(100 * kelvin, 1 / picosecond, 0.002 * picoseconds)

# Set up the simulation for minimization
platform = Platform.getPlatformByName('CUDA')
properties = {'CudaPrecision': 'mixed', 'DeviceIndex': '0'}
simulation = Simulation(psf.topology, system, integrator_minimization, platform, properties)
# Set the positions for the simulation
simulation.context.setPositions(pdb.positions)

# Minimization
print("Minimizing...")
simulation.minimizeEnergy()
# Save the final minimized structure to a PDB file
PDBFile.writeFile(simulation.topology, simulation.context.getState(getPositions=True).getPositions(), open(
'minimized_structure.pdb', 'w'))

# Set up the integrator for gradual heating
integrator_heating = LangevinIntegrator(100 * kelvin, 1 / picosecond, 0.002 * picoseconds)

# Set up the simulation for gradual heating
simulation = Simulation(psf.topology, system, integrator_heating, platform, properties)

# Gradual heating
print("Gradually heating...")
heating_time = 50 * nanosecond
number_of_steps = int(heating_time / (0.002 * picoseconds))
temperature_increment = 5 * kelvin / number_of_steps
for i in range(number_of_steps):
    temperature = 100 * kelvin + i * temperature_increment
    integrator_heating.setTemperature(temperature)
    simulation.step(1)

# Set up the integrator for NPT equilibration
integrator_equilibration = LangevinIntegrator(300 * kelvin, 1 / picosecond, 0.002 * picoseconds)
barostat = MonteCarloMembraneBarostat(1 * bar, 200 * bar * nanometer, MonteCarloMembraneBarostat.XYIsotropic,
                                      MonteCarloMembraneBarostat.ZFree, 300 * kelvin)
system.addForce(barostat)

# Set up the simulation for NPT equilibration
simulation = Simulation(psf.topology, system, integrator_equilibration, platform, properties)

# Set up the integrator for NPT equilibration
integrator_equilibration = LangevinIntegrator(300 * kelvin, 1 / picosecond, 0.002 * picoseconds)
pressure = 1.0 * bar
barostat = MonteCarloBarostat(pressure, temperature, frequency)
system.addForce(barostat)

# Set up the simulation for NPT equilibration
simulation = Simulation(psf.topology, system, integrator_equilibration, platform, properties)

# NPT equilibration with decreasing restraint
print('Running NPT equilibration with decreasing restraint')
equilibration_time = 30 * nanosecond
n_equilibration_steps = int(equilibration_time / (0.002 * picoseconds))
for i in range(n_equilibration_steps):
    current_restraint_distance = 0.5 * nanometer * (n_equilibration_steps - i) / n_equilibration_steps
    constraint_force.setGlobalParameterDefaultValue(0, current_restraint_distance)
    simulation.step(1)

# Remove the MonteCarloBarostat from the system after equilibration
for force in system.getForces():
    if isinstance(force, MonteCarloBarostat):
        system.removeForce(force)
        break

# Apply hydrogen mass repartitioning for production
repartitioned_system = ommtools.utils.hmr(system, residueList=None, scaling_factor=4)

# Set up the integrator for production
integrator_production = LangevinIntegrator(310 * kelvin, 0.1 / picosecond, 0.004 * picoseconds)

# Set up the simulation for production
simulation = Simulation(psf.topology, repartitioned_system, integrator_production, platform, properties)

# Production with hydrogen mass repartitioning
print('Running production with hydrogen mass repartitioning')
production_time = 500 * nanosecond
n_production_steps = int(production_time / (0.004 * picoseconds))
simulation.reporters.append(DCDReporter('production.dcd', 1000))
simulation.reporters.append(StateDataReporter('production.log', n_production_steps // 10, step=True, potentialE
nergy=True,
                                               temperature=True, progress=True, remainingTime=True, speed=True)
)
for i in range(n_production_steps):
    simulation.step(1)
```

I get this error

Gradually heating...
Traceback (most recent call last):
  File "script.py", line 52, in <module>
    simulation.step(1)
  File "/opt/ohpc/pub/libs/miniconda/4.10.3/envs/openmm1/lib/python3.8/site-packages/openmm/app/simulation.py",
 line 141, in step
    self._simulate(endStep=self.currentStep+steps)
  File "/opt/ohpc/pub/libs/miniconda/4.10.3/envs/openmm1/lib/python3.8/site-packages/openmm/app/simulation.py",
 line 210, in _simulate
    self.integrator.step(stepsToGo)
  File "/opt/ohpc/pub/libs/miniconda/4.10.3/envs/openmm1/lib/python3.8/site-packages/openmm/openmm.py", line 43
27, in step
    return _openmm.LangevinIntegrator_step(self, steps)
openmm.OpenMMException: Particle positions have not been set
````

Any idea about how I could fix this issue/improve my code?
Thanks!

**Comment by sef43** [comment]
In your script you create a new `Simulation` for each of your setup steps (minimize, heating, NPT, etc...). You will need to have a corresponding `simulation.context.setPositions` to set the positions as the error message is telling you.

**Comment by H-EKE** [comment]
Dear @sef43,

Thanks for your fast reply! I'm quite new in scripting. How I could use the ouput from minimization to do the equlibration, and the one from equilibration to do production?

**Comment by sef43** [comment]
There are two ways to achieve what you want:
1. store the positions from the previous part and then set them after you make a new simulation, e.g.:
``` python
# minimization 

minimized_positions = simulation.context.getState(getPositions=True).getPositions()

# new simulation settings 

simulation = Simulation(...)
simulation.context.setPositions(minimized_positions)
```

2. keep the same `System` and `Simulation` object and update the thermostat and barostats after minimization, take a look at these examples: 
https://openmm.github.io/openmm-cookbook/latest/notebooks/tutorials/protein_in_water.html  
https://openmm.github.io/openmm-cookbook/latest/notebooks/cookbook/Changing%20Temperature%20and%20Pressure.html

**Comment by H-EKE** [comment]
Thank you so much!!
