### ISSUE TITLE
unsupported operand error

### ISSUE THREAD

**Issue by OkKakao** [openmm/openmm#4059]
Hi

I'm trying to simulate keggin ion with custom forcefield, and encountered error.

This is my code.

```
from openmm.app import *
from openmm import *
from openmm.unit import *
from sys import stdout

name = 'PTA'
simulation_step = 1

params = CharmmParameterSet('PTA.prm')
psf = CharmmPsfFile(f'{name}.psf')
pdb = PDBFile(f'{name}.pdb')

platform = Platform.getPlatformByName('CUDA')
system = psf.createSystem(params, nonbondedMethod=NoCutoff, constraints=HBonds)

integrator = LangevinMiddleIntegrator(300*kelvin, 1/picosecond, 0.002*picoseconds)
simulation = Simulation(psf.topology, system, integrator, platform)
simulation.context.setPositions(pdb.positions)
simulation.minimizeEnergy()
simulation.reporters.append(PDBReporter('PTA_out.pdb', 1))
simulation.reporters.append(StateDataReporter(stdout, 1, step=True, potentialEnergy=True, temperature=True))
simulation.step(simulation_step)
```

Also, the following is the error message

```
Traceback (most recent call last):
  File "/home/compu/temp/PTA/PTA.py", line 14, in <module>
    system = psf.createSystem(params, nonbondedMethod=NoCutoff, constraints=HBonds)
  File "/home/compu/anaconda3/envs/openmmvenv/lib/python3.7/site-packages/openmm/app/charmmpsffile.py", line 1228, in createSystem
    force.addParticle(atm.charge, sigma_scale*atm.type.rmin*length_conv,
TypeError: unsupported operand type(s) for *: 'float' and 'NoneType'

Process finished with exit code 1
```

And here's my files.

[PTA.zip](https://github.com/openmm/openmm/files/11391419/PTA.zip)

I think that the error comes from the prm file, but I can't spot the problem...

**Comment by OkKakao** [comment]
Nevermind.....

I forgot to fill up one of the atom type.

I added description about O for nonbond interaction, and it worked well.
