### ISSUE TITLE
Unit compatibility bug?

### ISSUE THREAD

**Issue by lvotapka** [openmm/openmm#4069]
Hello,

I'm attempting to run the following script to compute a friction coefficient for input into a BrownianIntegrator:

```
from openmm import unit
temperature = 300*unit.kelvin
particle_molar_mass = 10.0*unit.amu
particle_mass = particle_molar_mass / unit.AVOGADRO_CONSTANT_NA
particle_mass = particle_mass.in_units_of(unit.kilograms)
beta = 1.0/(temperature * unit.BOLTZMANN_CONSTANT_kB)
beta = beta.in_units_of(unit.picoseconds**2 / (unit.nanometer**2 * unit.kilograms))
diffusion_coeff = 1.0 * unit.nanometers**2 / unit.picoseconds
friction_coeff = 1.0 / (beta*diffusion_coeff*particle_mass)
print("friction_coeff after:", friction_coeff.value_in_unit(1/unit.picoseconds))
```

When I run this, I get the following error:

```
Traceback (most recent call last):
  File "unit_error_script.py", line 14, in <module>
    print("friction_coeff after:", friction_coeff.value_in_unit(1/unit.picoseconds))
  File "/home/lvotapka/miniconda3/lib/python3.8/site-packages/openmm/unit/quantity.py", line 623, in value_in_unit
    val = self.in_units_of(unit)
  File "/home/lvotapka/miniconda3/lib/python3.8/site-packages/openmm/unit/quantity.py", line 659, in in_units_of
    raise TypeError('Unit "%s" is not compatible with Unit "%s".' % (self.unit, other_unit))
TypeError: Unit "/picosecond" is not compatible with Unit "1 /ps".
```

I may be missing something, or perhaps this is a bug in the unit library?

**Comment by peastman** [comment]
Change it to `value_in_unit(unit.picoseconds**-1)`.  `1/unit.picoseconds` is a Quantity (a value with attached units), not a unit.

**Comment by lvotapka** [comment]
Ah thank you that works! I'll remember that.
