### ISSUE TITLE
openmm.OpenMMException Error

### ISSUE THREAD

**Issue by jmkoral** [openmm/openmm#4073]
I recently upgraded OpenMM to version 8 and have since started receiving errors. Can someone help me determine what the issue is? Thank you in advance.

Warning: importing 'simtk.openmm' is deprecated.  Import 'openmm' instead.
mark1
mark100
Traceback (most recent call last):
  File "/cm/shared/apps/anaconda3/envs/SEEKR/seekr2/seekr2/run.py", line 853, in <module>
    run(model, instruction, min_total_simulation_length, 
  File "/cm/shared/apps/anaconda3/envs/SEEKR/seekr2/seekr2/run.py", line 578, in run
    anchor_info_to_run = choose_next_simulation_openmm(
  File "/cm/shared/apps/anaconda3/envs/SEEKR/seekr2/seekr2/run.py", line 208, in choose_next_simulation_openmm
    currentStep = get_current_step_openmm(
  File "/cm/shared/apps/anaconda3/envs/SEEKR/seekr2/seekr2/run.py", line 129, in get_current_step_openmm
    sim_openmm_obj = mmvt_sim_openmm.create_sim_openmm(
  File "/cm/shared/apps/anaconda3/envs/SEEKRNew/lib/python3.8/site-packages/seekr2-0+untagged.276.g3327298-py3.8.egg/seekr2/modules/mmvt_sim_openmm.py", line 230, in create_sim_openmm
    positions = add_simulation(
  File "/cm/shared/apps/anaconda3/envs/SEEKRNew/lib/python3.8/site-packages/seekr2-0+untagged.276.g3327298-py3.8.egg/seekr2/modules/mmvt_sim_openmm.py", line 154, in add_simulation
    sim_openmm.simulation = openmm_app.Simulation(
  File "/cm/shared/apps/anaconda3/envs/SEEKRNew/lib/python3.8/site-packages/openmm/app/simulation.py", line 103, in __init__
    self.context = mm.Context(self.system, self.integrator, platform, platformProperties)
  File "/cm/shared/apps/anaconda3/envs/SEEKRNew/lib/python3.8/site-packages/openmm/openmm.py", line 3749, in __init__
    _openmm.Context_swiginit(self, _openmm.new_Context(*args))
openmm.OpenMMException: Specified a Platform for a Context which does not support all required kernels

**Comment by jmkoral** [comment]
(SEEKRNew) xfang2@node09:~$ python -m openmm.testInstallation

OpenMM Version: 8.0
Git Revision: a7800059645f4471f4b91c21e742fe5aa4513cda

There are 4 Platforms available:

1 Reference - Successfully computed forces
2 CPU - Successfully computed forces
3 CUDA - Successfully computed forces
4 OpenCL - Successfully computed forces

Median difference in forces between platforms:

Reference vs. CPU: 6.31117e-06
Reference vs. CUDA: 6.7305e-06
CPU vs. CUDA: 7.44738e-07
Reference vs. OpenCL: 6.76294e-06
CPU vs. OpenCL: 8.07926e-07
CUDA vs. OpenCL: 2.71199e-07

All differences are within tolerance.

**Comment by jmkoral** [comment]
Tue May 16 17:28:49 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 470.57.02    Driver Version: 470.57.02    CUDA Version: 11.4     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ...  On   | 00000000:3B:00.0 Off |                  N/A |
| 27%   31C    P8    23W / 250W |      0MiB /  7982MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   1  NVIDIA GeForce ...  On   | 00000000:5E:00.0 Off |                  N/A |
| 27%   31C    P8     5W / 250W |      0MiB /  7982MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   2  NVIDIA GeForce ...  On   | 00000000:D8:00.0 Off |                  N/A |
| 27%   30C    P8    18W / 250W |      0MiB /  7982MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+

**Comment by peastman** [comment]
Can you provide details on exactly what you're doing, including your full script and any files needed to reproduce it?  Without that, it's impossible to know what's happening.

**Comment by jmkoral** [comment]
> Can you provide details on exactly what you're doing, including your full script and any files needed to reproduce it? Without that, it's impossible to know what's happening.

Thank you for the quick response. I am the administrator of the cluster, but I am going to try and get the researcher to respond to this thread with answers to your questions.

**Comment by xfang216** [comment]
Hi @peastman, thanks for helping with this. The program we are using is called Seekr2 which uses OpenMM as the simulation engine. The input files we have are for Seekr2 specifically and the program handles the interfacing with OpenMM. In this case, what files would you recommend providing to help you with the troubleshooting? 

Thank you!

**Comment by peastman** [comment]
You may need to contact the Seekr2 developers.  I can suggest a few things that might help for debugging.

The exception being thrown usually means one or more plugins aren't getting loaded.  Do you know whether Seekr2 provides any plugins of its own, or whether it's just using standard ones bundled with OpenMM?

Try starting a Python interpreter (the same one you use for running the program) and type the following commands.

```python
from openmm import *
print(Platform.getPluginLoadFailures())
```

It will tell you if any plugins failed to load, and hopefully provide useful error messages.

**Comment by xfang216** [comment]
Ah I see. Did that and it did show that there's an error loading a Seekr2 plugin. I will open up a thread on the Seekr2 github page. Thanks again for the help.

Error message fyi:
'Error loading library /cm/shared/apps/anaconda3/envs/SEEKR/lib/plugins/libSeekr2PluginCUDA.so: /cm/shared/apps/anaconda3/envs/SEEKR/lib/plugins/libSeekr2PluginCUDA.so: undefined symbol: _ZN6OpenMM9CudaArray10initializeERNS_14ComputeContextEiiRKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE'

**Comment by peastman** [comment]
From the error message, I suspect this is an ABI incompatibility.  Some libraries were compiled with the C++11 ABI and others with the older one.  See https://gcc.gnu.org/onlinedocs/libstdc++/manual/using_dual_abi.html.
