### ISSUE TITLE
Particle coordinate is NaN after a few nanoseconds using DrudeNoseHooverIntegrator

### ISSUE THREAD

**Issue by Alexandrina-Chen** [openmm/openmm#4121]
Dear OpenMM community,

Hope this finds you well.

I am recently testing the DrudeNoseHooverIntegrator for an ionic liquid system. I first equilibrate the system with the Langevin integrator since it is more robust. I find that it actually cannot control the Drude pairs dofs at the temperature as low as I set (1K), and there is strong heat flow from the normal dof to the Drude dofs, which also makes the normal dofs temperature lower than setting. So I want to use the DrudeNoseHooverIntegrator for a comparison reason and also for possible better dynamic properties.

First, I equilibrate my system using DrudeLangevinIntegrator for 20 ns with frictionCoeff = drudeFrictionCoeff= 10/ps and timestep = 1 fs. Then I save the last state of the equilibration as an .xml file and load it for the next DrudeNoseHooverIntegrator run. I tried different collisionFrequencies (10/ps and 1/ps) , drudeCollisionFrequencies (50/ps, 10/ps, 1/ps) and timesteps (1 fs, 0.5 fs, even 0.2 fs), but the run always collapses after a few ns (even hundreds of ps if I use a high collision frequency). The shorter the timestep is, the longer the run would survive. But it will finally collapse even using 0.2 fs timestep with the following error. 

```
Traceback (most recent call last):
  File "/beagle3/gavoth/sijiachen/Project/RTIL_Jesse3/test/JP-Small-2/run_openMM.py", line 118, in <module>
    simmd.step( int(freq_potential_output_ps / time_step_ps))
  File "/home/sijiachen/.conda/envs/openmm0800/lib/python3.9/site-packages/openmm/app/simulation.py", line 141, in step
    self._simulate(endStep=self.currentStep+steps)
  File "/home/sijiachen/.conda/envs/openmm0800/lib/python3.9/site-packages/openmm/app/simulation.py", line 206, in _simulate
    self.integrator.step(10) # Only take 10 steps at a time, to give Python more chances to respond to a control-c.
  File "/home/sijiachen/.conda/envs/openmm0800/lib/python3.9/site-packages/openmm/openmm.py", line 8792, in step
    return _openmm.NoseHooverIntegrator_step(self, steps)
openmm.OpenMMException: Particle coordinate is NaN.  For more information, see https://github.com/openmm/openmm/wiki/Frequently-Asked-Questions#nan
```
The energy always seems steady in my output. 

Since I save the checkpoint .xml file every 1 ns, I also tried to restart the simulation from the latest xml file, and it survived almost the same number of timesteps like the last run. Therefore, I feel it is not because of a bad initial configuration.

I attach an example run with all the inputs and some of my outputs for reference. This is a test system with 4000 real atoms and 2500 Drude particles in an air-liquid-air system. My actual system is 10 times bigger, but the problem is the same. 

I would appreciate any help! Thank you in advance.

Best,
Sijia

[example_drude_nh.tar.gz](https://github.com/openmm/openmm/files/11811773/example_drude_nh.tar.gz)

**Comment by peastman** [comment]
If DrudeLangevinIntegrator can't maintain the temperatures, then I suspect there's something else wrong in your system.  The integrator itself doesn't create any heat flow between degrees of freedom.  Rather, each degree of freedom is independently coupled to the heat bath.  Any flow between them is due to actual physical interactions within your system.

There isn't any situation when I would recommend using Nose-Hoover instead.  Langevin is more robust, has better theoretical properties, and is much faster.

Have you experimented with different friction coefficients in the DrudeLangevinIntegrator?

**Comment by Alexandrina-Chen** [comment]
Thank you for the advice! I have tested different friction coefficients previously. With larger friction coefficients (10/ps and 50/ps for system and drude, respectively), the results look much better. The force field for ionic liquids is difficult and complicated, and I agree that part of the bad behavior is because of the force field itself. Actually, I was not complaining the Langevin integrator and I really like it. There was one paper I read about the behavior of different thermostats for kinds of systems with different parameters (https://pubs.acs.org/doi/10.1021/acs.jpclett.9b02983).

But my final goal is actually to compare the results from the two integrators (as a benchmark). However, I cannot even have a trajectory from the Nose-Hoover integrator, since there is always the error "Particle coordinate is NaN" after several nanoseconds, while things work fine with Langevin for hundreds of nanoseconds. 

My question is actually from the strange behavior here. For example, I run the example test (attached above) from t=0, and the error appears after ~4680 ps. Then if I restart the simulation from a state file (.xml) stored at 4000ps, it would also survive for a very similar timesteps (at ~ 8680 ps) before the same error shows up. Again, if I restart from the state at 8000ps, it will come to the same error at ~ 12680 ps. 

While with different parameters, the timesteps it takes to failure are different, but it is repeatable. 

Therefore, I feel this is a strange behavior and it may need some attention. Sorry if I have any wrong assumption.
