### ISSUE TITLE
any way to run gromacs simulation in openmm successfully

### ISSUE THREAD

**Issue by zhangdai-hub** [openmm/openmm#4122]
We want to use openmm to execute gromacs' simulation. And we have prepared two gromax input files(.gro and .top) and openmm's scripts.
At first, we execute sub.sh under the test_01 folder that requires stmv01.top and em.gro. An error was encountered and the error message is as follows:
Traceback (most recent call last):
```
  File "/home/zhonggkxydlhxwlyjsuo/whs_guohui/test_big_system/zhangyb/spike_new/sys1/openmm-gmx/test_old/./openmm_read_gmx.py", line 40, in <module>
    simulation = Simulation(top.topology, system, integrator, platform, properties)
  File "/share/ccsuite/Other_support/anaconda3/lib/python3.9/site-packages/simtk/openmm/app/simulation.py", line 105, in __init__
    self.context = mm.Context(self.system, self.integrator, platform, platformProperties)
  File "/share/ccsuite/Other_support/anaconda3/lib/python3.9/site-packages/simtk/openmm/openmm.py", line 13232, in __init__
    _openmm.Context_swiginit(self, _openmm.new_Context(*args))
simtk.openmm.OpenMMException: The System has two constraints between the same atoms.  This will produce a singular constraint matrix.
```

We also made some attempts to remove some text content inside 'stmv01.top' file and modify it to 'stmv01_opmm.top' for dealing with this error. 'stmv01.top' file are deleted as follows:

```
#ifdef FLEXIBLE

[ bonds ]
;    ai     aj funct         c0         c1         c2         c3
      1      2     1   0.09572 376560.000000
      1      3     1   0.09572 376560.000000
      2      3     1   0.15139 0.000000

[ angles ]
;    ai     aj     ak funct         c0         c1         c2         c3
      2      1      3     5   104.5200000 460.240000 0.0000000 0.000000


#else





#endif
```

you could also see the difference in the content of the two files by taking a screenshot of the different.png, with stmv01_opmm.top on the left and stmv01.top on the right.
![different](https://github.com/openmm/openmm/assets/114983517/002c49e2-3281-498e-a0ff-f1698e5234e7)

Then we execute sub.sh under test_02 folder that requires stmv01_opmm.top and em.gro.
The simulation dosen't output the above error message, but we get into another trouble that our simulation stops at minimization and cannot proceed to the next step. Even though we modify the number of minimization steps to 1, the same result is obtained.
So, what do I have to do to run successfully and thanks for all the suggestions.
We upload all execution files. You can download it and execute if you are interested. Thank you to everyone who saw here.

[04_openmm_gmx.zip](https://github.com/openmm/openmm/files/11815645/04_openmm_gmx.zip)

**Comment by sef43** [comment]
Hello,

The error 
`simtk.openmm.OpenMMException: The System has two constraints between the same atoms.  This will produce a singular constraint matrix.`
 as you have determined is coming from the water molecules.

If you remove the 3rd bond definition for TIP3 in `stmv01.top` then it will work. e.g:
```
[ bonds ]
;    ai     aj funct         c0         c1         c2         c3
      1      2     1   0.09572 376560.000000
      1      3     1   0.09572 376560.000000

[ angles ]
;    ai     aj     ak funct         c0         c1         c2         c3
      2      1      3     5   104.5200000 460.240000 0.0000000 0.000000


```

The issue is that this is defining a bond between the two H atoms, while there is already the angle defined between H-O-H. This H-H bond caused the double constraint. Looking at standard TIP3 topology definitions they do not have this H-H bond, e.g. https://gitlab.com/gromacs/gromacs/-/blob/main/share/top/amber99.ff/tip3p.itp

**Comment by zhangdai-hub** [comment]
Hello

At first, thank you for your advice, we benefited a lot. We tried to avoid this error by annotating the definition of the third line, but the result is still stopping at minimization and cannot proceed to the next step.

The following is a comparison of the content of the modified two files as you suggest:
On the left is the content of the annotated file, and on the right is the original file.
![differnce](https://github.com/openmm/openmm/assets/114983517/84d52dd1-bf41-4d68-9495-f538c84451b8)


So, i would like to ask if you have any other suggestions. Thank you again for your suggestion and look forward to hearing from you again.

**Comment by sef43** [comment]
Do your input .gro and .top files work when you use Gromacs?

You system has a very high initial energy 
`print(simulation.context.getState(getEnergy=True).getPotentialEnergy())`
458407849647.59357 kJ/mol

So the minimizer will be failing to minimize it. This suggests there might be something wrong with your initial structure, i.e clashes, wrong box vectors etc

**Comment by zhangdai-hub** [comment]
First of all, thank you very much for your generous answer, and we are very inspired.

we will further optimize our system and make some new attempts.
