### ISSUE TITLE
Killed performance on CPU jobs

### ISSUE THREAD

**Issue by jgrosskopf** [openmm/openmm#4311]
I am trying to run CPU simulations (due to extremely long queue times on our GPU cluster) and the performance is killed dramatically -- much more than I would have anticipated. The current CPU run with a single node (48 cores) is ~0.2ns/day on a 95,000 atom system. From previous experience using Gromacs (I know they're optimized differently) I expected 70-100ns/day. GPU runs fantastically at 280ns/day with 2 GPU and 24 cores.

Simulations are run using 4fs timestep, langevin middle integrator, HMR at 3.5*amu, and LJPME handling all nonbonded interactions.
Number of threads is set to default, which I believe is the number of cores detected. I tried manually setting the thread number and this had no change. I also tried using 16 and 24 cores as opposed to 48 -- I thought it could have been a strange scaling bug. 

Has anyone else ran into this issue? Are there any suggestions from here?

**Comment by jgrosskopf** [comment]
Yes, the command I'm using to get my platform is:
platform = Platform.getPlatformByName('CPU')

**Comment by peastman** [comment]
Just to be absolutely certain, can you print out `context.getPlatform().getName()`?  I suspect this for two reasons: first, because the CPU platform should be a lot faster, and second, because changing the number of threads ought to have some effect.

Can you post your script?

**Comment by jgrosskopf** [comment]
Sure thing. 

print(emin_simulation.context.getPlatform().getName()) gives: CPU

I've attached my file below. Please forgive the repetitive code (among other things) -- this is a work in progress for my lab to utilize. You'll see that the first step is a 1fs relaxation step, but I've also excluded this and ran with 4fs in previous scripts using the same system/build here.

[system_setup_run.txt](https://github.com/openmm/openmm/files/13352605/system_setup_run.txt)

**Comment by peastman** [comment]
That's a lot of code, and I'm not quite sure what part I should be looking at.  Could you create a minimal test case?  The simplest way is to write out your System, State, and Integrator to [XML files](https://openmm.github.io/openmm-cookbook/latest/notebooks/cookbook/Saving%20Systems%20to%20XML%20Files.html).  Post them here, and then I can try simulating them.

What kind of CPU are you running on?  The exact model number if possible.

**Comment by jgrosskopf** [comment]
Sorry about that. Here's an XML file of the system I'm working with. I had to zip it in order to share it here (sorry if this isn't common practice, trying to learn github more) 

[system.zip](https://github.com/openmm/openmm/files/13357252/system.zip)

I run on Intel 6240R CPUs

**Comment by peastman** [comment]
I need the state and integrator too.

**Comment by jgrosskopf** [comment]
Here's a PDB file as the state:

[eq1_1.zip](https://github.com/openmm/openmm/files/13358970/eq1_1.zip)

The integrator I used:

emin_integrator = LangevinMiddleIntegrator(310*kelvin, 1/picosecond, 0.001*picoseconds)
emin_integrator.setConstraintTolerance(0.000001)

**Comment by peastman** [comment]
Thanks!  I'll give it a try.

**Comment by jgrosskopf** [comment]
Hi, just wanted to follow up on this. Any ideas what I could do to move forward? Thanks!

**Comment by peastman** [comment]
I'm trying to reproduce it, but the files you posted aren't compatible with each other.  The System has 93276 particles, but the PDB file only has 93275.

**Comment by jgrosskopf** [comment]
That's strange. I provided CRD and PSF files here. Do either of these work?
[step5_input.zip](https://github.com/openmm/openmm/files/13384553/step5_input.zip)

**Comment by peastman** [comment]
That has the right number of particles, so I can load it in.  Your input conformation has huge forces, and also doesn't come close to satisfying the constraints.  If I try to simulate it, the system blows up almost immediately.  I tried running an energy minimization but it just flails, possibly because the constraints are so badly violated.

Here is how I'm setting up the simulation.  Does this match what you're doing?

```python
from openmm import *
from openmm.app import *
from openmm.unit import *

system = XmlSerializer.deserialize(open('system.xml').read())
psf = CharmmPsfFile('step5_input.psf')
crd = CharmmCrdFile('step5_input.crd')
integrator = LangevinMiddleIntegrator(310*kelvin, 1/picosecond, 0.001*picoseconds)
integrator.setConstraintTolerance(0.000001)
platform = Platform.getPlatformByName('CPU')
simulation = Simulation(psf.topology, system, integrator, platform)
simulation.context.setPositions(crd.positions)
```

**Comment by jgrosskopf** [comment]
Yes, this matches what I'm doing in terms of integrator and system. I was also using restraints releasing them in a step-wise fashion across 5 simulations -- I didn't expect it to blow up so badly right away without restraints which is why I didn't mention it. I put my restraint conditions and function below that I use in my first simulation. 

Here's the restraint parameters I'm using:

eq1_fc_bb       = 4000.0                            # Positional restraint force constant for protein backbone (kJ/mol/nm^2)
eq1_fc_sc       = 2000.0                            # Positional restraint force constant for protein side-chain (kJ/mol/nm^2)
eq1_fc_lpos     = 1000.0                            # Positional restraint force constant for lipids (kJ/mol/nm^2)
eq1_fc_ldih     = 1000.0                            # Dihedral restraint force constant for lipids (kJ/mol/rad^2)

Here's the function I use for restraints:

`def restraints(system, crd, pro_bb, pro_sc, lip, lip_dih):

    boxlx = system.getDefaultPeriodicBoxVectors()[0][0].value_in_unit(nanometers)
    boxly = system.getDefaultPeriodicBoxVectors()[1][1].value_in_unit(nanometers)
    boxlz = system.getDefaultPeriodicBoxVectors()[2][2].value_in_unit(nanometers)

    if pro_bb > 0 or pro_sc > 0:
        # positional restraints for protein
        posresPROT = CustomExternalForce('k*periodicdistance(x, y, z, x0, y0, z0)^2;')
        posresPROT.addPerParticleParameter('k')
        posresPROT.addPerParticleParameter('x0')
        posresPROT.addPerParticleParameter('y0')
        posresPROT.addPerParticleParameter('z0')
        for line in open('restraints/prot_pos.txt', 'r'):
            segments = line.strip().split()
            atom1 = int(segments[0])
            state = segments[1]
            xpos  = crd.positions[atom1].value_in_unit(nanometers)[0]
            ypos  = crd.positions[atom1].value_in_unit(nanometers)[1]
            zpos  = crd.positions[atom1].value_in_unit(nanometers)[2]
            if state == 'BB' and pro_bb > 0:
                fc_ppos = pro_bb
                posresPROT.addParticle(atom1, [fc_ppos, xpos, ypos, zpos])
            if state == 'SC' and pro_sc > 0:
                fc_ppos = pro_sc
                posresPROT.addParticle(atom1, [fc_ppos, xpos, ypos, zpos])
        system.addForce(posresPROT)

    if lip > 0:
        # positional restraints for bilayer lipid head group
        posresMEMB = CustomExternalForce('k*periodicdistance(0, 0, z, 0, 0, z0)^2;')
        posresMEMB.addGlobalParameter('k', lip)
        posresMEMB.addPerParticleParameter('z0')
        for line in open('restraints/lipid_pos.txt', 'r'):
            segments = line.strip().split()
            atom1 = int(segments[0])
            zpos  = crd.positions[atom1].value_in_unit(nanometers)[2]
            posresMEMB.addParticle(atom1, [zpos])
        system.addForce(posresMEMB)

    if lip_dih > 0:
        # dihedral restraints for lipids
        dihresMEMB = CustomTorsionForce('fc_ldih*max(0, abs(diff+wrap) - rwidth)^2; \
                                         wrap = 2*pi*(step(-diff-pi)-step(diff-pi)); \
                                         diff = theta - rtheta0; \
                                         rtheta0 = theta0*pi/180; \
                                         rwidth = width*pi/180;')
        dihresMEMB.addGlobalParameter('fc_ldih', lip_dih)
        dihresMEMB.addGlobalParameter('pi', 3.141592653589793)
        dihresMEMB.addPerTorsionParameter('width')
        dihresMEMB.addPerTorsionParameter('theta0')
        for line in open('restraints/dihe.txt', 'r'):
            segments = line.strip().split()
            atom1  = int(segments[0])
            atom2  = int(segments[1])
            atom3  = int(segments[2])
            atom4  = int(segments[3])
            theta0 = float(segments[4])
            width  = float(segments[5])
            dihresMEMB.addTorsion(atom1,atom2,atom3,atom4,[width,theta0])
        system.addForce(dihresMEMB)

    return system`

**Comment by peastman** [comment]
That doesn't explain why the constraints aren't satisfied, though.  If this is the result of equilibration, they should all be satisfied to high accuracy.

**Comment by jgrosskopf** [comment]
This isn't the result of the equilibration, but rather starting it. If the constraints aren't satisfied, this would mean that the Hbonds constraints are being satisfied, given the below code I use to set up the system, right?

`nonbondedMethod = LJPME             #using LJPME to handle NB forces
nonbondedCutoff = 1.2*nanometers    #cutoff for calculating NB forces
ewaldErrorTolerance = 0.0005        #default
constraints = HBonds                #constrains Hbond movements
rigidWater = True
constraintTolerance = 0.000001      
hydrogenMass = 3.5*amu             
temperature = 310*kelvin

system = psf.createSystem(params, 
                          nonbondedMethod=nonbondedMethod, 
                          nonbondedCutoff=nonbondedCutoff,
                          ewaldErrorTolerance=ewaldErrorTolerance,
                          rigidWater=rigidWater,
                          hydrogenMass=hydrogenMass,
                          constraints=constraints)  
system.addForce(barostat)`

**Comment by jgrosskopf** [comment]
Could you try energy minimizing and then simulating? I've never had an issue with blowing up after energy minimization. Thanks.

**Comment by peastman** [comment]
I managed to get it to run by just letting it minimize for a long time.  Here are the speeds I get on my laptop (a Mac M1 Pro).

OpenCL: 5.7 ns/day
CPU: 0.4 ns/day

That is indeed a much bigger gap than usual.  On this computer I typically get about a 2x speed difference between GPU and CPU, not >10x.  I profiled it and found that most of the time is spent computing the CustomNonbondedForce used for Lennard-Jones interactions.  It's needed because this system has NBFIX terms.  Usually we can use NonbondedForce for LJ, but it doesn't support NBFIX, so in that case we instead use a CustomNonbondedForce with the expression `"(a/r6)^2-b/r6; r6=r^6;a=acoef(type1, type2);b=bcoef(type1, type2)"`.  `acoef()` and `bcoef()` are tabulated functions.

On the GPU that works fine.  We generate CUDA or OpenCL source code for evaluating the expression and compile it to a kernel that's just as efficient as the built-in forces.  On the CPU platform we also JIT compile machine code to evaluate the expression, but it isn't always as efficient.  For the standard math operations like `-` and `/` it generates very efficient vectorized code.  But it can't do that for the table lookups.  Instead it has to extract each of the four elements from the input vectors, invoke the function that does table lookups four times, and reassemble the results into a new vector.

So this is unfortunately an inefficient case.  If you were using an Amber force field instead of a CHARMM one, the CPU platform would be a lot faster.

**Comment by jgrosskopf** [comment]
Okay I'm both relieved and disappointed that you get roughly what I do. So is the use of the LJ CustomnNnbondedForce due to using LJPME for nonbonded interactions? Can I remove the NBFIX terms? I've used PME in troubleshooting in the past but to no improvement. 

I'll try using Amber force field and see if I get improvements here. Are there any other recommendations you'd have for this system?

**Comment by peastman** [comment]
It isn't related to PME.  Some CHARMM force fields use NBFIX terms, which are particular pairs of atom types that use different LJ parameters from what the standard combination rules give.  None of the Amber force fields use them.  Try Amber14.

**Comment by jgrosskopf** [comment]
Thanks for your help, I really appreciate it. I'll try the Amber force fields soon and report back here.

**Comment by jgrosskopf** [comment]
I just got around to simulating using a Amber14 force fields (took a lot of trial and error because the topology templates weren't matching the force fields (I read https://github.com/openmm/openmm/wiki/Frequently-Asked-Questions#template and everything seemed to be in check). 

Anyways, once I got the system working I only got an improvement to 1.3 ns/day on 48 cores and 1.3ns/day on 12 cores (??). An extremely modest improvement from the Charmm FF but the scaling is not what I expect it to be. Any thoughts on what might be happening here?

**Comment by peastman** [comment]
That still seems very slow.  For comparison I just tested the ApoA1 benchmark which is about the same size as your system (92,224 atoms).  I ran it on my laptop which has 10 cores, but two of them are efficiency cores that don't add a lot to performance.  It gets 9.5 ns/day on CPU and 38.4 ns/day on OpenCL.

If you post your new system I can try it and see what I get.

OpenMM's CPU platform doesn't have great scaling with number of cores.  It's fine for running on a single typical CPU or 8 or 10 cores, but it won't scale to 48.  In that case, you're better off limiting the number of threads and just running multiple independent simulations at once.  But even given that, your numbers still seem low.

**Comment by jgrosskopf** [comment]
Hi. Sorry for the delay. Attached here is the new system that I'm working with. 
[system_a.zip](https://github.com/openmm/openmm/files/13443773/system_a.zip)

Is the timestep 4fs with the ApoA1 benchmark? If I can get up to ~60-70ns/day on 48 cores I'd be incredibly happy. The actions of interest in my system happen on the 100s of ns timescale, so if I can reach out to ~500 ns in a 7 day window (cluster wall time limit) and launch multiple jobs that'd be great.

**Comment by peastman** [comment]
This new system is a little smaller than the previous one: 93255 particles rather than 93276.  Can you provide coordinates for it, preferably as a serialized State?  Call `simulation.saveState('state.xml')` to create the file.

**Comment by jgrosskopf** [comment]
Ah, completely forgot that I had to rebuild the system to get the new forcefields to work. Sorry about that. Here are the coordinates. 
[state_cpu.zip](https://github.com/openmm/openmm/files/13452821/state_cpu.zip)

**Comment by peastman** [comment]
Here's a script I wrote to benchmark it.  I saved another State after energy minimizing it so I wouldn't need to keep doing that on every run.  If you're running from your original State, add a call to `LocalEnergyMinimizer.minimize(context, tolerance=100)` immediately after calling `setState()`.

```python
from openmm import *
from openmm.unit import *
import time

system = XmlSerializer.deserialize(open('system_a.xml').read())
state = XmlSerializer.deserialize(open('state_minimized.xml').read())
integrator = LangevinMiddleIntegrator(310*kelvin, 1/picosecond, 0.004*picoseconds)
integrator.setConstraintTolerance(0.000001)
platform = Platform.getPlatformByName('CPU')
context = Context(system, integrator, platform)
context.setState(state)
context.setVelocitiesToTemperature(310*kelvin)
integrator.step(10)
context.getState(getEnergy=True)
t1 = time.time()
steps = 500
integrator.step(steps)
context.getState(getEnergy=True)
t2 = time.time()
elapsedDays = (t2-t1)/86400.0
elapsedNs = steps*integrator.getStepSize().value_in_unit(nanosecond)
print(elapsedNs/elapsedDays)
```

Running on my laptop, it gets 5.4 ns/day on CPU, and 25.7 ns/day on GPU (OpenCL).  How does that compare to your results?

**Comment by jgrosskopf** [comment]
Hello,

I've tried running this and unfortunately I've been getting a seg fault issue. The seg fault is happening at "integrator.step(10)" and this is the error message at /var/log/messages on the node:

```
Nov 28 10:13:11 cn06 kernel: python[230633]: segfault at 560fd76bcb64 ip 00007f90a5a1b422 sp 00007f90a4d97db8 error 4
Nov 28 10:13:11 cn06 kernel: python[230629]: segfault at 560fd76bcb64 ip 00007f90a5a1b422 sp 00007f908e56adb8 error 4
Nov 28 10:13:11 cn06 kernel: in libOpenMMCPU.so[7f90a59d6000+5d000]
Nov 28 10:13:11 cn06 kernel: 
Nov 28 10:13:11 cn06 kernel: in libOpenMMCPU.so[7f90a59d6000+5d000]
```

Is this something that you are familiar with?

**Comment by peastman** [comment]
Try running it inside gdb or lldb.  Run it until it segfaults, then type `bt` to get a stack trace showing where it happened.  Post it here.

**Comment by jgrosskopf** [comment]
Here is the result:

```
(gdb) bt
#0  0x00007fffec385422 in OpenMM::CpuNonbondedForce::exptermsApprox(float) () from /hpc/apps/miniconda3/4.9.2/envs/openmm-7.7.0/lib/plugins/libOpenMMCPU.so
#1  0x00007fffec3858c8 in OpenMM::CpuNonbondedForce::threadComputeDirect(OpenMM::ThreadPool&, int) () from /hpc/apps/miniconda3/4.9.2/envs/openmm-7.7.0/lib/plugins/libOpenMMCPU.so
#2  0x00007ffff02e0e5e in OpenMM::threadBody(void*) () from /hpc/apps/miniconda3/4.9.2/envs/openmm-7.7.0/lib/python3.10/site-packages/openmm/../../../libOpenMM.so.7.7
#3  0x00007ffff7bc6ea5 in start_thread () from /lib64/libpthread.so.0
#4  0x00007ffff6fde8dd in clone () from /lib64/libc.so.6
```

**Comment by peastman** [comment]
Is it possible that your simulation has run out of memory?  Or alternatively that it's exploded?
