### ISSUE TITLE
Error when using `amoeba2018.xml` together with `gaff-2.11` for simulating a protein-ligand complex 

### ISSUE THREAD

**Issue by taoliu032** [openmm/openmm#4336]
Hi!

I was trying to simulate a protein-ligand complex structure (pdb file and ligand sdf files are attached below). The protein has natural amino acids only and the ligand is a small organic molecule with sulfur. I was planning to use amoeba2018 force field for the protein and gaff-2.11 for the ligand. So I wrote code like this:

```python
from openmm import *
from openmm.app import *
from openmm.unit import *
from openff.toolkit.topology import Molecule
from openmmforcefields.generators import GAFFTemplateGenerator

pdb = PDBFile(input_pdb_file) # see the attached pdb file
ligand_molecule = Molecule.from_file(lig_sdf_file)    

forcefield = ForceField('amoeba2018.xml') # also tried `amber14/protein.ff14SB.xml`
gaff = GAFFTemplateGenerator(molecules=ligand_molecule, forcefield='gaff-2.11')    
forcefield.registerTemplateGenerator(gaff.generator)
system = forcefield.createSystem(pdb.topology, nonbondedMethod=NoCutoff, constraints=None)
``` 

I got an error: 
```
Warning: importing 'simtk.openmm' is deprecated.  Import 'openmm' instead.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/taoliu/miniconda3/envs/e2edna_conda_env/lib/python3.8/site-packages/openmm/app/forcefield.py", line 1363, in createSystem
    force.createForce(sys, data, nonbondedMethod, nonbondedCutoff, args)
  File "/home/taoliu/miniconda3/envs/e2edna_conda_env/lib/python3.8/site-packages/openmm/app/forcefield.py", line 4800, in createForce
    className = self.classNameForType[data.atomType[atom]]
KeyError: 'c'
```
Instead of `amoeba2018.xml`, I also tried `amber14/protein.ff14SB.xml` which did not give out any error. Anyone cares to share some thoughts? Thanks a lot!

[protein-ligand_pdb_file_and_ligand_sdf_file.zip](https://github.com/openmm/openmm/files/13549162/protein-ligand_pdb_file_and_ligand_sdf_file.zip)

**Comment by taoliu032** [comment]
Ah that makes a lot of sense. Thanks Peter for the rapid answer!
