### ISSUE TITLE
My openmm script is running fine with openmm=7 but showing particle coordinate is naN in openmm=8

### ISSUE THREAD

**Issue by The4thOne** [openmm/openmm#4355]
My openmm script is running fine with openmm=7 (specifically 7.6 and 7.7) but showing "particle coordinate is naN" in openmm=8. I have used the pdb attached below. The issue is happening for both minimization as well as simulation. I am running in CPU.

**Note:** While running in openmm=8, the moment I added the ions (the last line in the pdb) this issue started appearing. Removing the ions from the pdb works fine!

In openmm=7 everything is working fine.

ATOM      0  P   G   A   0      91.478 107.909  63.167  1.00  0.00           P
ATOM      1  S   G   A   0      93.160 106.070  66.960  1.00  0.00           S
ATOM      2  B   G   A   0      92.953 109.661  70.118  1.00  0.00           B
ATOM      3  P   G   A   1      90.101 104.043  67.135  1.00  0.00           P
ATOM      4  S   G   A   1      91.245 102.454  71.227  1.00  0.00           S
ATOM      5  B   G   A   1      89.502 106.276  73.534  1.00  0.00           B
ATOM      6  P   C   A   2      88.339 100.222  71.013  1.00  0.00           P
ATOM      7  S   C   A   2      87.911 100.337  75.523  1.00  0.00           S
ATOM      8  B   C   A   2      87.112 104.334  75.615  1.00  0.00           B
ATOM      9  P   G   A   3      84.747  98.522  75.097  1.00  0.00           P
ATOM     10  S   G   A   3      82.775 100.655  78.606  1.00  0.00           S
ATOM     11  B   G   A   3      82.398 105.119  76.921  1.00  0.00           B
ATOM     12  P   A   A   4      79.751  98.818  77.610  1.00  0.00           P
ATOM     13  S   A   A   4      78.213  98.699  81.872  1.00  0.00           S
ATOM     14  B   A   A   4      76.912 103.157  82.039  1.00  0.00           B
ATOM     15  P   C   A   5      75.744  96.193  80.827  1.00  0.00           P
ATOM     16  S   C   A   5      79.013  93.061  81.097  1.00  0.00           S
ATOM     17  B   C   A   5      76.011  90.244  80.806  1.00  0.00           B
ATOM     18  P   G   A   6      79.448  93.963  84.632  1.00  0.00           P
ATOM     19  S   G   A   6      80.695  98.224  83.655  1.00  0.00           S
ATOM     20  B   G   A   6      76.276 100.027  84.118  1.00  0.00           B
ATOM     21  P   A   A   7      82.492  98.352  86.858  1.00  0.00           P
ATOM     22  S   A   A   7      86.114 100.489  85.122  1.00  0.00           S
ATOM     23  B   A   A   7      84.245 104.700  84.503  1.00  0.00           B
ATOM     24  P   U   A   8      87.266 100.964  88.579  1.00  0.00           P
ATOM     25  S   U   A   8      85.905 105.297  88.496  1.00  0.00           S
ATOM     26  B   U   A   8      81.823 104.979  88.191  1.00  0.00           B
ATOM     27  P   C   A   9      86.516 105.684  92.097  1.00  0.00           P
ATOM     28  S   C   A   9      82.681 108.100  92.428  1.00  0.00           S
ATOM     29  B   C   A   9      80.711 104.434  92.405  1.00  0.00           B
ATOM     30  P   C   A  10      83.364 108.718  95.984  1.00  0.00           P
ATOM     31  S   C   A  10      78.922 108.646  96.878  1.00  0.00           S
ATOM     32  B   C   A  10      79.085 104.570  96.372  1.00  0.00           B
ATOM     33  P   G   A  11      79.721 109.191 100.421  1.00  0.00           P
ATOM     34  S   G   A  11      76.237 106.588 101.713  1.00  0.00           S
ATOM     35  B   G   A  11      78.050 102.280 100.670  1.00  0.00           B
ATOM     36  P   G   A  12      77.275 107.218 105.178  1.00  0.00           P
ATOM     37  S   G   A  12      75.850 103.135 106.545  1.00  0.00           S
ATOM     38  B   G   A  12      79.205 100.470 104.379  1.00  0.00           B
ATOM     39  P   C   A  13      77.216 104.055 109.827  1.00  0.00           P
ATOM     40  S   C   A  13      78.272  99.779 110.915  1.00  0.00           S
ATOM     41  B   C   A  13      80.171  98.725 107.415  1.00  0.00           B
ATOM     42  P   C   A  14      80.027 101.251 113.788  1.00  0.00           P
ATOM     43  S   C   A  14      83.423  98.281 113.336  1.00  0.00           S
ATOM     44  B   C   A  14      83.453 100.054 109.581  1.00  0.00           B
ATOM     45  P   A   A  15      85.156 100.099 116.018  1.00  0.00           P
ATOM     46  S   A   A  15      88.894 101.361 113.708  1.00  0.00           S
ATOM     47  B   A   A  15      91.657  97.985 115.377  1.00  0.00           B
ATOM     48  P   U   A  16      87.726 100.104 110.460  1.00  0.00           P
ATOM     49  S   U   A  16      91.986  99.260 109.102  1.00  0.00           S
ATOM     50  B   U   A  16      92.758  96.460 112.032  1.00  0.00           B
ATOM     51  P   C   A  17      90.366  97.843 106.128  1.00  0.00           P
ATOM     52  S   C   A  17      93.634  94.741 105.657  1.00  0.00           S
ATOM     53  B   C   A  17      92.157  93.281 109.225  1.00  0.00           B
ATOM     54  P   A   A  18      91.692  93.445 102.811  1.00  0.00           P
ATOM     55  S   A   A  18      88.119  92.056 105.262  1.00  0.00           S
ATOM     56  B   A   A  18      85.966  96.160 105.878  1.00  0.00           B
ATOM     57  P   C   A  19      86.449  90.997 102.161  1.00  0.00           P
ATOM     58  S   C   A  19      82.328  91.641 103.977  1.00  0.00           S
ATOM     59  B   C   A  19      82.534  95.796 104.131  1.00  0.00           B
ATOM     60  P   C   A  20      80.690  90.738 100.811  1.00  0.00           P
ATOM     61  S   C   A  20      77.054  93.195 101.975  1.00  0.00           S
ATOM     62  B   C   A  20      79.064  96.769 101.770  1.00  0.00           B
ATOM     63  P   G   A  21      75.396  92.589  98.750  1.00  0.00           P
ATOM     64  S   G   A  21      73.297  96.607  99.109  1.00  0.00           S
ATOM     65  B   G   A  21      76.873  99.683  98.300  1.00  0.00           B
ATOM     66  P   G   A  22      71.602  96.172  95.875  1.00  0.00           P
ATOM     67  S   G   A  22      71.603 100.685  95.346  1.00  0.00           S
ATOM     68  B   G   A  22      76.253 101.561  94.502  1.00  0.00           B
ATOM     69  P   G   A  23      69.944 100.530  92.064  1.00  0.00           P
ATOM     70  S   G   A  23      72.232 104.311  91.070  1.00  0.00           S
ATOM     71  B   G   A  23      75.576 100.982  90.375  1.00  0.00           B
ATOM     72  P   G   A  24      70.989 104.793  87.640  1.00  0.00           P
ATOM     73  S   G   A  24      74.999 106.821  86.976  1.00  0.00           S
ATOM     74  B   G   A  24      77.466 102.687  86.988  1.00  0.00           B
ATOM     75  P   A   A  25      74.553 107.836  83.470  1.00  0.00           P
ATOM     76  S   A   A  25      78.791 109.312  84.123  1.00  0.00           S
ATOM     77  B   A   A  25      80.264 104.933  83.424  1.00  0.00           B
ATOM     78  P   G   A  26      79.217 111.605  81.281  1.00  0.00           P
ATOM     79  S   G   A  26      83.578 111.145  82.456  1.00  0.00           S
ATOM     80  B   G   A  26      84.377 108.044  78.942  1.00  0.00           B
ATOM     81  P   C   A  27      84.955 114.259  81.078  1.00  0.00           P
ATOM     82  S   C   A  27      89.005 112.247  80.538  1.00  0.00           S
ATOM     83  B   C   A  27      87.574 109.557  77.718  1.00  0.00           B
ATOM     84  P   C   A  28      90.342 115.325  79.032  1.00  0.00           P
ATOM     85  S   C   A  28      94.566 113.646  78.672  1.00  0.00           S
ATOM     86  B   C   A  28      92.798 112.344  75.147  1.00  0.00           B
ATOM     87  P   U   A  29      95.914 117.062  78.403  1.00  0.00           P
ATOM     88  S   U   A  29     100.203 115.998  79.549  1.00  0.00           S
ATOM     89  B   U   A  29     101.939 119.621  80.892  1.00  0.00           B
ATOM     90  P   U   A  30      99.196 113.767  82.301  1.00  0.00           P
ATOM     91  S   U   A  30     103.595 112.759  82.930  1.00  0.00           S
ATOM     92  B   U   A  30     103.540 114.138  86.820  1.00  0.00           B
ATOM     93  P   C   A  31     103.196 109.216  83.835  1.00  0.00           P
ATOM     94  S   C   A  31     107.226 109.622  85.922  1.00  0.00           S
ATOM     95  B   C   A  31     105.760 111.441  89.336  1.00  0.00           B
ATOM     96  P   G   A  32     107.568 106.145  87.064  1.00  0.00           P
ATOM     97  S   G   A  32     110.410 107.777  90.221  1.00  0.00           S
ATOM     98  B   G   A  32     107.525 109.388  93.661  1.00  0.00           B
ATOM     99  P   G   A  33     111.417 104.488  91.511  1.00  0.00           P
ATOM    100  S   G   A  33     112.197 106.491  95.515  1.00  0.00           S
ATOM    101  B   G   A  33     107.779 107.091  97.344  1.00  0.00           B
ATOM    102  P   A   A  34     113.464 103.365  96.978  1.00  0.00           P
ATOM    103  S   A   A  34     112.032 104.782 101.035  1.00  0.00           S
ATOM    104  B   A   A  34     107.639 103.851  99.824  1.00  0.00           B
ATOM    105  P   A   A  35     113.252 101.744 102.703  1.00  0.00           P
ATOM    106  S   A   A  35     109.768 102.065 105.592  1.00  0.00           S
ATOM    107  B   A   A  35     106.912 100.400 102.280  1.00  0.00           B
ATOM    108  P   G   A  36     110.920  99.114 107.452  1.00  0.00           P
ATOM    109  S   G   A  36     106.613  98.019 108.381  1.00  0.00           S
ATOM    110  B   G   A  36     106.398  96.251 103.976  1.00  0.00           B
ATOM    111  P   A   A  37     107.801  95.046 110.178  1.00  0.00           P
ATOM    112  S   A   A  37     103.666  94.774 112.043  1.00  0.00           S
ATOM    113  B   A   A  37     100.795  92.060 109.420  1.00  0.00           B
ATOM    114  P   A   A  38     105.083  93.151 115.020  1.00  0.00           P
ATOM    115  S   A   A  38     101.101  91.049 115.451  1.00  0.00           S
ATOM    116  B   A   A  38     101.416  88.340 111.668  1.00  0.00           B
ATOM    117  P   C   A  39     102.213  89.155 118.396  1.00  0.00           P
ATOM    118  S   C   A  39      99.581  85.808 116.854  1.00  0.00           S
ATOM    119  B   C   A  39     102.236  84.939 113.756  1.00  0.00           B
ATOM    120  P   G   A  40     100.223  83.685 119.783  1.00  0.00           P
ATOM    121  S   G   A  40     100.094  80.216 116.885  1.00  0.00           S
ATOM    122  B   G   A  40     104.726  80.760 115.952  1.00  0.00           B
ATOM    123  P   G   A  41     100.202  77.677 119.536  1.00  0.00           P
ATOM    124  S   G   A  41     102.569  75.164 116.609  1.00  0.00           S
ATOM    125  B   G   A  41     106.627  77.335 117.957  1.00  0.00           B
ATOM    126  P   C   A  42     102.692  72.350 118.964  1.00  0.00           P
ATOM    127  S   C   A  42     106.659  71.212 117.106  1.00  0.00           S
ATOM    128  B   C   A  42     108.327  74.231 119.409  1.00  0.00           B
ATOM    129  P   G   A  43     106.806  68.254 119.282  1.00  0.00           P
ATOM    130  S   G   A  43     111.322  68.550 119.192  1.00  0.00           S
ATOM    131  B   G   A  43     111.493  71.917 122.576  1.00  0.00           B
ATOM    132  P   C   A  44     111.644  65.516 121.235  1.00  0.00           P
ATOM    133  S   C   A  44     115.519  67.224 122.843  1.00  0.00           S
ATOM    134  B   C   A  44     113.321  69.852 125.172  1.00  0.00           B
ATOM    135  P   C   A  45     116.027  64.237 124.919  1.00  0.00           P
ATOM    136  S   C   A  45     118.260  66.809 127.908  1.00  0.00           S
ATOM    137  B   C   A  45     114.559  68.269 129.035  1.00  0.00           B
ATOM    138  P   G   A  46     118.898  63.855 129.998  1.00  0.00           P
ATOM    139  S   G   A  46     118.844  66.535 133.651  1.00  0.00           S
ATOM    140  B   G   A  46     114.107  67.116 133.890  1.00  0.00           B
ATOM    141  P   C   A  47     119.521  63.661 135.830  1.00  0.00           P
ATOM    142  S   C   A  47     117.228  65.754 139.127  1.00  0.00           S
ATOM    143  B   C   A  47     113.683  65.082 137.084  1.00  0.00           B
ATOM    144  P   C   A  48     117.913  62.824 141.230  1.00  0.00           P
ATOM    145  S   C   A  48     114.040  63.505 143.475  1.00  0.00           S
ATOM    146  B   C   A  48     111.935  62.370 140.070  1.00  0.00           B
ATOM    147  P   G   A  49     114.847  60.519 145.462  1.00  0.00           P
ATOM    148  S   G   A  49     110.423  59.677 145.945  1.00  0.00           S
ATOM    149  B   G   A  49     109.271  58.440 141.520  1.00  0.00           B
ATOM    150  P   G   A  50     111.103  56.572 147.790  1.00  0.00           P
ATOM    151  S   G   A  50     114.451  55.091 145.101  1.00  0.00           S
ATOM    152  B   G   A  50     113.862  50.390 145.639  1.00  0.00           B
ATOM    153  P   A   A  51     112.539  55.870 142.064  1.00  0.00           P
ATOM    154  S   A   A  51     114.507  52.346 139.976  1.00  0.00           S
ATOM    155  B   A   A  51     112.073  49.095 142.285  1.00  0.00           B
ATOM    156  P   A   A  52     112.590  53.053 136.924  1.00  0.00           P
ATOM    157  S   A   A  52     112.406  48.652 135.834  1.00  0.00           S
ATOM    158  B   A   A  52     109.455  47.692 139.326  1.00  0.00           B
ATOM    159  P   A   A  53     110.496  49.585 132.837  1.00  0.00           P
ATOM    160  S   A   A  53     106.518  49.543 135.003  1.00  0.00           S
ATOM    161  B   A   A  53     108.071  51.725 138.830  1.00  0.00           B
ATOM    162  P   C   A  54     105.473  52.225 132.719  1.00  0.00           P
ATOM    163  S   C   A  54     103.012  54.017 136.071  1.00  0.00           S
ATOM    164  B   C   A  54     106.551  55.091 137.784  1.00  0.00           B
ATOM    165  P   G   A  55     102.200  56.969 134.042  1.00  0.00           P
ATOM    166  S   G   A  55     102.290  59.474 137.839  1.00  0.00           S
ATOM    167  B   G   A  55     107.064  59.998 138.295  1.00  0.00           B
ATOM    168  P   G   A  56     101.438  62.517 135.963  1.00  0.00           P
ATOM    169  S   G   A  56     103.649  64.973 139.077  1.00  0.00           S
ATOM    170  B   G   A  56     108.096  64.037 137.633  1.00  0.00           B
ATOM    171  P   C   A  57     102.980  68.117 137.302  1.00  0.00           P
ATOM    172  S   C   A  57     106.811  69.765 139.086  1.00  0.00           S
ATOM    173  B   C   A  57     109.056  67.434 136.541  1.00  0.00           B
ATOM    174  P   G   A  58     106.372  72.948 137.306  1.00  0.00           P
ATOM    175  S   G   A  58     110.890  73.360 137.192  1.00  0.00           S
ATOM    176  B   G   A  58     111.716  70.360 133.551  1.00  0.00           B
ATOM    177  P   G   A  59     110.676  76.584 135.447  1.00  0.00           P
ATOM    178  S   G   A  59     114.677  75.576 133.572  1.00  0.00           S
ATOM    179  B   G   A  59     113.048  72.643 130.182  1.00  0.00           B
ATOM    180  P   C   A  60     114.735  78.711 131.661  1.00  0.00           P
ATOM    181  S   C   A  60     117.212  76.546 128.539  1.00  0.00           S
ATOM    182  B   C   A  60     113.868  74.587 127.108  1.00  0.00           B
ATOM    183  P   G   A  61     117.388  79.585 126.485  1.00  0.00           P
ATOM    184  S   G   A  61     117.667  76.987 122.776  1.00  0.00           S
ATOM    185  B   G   A  61     113.080  75.747 122.302  1.00  0.00           B
ATOM    186  P   C   A  62     117.896  80.015 120.719  1.00  0.00           P
ATOM    187  S   C   A  62     115.915  77.852 117.261  1.00  0.00           S
ATOM    188  B   C   A  62     112.214  77.581 119.130  1.00  0.00           B
ATOM    189  P   U   A  63     116.193  81.042 115.464  1.00  0.00           P
ATOM    190  S   U   A  63     112.443  80.245 113.049  1.00  0.00           S
ATOM    191  B   U   A  63     110.439  80.512 116.639  1.00  0.00           B
ATOM    192  P   C   A  64     112.902  83.609 111.647  1.00  0.00           P
ATOM    193  S   C   A  64     108.652  83.749 110.067  1.00  0.00           S
ATOM    194  B   C   A  64     108.250  87.522 111.709  1.00  0.00           B
ATOM    195  P   A   A  65     110.144  83.982 106.718  1.00  0.00           P
ATOM    196  S   A   A  65     106.831  86.500 104.892  1.00  0.00           S
ATOM    197  B   A   A  65     106.277  89.852 108.110  1.00  0.00           B
ATOM    198  P   G   A  66     109.047  86.669 101.967  1.00  0.00           P
ATOM    199  S   G   A  66     109.071  91.203 101.794  1.00  0.00           S
ATOM    200  B   G   A  66     110.435  94.430 105.058  1.00  0.00           B
ATOM    201  P   U   A  67     106.407  91.387  99.272  1.00  0.00           P
ATOM    202  S   U   A  67     103.167  89.315 101.700  1.00  0.00           S
ATOM    203  B   U   A  67     104.280  91.196 105.199  1.00  0.00           B
ATOM    204  P   A   A  68     100.999  91.548  99.757  1.00  0.00           P
ATOM    205  S   A   A  68      97.821  92.043 102.951  1.00  0.00           S
ATOM    206  B   A   A  68     100.498  94.041 106.239  1.00  0.00           B
ATOM    207  P   G   A  69      96.681  94.636 100.608  1.00  0.00           P
ATOM    208  S   G   A  69      95.091  97.236 103.961  1.00  0.00           S
ATOM    209  B   G   A  69      98.756  98.154 106.847  1.00  0.00           B
ATOM    210  P   A   A  70      94.513 100.004 101.615  1.00  0.00           P
ATOM    211  S   A   A  70      95.514 102.841 105.010  1.00  0.00           S
ATOM    212  B   A   A  70     100.043 101.672 105.178  1.00  0.00           B
ATOM    213  P   A   A  71      95.274 105.783 102.822  1.00  0.00           P
ATOM    214  S   A   A  71      98.509 107.636 105.398  1.00  0.00           S
ATOM    215  B   A   A  71     101.910 105.138 103.437  1.00  0.00           B
ATOM    216  P   C   A  72      98.612 110.717 103.407  1.00  0.00           P
ATOM    217  S   C   A  72     103.031 110.957 104.405  1.00  0.00           S
ATOM    218  B   C   A  72     103.950 108.177 101.408  1.00  0.00           B
ATOM    219  P   C   A  73     103.135 114.301 102.892  1.00  0.00           P
ATOM    220  S   C   A  73     107.484 113.617 101.851  1.00  0.00           S
ATOM    221  B   C   A  73     106.169 111.051  98.920  1.00  0.00           B
ATOM    222  P   G   A  74     107.554 116.941 100.289  1.00  0.00           P
ATOM    223  S   G   A  74     110.575 115.412  97.275  1.00  0.00           S
ATOM    224  B   G   A  74     107.386 113.116  94.503  1.00  0.00           B
ATOM    225  P   A   A  75     110.624 118.717  95.667  1.00  0.00           P
ATOM    226  S   A   A  75     111.594 116.708  91.719  1.00  0.00           S
ATOM    227  B   A   A  75     107.257 115.193  91.000  1.00  0.00           B
ATOM    228  P   A   A  76     111.406 119.896  89.897  1.00  0.00           P
ATOM    229  S   A   A  76     110.013 117.499  86.292  1.00  0.00           S
ATOM    230  B   A   A  76     106.118 119.712  84.853  1.00  0.00           B
ATOM    231  P   C   A  77     112.663 118.847  84.130  1.00  0.00           P
ATOM    232  S   C   A  77     109.939 117.990  80.597  1.00  0.00           S
ATOM    233  B   C   A  77     107.249 120.970  81.458  1.00  0.00           B
ATOM    234  P   G   A  78     112.267 119.439  78.150  1.00  0.00           P
ATOM    235  S   G   A  78     108.656 120.611  75.647  1.00  0.00           S
ATOM    236  B   G   A  78     106.957 124.447  77.933  1.00  0.00           B
ATOM    237  P   G   A  79     110.737 122.121  73.022  1.00  0.00           P
ATOM    238  S   G   A  79     107.502 125.159  72.087  1.00  0.00           S
ATOM    239  B   G   A  79     107.367 128.187  75.818  1.00  0.00           B
ATOM    240  P   G   A  80     109.743 126.655  69.583  1.00  0.00           P
ATOM    241  S   G   A  80     110.646 130.250  72.193  1.00  0.00           S
ATOM    242  B   G   A  80     107.883 133.819  73.560  1.00  0.00           B
ATOM    243  P   U   A  81     112.670 131.792  69.547  1.00  0.00           P
ATOM    244  S   U   A  81     114.606 134.169  72.881  1.00  0.00           S
ATOM    245  B   U   A  81     110.847 136.105  73.101  1.00  0.00           B
ATOM    246  P   G   A  82     117.004 135.559  70.465  1.00  0.00           P
ATOM    247  S   G   A  82     119.395 137.632  73.728  1.00  0.00           S
ATOM    248  B   G   A  82     117.148 141.834  73.704  1.00  0.00           B
ATOM    249  P   A   A  83     117.684 135.434  76.117  1.00  0.00           P
ATOM    250  S   A   A  83     117.522 138.714  79.243  1.00  0.00           S
ATOM    251  B   A   A  83     114.483 140.835  76.520  1.00  0.00           B
ATOM    252  P   G   A  84     115.384 136.381  81.103  1.00  0.00           P
ATOM    253  S   G   A  84     112.641 139.715  82.511  1.00  0.00           S
ATOM    254  B   G   A  84     110.452 140.672  78.352  1.00  0.00           B
ATOM    255  P   C   A  85     110.577 137.027  83.925  1.00  0.00           P
ATOM    256  S   C   A  85     106.704 139.287  83.225  1.00  0.00           S
ATOM    257  B   C   A  85     106.979 139.486  79.111  1.00  0.00           B
ATOM    258  P   C   A  86     104.916 136.271  84.331  1.00  0.00           P
ATOM    259  S   C   A  86     103.240 135.442  80.181  1.00  0.00           S
ATOM    260  B   C   A  86     106.144 132.757  78.925  1.00  0.00           B
ATOM    261  P   C   A  87     100.438 133.597  81.678  1.00  0.00           P
ATOM    262  S   C   A  87     100.328 130.990  77.963  1.00  0.00           S
ATOM    263  B   C   A  87     103.932 129.128  78.796  1.00  0.00           B
ATOM    264  P   G   A  88      97.490 129.031  79.237  1.00  0.00           P
ATOM    265  S   G   A  88      99.028 125.421  76.948  1.00  0.00           S
ATOM    266  B   G   A  88     103.118 124.184  79.161  1.00  0.00           B
ATOM    267  P   U   A  89      96.123 123.361  77.841  1.00  0.00           P
ATOM    268  S   U   A  89      97.319 119.987  75.042  1.00  0.00           S
ATOM    269  B   U   A  89     101.288 118.827  75.410  1.00  0.00           B
ATOM    270  P   C   A  90      95.127 120.831  72.209  1.00  0.00           P
ATOM    271  S   C   A  90      94.911 125.281  73.080  1.00  0.00           S
ATOM    272  B   C   A  90      91.119 125.191  71.453  1.00  0.00           B
ATOM    273  P   A   A  91      97.344 125.882  70.392  1.00  0.00           P
ATOM    274  S   A   A  91     100.442 126.393  73.648  1.00  0.00           S
ATOM    275  B   A   A  91     102.277 122.131  73.299  1.00  0.00           B
ATOM    276  P   C   A  92     102.654 128.440  71.541  1.00  0.00           P
ATOM    277  S   C   A  92      99.284 131.060  70.044  1.00  0.00           S
ATOM    278  B   C   A  92      98.607 132.600  73.811  1.00  0.00           B
ATOM    279  P   A   A  93     101.815 133.088  68.313  1.00  0.00           P
ATOM    280  S   A   A  93      99.576 136.837  69.496  1.00  0.00           S
ATOM    281  B   A   A  93     101.531 136.211  73.728  1.00  0.00           B
ATOM    282  P   G   A  94     102.088 138.939  67.832  1.00  0.00           P
ATOM    283  S   G   A  94     101.240 142.082  70.982  1.00  0.00           S
ATOM    284  B   G   A  94     103.825 139.928  74.364  1.00  0.00           B
ATOM    285  P   C   A  95     103.781 144.332  69.577  1.00  0.00           P
ATOM    286  S   C   A  95     104.375 145.939  73.775  1.00  0.00           S
ATOM    287  B   C   A  95     106.406 142.446  74.763  1.00  0.00           B
ATOM    288  P   U   A  96     106.965 148.268  72.618  1.00  0.00           P
ATOM    289  S   U   A  96     108.909 148.234  76.723  1.00  0.00           S
ATOM    290  B   U   A  96     110.010 144.314  76.074  1.00  0.00           B
ATOM    291  P   C   A  97     111.458 150.425  75.242  1.00  0.00           P
ATOM    292  S   C   A  97     114.511 149.088  78.312  1.00  0.00           S
ATOM    293  B   C   A  97     111.650 149.865  81.183  1.00  0.00           B
HETATM  294  K   K   D  98      24.789   3.771 148.531  1.00  0.00           K

**Comment by peastman** [comment]
Can you post your script and any other files needed to reproduce this?

**Comment by The4thOne** [comment]
I am attaching all of them in the following zip file.
[Test.zip](https://github.com/openmm/openmm/files/13680912/Test.zip)

**Comment by peastman** [comment]
When I run your script it immediately fails with an exception:

```
Traceback (most recent call last):
  File "/home/peastman/temp5/rnamd.py", line 677, in <module>
    simulation.minimizeEnergy(tolerance=1e-5*u.kilocalorie_per_mole)
  File "/home/peastman/miniconda3/envs/cf/lib/python3.9/site-packages/openmm/app/simulation.py", line 143, in minimizeEnergy
    mm.LocalEnergyMinimizer.minimize(self.context, tolerance, maxIterations, reporter)
  File "/home/peastman/miniconda3/envs/cf/lib/python3.9/site-packages/openmm/openmm.py", line 11302, in minimize
    tolerance = tolerance.value_in_unit(unit.kilojoules_per_mole/unit.nanometer)
  File "/home/peastman/miniconda3/envs/cf/lib/python3.9/site-packages/openmm/unit/quantity.py", line 626, in value_in_unit
    val = self.in_units_of(unit)
  File "/home/peastman/miniconda3/envs/cf/lib/python3.9/site-packages/openmm/unit/quantity.py", line 662, in in_units_of
    raise TypeError('Unit "%s" is not compatible with Unit "%s".' % (self.unit, other_unit))
TypeError: Unit "kilocalorie/mole" is not compatible with Unit "kilojoule/(nanometer*mole)".
```

Once I fix that, I find that two or your CustomNonbondedForces produce nan for energy.  Looking at the energy expressions, I see you're trying to mask off certain interactions by multiplying by a prefactor that equals either 0 or 1: `step(radii_ion_ion - r)*eps_ion_ion*`.  That isn't an effective way of doing it.  If anything causes the rest of the expression to become nan or infinite, such as dividing by 0, then multiplying by 0 will still produce nan.  Instead you need to use a `select()` function so the result will be completely ignored: `select(step(radii_ion_ion - r)*eps_ion_ion, ..., 0)`.  Once I make that change to your expressions, it runs successfully.

**Comment by The4thOne** [comment]
Thank you very much for your response. 
However, although I have implemented the select() it is throwing the same following error. I don't know why. 


Performing minimization
Traceback (most recent call last):
  File "/home/dirac/Desktop/TBox_Openmm/Production_test3/rnamd.py", line 682, in <module>
    simulation.minimizeEnergy(tolerance=1e-3*u.kilojoule_per_mole)
  File "/home/dirac/anaconda3/envs/openmm/lib/python3.9/site-packages/openmm/app/simulation.py", line 137, in minimizeEnergy
    mm.LocalEnergyMinimizer.minimize(self.context, tolerance, maxIterations)
  File "/home/dirac/anaconda3/envs/openmm/lib/python3.9/site-packages/openmm/openmm.py", line 17208, in minimize
    return _openmm.LocalEnergyMinimizer_minimize(context, tolerance, maxIterations)
openmm.OpenMMException: Particle coordinate is NaN.  For more information, see https://github.com/openmm/openmm/wiki/Frequently-Asked-Questions#nan


 Can you please tell me what did you fix at first? Or any other clue?

**Comment by peastman** [comment]
I changed line 169 to

```python
LJForce_rna_rna = mm.CustomNonbondedForce("select(step(radii_rna_rna-r)*eps_rna_rna, eps_rna_rna*(((dia_mg/(r+dia_mg-radii_rna_rna))^12)-(2.0*((dia_mg/(r+dia_mg-radii_rna_rna))^6))+1), 0); \
```

line 193 to

```python
LJForce_ion_ion = mm.CustomNonbondedForce("select(step(radii_ion_ion - r)*eps_ion_ion, eps_ion_ion*(((dia_mg/(r+dia_mg-radii_ion_ion))^12)-(2.0*((dia_mg/(r+dia_mg-radii_ion_ion))^6))+1), 0); \
```

and line 225 to

```python
LJForce_rna_ion = mm.CustomNonbondedForce("select(factor*step(radii_rna_ion - r)*eps_rna_ion, factor*eps_rna_ion*(((dia_mg/(r+dia_mg-radii_rna_ion))^12)-(2.0*((dia_mg/(r+dia_mg-radii_rna_ion))^6))+1), 0); \
```
