### ISSUE TITLE
OpenMMException: clSetKernelArg with openMM 8.1.0 and 8.1.1

### ISSUE THREAD

**Issue by des2037** [openmm/openmm#4399]
Hi OpenMM community,

I'm trying to benchmark openMM 8.1.0 and 8.1.1 on Frontier (OLCF), given the reported improvements in the OpenCL implementation.

However, I'm getting this error:
```Traceback (most recent call last):
  File "/lustre/orion/bip109/scratch/des2037/bip234_stuff/incite_2023_benchmarks/mfs_project_charmm-gui-8961969635/openmm_8.1.1/openmm_run.py", line 169, in <module>
    simulation.step(inputs.nstep)
  File "/ccs/proj/bip109/frontier/conda/miniconda3_py310_23.3.1-0_2023_05_10/envs/openmm_8.1.0/lib/python3.12/site-packages/openmm/app/simulation.py", line 147, in step
    self._simulate(endStep=self.currentStep+steps)
  File "/ccs/proj/bip109/frontier/conda/miniconda3_py310_23.3.1-0_2023_05_10/envs/openmm_8.1.0/lib/python3.12/site-packages/openmm/app/simulation.py", line 212, in _simulate
    self.integrator.step(10) # Only take 10 steps at a time, to give Python more chances to respond to a control-c.
    ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/ccs/proj/bip109/frontier/conda/miniconda3_py310_23.3.1-0_2023_05_10/envs/openmm_8.1.0/lib/python3.12/site-packages/openmm/openmm.py", line 9954, in step
    return _openmm.LangevinIntegrator_step(self, steps)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
openmm.OpenMMException: clSetKernelArg```


This is a "production" simulation from CHARMM-GUI's equilibration protocol (i.e., vanilla MD). Interestingly, I have no problems running the simulation with OpenMM 8.0.0.

Frontier nodes are composed of AMD CPUs/GPUs (AMD 3rd Gen EPYC, and AMD MI250X, respectively). I've tried running both 8.1.0 and 8.1.1 with ROCM 5.3.0, 5.3.4, 5.4.3, and 5.7.1--all resulted in the above error.

Any ideas?

Thanks!
Derek

**Comment by bdenhollander** [comment]
Are you able to run the benchmarks included with OpenMM? Based on the path in the error message, the benchmark script would probably be in `/ccs/proj/bip109/frontier/conda/miniconda3_py310_23.3.1-0_2023_05_10/envs/openmm_8.1.0/Library/share/openmm/examples/benchmark.py`. Checking this would help to narrow down whether it's an installation issue or something in a custom script.

**Comment by des2037** [comment]
I am indeed able to run the benchmark.py (up to the Amber tests, at which point it fails to due a lack of connectivity). 

Here is an example output: 
```$ python benchmark.py --platform "OpenCL" 
/autofs/nccs-svm1_proj/bip109/frontier/conda/miniconda3_py310_23.3.1-0_2023_05_10/envs/openmm_8.1.0/share/openmm/examples/benchmark.py:496: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  system_info['timestamp'] = datetime.utcnow().isoformat()
/bin/sh: nvidia-smi: command not found
hostname: frontier06123
timestamp: 2024-01-21T15:25:33.762754
openmm_version: 8.1.0.dev-43f571d
cpuinfo: AMD EPYC 7A53 64-Core Processor
cpuarch: x86_64
system: Linux
test: gbsa
constraints: HBonds
hydrogen_mass: 1.5
cutoff: 2.0
ensemble: NVT
precision: single
timestep_in_fs: 4.0
platform: OpenCL
platform_properties: {'DeviceIndex': '0', 'DeviceName': 'gfx90a:sramecc+:xnack-', 'OpenCLPlatformIndex': '0', 'OpenCLPlatformName': 'AMD Accelerated Parallel Processing', 'Precision': 'single', 'UseCpuPme': 'false', 'DisablePmeStream': 'false'}
steps: 133264
elapsed_time: 59.804983
ns_per_day: 770.1036952054645
```

So it seems the installation is okay and that something is wrong in the input scripts (though they work for openMM 8.0.0, on the same machine). Any thoughts to how input scripts need to be changed to be compatible with v8.0.1+? 

Thanks very much for your help!!!
