### ISSUE TITLE
Openmm 7.7 plugin PythonAPI Vec3 TypeError, with PythonInstall warning

### ISSUE THREAD

**Issue by blannek** [openmm/openmm#4481]
Hi,

I am trying to get a plugin working that is only compatible with Openmm < 8.0 (mainly due to removal of fftpack.h), and currently using Openmm 7.7. The install seems all working well, but in PythonAPI, it would throw TypeError with Vec3 with either input or output, such as
`mpid_force.getElectrostaticPotential([Vec3(1.0, 2.0, 3.0), Vec3(2.0,3.0,4.0)], context)`
where getElectrostaticPotential is defined as
`void getElectrostaticPotential(const std::vector< OpenMM::Vec3 >& inputGrid,
                                     Context& context, std::vector< double >& outputElectrostaticPotential);`
with the Error message as
```
Traceback (most recent call last):
  File "/home/bruce/debug/test.py", line 65, in <module>
    main()
  File "/home/bruce/debug/test.py", line 37, in main
    loss = mpid_force.getElectrostaticPotential(a, context)
  File "/home/bruce/miniconda3/envs/mpid/lib/python3.10/site-packages/mpidplugin-1.0-py3.10-linux-x86_64.egg/mpidplugin.py", line 648, in getElectrostaticPotential
    return _mpidplugin.MPIDForce_getElectrostaticPotential(self, inputGrid, context)
TypeError: in method 'MPIDForce_getElectrostaticPotential', argument 2 of type 'std::vector< OpenMM::Vec3,std::allocator< OpenMM::Vec3 > > const &'
```
When checking this issue, I found when compiling this plugin, the make PythonInstall would give quite a lot warning message, seems warning the typemaps not working very well. The following is the warning messages.
```
(mpid) bruce@DESKTOP-PERP2LV:~/software/MPIDOpenMMPlugin/build$ make PythonInstall
[100%] Generating MPIDPluginWrapper.cpp
/home/bruce/miniconda3/envs/mpid/include/swig/OpenMMSwigHeaders.i:617: Warning 314: 'None' is a python keyword, renaming to '_None'
/home/bruce/miniconda3/envs/mpid/include/openmm/Vec3.h:64: Warning 389: operator[] ignored (consider using %extend)
/home/bruce/miniconda3/envs/mpid/include/openmm/Vec3.h:68: Warning 389: operator[] ignored (consider using %extend)
/home/bruce/miniconda3/envs/mpid/include/swig/OpenMMSwigHeaders.i:449: Warning 453: Can't apply (OpenMM::Context &OUTPUT). No typemaps are defined.
/home/bruce/miniconda3/envs/mpid/include/swig/OpenMMSwigHeaders.i:481: Warning 453: Can't apply (std::vector< int,std::allocator< int > > &OUTPUT). No typemaps are defined.
/home/bruce/miniconda3/envs/mpid/include/swig/OpenMMSwigHeaders.i:482: Warning 453: Can't apply (std::vector< double,std::allocator< double > > &OUTPUT). No typemaps are defined.
/home/bruce/miniconda3/envs/mpid/include/swig/OpenMMSwigHeaders.i:492: Warning 453: Can't apply (std::string &OUTPUT). No typemaps are defined.
/home/bruce/miniconda3/envs/mpid/include/swig/OpenMMSwigHeaders.i:493: Warning 453: Can't apply (std::vector< double,std::allocator< double > > &OUTPUT). No typemaps are defined.
/home/bruce/miniconda3/envs/mpid/include/swig/OpenMMSwigHeaders.i:502: Warning 453: Can't apply (OpenMM::Context &OUTPUT). No typemaps are defined.
/home/bruce/miniconda3/envs/mpid/include/swig/OpenMMSwigHeaders.i:549: Warning 453: Can't apply (std::vector< double,std::allocator< double > > &OUTPUT). No typemaps are defined.
/home/bruce/miniconda3/envs/mpid/include/swig/OpenMMSwigHeaders.i:670: Warning 453: Can't apply (std::vector< int,std::allocator< int > > &OUTPUT). No typemaps are defined.
/home/bruce/miniconda3/envs/mpid/include/swig/OpenMMSwigHeaders.i:687: Warning 453: Can't apply (OpenMM::Context &OUTPUT). No typemaps are defined.
/home/bruce/miniconda3/envs/mpid/include/swig/OpenMMSwigHeaders.i:731: Warning 453: Can't apply (std::vector< double,std::allocator< double > > &OUTPUT). No typemaps are defined.
/home/bruce/miniconda3/envs/mpid/include/swig/OpenMMSwigHeaders.i:747: Warning 453: Can't apply (std::vector< double,std::allocator< double > > &OUTPUT). No typemaps are defined.
/home/bruce/miniconda3/envs/mpid/include/swig/OpenMMSwigHeaders.i:773: Warning 453: Can't apply (OpenMM::Context &OUTPUT). No typemaps are defined.
/home/bruce/miniconda3/envs/mpid/include/swig/OpenMMSwigHeaders.i:810: Warning 453: Can't apply (std::vector< double,std::allocator< double > > &OUTPUT). No typemaps are defined.
/home/bruce/miniconda3/envs/mpid/include/swig/OpenMMSwigHeaders.i:813: Warning 453: Can't apply (std::vector< double,std::allocator< double > > &OUTPUT). No typemaps are defined.
/home/bruce/miniconda3/envs/mpid/include/swig/OpenMMSwigHeaders.i:816: Warning 453: Can't apply (std::vector< double,std::allocator< double > > &OUTPUT). No typemaps are defined.
/home/bruce/miniconda3/envs/mpid/include/swig/OpenMMSwigHeaders.i:840: Warning 453: Can't apply (OpenMM::Vec3 &OUTPUT). No typemaps are defined.
/home/bruce/miniconda3/envs/mpid/include/swig/OpenMMSwigHeaders.i:841: Warning 453: Can't apply (OpenMM::Vec3 &OUTPUT). No typemaps are defined.
/home/bruce/miniconda3/envs/mpid/include/swig/OpenMMSwigHeaders.i:842: Warning 453: Can't apply (OpenMM::Vec3 &OUTPUT). No typemaps are defined.
/home/bruce/miniconda3/envs/mpid/include/swig/OpenMMSwigHeaders.i:913: Warning 453: Can't apply (std::vector< OpenMM::Vec3,std::allocator< OpenMM::Vec3 > > &OUTPUT). No typemaps are defined.
/home/bruce/miniconda3/envs/mpid/include/swig/OpenMMSwigHeaders.i:916: Warning 453: Can't apply (std::vector< OpenMM::Vec3,std::allocator< OpenMM::Vec3 > > &OUTPUT). No typemaps are defined.
/home/bruce/miniconda3/envs/mpid/include/swig/OpenMMSwigHeaders.i:931: Warning 453: Can't apply (std::string &OUTPUT). No typemaps are defined.
/home/bruce/miniconda3/envs/mpid/include/swig/OpenMMSwigHeaders.i:932: Warning 453: Can't apply (std::string &OUTPUT). No typemaps are defined.
/home/bruce/miniconda3/envs/mpid/include/swig/OpenMMSwigHeaders.i:1022: Warning 453: Can't apply (std::vector< double,std::allocator< double > > &OUTPUT). No typemaps are defined.
/home/bruce/miniconda3/envs/mpid/include/swig/OpenMMSwigHeaders.i:1049: Warning 453: Can't apply (std::vector< double,std::allocator< double > > &OUTPUT). No typemaps are defined.
/home/bruce/miniconda3/envs/mpid/include/swig/OpenMMSwigHeaders.i:1105: Warning 453: Can't apply (std::vector< double,std::allocator< double > > &OUTPUT). No typemaps are defined.
/home/bruce/miniconda3/envs/mpid/include/swig/OpenMMSwigHeaders.i:1112: Warning 453: Can't apply (OpenMM::Context &OUTPUT). No typemaps are defined.
/home/bruce/miniconda3/envs/mpid/include/swig/OpenMMSwigHeaders.i:1140: Warning 453: Can't apply (std::vector< double,std::allocator< double > > &OUTPUT). No typemaps are defined.
/home/bruce/miniconda3/envs/mpid/include/swig/OpenMMSwigHeaders.i:1255: Warning 453: Can't apply (std::string &OUTPUT). No typemaps are defined.
/home/bruce/miniconda3/envs/mpid/include/swig/OpenMMSwigHeaders.i:1268: Warning 453: Can't apply (std::string &OUTPUT). No typemaps are defined.
/home/bruce/miniconda3/envs/mpid/include/swig/OpenMMSwigHeaders.i:1286: Warning 453: Can't apply (OpenMM::Context &OUTPUT). No typemaps are defined.
/home/bruce/miniconda3/envs/mpid/include/swig/OpenMMSwigHeaders.i:1348: Warning 453: Can't apply (OpenMM::Context &OUTPUT). No typemaps are defined.
/home/bruce/miniconda3/envs/mpid/include/swig/OpenMMSwigHeaders.i:1421: Warning 453: Can't apply (std::vector< double,std::allocator< double > > &OUTPUT). No typemaps are defined.
/home/bruce/miniconda3/envs/mpid/include/swig/OpenMMSwigHeaders.i:1422: Warning 453: Can't apply (std::vector< double,std::allocator< double > > &OUTPUT). No typemaps are defined.
/home/bruce/miniconda3/envs/mpid/include/swig/OpenMMSwigHeaders.i:1475: Warning 453: Can't apply (std::vector< OpenMM::Vec3,std::allocator< OpenMM::Vec3 > > &OUTPUT). No typemaps are defined.
/home/bruce/miniconda3/envs/mpid/include/swig/OpenMMSwigHeaders.i:1478: Warning 453: Can't apply (std::vector< OpenMM::Vec3,std::allocator< OpenMM::Vec3 > > &OUTPUT). No typemaps are defined.
/home/bruce/miniconda3/envs/mpid/include/swig/OpenMMSwigHeaders.i:1481: Warning 453: Can't apply (OpenMM::Context &OUTPUT). No typemaps are defined.
/home/bruce/miniconda3/envs/mpid/include/swig/OpenMMSwigHeaders.i:1527: Warning 453: Can't apply (OpenMM::Context &OUTPUT). No typemaps are defined.
/home/bruce/miniconda3/envs/mpid/include/swig/OpenMMSwigHeaders.i:1547: Warning 453: Can't apply (std::vector< double,std::allocator< double > > &OUTPUT). No typemaps are defined.
/home/bruce/miniconda3/envs/mpid/include/swig/OpenMMSwigHeaders.i:1582: Warning 453: Can't apply (std::vector< double,std::allocator< double > > &OUTPUT). No typemaps are defined.
/home/bruce/miniconda3/envs/mpid/include/swig/OpenMMSwigHeaders.i:1590: Warning 453: Can't apply (OpenMM::Context &OUTPUT). No typemaps are defined.
/home/bruce/miniconda3/envs/mpid/include/swig/OpenMMSwigHeaders.i:1616: Warning 453: Can't apply (std::vector< double,std::allocator< double > > &OUTPUT). No typemaps are defined.
/home/bruce/miniconda3/envs/mpid/include/swig/OpenMMSwigHeaders.i:1621: Warning 453: Can't apply (OpenMM::Context &OUTPUT). No typemaps are defined.
/home/bruce/miniconda3/envs/mpid/include/swig/OpenMMSwigHeaders.i:1653: Warning 453: Can't apply (std::vector< int,std::allocator< int > > &OUTPUT). No typemaps are defined.
/home/bruce/miniconda3/envs/mpid/include/swig/OpenMMSwigHeaders.i:1654: Warning 453: Can't apply (std::vector< double,std::allocator< double > > &OUTPUT). No typemaps are defined.
/home/bruce/miniconda3/envs/mpid/include/swig/OpenMMSwigHeaders.i:1660: Warning 453: Can't apply (std::vector< int,std::allocator< int > > &OUTPUT). No typemaps are defined.
/home/bruce/miniconda3/envs/mpid/include/swig/OpenMMSwigHeaders.i:1661: Warning 453: Can't apply (std::vector< double,std::allocator< double > > &OUTPUT). No typemaps are defined.
/home/bruce/miniconda3/envs/mpid/include/swig/OpenMMSwigHeaders.i:1670: Warning 453: Can't apply (OpenMM::Context &OUTPUT). No typemaps are defined.
/home/bruce/miniconda3/envs/mpid/include/swig/OpenMMSwigHeaders.i:1756: Warning 453: Can't apply (std::vector< int,std::allocator< int > > &OUTPUT). No typemaps are defined.
/home/bruce/miniconda3/envs/mpid/include/swig/OpenMMSwigHeaders.i:1771: Warning 453: Can't apply (std::vector< double,std::allocator< double > > &OUTPUT). No typemaps are defined.
/home/bruce/miniconda3/envs/mpid/include/swig/OpenMMSwigHeaders.i:1772: Warning 453: Can't apply (std::vector< double,std::allocator< double > > &OUTPUT). No typemaps are defined.
/home/bruce/miniconda3/envs/mpid/include/swig/OpenMMSwigHeaders.i:1793: Warning 453: Can't apply (std::vector< int,std::allocator< int > > &OUTPUT). No typemaps are defined.
/home/bruce/miniconda3/envs/mpid/include/swig/OpenMMSwigHeaders.i:1796: Warning 453: Can't apply (std::vector< std::vector< int,std::allocator< int > >,std::allocator< std::vector< int,std::allocator< int > > > > &OUTPUT). No typemaps are defined.
/home/bruce/miniconda3/envs/mpid/include/swig/OpenMMSwigHeaders.i:1807: Warning 453: Can't apply (std::vector< OpenMM::Vec3,std::allocator< OpenMM::Vec3 > > &OUTPUT). No typemaps are defined.
/home/bruce/miniconda3/envs/mpid/include/swig/OpenMMSwigHeaders.i:1810: Warning 453: Can't apply (std::vector< OpenMM::Vec3,std::allocator< OpenMM::Vec3 > > &OUTPUT). No typemaps are defined.
/home/bruce/miniconda3/envs/mpid/include/swig/OpenMMSwigHeaders.i:1813: Warning 453: Can't apply (std::vector< OpenMM::Vec3,std::allocator< OpenMM::Vec3 > > &OUTPUT). No typemaps are defined.
/home/bruce/miniconda3/envs/mpid/include/swig/OpenMMSwigHeaders.i:1816: Warning 453: Can't apply (std::vector< double,std::allocator< double > > &OUTPUT). No typemaps are defined.
/home/bruce/miniconda3/envs/mpid/include/swig/OpenMMSwigHeaders.i:1819: Warning 453: Can't apply (OpenMM::Context &OUTPUT). No typemaps are defined.
/home/bruce/miniconda3/envs/mpid/include/swig/OpenMMSwigHeaders.i:1820: Warning 453: Can't apply (std::vector< double,std::allocator< double > > &OUTPUT). No typemaps are defined.
/home/bruce/miniconda3/envs/mpid/include/swig/OpenMMSwigHeaders.i:1824: Warning 453: Can't apply (OpenMM::Context &OUTPUT). No typemaps are defined.
/home/bruce/miniconda3/envs/mpid/include/swig/OpenMMSwigHeaders.i:1870: Warning 453: Can't apply (OpenMM::Context &OUTPUT). No typemaps are defined.
/home/bruce/miniconda3/envs/mpid/include/swig/OpenMMSwigHeaders.i:1957: Warning 453: Can't apply (std::vector< double,std::allocator< double > > &OUTPUT). No typemaps are defined.
/home/bruce/miniconda3/envs/mpid/include/swig/OpenMMSwigHeaders.i:1974: Warning 453: Can't apply (std::string &OUTPUT). No typemaps are defined.
/home/bruce/miniconda3/envs/mpid/include/swig/OpenMMSwigHeaders.i:1975: Warning 453: Can't apply (std::vector< double,std::allocator< double > > &OUTPUT). No typemaps are defined.
/home/bruce/miniconda3/envs/mpid/include/swig/OpenMMSwigHeaders.i:1985: Warning 453: Can't apply (std::set< int > &OUTPUT). No typemaps are defined.
/home/bruce/miniconda3/envs/mpid/include/swig/OpenMMSwigHeaders.i:1986: Warning 453: Can't apply (std::set< int > &OUTPUT). No typemaps are defined.
/home/bruce/miniconda3/envs/mpid/include/swig/OpenMMSwigHeaders.i:1991: Warning 453: Can't apply (OpenMM::Context &OUTPUT). No typemaps are defined.
/home/bruce/miniconda3/envs/mpid/include/swig/OpenMMSwigHeaders.i:2027: Warning 453: Can't apply (OpenMM::Context &OUTPUT). No typemaps are defined.
/home/bruce/miniconda3/envs/mpid/include/swig/OpenMMSwigHeaders.i:2071: Warning 453: Can't apply (std::vector< double,std::allocator< double > > &OUTPUT). No typemaps are defined.
/home/bruce/miniconda3/envs/mpid/include/swig/OpenMMSwigHeaders.i:2085: Warning 453: Can't apply (std::set< int > &OUTPUT). No typemaps are defined.
/home/bruce/miniconda3/envs/mpid/include/swig/OpenMMSwigHeaders.i:2093: Warning 453: Can't apply (OpenMM::Context &OUTPUT). No typemaps are defined.
/home/bruce/miniconda3/envs/mpid/include/swig/OpenMMSwigHeaders.i:2170: Warning 453: Can't apply (std::vector< double,std::allocator< double > > &OUTPUT). No typemaps are defined.
/home/bruce/miniconda3/envs/mpid/include/swig/OpenMMSwigHeaders.i:2175: Warning 453: Can't apply (std::string &OUTPUT). No typemaps are defined.
/home/bruce/miniconda3/envs/mpid/include/swig/OpenMMSwigHeaders.i:2176: Warning 453: Can't apply (std::string &OUTPUT). No typemaps are defined.
/home/bruce/miniconda3/envs/mpid/include/swig/OpenMMSwigHeaders.i:2184: Warning 453: Can't apply (std::string &OUTPUT). No typemaps are defined.
/home/bruce/miniconda3/envs/mpid/include/swig/OpenMMSwigHeaders.i:2202: Warning 453: Can't apply (std::string &OUTPUT). No typemaps are defined.
/home/bruce/miniconda3/envs/mpid/include/swig/OpenMMSwigHeaders.i:2203: Warning 453: Can't apply (std::vector< double,std::allocator< double > > &OUTPUT). No typemaps are defined.
/home/bruce/miniconda3/envs/mpid/include/swig/OpenMMSwigHeaders.i:2212: Warning 453: Can't apply (OpenMM::Context &OUTPUT). No typemaps are defined.
/home/bruce/miniconda3/envs/mpid/include/swig/OpenMMSwigHeaders.i:2242: Warning 453: Can't apply (OpenMM::Context &OUTPUT). No typemaps are defined.
/home/bruce/miniconda3/envs/mpid/include/swig/OpenMMSwigHeaders.i:2306: Warning 453: Can't apply (std::vector< double,std::allocator< double > > &OUTPUT). No typemaps are defined.
/home/bruce/miniconda3/envs/mpid/include/swig/OpenMMSwigHeaders.i:2317: Warning 453: Can't apply (std::vector< double,std::allocator< double > > &OUTPUT). No typemaps are defined.
/home/bruce/miniconda3/envs/mpid/include/swig/OpenMMSwigHeaders.i:2336: Warning 453: Can't apply (std::string &OUTPUT). No typemaps are defined.
/home/bruce/miniconda3/envs/mpid/include/swig/OpenMMSwigHeaders.i:2337: Warning 453: Can't apply (std::vector< double,std::allocator< double > > &OUTPUT). No typemaps are defined.
/home/bruce/miniconda3/envs/mpid/include/swig/OpenMMSwigHeaders.i:2346: Warning 453: Can't apply (OpenMM::Context &OUTPUT). No typemaps are defined.
/home/bruce/miniconda3/envs/mpid/include/swig/OpenMMSwigHeaders.i:2375: Warning 453: Can't apply (std::vector< double,std::allocator< double > > &OUTPUT). No typemaps are defined.
/home/bruce/miniconda3/envs/mpid/include/swig/OpenMMSwigHeaders.i:2381: Warning 453: Can't apply (OpenMM::Context &OUTPUT). No typemaps are defined.
/home/bruce/miniconda3/envs/mpid/include/swig/OpenMMSwigHeaders.i:2400: Warning 453: Can't apply (OpenMM::Context &OUTPUT). No typemaps are defined.
/home/bruce/miniconda3/envs/mpid/include/swig/OpenMMSwigHeaders.i:2448: Warning 453: Can't apply (OpenMM::Context &OUTPUT). No typemaps are defined.
/home/bruce/miniconda3/envs/mpid/include/swig/OpenMMSwigHeaders.i:2449: Warning 453: Can't apply (std::vector< double,std::allocator< double > > &OUTPUT). No typemaps are defined.
/home/bruce/miniconda3/envs/mpid/include/swig/OpenMMSwigHeaders.i:2453: Warning 453: Can't apply (OpenMM::Context &OUTPUT). No typemaps are defined.
/home/bruce/miniconda3/envs/mpid/include/swig/OpenMMSwigHeaders.i:2456: Warning 453: Can't apply (OpenMM::Context &OUTPUT). No typemaps are defined.
/home/bruce/miniconda3/envs/mpid/include/swig/OpenMMSwigHeaders.i:2478: Warning 453: Can't apply (OpenMM::Context &OUTPUT). No typemaps are defined.
/home/bruce/miniconda3/envs/mpid/include/swig/OpenMMSwigHeaders.i:2507: Warning 453: Can't apply (OpenMM::Context &OUTPUT). No typemaps are defined.
/home/bruce/miniconda3/envs/mpid/include/swig/OpenMMSwigHeaders.i:2550: Warning 453: Can't apply (OpenMM::Context &OUTPUT). No typemaps are defined.
/home/bruce/miniconda3/envs/mpid/include/swig/OpenMMSwigHeaders.i:2565: Warning 453: Can't apply (OpenMM::SerializationNode &OUTPUT). No typemaps are defined.
/home/bruce/miniconda3/envs/mpid/include/swig/OpenMMSwigHeaders.i:2589: Warning 453: Can't apply (ContextImpl &OUTPUT). No typemaps are defined.
/home/bruce/miniconda3/envs/mpid/include/swig/OpenMMSwigHeaders.i:2621: Warning 453: Can't apply (ContextImpl &OUTPUT). No typemaps are defined.
/home/bruce/miniconda3/envs/mpid/include/swig/OpenMMSwigHeaders.i:2622: Warning 453: Can't apply (ContextImpl &OUTPUT). No typemaps are defined.
/home/bruce/miniconda3/envs/mpid/include/swig/OpenMMSwigHeaders.i:2657: Warning 453: Can't apply (OpenMM::Vec3 &OUTPUT). No typemaps are defined.
/home/bruce/miniconda3/envs/mpid/include/swig/OpenMMSwigHeaders.i:2658: Warning 453: Can't apply (OpenMM::Vec3 &OUTPUT). No typemaps are defined.
/home/bruce/miniconda3/envs/mpid/include/swig/OpenMMSwigHeaders.i:2659: Warning 453: Can't apply (OpenMM::Vec3 &OUTPUT). No typemaps are defined.
/home/bruce/miniconda3/envs/mpid/lib/python3.10/site-packages/setuptools/_distutils/cmd.py:66: SetuptoolsDeprecationWarning: setup.py install is deprecated.
!!

        ********************************************************************************
        Please avoid running ``setup.py`` directly.
        Instead, use pypa/build, pypa/installer or other
        standards-based tools.

        See https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html for details.
        ********************************************************************************

!!
  self.initialize_options()
/home/bruce/miniconda3/envs/mpid/lib/python3.10/site-packages/setuptools/_distutils/cmd.py:66: EasyInstallDeprecationWarning: easy_install command is deprecated.
!!

        ********************************************************************************
        Please avoid running ``setup.py`` and ``easy_install``.
        Instead, use pypa/build, pypa/installer or other
        standards-based tools.

        See https://github.com/pypa/setuptools/issues/917 for details.
        ********************************************************************************

!!
  self.initialize_options()
zip_safe flag not set; analyzing archive contents...
__pycache__._mpidplugin.cpython-310: module references __file__
[100%] Built target PythonInstall

```

The environment information
Python=3.10.13
openmm=7.7.0
swig=3.0.8 or 4.0.2 (both attempted)
g++=11.4 or 8.2 (both attempted)

Does anyone have an idea how to fix this issue?
Thanks in advance!

**Comment by peastman** [comment]
Typemaps are how you tell SWIG how to convert types between Python and C++.  OpenMM defines a lot of typemaps to handle classes like Vec3.  They're contained in [this file](https://github.com/openmm/openmm/blob/master/wrappers/python/src/swig_doxygen/swig_lib/python/typemaps.i).  I think you should be able to use it directly.  Add `%include "typemaps.h"` to the top of your interface file to include it.

**Comment by blannek** [comment]
> Typemaps are how you tell SWIG how to convert types between Python and C++. OpenMM defines a lot of typemaps to handle classes like Vec3. They're contained in [this file](https://github.com/openmm/openmm/blob/master/wrappers/python/src/swig_doxygen/swig_lib/python/typemaps.i). I think you should be able to use it directly. Add `%include "typemaps.h"` to the top of your interface file to include it.

I should have mentioned this. Since I opened the openmm and swig with conda, the typemaps.i file exists in my conda path
`~/miniconda3/envs/mpid/include/swig`
which only has several lines differernt with the file you provide, i.e., it definitely contains typemaps of context and Vec3, and I have checked this path is set as input directory for swig. Also, I tried directly including the file you provide or replace the file in conda include path, neither helps. The plugin is at [here](https://github.com/andysim/MPIDOpenMMPlugin) if you need.

**Comment by peastman** [comment]
I see that you even get warnings about lines that only involve standard types like

> /home/bruce/miniconda3/envs/mpid/include/swig/OpenMMSwigHeaders.i:481: Warning 453: Can't apply (std::vector< int,std::allocator< int > > &OUTPUT). No typemaps are defined.

I'm really not sure what's going on with that.  It's possible that warning is a red herring and not directly related to your problem.  Try opening the .cpp file generated by SWIG and find the implementation of `MPIDForce_getElectrostaticPotential()`.  You should be able to find the code that's producing the exception.  What type or types is it looking for?

**Comment by blannek** [comment]
> I see that you even get warnings about lines that only involve standard types like
> 
> > /home/bruce/miniconda3/envs/mpid/include/swig/OpenMMSwigHeaders.i:481: Warning 453: Can't apply (std::vector< int,std::allocator< int > > &OUTPUT). No typemaps are defined.
> 
Good point. I am sure the vector is working. Currently I am hacking by replacing the vector<Vec3> by vector<double> and it definitely works.
> I'm really not sure what's going on with that. It's possible that warning is a red herring and not directly related to your problem. Try opening the .cpp file generated by SWIG and find the implementation of `MPIDForce_getElectrostaticPotential()`. You should be able to find the code that's producing the exception. What type or types is it looking for?
>
I am not familiar with swig generated .cpp file, but the following should be what you ask for. It seems asking for correct type to me.
```
SWIGINTERN PyObject *_wrap_MPIDForce_getElectrostaticPotential(PyObject *SWIGUNUSEDPARM(self), PyObject *args) {
  PyObject *resultobj = 0;
  OpenMM::MPIDForce *arg1 = (OpenMM::MPIDForce *) 0 ;
  std::vector< OpenMM::Vec3,std::allocator< OpenMM::Vec3 > > *arg2 = 0 ;
  OpenMM::Context *arg3 = 0 ;
  std::vector< double,std::allocator< double > > *arg4 = 0 ;
  void *argp1 = 0 ;
  int res1 = 0 ;
  int res2 = SWIG_OLDOBJ ;
  void *argp3 = 0 ;
  int res3 = 0 ;
  std::vector< double,std::allocator< double > > temp4 ;
  int res4 = SWIG_TMPOBJ ;
  PyObject *swig_obj[3] ;
  
  arg4 = &temp4;
  if (!SWIG_Python_UnpackTuple(args, "MPIDForce_getElectrostaticPotential", 3, 3, swig_obj)) SWIG_fail;
  res1 = SWIG_ConvertPtr(swig_obj[0], &argp1,SWIGTYPE_p_OpenMM__MPIDForce, 0 |  0 );
  if (!SWIG_IsOK(res1)) {
    SWIG_exception_fail(SWIG_ArgError(res1), "in method '" "MPIDForce_getElectrostaticPotential" "', argument " "1"" of type '" "OpenMM::MPIDForce *""'"); 
  }
  arg1 = reinterpret_cast< OpenMM::MPIDForce * >(argp1);
  {
    std::vector< OpenMM::Vec3,std::allocator< OpenMM::Vec3 > > *ptr = (std::vector< OpenMM::Vec3,std::allocator< OpenMM::Vec3 > > *)0;
    res2 = swig::asptr(swig_obj[1], &ptr);
    if (!SWIG_IsOK(res2)) {
      SWIG_exception_fail(SWIG_ArgError(res2), "in method '" "MPIDForce_getElectrostaticPotential" "', argument " "2"" of type '" "std::vector< OpenMM::Vec3,std::allocator< OpenMM::Vec3 > > const &""'"); 
    }
    if (!ptr) {
      SWIG_exception_fail(SWIG_ValueError, "invalid null reference " "in method '" "MPIDForce_getElectrostaticPotential" "', argument " "2"" of type '" "std::vector< OpenMM::Vec3,std::allocator< OpenMM::Vec3 > > const &""'"); 
    }
    arg2 = ptr;
  }
  res3 = SWIG_ConvertPtr(swig_obj[2], &argp3, SWIGTYPE_p_OpenMM__Context,  0 );
  if (!SWIG_IsOK(res3)) {
    SWIG_exception_fail(SWIG_ArgError(res3), "in method '" "MPIDForce_getElectrostaticPotential" "', argument " "3"" of type '" "OpenMM::Context &""'"); 
  }
  if (!argp3) {
    SWIG_exception_fail(SWIG_ValueError, "invalid null reference " "in method '" "MPIDForce_getElectrostaticPotential" "', argument " "3"" of type '" "OpenMM::Context &""'"); 
  }
  arg3 = reinterpret_cast< OpenMM::Context * >(argp3);
  (arg1)->getElectrostaticPotential((std::vector< OpenMM::Vec3,std::allocator< OpenMM::Vec3 > > const &)*arg2,*arg3,*arg4);
  resultobj = SWIG_Py_Void();
  if (SWIG_IsTmpObj(res4)) {
    resultobj = SWIG_Python_AppendOutput(resultobj, swig::from((*arg4)));
  } else {
    int new_flags = SWIG_IsNewObj(res4) ? (SWIG_POINTER_OWN |  0 ) :  0 ;
    resultobj = SWIG_Python_AppendOutput(resultobj, SWIG_NewPointerObj((void*)(arg4), SWIGTYPE_p_std__vectorT_double_std__allocatorT_double_t_t, new_flags));
  }
  if (SWIG_IsNewObj(res2)) delete arg2;
  return resultobj;
fail:
  if (SWIG_IsNewObj(res2)) delete arg2;
  return NULL;
}
```
