### ISSUE TITLE
TypeError in custom integrator despite correct type

### ISSUE THREAD

**Issue by bbye98** [openmm/openmm#4529]
Hello!

I recently installed OpenMM 7.7.0 with Python 3.10 on a new machine with a custom integrator found [here](https://github.com/bbye98/mdhelper/tree/main/lib/openmm-ic-plugin).

Bizarrely, when I call `simulation.step(timesteps)` with the custom integrator registered the first time, it works fine. Then, the second time I call it, get the following error despite the `timesteps` being an `int`:

```
^CTraceback (most recent call last):
  File "/home/bye/miniconda3/envs/research/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/bye/miniconda3/envs/research/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/bye/.vscode-server/extensions/ms-python.debugpy-2024.4.0-linux-x64/bundled/libs/debugpy/adapter/../../debugpy/launcher/../../debugpy/__main__.py", line 39, in <module>
    cli.main()
  File "/home/bye/.vscode-server/extensions/ms-python.debugpy-2024.4.0-linux-x64/bundled/libs/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/cli.py", line 430, in main
    run()
  File "/home/bye/.vscode-server/extensions/ms-python.debugpy-2024.4.0-linux-x64/bundled/libs/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/cli.py", line 284, in run_file
    runpy.run_path(target, run_name="__main__")
  File "/home/bye/.vscode-server/extensions/ms-python.debugpy-2024.4.0-linux-x64/bundled/libs/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 321, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "/home/bye/.vscode-server/extensions/ms-python.debugpy-2024.4.0-linux-x64/bundled/libs/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 135, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/home/bye/.vscode-server/extensions/ms-python.debugpy-2024.4.0-linux-x64/bundled/libs/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 124, in _run_code
    exec(code, run_globals)
  File "/mnt/e/research/gcme/coacervate/scripts/nvt_coacervate_confined.py", line 496, in <module>
    run(N, N_p, x_p, x_c, dV_md, bc, frames, path=f"{path}/{bc}")
  File "/mnt/e/research/gcme/coacervate/scripts/nvt_coacervate_confined.py", line 450, in run
    simulation.step(10000)
  File "/home/bye/miniconda3/envs/research/lib/python3.10/site-packages/openmm/app/simulation.py", line 141, in step
    self._simulate(endStep=self.currentStep+steps)
  File "/home/bye/miniconda3/envs/research/lib/python3.10/site-packages/openmm/app/simulation.py", line 210, in _simulate
    self.integrator.step(stepsToGo)
  File "/home/bye/miniconda3/envs/research/lib/python3.10/site-packages/openmm_ic-1.0-py3.10-linux-x86_64.egg/openmm_ic.py", line 373, in step
    return _openmm_ic.ICLangevinIntegrator_step(self, steps)
TypeError: in method 'ICLangevinIntegrator_step', argument 2 of type 'int'
```

In Python debugging mode, calling `simulation.step` with `timesteps` of 1, 2, and 3 works fine. For all values above 4, I get the error above.

Am I missing something simple or is this a SWIG-related issue? Despite including `%include "swig/typemaps.i"` at the top of the [interface file](https://github.com/bbye98/mdhelper/blob/main/lib/openmm-ic-plugin/python/icplugin.i), I still get a number of `... No typemaps are defined.` errors when compiling.

Thank you!

**Comment by bbye98** [comment]
@peastman Yes, this is a custom CUDA implementation. I started having issues on my new computer/install, despite this custom integrator (compiled a while back) working solidly on my older machine.

OpenMM 8.1.0 with Python 3.12 did not resolve the issue, unfortunately:

```
Traceback (most recent call last):
  File "/home/bye/research/gaussian/src/nvt_coacervate_confined_8.py", line 496, in <module>
    run(N, N_p, x_p, x_c, dV_md, bc, frames, path=f"{path}/{bc}")
  File "/home/bye/research/gaussian/src/nvt_coacervate_confined_8.py", line 451, in run
    simulation.step(timesteps)
  File "/home/bye/miniconda3/envs/openmm8/lib/python3.11/site-packages/openmm/app/simulation.py", line 147, in step
    self._simulate(endStep=self.currentStep+steps)
  File "/home/bye/miniconda3/envs/openmm8/lib/python3.11/site-packages/openmm/app/simulation.py", line 216, in _simulate
    self.integrator.step(stepsToGo)
  File "/home/bye/miniconda3/envs/openmm8/lib/python3.11/site-packages/constvplugin-1.0-py3.11-linux-x86_64.egg/constvplugin.py", line 386, in step
    return _constvplugin.ConstVLangevinIntegrator_step(self, steps)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: in method 'ConstVLangevinIntegrator_step', argument 2 of type 'int'
```

The value of `timesteps` is `10_000_000` and is an `int` as reported by Python's `type()`.

**Comment by peastman** [comment]
Don't use 8.1.0.  It has a serious bug that can cause crashes.  The current release is 8.1.1.

When you built your plugin, SWIG generated a .cxx file defining the interface.  I suggest looking at that file.  Find the definition of `ICLangevinIntegrator_step()` and see if you can identify what line it's happening at.  If necessary you can add debugging code to that file to figure out what type of object is being passed to it.  And of course, check your Python code to see what kind of object you're passing to `step()`.

**Comment by bbye98** [comment]
I believe you are referring to this chunk of code:

```
SWIGINTERN PyObject *_wrap_ICLangevinIntegrator_step(PyObject *self, PyObject *args) {
  PyObject *resultobj = 0;
  ICPlugin::ICLangevinIntegrator *arg1 = (ICPlugin::ICLangevinIntegrator *) 0 ;
  int arg2 ;
  void *argp1 = 0 ;
  int res1 = 0 ;
  int val2 ;
  int ecode2 = 0 ;
  PyObject *swig_obj[2] ;
  
  (void)self;
  if (!SWIG_Python_UnpackTuple(args, "ICLangevinIntegrator_step", 2, 2, swig_obj)) SWIG_fail;
  res1 = SWIG_ConvertPtr(swig_obj[0], &argp1,SWIGTYPE_p_ICPlugin__ICLangevinIntegrator, 0 |  0 );
  if (!SWIG_IsOK(res1)) {
    SWIG_exception_fail(SWIG_ArgError(res1), "in method '" "ICLangevinIntegrator_step" "', argument " "1"" of type '" "ICPlugin::ICLangevinIntegrator *""'"); 
  }
  arg1 = reinterpret_cast< ICPlugin::ICLangevinIntegrator * >(argp1);
  ecode2 = SWIG_AsVal_int(swig_obj[1], &val2);
  if (!SWIG_IsOK(ecode2)) {
    SWIG_exception_fail(SWIG_ArgError(ecode2), "in method '" "ICLangevinIntegrator_step" "', argument " "2"" of type '" "int""'");
  } 
  arg2 = static_cast< int >(val2);
  {
    try {
      (arg1)->step(arg2);
    } catch (std::exception &e) {
      PyErr_SetString(PyExc_Exception, const_cast<char *>(e.what()));
      return NULL;
    }
  }
  resultobj = SWIG_Py_Void();
  return resultobj;
fail:
  return NULL;
}
```

I believe the error lies in `ecode2 = SWIG_AsVal_int(swig_obj[1], &val2);`, in that the `int` I pass to `simulation.step()` is failing to be typecasted...into an `int`? I'm not too well-versed in C++, so I appreciate any guidance you may be able to provide.

**Comment by peastman** [comment]
Are you absolutely certain you're really passing an int?  Can you show your code?

**Comment by bbye98** [comment]
@peastman Absolutely! Here's a snippet of the full simulation code (after setting up the simulation):

```
def run(N: int, N_p: int, x_p: float, x_c: float, dV_md: float, bc: str, 
        frames: int, *, T: unit.Quantity = 300 * unit.kelvin,
        size: unit.Quantity = 0.275 * unit.nanometer,
        mass: unit.Quantity = 18.01528 * unit.gram / unit.mole,
        N_m: float = 4.0, rho_md: float = 2.5, L_z_scale: float = 2.5,
        b_md: float = 0.8, k_md: float = 100.0, u_shift_md: float = 1e-3,
        varepsilon_r: float = 78.0, a_scale: float = 1.0, dt_md: float = 0.02,
        every: int = 10_000, device: int = 0, index: int = None, 
        path: str = os.getcwd(), verbose: bool = True) -> None:

    # ...system initialization

    integrator = ICLangevinIntegrator(T, gamma, dt)

    # ...setting up image charges

    simulation = app.Simulation(topology, system, integrator, plat, prop)
    simulation.context.setPositions(pos) # energy-minimized initial state

    # Write topology file
    with open(f"{fname}.cif", "w") as f:
        app.PDBxFile.writeFile(simulation.topology, pos, f, keepIds=True)
    logging.info(f"Wrote topology to '{fname}.cif'.")

    ### INITIAL EQUILIBRATION
    
    logging.info("Starting initial equilibration...")

    # Register checkpoint, thermodynamic state data, and trajectory reporters
    simulation.reporters.append(app.CheckpointReporter(f"{fname}_equil.chk", 10 * every))
    logging.info("Registered checkpoint reporter writing to "
                 f"'{fname}_equil.cif' to the simulation.")
    simulation.reporters.append(NetCDFReporter(f"{fname}_equil.nc", every))
    logging.info("Registered trajectory reporter writing to "
                 f"'{fname}_equil.nc' to the simulation.")
    timesteps = 10_000 # frames * every // 5
    for o in [sys.stdout, f"{fname}_equil.log"]:
        simulation.reporters.append(
            app.StateDataReporter(
                o, reportInterval=every, step=True, temperature=True, 
                volume=True, potentialEnergy=True, kineticEnergy=True,
                totalEnergy=True, remainingTime=True, speed=True, 
                totalSteps=timesteps
            )
        )
    logging.info("Registered state data reporter writing to "
                 f"'{fname}_equil.log' to the simulation.")
    
    # Run NVT equilibration
    logging.info(f"Starting NVT equilibration with {timesteps:,} timesteps...")
    simulation.step(timesteps)
    simulation.saveState(f"{fname}_equil.xml")
    logging.info("Simulation completed. Wrote final simulation state "
                 f"to '{fname}_equil.xml'.")

    ### CHARGING
    
    logging.info("Starting charging process...")

    for i, sign in enumerate((1, -1)):
        ii = N + i * N_wall // 2
        for j in range(N_wall // 2):
            pair_elec_rec.setParticleParameters(ii + j, sign * q_w_scaled, 0, 0)
            pair_elec_dir.setParticleParameters(ii + j, (sign * q_w_scaled, 1))
    pair_elec_rec.updateParametersInContext(simulation.context)
    pair_elec_dir.updateParametersInContext(simulation.context)
    logging.info("Updated wall particle charges in the simulation context.")

    # Register checkpoint, thermodynamic state data, and trajectory reporters
    simulation.reporters = []
    simulation.reporters.append(app.CheckpointReporter(f"{fname}_charge.chk", 10 * every))
    logging.info("Registered checkpoint reporter writing to "
                 f"'{fname}_charge.cif' to the simulation.")
    simulation.reporters.append(NetCDFReporter(f"{fname}_charge.nc", every / 100))
    logging.info("Registered trajectory reporter writing to "
                 f"'{fname}_charge.nc' to the simulation.")
    timesteps = 10_000 # frames * every // 5
    for o in [sys.stdout, f"{fname}_charge.log"]:
        simulation.reporters.append(
            app.StateDataReporter(
                o, reportInterval=every, step=True, temperature=True, 
                volume=True, potentialEnergy=True, kineticEnergy=True,
                totalEnergy=True, remainingTime=True, speed=True, 
                totalSteps=timesteps
            )
        )
    logging.info("Registered state data reporter writing to "
                 f"'{fname}_charge.log' to the simulation.")
    
    # Run NVT charging
    logging.info(f"Starting NVT charging with {timesteps:,} timesteps...")
    simulation.step(timesteps)
    simulation.saveState(f"{fname}_charge.xml")
    logging.info("Simulation completed. Wrote final simulation state "
                 f"to '{fname}_charge.xml'.")

    ### NVT PRODUCTION RUN
    
    logging.info("Starting NVT run...")

    # Register checkpoint, thermodynamic state data, and trajectory reporters
    simulation.reporters = []
    simulation.reporters.append(app.CheckpointReporter(f"{fname}.chk", 100 * every))
    logging.info("Registered checkpoint reporter writing to "
                 f"'{fname}.cif' to the simulation.")
    simulation.reporters.append(NetCDFReporter(f"{fname}.nc", every))
    logging.info("Registered trajectory reporter writing to "
                 f"'{fname}.nc' to the simulation.")
    timesteps = 10_000 # frames * every
    for o in [sys.stdout, f"{fname}.log"]:
        simulation.reporters.append(
            app.StateDataReporter(
                o, reportInterval=every, step=True, temperature=True, 
                volume=True, potentialEnergy=True, kineticEnergy=True,
                totalEnergy=True, remainingTime=True, speed=True, 
                totalSteps=timesteps
            )
        )
    logging.info("Registered state data reporter writing to "
                 f"'{fname}.log' to the simulation.")
    
    # Run NVT simulation
    logging.info(f"Starting NVT run with {timesteps:,} timesteps...")
    simulation.step(timesteps)
    simulation.saveState(f"{fname}.xml")
    logging.info("Simulation completed. Wrote final simulation state "
                 f"to '{fname}.xml'.")

if __name__ == "__main__":
    N = 48_000
    N_p = 40
    x_p = 317 / 600 # 0.2641581561368157 each
    x_c = 1_673 / 24_000 # 0.03485328999272898 each
    dV_md = 1
    bc = "ic"
    frames = 1_000
    path = "/mnt/e/research/gcme/coacervate/data"
    run(N, N_p, x_p, x_c, dV_md, bc, frames, path=f"{path}/{bc}")
```

The first `simulation.step(timesteps)` call under `INITIAL EQUILIBRATION` runs without any issues. The `simulation.step(timesteps)` call under `CHARGING` gives me the error I reported previously. You can see I've overwritten what I normally would have used as my number of timesteps with just `10_000`, which is an `int`.

**Comment by bbye98** [comment]
It may be worthwhile to point out that should I comment out the `INITIAL EQUILIBRATION` section, the `simulation.step(timesteps)` call under `CHARGING` works fine, but the `simulation.step(timesteps)` call under `NVT PRODUCTION RUN` raises the TypeError still. Looks like this is only affecting the second call onwards?

**Comment by bbye98** [comment]
I've had some more success with changing the second argument of `simulation.reporters.append(NetCDFReporter(f"{fname}_charge.nc", every / 100))` to an `int`, i.e., `every // 100`. Haven't tested all possible cases, but so far nothing has crashed yet.

Closing this issue for the time being!
