### ISSUE TITLE
Interaction energy

### ISSUE THREAD

**Issue by maciejwisniewski-drugdiscovery** [openmm/openmm#4543]
Hello, I will be conducting molecular dynamics for several protein-ligand complexes. Is it possible to calculate the interaction energy between the protein and the ligand for individual simulation steps?

**Comment by peastman** [comment]
See https://openmm.github.io/openmm-cookbook/latest/notebooks/cookbook/Computing%20Interaction%20Energies.html.

**Comment by maciejwisniewski-drugdiscovery** [comment]
Thanks, but when I am trying to reproduce this tutorial with my code:

```
from openmm import *
from openmm.app import *
from openmm.unit import *
from openff.toolkit.topology import Molecule, Topology
from openmmforcefields.generators import GAFFTemplateGenerator


modeller = pdbfile.PDBFile('topology.pdb')
forcefield = ForceField("amber14-all.xml","amber14/tip3pfb.xml")
ligand_file='6ny0_ligand.sdf'
gaff = GAFFTemplateGenerator(molecules=Molecule.from_file(ligand_file,allow_undefined_stereo=True))
forcefield.registerTemplateGenerator(gaff.generator)

system = 
 forcefield.createSystem(modeller.topology, nonbondedMethod=PME, nonbondedCutoff=1*nanometer, constraints=None)

solvent = set([a.index for a in modeller.topology.atoms() if a.residue.name in ('HOH', 'Cl','Na')])
#ligand = set([a.index for a in modeller.topology.atoms() if a.residue.name in ('UNK')])
protein = set([a.index for a in modeller.topology.atoms() if (a.index not in solvent)])

for force in system.getForces():
	if isinstance(force, NonbondedForce):
		force.setForceGroup(0)
		force.addGlobalParameter("solute_coulomb_scale", 1)
		force.addGlobalParameter("solute_lj_scale", 1)
		force.addGlobalParameter("solvent_coulomb_scale", 1)
		force.addGlobalParameter("solvent_lj_scale", 1)
		for i in range(force.getNumParticles()):
			charge, sigma, epsilon = force.getParticleParameters(i)
			force.setParticleParameters(i, 0, 0, 0)
			if i in protein:
				force.addParticleParameterOffset("solute_coulomb_scale", i, charge, 0, 0)
				force.addParticleParameterOffset("solute_lj_scale", i, 0, sigma, epsilon)
			else:
				force.addParticleParameterOffset("solvent_coulomb_scale", i, charge, 0, 0)
				force.addParticleParameterOffset("solvent_lj_scale", i, 0, sigma, epsilon)
		for i in range(force.getNumExceptions()):
			p1, p2, chargeProd, sigma, epsilon = force.getExceptionParameters(i)
			force.setExceptionParameters(i, p1, p2, 0, 0, 0)
	else:
		force.setForceGroup(2)

integrator = LangevinIntegrator(300*kelvin,5.0/picoseconds,2.0*femtoseconds)
context = Context(system, integrator)
context.setPositions(modeller.positions)

def energy(solute_coulomb_scale, solute_lj_scale, solvent_coulomb_scale, solvent_lj_scale):
    context.setParameter("solute_coulomb_scale", solute_coulomb_scale)
    context.setParameter("solute_lj_scale", solute_lj_scale)
    context.setParameter("solvent_coulomb_scale", solvent_coulomb_scale)
    context.setParameter("solvent_lj_scale", solvent_lj_scale)
    return context.getState(getEnergy=True, groups={0}).getPotentialEnergy()

total_coulomb = energy(1, 0, 1, 0)
```

This Error occurs:

> Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/mnt/evafs/groups/sfglab/mwisniewski/anaconda3/envs/openmm/lib/python3.9/site-packages/openmm/openmm.py", line 12111, in getState
    state = _openmm.Context_getState(self, types, enforcePeriodicBox, groups_mask)
openmm.OpenMMException: clSetKernelArg

Do you have an idea what I'm doing wrong?
