### ISSUE TITLE
No template found for residue

### ISSUE THREAD

**Issue by pradipchm** [openmm/openmm#4550]
Hi,
I'm trying to simulate with the openmm files generated from Ligpargen python. I know this is a common problem people faced and I could not figured from those discussions. The error shows
`ValueError: No template found for residue 1 (PBA).  The set of atoms matches PBA, but the bonds are different.  For more information, see https://github.com/openmm/openmm/wiki/Frequently-Asked-Questions#template`
here is my PDB file,
```xml
TITLE     GROwing Monsters And Cloning Shrimps
REMARK    THIS IS A SIMULATION BOX
CRYST1   37.575   37.575   37.575  90.00  90.00  90.00 P 1           1
MODEL        1
ATOM      1  O2  PBA     1      21.499  20.696  17.980  1.00  0.00           O
ATOM      2  O1  PBA     1      19.756  21.167  16.682  1.00  0.00           O
ATOM      3  H1  PBA     1      20.321  21.615  16.290  1.00  0.00           H
ATOM      4  C7  PBA     1      20.306  20.549  17.651  1.00  0.00           C
ATOM      5  N1  PBA     1      17.027  16.742  20.324  1.00  0.00           N
ATOM      6  H1A PBA     1      16.401  16.394  19.784  1.00  0.00           H
ATOM      7  H1B PBA     1      17.531  16.092  20.660  1.00  0.00           H
ATOM      8  C2  PBA     1      18.159  19.297  17.898  1.00  0.00           C
ATOM      9  H2  PBA     1      17.828  19.755  17.160  1.00  0.00           H
ATOM     10  C3  PBA     1      17.366  18.357  18.546  1.00  0.00           C
ATOM     11  H3  PBA     1      16.505  18.186  18.241  1.00  0.00           H
ATOM     12  C4  PBA     1      17.861  17.673  19.650  1.00  0.00           C
ATOM     13  C5  PBA     1      19.149  17.929  20.106  1.00  0.00           C
ATOM     14  H5  PBA     1      19.480  17.471  20.845  1.00  0.00           H
ATOM     15  C6  PBA     1      19.942  18.869  19.459  1.00  0.00           C
ATOM     16  H6  PBA     1      20.804  19.040  19.764  1.00  0.00           H
ATOM     17  C1  PBA     1      19.447  19.553  18.355  1.00  0.00           C
TER
ENDMDL
```
Here is part of xml file
```xml
<ForceField>
<AtomTypes>
<Type name="opls_807" class="O807" element="O" mass="15.999"/>
<Type name="opls_808" class="O808" element="O" mass="15.999"/>
<Type name="opls_810" class="H810" element="H" mass="1.008"/>
<Type name="opls_801" class="C801" element="C" mass="12.011"/>
<Type name="opls_809" class="N809" element="N" mass="14.007"/>
<Type name="opls_811" class="H811" element="H" mass="1.008"/>
<Type name="opls_812" class="H812" element="H" mass="1.008"/>
<Type name="opls_802" class="C802" element="C" mass="12.011"/>
<Type name="opls_813" class="H813" element="H" mass="1.008"/>
<Type name="opls_803" class="C803" element="C" mass="12.011"/>
<Type name="opls_814" class="H814" element="H" mass="1.008"/>
<Type name="opls_804" class="C804" element="C" mass="12.011"/>
<Type name="opls_805" class="C805" element="C" mass="12.011"/>
<Type name="opls_815" class="H815" element="H" mass="1.008"/>
<Type name="opls_806" class="C806" element="C" mass="12.011"/>
<Type name="opls_816" class="H816" element="H" mass="1.008"/>
<Type name="opls_800" class="C800" element="C" mass="12.011"/>
</AtomTypes>
<Residues>
<Residue name="PBA">
<Atom name="O2" type="opls_807"/>
<Atom name="O1" type="opls_808"/>
<Atom name="H1" type="opls_810"/>
<Atom name="C7" type="opls_801"/>
<Atom name="N1" type="opls_809"/>
<Atom name="H1A" type="opls_811"/>
<Atom name="H1B" type="opls_812"/>
<Atom name="C2" type="opls_802"/>
<Atom name="H2" type="opls_813"/>
<Atom name="C3" type="opls_803"/>
<Atom name="H3" type="opls_814"/>
<Atom name="C4" type="opls_804"/>
<Atom name="C5" type="opls_805"/>
<Atom name="H5" type="opls_815"/>
<Atom name="C6" type="opls_806"/>
<Atom name="H6" type="opls_816"/>
<Atom name="C1" type="opls_800"/>
<Bond from="3" to="16"/>
<Bond from="7" to="16"/>
<Bond from="9" to="7"/>
<Bond from="11" to="9"/>
<Bond from="12" to="11"/>
<Bond from="14" to="16"/>
<Bond from="0" to="3"/>
<Bond from="1" to="3"/>
<Bond from="4" to="11"/>
<Bond from="2" to="1"/>
<Bond from="5" to="4"/>
<Bond from="6" to="4"/>
<Bond from="8" to="7"/>
<Bond from="10" to="9"/>
<Bond from="13" to="12"/>
<Bond from="15" to="14"/>
<Bond from="14" to="12"/>
</Residue>
```
Can you help to figure out the issue. Appreciate your help.

**Comment by peastman** [comment]
There's at least one clear problem: your PDB file doesn't have any CONECT records.  Without them, it doesn't know what atoms are bonded and can't match templates.  This is discussed in the FAQ entry linked in the error message.

**Comment by pradipchm** [comment]
Thanks. It helped. I need one more suggestion. I am trying to run organic crystal simulation. Unlike gromacs gro file where atom names for each residue has to be same with the top file, now for openmm run I observed that if the pdb file has same atom name it complains. Now I changed the atom names to have unique name, still it shows
`Traceback (most recent call last):
  File "/storage/nas_scr/shared/groups/valsson/Pradip_Runs/ROY/ROY_Polymorphs_New_Runs_480_CRcoupl-OPLS-AA/openmm_run/PABA_Runs/PABA_Crystal_OPLS_openmm/openmm_Energymin.py", line 9, in <module>
    system = forcefield.createSystem(pdb.topology, nonbondedMethod=PME,
  File "/home/ps0579/.conda/envs/md-python/lib/python3.10/site-packages/openmm/app/forcefield.py", line 1247, in createSystem
    templateForResidue = self._matchAllResiduesToTemplates(data, topology, residueTemplates, ignoreExternalBonds)
  File "/home/ps0579/.conda/envs/md-python/lib/python3.10/site-packages/openmm/app/forcefield.py", line 1462, in _matchAllResiduesToTemplates
    raise ValueError('No template found for residue %d (%s).  %s  For more information, see https://github.com/openmm/openmm/wiki/Frequently-Asked-Questions#template' % (res.index+1, res.name, _findMatchErrors(self, res)))
ValueError: No template found for residue 1 (UNK).  This might mean your input topology is missing some atoms or bonds, or possibly that you are using the wrong force field.  For more information, see https://github.com/openmm/openmm/wiki/Frequently-Asked-Questions#template`

Now I don't understand how will it match the atom name with the topology xml file.  Here is the pdb file of a test case with only two  units. 
```xml
HEADER    CSD ENTRY AMBNAC01
SCALE1      0.053905  0.000000  0.003354       0.000000
SCALE2      0.000000  0.259067  0.000000       0.000000
SCALE3      0.000000  0.000000  0.053746       0.000000
COMPND    PABA_N480_Initial.pdb
AUTHOR    GENERATED BY OPEN BABEL 3.1.1
CRYST1   18.551    3.860   18.642  90.00  93.56  90.00 P1          1
HETATM    1  O2  UNK     1      16.965   3.826  -0.335  1.00  0.00           O
HETATM    2  O1  UNK     1      17.952   2.862   1.403  1.00  0.00           O
HETATM    3  H1  UNK     1      18.657   3.339   0.986  1.00  0.00           H
HETATM    4  C7  UNK     1      16.875   3.211   0.733  1.00  0.00           C
HETATM    5  N1  UNK     1      11.938   1.900   3.100  1.00  0.00           N
HETATM    6  H1A UNK     1      11.155   1.992   2.586  1.00  0.00           H
HETATM    7  H1B UNK     1      11.902   1.243   3.703  1.00  0.00           H
HETATM    8  C2  UNK     1      15.552   2.153   2.556  1.00  0.00           C
HETATM    9  H2  UNK     1      16.396   1.969   3.033  1.00  0.00           H
HETATM   10  C3  UNK     1      14.349   1.830   3.137  1.00  0.00           C
HETATM   11  H3  UNK     1      14.311   1.289   4.038  1.00  0.00           H
HETATM   12  C4  UNK     1      13.147   2.170   2.499  1.00  0.00           C
HETATM   13  C5  UNK     1      13.201   2.803   1.256  1.00  0.00           C
HETATM   14  H5  UNK     1      12.378   2.941   0.819  1.00  0.00           H
HETATM   15  C6  UNK     1      14.401   3.127   0.692  1.00  0.00           C
HETATM   16  H6  UNK     1      14.408   3.609  -0.205  1.00  0.00           H
HETATM   17  C1  UNK     1      15.608   2.805   1.323  1.00  0.00           C
HETATM   18  O4  UNK     1      -0.872   1.839   7.660  1.00  0.00           O
HETATM   19  O3  UNK     1       0.847   1.026   8.816  1.00  0.00           O
HETATM   20  H7  UNK     1       0.334   1.502   9.545  1.00  0.00           H
HETATM   21  C14 UNK     1       0.235   1.263   7.699  1.00  0.00           C
HETATM   22  N2  UNK     1       2.961  -0.172   2.975  1.00  0.00           N
HETATM   23  H2A UNK     1       2.480  -0.066   2.177  1.00  0.00           H
HETATM   24  H2B UNK     1       3.508  -0.814   2.958  1.00  0.00           H
HETATM   25  C9  UNK     1       2.150   0.181   6.533  1.00  0.00           C
HETATM   26  H8  UNK     1       2.561  -0.023   7.442  1.00  0.00           H
HETATM   27  C10 UNK     1       2.819  -0.174   5.375  1.00  0.00           C
HETATM   28  H9  UNK     1       3.704  -0.660   5.470  1.00  0.00           H
HETATM   29  C11 UNK     1       2.263   0.136   4.125  1.00  0.00           C
HETATM   30  C12 UNK     1       1.029   0.785   4.062  1.00  0.00           C
HETATM   31  H10 UNK     1       0.601   0.965   3.163  1.00  0.00           H
HETATM   32  C13 UNK     1       0.373   1.130   5.221  1.00  0.00           C
HETATM   33  H11 UNK     1      -0.473   1.671   5.210  1.00  0.00           H
HETATM   34  C8  UNK     1       0.922   0.841   6.477  1.00  0.00           C
CONECT    1    4    4
CONECT    2    4    3
CONECT    3    2
CONECT    4    1    1   17    2
CONECT    5   12    6    7
CONECT    6    5
CONECT    7    5
CONECT    8   17   17    9   10
CONECT    9    8
CONECT   10   12   12    8   11
CONECT   11   10
CONECT   12   13    5   10   10
CONECT   13   15   15   14   12
CONECT   14   13
CONECT   15   16   13   13   17
CONECT   16   15
CONECT   17   15    4    8    8
CONECT   18   21   21
CONECT   19   21   20
CONECT   20   19
CONECT   21   34   18   18   19
CONECT   22   23   24   29
CONECT   23   22
CONECT   24   22
CONECT   25   27   27   34   26
CONECT   26   25
CONECT   27   29   28   25   25
CONECT   28   27
CONECT   29   22   30   30   27
```

**Comment by peastman** [comment]
Does your force field have a template for that molecule?  You quoted a template in your XML file earlier, but it was for a different molecule with a different number of atoms.

**Comment by pradipchm** [comment]
Yes, the same xml I copied here. It's a organic crystal so same molecule is repeating periodically. In gromacs run, your top file is for single molecule and at the end of top file you mention how many same molecule are there in crystal. But how that works for openmm pdb and xml file?

**Comment by peastman** [comment]
Your PDB file lists it as a single residue (every atom lists its residue ID as 1).  Therefore, OpenMM expects the entire thing to match a single template.  It looks like your file is intended to be two copies of the same molecule?  In that case, set the residue ID to 2 for the second one.  In that case it will match each one independently.  Atom names only need to be unique within each residue.  It's normal for every residue of the same type to use the same atom names.

**Comment by pradipchm** [comment]
Thanks. It worked. For gromacs run previously, when I converted pdb to gro, even with same residue seq number it ran without any issue. Now I changed the residue seq number and it worked.

**Comment by pradipchm** [comment]
One last thing, While printing the pdb file, the atoms name for the first three atom has changed, but the next run after Energy minimization, ran without any issue. I hope even the atom names has changed, shouldn't be a problem.

```xml
REMARK   1 CREATED WITH OPENMM 8.1.1, 2024-06-03
CRYST1   55.653   38.600   37.284  90.00  93.56  90.00 P 1           1
MODEL        1
HETATM    1  OXT UNK A   1      15.837   3.725  18.327  1.00  0.00           O
HETATM    2  O   UNK A   1      16.875   2.720  20.022  1.00  0.00           O
HETATM    3  H   UNK A   1      17.637   3.070  19.586  1.00  0.00           H
HETATM    4  C7  UNK A   1      15.741   3.067  19.362  1.00  0.00           C
HETATM    5  N1  UNK A   1      10.671   1.896  21.609  1.00  0.00           N
HETATM    6  H1A UNK A   1       9.857   2.042  21.030  1.00  0.00           H
HETATM    7  H1B UNK A   1      10.574   0.989  22.044  1.00  0.00           H
HETATM    8  C2  UNK A   1      14.302   2.049  21.171  1.00  0.00           C
HETATM    9  H2  UNK A   1      15.193   1.744  21.701  1.00  0.00           H
HETATM   10  C3  UNK A   1      13.042   1.763  21.730  1.00  0.00           C
HETATM   11  H3  UNK A   1      12.997   1.239  22.673  1.00  0.00           H
HETATM   12  C4  UNK A   1      11.867   2.158  21.066  1.00  0.00           C
HETATM   13  C5  UNK A   1      11.955   2.827  19.832  1.00  0.00           C
HETATM   14  H5  UNK A   1      11.063   3.141  19.312  1.00  0.00           H
HETATM   15  C6  UNK A   1      13.215   3.108  19.268  1.00  0.00           C
HETATM   16  H6  UNK A   1      13.270   3.643  18.331  1.00  0.00           H
HETATM   17  C1  UNK A   1      14.399   2.727  19.937  1.00  0.00           C
```

**Comment by peastman** [comment]
It's "fixing" your names for you.  UNK is the code for an unknown amino acid, and the atoms in an amino acid are supposed to have certain names.
