### ISSUE TITLE
Extremely high temperatures - NVT - LangevinMiddleIntegrator - Energy is NaN

### ISSUE THREAD

**Issue by NooraAz** [openmm/openmm#4575]
I'm running an NVT Equilibration _after a minimization step_. The step size is `0.5*femtoseconds` and every 10 steps the energy and temperature are printed out.  There are two issues: 

1. Temperature is unusually high
2. After 120*femtoseconds I get `Energy is NaN` error. 

Here is the output:
```
#"Step","Potential Energy (kJ/mole)","Temperature (K)"
10,2.3599107708835e+17,41710745999510.97
20,2.1229620100387622e+17,110595117992355.8
30,3.1981234119979955e+17,283352467604828.25
40,9.09124702952227e+17,457218656600404.5
50,1.9296812425512225e+18,471938922689695.0
60,2.786901100375048e+18,470683093282652.56
70,3.2775528428056084e+18,415020170590420.25
80,3.682141059896312e+18,398009239819635.44
90,4.4598138058823434e+18,433873075582187.7
100,5.964674315226972e+18,504943147345444.06
110,8.0728107456261e+18,638124855429887.1
Traceback (most recent call last):
  File "MD.py", line 52, in <module>
    simulation.step(2000)
  File "python3.9/site-packages/openmm/app/simulation.py", line 147, in step
    self._simulate(endStep=self.currentStep+steps)
  File "python3.9/site-packages/openmm/app/simulation.py", line 249, in _simulate
    self._generate_reports(unwrapped, False)
  File "python3.9/site-packages/openmm/app/simulation.py", line 269, in _generate_reports
    reporter.report(self, state)
  File "python3.9/site-packages/openmm/app/statedatareporter.py", line 206, in report
    self._checkForErrors(simulation, state)
  File "python3.9/site-packages/openmm/app/statedatareporter.py", line 365, in _checkForErrors
    raise ValueError('Energy is NaN.  For more information, see https://github.com/openmm/openmm/wiki/Frequently-Asked-Questions#nan')
ValueError: Energy is NaN.  For more information, see https://github.com/openmm/openmm/wiki/Frequently-Asked-Questions#nan
```

I have looked up [this guide in FAQ](https://github.com/openmm/openmm/wiki/Frequently-Asked-Questions#nan). When I look at forces in the `state` file, there are some large forces, for example, the third line here:
```
<Force x="-.3307507634162903" y="-8.56352424621582" z="2.2162818908691406"/>
<Force x="2.4157888889312744" y="-4.14804220199585" z="-4.637653350830078"/>
<Force x="66.98435974121094" y="146.25271606445312" z="60.41606140136719"/>
<Force x="-.61066073179245" y=".2916408181190491" z=".524437665939331"/>
<Force x="9.389219284057617" y="1.993322491645813" z="-15.967960357666016"/>
<Force x="-7.997025012969971" y="3.30397891998291" z="2.129593849182129"/>
```

however, I don't how I should approach resolving the issue. 

Here is the code and my input file:
```
from openmm.app import *
from openmm import *
from openmm.unit import *
from sys import stdout
import sys
name = sys.argv[1]

# load pdb structure and set force fields
pdb = PDBFile('solvated.pdb')
forcefield = ForceField('charmm36.xml', 'charmm36/water.xml')

# add solvent
modeller = Modeller(pdb.topology, pdb.positions)

# local energy minimization
system = forcefield.createSystem(modeller.topology)
integrator = VerletIntegrator(1*femtoseconds)
simulation = Simulation(modeller.topology, system, integrator)
simulation.context.setPositions(modeller.positions)
simulation.minimizeEnergy()

# save results
state = simulation.context.getState(getPositions=True, getVelocities=True, getForces=True, getEnergy=True, getParameters=True, enforcePeriodicBox=True)
with open('output'+name+'.pdb', 'w') as f:
    PDBFile.writeFile(simulation.topology, state.getPositions(), f)
with open('state_min'+name+'.xml', 'w') as f:
    f.write(XmlSerializer.serialize(state))
with open('system_min'+name+'.xml', 'w') as f:
    f.write(XmlSerializer.serialize(simulation.system))

########################## NVT Equilibration ######################################
with open('system_min'+name+'.xml', 'r') as f:
    system = XmlSerializer.deserialize(f.read())
with open('state_min'+name+'.xml', 'r') as f:
    state = XmlSerializer.deserialize(f.read())
pdb = PDBFile('output'+name+'.pdb')
integrator = LangevinMiddleIntegrator(300*kelvin, 1/picosecond, 0.5*femtoseconds)
simulation = Simulation(pdb.topology, system, integrator)
simulation.context.setState(state)
simulation.reporters.append(DCDReporter('NVT'+name+'.dcd', 1000))
simulation.reporters.append(StateDataReporter(stdout, 10, step=True, potentialEnergy=True, temperature=True))
simulation.step(2000)
state = simulation.context.getState(getPositions=True, getVelocities=True, getForces=True, getEnergy=True, getParameters=True, enforcePeriodicBox=True)
with open('NVT'+name+'.pdb', 'w') as f:
    PDBFile.writeFile(simulation.topology, state.getPositions(), f)
with open('state_NVT'+name+'.xml', 'w') as f:
    f.write(XmlSerializer.serialize(state))
with open('system_NVT'+name+'.xml', 'w') as f:
    f.write(XmlSerializer.serialize(simulation.system))
```
[solvated.txt](https://github.com/user-attachments/files/16021175/solvated.txt)

**Comment by NooraAz** [comment]
After increasing the friction coeff to `1/femtosecond` there is no longer NaN error. 
`integrator = LangevinMiddleIntegrator(300*kelvin, 1/femtosecond, 0.5*femtoseconds)`

But the Temperature is still high. Here are few last lines: 
```
1930,3.130331267021253e+16,6805796243066.241
1940,3.075527836645809e+16,7255270147597.422
1950,3.2681969791814028e+16,6741697839331.266
1960,3.1675124130267564e+16,6986372944749.835
1970,3.096060263348937e+16,7722287784573.218
1980,3.109871103143145e+16,7010960828748.209
1990,3.0095252253590324e+16,7178488169299.028
2000,3.061491507712962e+16,7626361970966.88
```

**Comment by peastman** [comment]
The problem is in how you handle periodic boundary conditions.  You create the system with

```python
system = forcefield.createSystem(modeller.topology)
```

Since you don't specify a nonbonded method, it defaults to `NoCutoff`.  That means you're simulating a nonperiodic system with no cutoff applied to nonbonded interactions.  Your molecules all happen to be packed into a cube, but as far as the simulation is concerned, it's an isolated cube floating in empty space.  When you call `minimizeEnergy()`, the minimizer is free to move molecules outside the cube.

Next you create a State with

```python
state = simulation.context.getState(getPositions=True, getVelocities=True, getForces=True, getEnergy=True, getParameters=True, enforcePeriodicBox=True)
```

You specify `enforcePeriodicBox=True`, so it takes that system that was minimized without periodic boundary conditions, and wraps all the molecules back into a periodic box.  In the process, lots of atoms end up right on top of each other.  This causes the simulation to blow up immediately.

The fix is very simple: when you call `createSystem()`, add the argument `nonbondedMethod=PME`.  That tells it to treat the system as periodic, and to use PME for calculating nonbonded interactions.

**Comment by NooraAz** [comment]
Thanks so much for your explanation! Yes, `nonbondedMethod=PME` solved the issue.
