### ISSUE TITLE
Particle coordinate is NaN. 

### ISSUE THREAD

**Issue by Toni0914** [openmm/openmm#4591]
I've been struggling to increase the total duration of my simulation run time. The largest simulation I've been able to run is 4 * 10⁻⁻⁷, 4 femtosecond time step size and 10 million total steps. I've tried adding a custom force but that hasn't changed the error. 
I've attached the the code and the full error. 

```python
from openmm.app import *
from openmm import *
from openmm.unit import *
from sys import stdout

#choose PDB file to use for simulation
pdb = PDBFile("2htfNew.pdb")

#force field used in simulation, has to be .xml file,
forcefield = ForceField("amber14-all.xml", "amber14/tip3pfb.xml")

#creates mathematical description of system that's going to be simulated using topology from PDB file and force field, nonbondedMethod=PME means use particle mesh Ewald for long range electrostatic interactions, nonbondedCutoff=1*nanometer means cutoff dirt pace interactions at 1 nanometer, constraints=HBonds means constrain the length of bonds involving hydrogen atoms
system = forcefield.createSystem(pdb.topology, nonbondedMethod=PME, nonbondedCutoff=1 * nanometer, constraints=HBonds)

#Langevin dynamics and 3 things it needs: simulation temp, friction coefficient, and step size
integrator = LangevinMiddleIntegrator(300 * kelvin, 1 / picosecond, 0.004 * picoseconds)

#Initialise the CustomExternalForce for positional restraints
restraint_force = CustomExternalForce("k * periodicdistance(x, y, z, x0, y0, z0)^2")
#Add global paramter for force constant
restraint_force.addGlobalParameter("k", 100.0 * kilojoules_per_mole / nanometer)
#Add per-particle parameters for reference positions
restraint_force.addPerParticleParameter("x0")
restraint_force.addPerParticleParameter("y0")
restraint_force.addPerParticleParameter("z0")
chains = list(pdb.topology.chains())
for atom in chains[0].atoms():
    if atom.element.symbol != "H" and atom.residue.name != "HOH":
        restraint_force.addParticle(atom.index, pdb.positions[atom.index])

system.addForce(restraint_force)

#begins new simulation with molecular topology, system, and integrator
simulation = Simulation(pdb.topology, system, integrator)

#specifies initial atom positions for simulation, from PDB file
simulation.context.setPositions(pdb.positions)

#local energy minimization, "coordinates in PDB file might produce very large forces"
simulation.minimizeEnergy()

#writes structure to a new PDB file, named output.pdb and should update every 1000 time steps
simulation.reporters.append(PDBReporter("2htf_outputDeltaBil.pdb", 1000000))

#status reports as simulation runs every 1000 time steps, current step index, potential energy of the system, and temp. stdout is the output file (write to console) can give a file name to save it too
simulation.reporters.append(
    StateDataReporter(
        "delta_outputBil.txt",
        1000000,
        step=True,
        potentialEnergy=True,
        kineticEnergy=True,
        totalSteps=10000000,
        remainingTime=True,
        temperature=True,
        separator="|",
    )
)

#run simulation
simulation.step(10000000)
``` 

`Traceback (most recent call last):
  File "/u/name/ondemand/data/sys/myjobs/projects/default/4/2htfSimulatePdb.py", line 52, in <module>
    simulation.step(10000000)
  File "/u/name/.conda/envs/openmm/lib/python3.12/site-packages/openmm/app/simulation.py", line 147, in step
    self._simulate(endStep=self.currentStep+steps)
  File "/u/name/.conda/envs/openmm/lib/python3.12/site-packages/openmm/app/simulation.py", line 212, in _simulate
    self.integrator.step(10) # Only take 10 steps at a time, to give Python more chances to respond to a control-c.
    ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/u/name/.conda/envs/openmm/lib/python3.12/site-packages/openmm/openmm.py", line 15287, in step
    return _openmm.LangevinMiddleIntegrator_step(self, steps)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
openmm.OpenMMException: Particle coordinate is NaN.  For more information, see https://github.com/openmm/openmm/wiki/Frequently-Asked-Questions#nan`

**Comment by peastman** [comment]
Try adding the argument `hydrogenMass=1.5*amu` to the call to `createSystem()`.  To make integration stable at a 4 fs time step, you sometimes need a little mass repartitioning in addition to the bond constraints.

**Comment by Toni0914** [comment]
That worked, thank you!
