### ISSUE TITLE
scipy 1.14 breaks loading of AMBER NetCDF restart files

### ISSUE THREAD

**Issue by timpalpant** [openmm/openmm#4601]
`NetCDFFile` is no longer exported in scipy 1.14 (as a result of https://github.com/scipy/scipy/pull/19904). This breaks the import [here](https://github.com/openmm/openmm/blob/master/wrappers/python/openmm/app/internal/amber_file_parser.py#L1443) when attempting to load an AMBER NetCDF restart file. It may need to be updated with an additional case such as:
```python
from scipy.io import netcdf_file as NetCDFFile
```

A simple repro is to run the benchmark script:
```bash
~/src/openmm/examples$ conda create -n openmm openmm scipy
~/src/openmm/examples$ conda activate openmm
~/src/openmm/examples$ python benchmark.py --platform=Reference --test amber20-dhfr

timestamp: 2024-07-25T13:54:25.497144
openmm_version: 8.1.2.dev-440a9c7
cpuinfo: AMD Ryzen Threadripper PRO 5975WX 32-Cores
cpuarch: x86_64
system: Linux
Traceback (most recent call last):
  File "/home/tim/conda/envs/openmm/lib/python3.12/site-packages/openmm/app/internal/amber_file_parser.py", line 1443, in __init__
    from scipy.io import NetCDFFile
ImportError: cannot import name 'NetCDFFile' from 'scipy.io' (/home/tim/conda/envs/openmm/lib/python3.12/site-packages/scipy/io/__init__.py). Did you mean: 'netcdf_file'?

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/tim/conda/envs/openmm/lib/python3.12/site-packages/openmm/app/internal/amber_file_parser.py", line 1447, in __init__
    from scipy.io.netcdf import NetCDFFile
ImportError: cannot import name 'NetCDFFile' from 'scipy.io.netcdf' (/home/tim/conda/envs/openmm/lib/python3.12/site-packages/scipy/io/netcdf.py). Did you mean: 'netcdf_file'?

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/tim/conda/envs/openmm/lib/python3.12/site-packages/openmm/app/internal/amber_file_parser.py", line 1537, in readAmberCoordinates
    crdfile = AmberNetcdfRestart(filename)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tim/conda/envs/openmm/lib/python3.12/site-packages/openmm/app/internal/amber_file_parser.py", line 1449, in __init__
    raise ImportError('scipy is necessary to parse NetCDF '
ImportError: scipy is necessary to parse NetCDF restarts

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/tim/conda/envs/openmm/lib/python3.12/site-packages/openmm/app/internal/amber_file_parser.py", line 1541, in readAmberCoordinates
    crdfile = AmberAsciiRestart(filename)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tim/conda/envs/openmm/lib/python3.12/site-packages/openmm/app/internal/amber_file_parser.py", line 1261, in __init__
    lines = f.readlines()
            ^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x84 in position 399: invalid start byte

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/tim/src/openmm/examples/benchmark.py", line 549, in <module>
    runOneTest(test, args)
  File "/home/tim/src/openmm/examples/benchmark.py", line 301, in runOneTest
    system, positions, test_parameters = retrieveTestSystem(testName, pme_cutoff=options.pme_cutoff, bond_constraints=options.bond_constraints, polarization=options.polarization, epsilon=options.epsilon)
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tim/src/openmm/examples/benchmark.py", line 191, in retrieveTestSystem
    inpcrd = app.AmberInpcrdFile(os.path.join(dirname, f'PME/Coordinates/{fileName}.inpcrd'))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tim/conda/envs/openmm/lib/python3.12/site-packages/openmm/app/amberinpcrdfile.py", line 81, in __init__
    results = amber_file_parser.readAmberCoordinates(file)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tim/conda/envs/openmm/lib/python3.12/site-packages/openmm/app/internal/amber_file_parser.py", line 1547, in readAmberCoordinates
    raise TypeError('Could not parse Amber ASCII restart file %s' %
TypeError: Could not parse Amber ASCII restart file Amber20_Benchmark_Suite/PME/Coordinates/JAC.inpcrd
```

**Comment by peastman** [comment]
Thanks!  If you want to fix it, a PR would be welcome.
