### ISSUE TITLE
Custom Force exclusion error when using CPU but not GPU

### ISSUE THREAD

**Issue by LeoFHall** [openmm/openmm#4655]
Hi !
I'm trying to run solvation energy calculations using a custom non-bonded force, and I get a very weird case where if I use a GPU with the following setup, it works fine:
```
GPUplatform = mm.Platform.getPlatformByName('CUDA')
GPUplatformProperties = {'Precision': 'single'}
[...]
simulation = app.Simulation(topology, system, integrator, GPUplatform, GPUplatformProperties)
```

However if I change the lines to run on a CPU platform:
```
[code]CPUplatform = mm.Platform.getPlatformByName('CPU')
[...]
simulation = app.Simulation(topology, system, integrator, CPUplatform)
```

I get the following error :
```
Building systems...
nonbonded force is : <openmm.openmm.NonbondedForce; proxy of <Swig Object of type 'OpenMM::NonbondedForce *' at 0x7f72e093dfb0> >
Traceback (most recent call last):
  File "/lustre07/scratch/hall2401/OPENMM/Solvation_Energy/./simulate_firstframe_with_many_methods.py", line 110, in <module>
    simulation = app.Simulation(topology, system, integrator, CPUplatform)#, GPUplatformProperties)
  File "/cvmfs/soft.computecanada.ca/easybuild/software/2020/avx2/MPI/gcc9/cuda11.4/openmpi4/openmm/8.0.0/lib/python3.10/site-packages/openmm/app/simulation.py", line 101, in __init__
    self.context = mm.Context(self.system, self.integrator, platform)
  File "/cvmfs/soft.computecanada.ca/easybuild/software/2020/avx2/MPI/gcc9/cuda11.4/openmpi4/openmm/8.0.0/lib/python3.10/site-packages/openmm/openmm.py", line 11512, in __init__
    _openmm.Context_swiginit(self, _openmm.new_Context(*args))
openmm.OpenMMException: All Forces must have identical exclusions
[/code]
```
I've done a few tests with commenting and modifying lines, and changing the platform is definitely what triggers the error to be thrown or not, wether this is what actually causes the error or if the error should be thrown and doesn't in GPU for some other reason, I don't know.

thanks for the help
Leo

Here is the full code for reference:
```
#always include at the top of simulation
import openmm.app as app
import openmm as mm
import openmm.unit as unit
import os
os.environ['JAX_ENABLE_X64'] = '1' #set JAX to 64bits by default
from time import perf_counter as pf
import MDAnalysis as mda
import numpy as np

testcode = 'firstframe-excludbond1-lambda100'
test=0
print('test ',test)
test+=1

start = pf()
LAMBDA = 100 #LAMBDA
TEMP = 298#TEMP
pdb = app.PDBFile('ZGY_1p5nmPadWaterCube.pdb')
forcefield = app.ForceField('./amber99sb-ZGY-hack.xml','/home/leo/.conda/envs/openmmEnv/lib/python3.10/site-packages/openmm/app/data/tip3p.xml')
#forcefield = app.ForceField('/home/hall2401/ForceFields/amber99sb-ZGY-hack.xml','/home/hall2401/ForceFields/tip3p.xml')

# System Configuration
nonbondedMethod = app.PME
nonbondedCutoff = 1.2*unit.nanometers
ewaldErrorTolerance = 0.0005
constraints = None
lambda_value = LAMBDA/100 #LAMBDA will be given as a percentage for purpose of filenames

# Integration Options
dt = 0.0005*unit.picoseconds # 0.5 femtoseconds
temperature = TEMP*unit.kelvin 
friction = 1.0/unit.picosecond
pressure = 1.0*unit.atmospheres
barostatInterval = 25

# Simulation Options
steps = 200000#00 #0.1ns with the 0.5fs timestep
equilibrationSteps = 10000#00 #0.05ns equilibration
CPUplatform = mm.Platform.getPlatformByName('CPU')
GPUplatform = mm.Platform.getPlatformByName('CUDA')
GPUplatformProperties = {'Precision': 'single'}
pdbReporter = app.PDBReporter('trajectory-solvation_water_TEMP_LAMBDA_RUN-{}.pdb'.format(testcode), 1000)
dataReporter = app.StateDataReporter('trajectory-solvation_water_TEMP_LAMBDA_RUN-{}.csv'.format(testcode), 500, totalSteps=steps,
    step=True, speed=True, progress=True, potentialEnergy=True, temperature=True, separator=',')
#checkpointReporter = app.CheckpointReporter('checkpoint-solvation_water_TEMP_LAMBDA_RUN.chk', 10000)

# Create the system
print('Building system...')
topology = pdb.topology
positions = pdb.positions
system = forcefield.createSystem(topology=topology, nonbondedMethod=nonbondedMethod, nonbondedCutoff=nonbondedCutoff,
    constraints=constraints, ewaldErrorTolerance=ewaldErrorTolerance)

#Get residue of interest
target_residue_index = 0  # Index of the target glycine residue
target_atoms = [atom.index for atom in pdb.topology.atoms() if atom.residue.index == target_residue_index]
solvent_atoms = [atom.index for atom in pdb.topology.atoms() if atom.residue.index != target_residue_index]


integrator = mm.LangevinMiddleIntegrator(temperature, friction, dt)

# Get the NonbondedForce object
#we get the first element of a list that presumably contains just one element as there should be only one nonbonded force object
nonbonded_force = [force for force in system.getForces() if isinstance(force, mm.NonbondedForce)][0] 
print('nonbonded force is :',nonbonded_force)
    
# Lambda parametre already defined
#dielectric constant is not considered as we're doing an explicit solvent simulation
# Create a CustomNonbondedForce that scales both Lennard-Jones and Coulombic interactions
custom_force = mm.CustomNonbondedForce(
    'lambda*(4*epsilon*((sigma/r)^12 - (sigma/r)^6) + 138.935456*charge1*charge2*(1/r)); '
    'sigma=0.5*(sigma1+sigma2); epsilon=sqrt(epsilon1*epsilon2)')
#138.9... is the value of the Coulomb constant in Openmm in kJ/nm
custom_force.addGlobalParameter('lambda', lambda_value)
#charge, sigma and epsilon are named parametres whose value will be input for each relevant particle
custom_force.addPerParticleParameter('charge')
custom_force.addPerParticleParameter('sigma')
custom_force.addPerParticleParameter('epsilon')
#give it the same parametres as other nonbonded forces
custom_force.setCutoffDistance(nonbondedCutoff)
custom_force.setNonbondedMethod(mm.CustomNonbondedForce.CutoffPeriodic)


# Add particles to the custom force using parameters from the existing force field
#the whole system must be included in the custom force because the residue can interact with the whole system
for i in range(system.getNumParticles()):
    charge, sigma, epsilon = nonbonded_force.getParticleParameters(i)
    custom_force.addParticle([charge, sigma, epsilon]) #when called for the i'th time, sets the parametres for the i'th particle
    
    # Enable lambda scaling for interactions involving the target glycine residue
    if i in target_atoms:
        #setParticleParametre means interactions will be calculated for this particle - already is
        #custom_force.setParticleParameters(i, [charge, sigma, epsilon])
        nonbonded_force.setParticleParameters(i, 0, 0, 0) #remove target atoms from the nonbonded force. This is definitely necessary
    
custom_force.addInteractionGroup(target_atoms,solvent_atoms)
# Add exclusions to avoid double-counting interactions that are already included in bonded interactions
#the residue presumably only interacts with itself through bonded interactions
# Extract bonds from the topology and convert to the required format
bonds = [(bond[0].index, bond[1].index) for bond in pdb.topology.bonds()]
#print(bonds)

# Add exclusions for 1-2 interactions (atoms directly bonded to each other - this is what the second argument is for)
custom_force.createExclusionsFromBonds(bonds, 1)

# Add the custom force to the system
system.addForce(custom_force)
simulation = app.Simulation(topology, system, integrator, GPUplatform, GPUplatformProperties)
simulation.context.setPositions(positions)

print("performing energy minimisation...")
simulation.minimizeEnergy()
simulation.context.setVelocitiesToTemperature(temperature)

print("equilibrating system...")
#simulation.reporters.append(dataReporter)
simulation.step(equilibrationSteps)


# Simulate
print('Simulating...')
simulation.reporters.append(pdbReporter)
simulation.reporters.append(dataReporter) #already added during equilibration
#simulation.reporters.append(checkpointReporter)
simulation.currentStep = 0
simulation.step(steps)

end = pf()
print('runtime (mn) = ',(end-start)/60)
```

**Comment by peastman** [comment]
Can you post the input files?  I'd like to try to reproduce it.

**Comment by LeoFHall** [comment]
Yes of course !
I had to change the extentions to .txt to get github to accept them.
The changes in the amberff99sb ZGY hack file are  in lines 6848 to 6868, it's a zwitterionic residue created from elements of GLY, CGLY and NGLY.

[amber99sb-ZGY-hack.xml.txt](https://github.com/user-attachments/files/16968313/amber99sb-ZGY-hack.xml.txt)
[tip3p.xml.txt](https://github.com/user-attachments/files/16968315/tip3p.xml.txt)
[ZGY_1p5nmPadWaterCube.pdb.txt](https://github.com/user-attachments/files/16968317/ZGY_1p5nmPadWaterCube.pdb.txt)

**Comment by peastman** [comment]
The problem is here:

```python
# Add exclusions for 1-2 interactions (atoms directly bonded to each other - this is what the second argument is for)
custom_force.createExclusionsFromBonds(bonds, 1)
```

The NonbondedForce has exceptions for all 1-2, 1-3, and 1-4 interactions.  The CustomNonbondedForce only has exclusions for 1-2 interactions.  Since a single neighbor list is shared by both classes, they have to exclude an identical set of interactions.

So why does it happen for CPU but not CUDA?  Because interaction groups are implemented differently in the two platforms.  When using an interaction group on CUDA, CustomNonbondedForce doesn't use the main neighbor list.  Instead it builds its own data structure to optimize the calculation in a different way.  That's why it doesn't care what interactions are excluded in the main neighbor list.

**Comment by LeoFHall** [comment]
oh ok, thanks !
So if I understand correctly, if I want to properly emulate the nonbonded force with customforce I want to replace this line with 
`createExclusionBonds(bonds,3)`
to get all the bonded interactions ?

**Comment by LeoFHall** [comment]
Ah, no it very much isn't, that might explain why I have weird results.

Basically I want my custom nonbonded force to replace the regular one but use the same parametres, and only compute interactions between Gly and the surrounding water. The idea is to then scale that with the lambda factor to then get a solvation energy in an alchemical pathway.

so in the default nonbonded force Gly parametres are set to 0, because I thought all the 1-2, 1-3 and 1-4 parametres were taken care of by bondedforce.

Maybe I could create a new custom force to have :
1) all the solvent molecules interacting with each other through the regular nonbonded force
2) Gly and the solvent interacting through the scalable force
3) Gly internal energies, I don't know how

**Comment by peastman** [comment]
The NonbondedForce is still computing the 1-4 interactions, because you don't call `setExceptionParameters()` on it to change them.  It sounds like that's what you want?  The thing you're missing is internal interactions in the solute that are further apart than 1-4.  Since it's a tiny solute, you could maybe use a CustomBondForce and enumerate them explicitly?  For a larger solute, another CustomNonbondedForce with an interaction group would make more sense.

**Comment by LeoFHall** [comment]
Don't I want the bonded force to compute the 1-4 interactions ?

Also looking into this issue https://github.com/openmm/openmm/issues/3281
I realised an issue I have was I was mixing PME on the nonbonded force and cutoffPeriodic on the custom force that supposed to replace it, so that probably didn't make sense...

**Comment by peastman** [comment]
> Don't I want the bonded force to compute the 1-4 interactions ?

That's up to you.  Just make sure they get computed exactly once, wherever you decide to compute them.

**Comment by LeoFHall** [comment]
But doesn't bonded force calculate them by default ?
so if I'm only modifying the nonbonded force, they'd still be calculated by bonded, right ?

**Comment by peastman** [comment]
The 1-4 Coulomb and Lennard-Jones interactions are normally calculated by the NonbondedForce.  If you choose, you can create a CustomBondForce to calculate them instead.

**Comment by LeoFHall** [comment]
ok, thanks a lot for the help, I think things work now !
