### ISSUE TITLE
Extremely slow XTC.writeModel() in 8.2beta

### ISSUE THREAD

**Issue by egallicc** [openmm/openmm#4676]
This is part of testing the 8.2 beta release (issue #4659).

I am observing extremely slow write speeds of the XTC writeModel() function in 8.2beta compared to 8.1.1.

An example that illustrates the issue is compiled [here](https://www.dropbox.com/scl/fo/73y2wbcasol931x4890ri/AFX__Y1PVmL3g91VjYT2Jc8?rlkey=lic7h1ruzdmg7zyucjgto1d3t&st=5rv84bk6&dl=0)

With 8.1.1:
```
(atm8.1.1)> python md-xtc.py 
Using platform CUDA
Potential energy = -541935.8524251664 kJ/mol
MD ...
#"Step","Potential Energy (kJ/mole)","Total Energy (kJ/mole)","Temperature (K)","Box Volume (nm^3)","Speed (ns/day)"
451000,-542276.9163599703,-431230.21494620765,300.54340328899514,431.1123095312918,0
452000,-542836.3727213228,-431225.86640610814,302.06931843745167,431.1123095312918,84.3
453000,-542704.0485093542,-431242.1684374083,301.6670675249856,431.1123095312918,86.7
454000,-541873.647889405,-431233.87175044976,299.44207650109496,431.1123095312918,87.5
455000,-542837.9412805415,-431232.0324806739,302.05687544822734,431.1123095312918,86.7
456000,-541998.2077876558,-431230.13177531597,299.78931491608273,431.1123095312918,87
457000,-542289.7645247355,-431230.94624976494,300.5761970834819,431.1123095312918,86.8
458000,-541791.4160681418,-431243.7170121907,299.1928736023263,431.1123095312918,87.1
459000,-542814.6998758563,-431228.2301779565,302.00426430545673,431.1123095312918,87.3
460000,-542605.6939347913,-431220.9801732194,301.4582200288977,431.1123095312918,86.7
MD time: 10.708085536956787 sec
```

With 8.2beta:
```
(atm8.2.0beta)> python md-xtc.py 
Using platform CUDA
Potential energy = -541935.8566118958 kJ/mol
MD ...
#"Step","Potential Energy (kJ/mole)","Total Energy (kJ/mole)","Temperature (K)","Box Volume (nm^3)","Speed (ns/day)"
451000,-542575.906920725,-431227.04191206815,301.36119682994104,431.1123095312918,0
452000,-542428.3709853915,-431238.98538851563,300.92957225612696,431.1123095312918,0.562
453000,-543253.1009165146,-431235.2847197481,303.17168614794065,431.1123095312918,0.577
454000,-542342.0927142426,-431234.7901364764,300.70741788682676,431.1123095312918,0.581
455000,-542729.147528532,-431237.01319669466,301.7489494549842,431.1123095312918,0.588
^[[C456000,-542217.9556918191,-431240.4297743102,300.35618260793353,431.1123095312918,0.595
457000,-543483.3904177193,-431243.2867134906,303.7732982908567,431.1123095312918,0.597
458000,-543247.1650566608,-431237.9111496712,303.1485126571772,431.1123095312918,0.598
459000,-542144.3434865503,-431239.37394209736,300.1598117206318,431.1123095312918,0.602
460000,-542731.5632719728,-431240.0183581215,301.74735421905893,431.1123095312918,0.604
MD time: 1428.6539731025696  sec
```
which is more than 100 times slower than with 8.1.1.

**Comment by egallicc** [comment]
The problem is specific to the XTC `writeModel()` functionality. The speed of the `XTCReporter` is similar in the two versions.

**Comment by egallicc** [comment]
Stopping the 8.2beta run prematurely shows that it is likely stuck in a `np.abs()` check:

```
^CTraceback (most recent call last):
  File "/nfs/egallicchio/Dropbox/misc/XTC-write-model-issue/md-xtc.py", line 68, in <module>
    xtc.writeModel(positions, periodicBoxVectors=boxsize)
  File "/nfs/egallicchio-d/miniforge3/envs/atm8.2.0beta/lib/python3.12/site-packages/openmm/app/xtcfile.py", line 102, in writeModel
    if (np.abs(positions * 1000) > (2 ** 31 - 1)).any():
        ^^^^^^^^^^^^^^^^^^^^^^^^
KeyboardInterrupt
```

Maybe a numpy issue?

8.2beta conda environment:
```
numpy                     1.26.4          py312heda63a1_0    conda-forge
```

8.1.1 conda environment:
```
numpy                     1.26.3          py312heda63a1_0    conda-forge
```

**Comment by peastman** [comment]
XTCReporter just calls `writeModel()`:

https://github.com/openmm/openmm/blob/f48eb17ba3a537e93beb1a60bb3e8c7b4099d3dc/wrappers/python/openmm/app/xtcreporter.py#L75-L77

If it's fast in that case but slow when you call it directly, that suggests there must be a difference in how you're calling it.  What do you pass for `positions`?

**Comment by egallicc** [comment]
Okay, thank you, this explains it. I was doing:
```
    positions = simulation.context.getState(getPositions=True).getPositions()
    xtc.writeModel(positions, periodicBoxVectors=boxsize)
```

With
```
    positions = simulation.context.getState(getPositions=True).getPositions(asNumpy=True)
    xtc.writeModel(positions, periodicBoxVectors=boxsize)
```
it is indeed much faster.

**Comment by peastman** [comment]
But it still shouldn't be any slower than the old version.  Let me investigate and see if I can improve it.

**Comment by egallicc** [comment]
Given the vast difference in performance, would it make sense to issue a warning in this case? Alternatively, internally convert `positions` to numpy if it is not already a numpy array?

**Comment by egallicc** [comment]
> But it still shouldn't be any slower than the old version. Let me investigate and see if I can improve it.

To confirm, 8.2beta is not visibly slower than 8.1.1 when passing a numpy version of `positions`.

**Comment by peastman** [comment]
> Alternatively, internally convert positions to numpy if it is not already a numpy array?

That's what I was thinking.

**Comment by peastman** [comment]
Adding the line

```python
positions = np.asarray(positions)
```

fixes it.  I'll create a PR as soon as we get CI working again.

**Comment by peastman** [comment]
The fix is in #4679, if you want to test it.

**Comment by egallicc** [comment]
Confirmed. It corrects the problem. Thanks!

**Comment by peastman** [comment]
Thanks!
