### ISSUE TITLE
Building for Intel GPU MAX 1550 with failiing OpenCL tests

### ISSUE THREAD

**Issue by nec4** [openmm/openmm#4689]
Hello all,

Thanks for the great tools. I have used OpenMM briefly in the past but wanted to install it for use now on some Intel GPU Max 1550s (The "Ponte Vecchio" GPU line from Intel) on Rocky8.9 using OpenCL. However, I am seeing several tests fail.

My build environment:

```
$ cat /etc/os-release
NAME="Rocky Linux"
VERSION="8.9 (Green Obsidian)"
ID="rocky"
ID_LIKE="rhel centos fedora"
VERSION_ID="8.9"
PLATFORM_ID="platform:el8"
PRETTY_NAME="Rocky Linux 8.9 (Green Obsidian)"
ANSI_COLOR="0;32"
LOGO="fedora-logo-icon"
CPE_NAME="cpe:/o:rocky:rocky:8:GA"
HOME_URL="https://rockylinux.org/"
BUG_REPORT_URL="https://bugs.rockylinux.org/"
SUPPORT_END="2029-05-31"
ROCKY_SUPPORT_PRODUCT="Rocky-Linux-8"
ROCKY_SUPPORT_PRODUCT_VERSION="8.9"
REDHAT_SUPPORT_PRODUCT="Rocky Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="8.9"

$ gcc --version
gcc (GCC) 13.2.0
Copyright (C) 2023 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

Using the OpenCL library from Intel OneAPI 2024.2.0 and Python 3.12.6. I have elected to use gcc/g++ because my initial experience with the new intel compilers (icx and icpx) was generally much worse (many more failing tests and segfaults etc). My build process is the following:

```
$ cmake .. -DCMAKE_INSTALL_PREFIX=/scratch/usr/bzfbnick/pvc_openmm/openmm-8.1.2/install-dir -DPYTHON_EXECUTABLE=$(which python) -DOPENCL_INCLUDE_DIR=/sw/compiler/intel/oneapi/2024.2/include/sycl -DOPENCL_LIBRARY=/sw/compiler/intel/oneapi/2024.2/lib/libOpenCL.so -DCMAKE_C_COMPILER=gcc -DCMAKE_CXX_COMPILER=g++ &> configure.log
$ make -j 32 &> make.log
$ make test &> test.log
$ ctest --rerun-failed --output-on-failure &> failed_tests.log
$ make install &> install.log
$ make PythonInstall -j 32 &> install_python.log
```

Please see the attached log files for the verbose output. Several tests seem to fail with varying degrees of severity:
```
The following tests FAILED:
         69 - TestOpenCLCustomAngleForceMixed (SEGFAULT)
         70 - TestOpenCLCustomAngleForceDouble (SEGFAULT)
         78 - TestOpenCLCustomCVForceMixed (SEGFAULT)
         79 - TestOpenCLCustomCVForceDouble (SEGFAULT)
         92 - TestOpenCLCustomHbondForceSingle (Timeout)
         93 - TestOpenCLCustomHbondForceMixed (Timeout)
         94 - TestOpenCLCustomHbondForceDouble (Timeout)
         96 - TestOpenCLCustomIntegratorMixed (SEGFAULT)
         97 - TestOpenCLCustomIntegratorDouble (Failed)
        110 - TestOpenCLDispersionPMESingle (Failed)
        111 - TestOpenCLDispersionPMEMixed (Failed)
        113 - TestOpenCLEwaldSingle (Failed)
        114 - TestOpenCLEwaldMixed (Failed)
        152 - TestOpenCLNonbondedForceSingle (Failed)
        153 - TestOpenCLNonbondedForceMixed (Failed)
        215 - TestOpenCLAmoebaGeneralizedKirkwoodForceSingle (Failed)
        216 - TestOpenCLAmoebaGeneralizedKirkwoodForceMixed (Failed)
        218 - TestOpenCLAmoebaMultipoleForceMixed (Failed)
        223 - TestOpenCLHippoNonbondedForceSingle (Failed)
        224 - TestOpenCLHippoNonbondedForceMixed (Failed)
        238 - TestOpenCLDrudeLangevinIntegratorSingle (Failed)
        239 - TestOpenCLDrudeLangevinIntegratorMixed (Failed)
```

For the non-segfault tests output, see the attached log, `failed_tests.log`. Additionally, all `OpenCLCustomHBondForce` tests timeout:
```
        Start  92: TestOpenCLCustomHbondForceSingle
 92/290 Test  #92: TestOpenCLCustomHbondForceSingle .................***Timeout 1500.12 sec
        Start  93: TestOpenCLCustomHbondForceMixed
 93/290 Test  #93: TestOpenCLCustomHbondForceMixed ..................***Timeout 1500.12 sec
        Start  94: TestOpenCLCustomHbondForceDouble
 94/290 Test  #94: TestOpenCLCustomHbondForceDouble .................***Timeout 1500.12 sec
```

Executing the Python runtime tests also reveals a large difference for the OpenCL platform:
```
$ python -m openmm.testInstallation -v

OpenMM Version: 8.1.2
Git Revision: Unknown

There are 3 Platforms available:

1 Reference - Successfully computed forces
2 CPU - Successfully computed forces
3 OpenCL - Successfully computed forces

Median difference in forces between platforms:

Reference vs. CPU: 6.29606e-06
Reference vs. OpenCL: 0.0575972  *** LARGE DIFFERENCE **
CPU vs. OpenCL: 0.0576003  *** LARGE DIFFERENCE **
Problem with OpenMM installation encountered. OpenMM will not work correctly until the problem has been fixed.


Error message: Large differences observed. See messages above.
```

Is there any idea why these tests are failing or what could be going wrong? Let me know if can run more tests or provide more information. Thanks.

[test.log](https://github.com/user-attachments/files/17340947/test.log)
[make.log](https://github.com/user-attachments/files/17340948/make.log)
[install_python.log](https://github.com/user-attachments/files/17340949/install_python.log)
[install.log](https://github.com/user-attachments/files/17340950/install.log)
[failed_tests.log](https://github.com/user-attachments/files/17340951/failed_tests.log)
[configure.log](https://github.com/user-attachments/files/17340952/configure.log)

**Comment by bdenhollander** [comment]
Do you have the output from `clinfo`? Since OpenCL can also run on a CPU, do you see GPU activity? Running `examples/benchmark.py` will run longer and could make it easier to observe than the short tests.

**Comment by nec4** [comment]
Attached is the ouput.
[clinfo_dump.txt](https://github.com/user-attachments/files/17342784/clinfo_dump.txt)

Seems that it can detect the GPUs:

```
  Platform Name                                   Intel(R) OpenCL Graphics
Number of devices                                 8
  Device Name                                     Intel(R) Data Center GPU Max 1550
  Device Vendor                                   Intel(R) Corporation
  Device Vendor ID                                0x8086
  Device Version                                  OpenCL 3.0 NEO
  Device UUID                                     8680d50b-2f00-0000-3a00-000000000001
  Driver UUID                                     32332e33-352e-3237-3139-312e34320000
  Valid Device LUID                               No
  Device LUID                                     a0c0-f1affc7f0000
  Device Node Mask                                0
  Device Numeric Version                          0xc00000 (3.0.0)
  Driver Version                                  23.35.27191.42
  Device OpenCL C Version                         OpenCL C 1.2
...
  ```

**Comment by nec4** [comment]
Regarding the benchmark:

```
python benchmark.py --platform OpenCL
/scratch/usr/bzfbnick/pvc_openmm/gcc/openmm-8.1.2/examples/benchmark.py:496: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  system_info['timestamp'] = datetime.utcnow().isoformat()
/bin/sh: nvidia-smi: command not found
hostname: bgi1002
timestamp: 2024-10-11T12:50:39.870086
openmm_version: 8.1.2.dev-Unknown
cpuinfo: Intel(R) Xeon(R) Platinum 8480L
cpuarch: x86_64
system: Linux
test: gbsa
constraints: HBonds
hydrogen_mass: 1.5
cutoff: 2.0
ensemble: NVT
precision: single
timestep_in_fs: 4.0
platform: OpenCL
platform_properties: {'DeviceIndex': '0', 'DeviceName': 'Intel(R) Data Center GPU Max 1550', 'OpenCLPlatformIndex': '1', 'OpenCLPlatformName': 'Intel(R) OpenCL Graphics', 'Precision': 'single', 'UseCpuPme': 'false', 'DisablePmeStream': 'false'}
steps: 193163
elapsed_time: 59.768962
ns_per_day: 1116.9197283365902

test: rf
constraints: HBonds
hydrogen_mass: 1.5
cutoff: 1.0
ensemble: NVT
precision: single
timestep_in_fs: 4.0
platform: OpenCL
platform_properties: {'DeviceIndex': '0', 'DeviceName': 'Intel(R) Data Center GPU Max 1550', 'OpenCLPlatformIndex': '1', 'OpenCLPlatformName': 'Intel(R) OpenCL Graphics', 'Precision': 'single', 'UseCpuPme': 'false', 'DisablePmeStream': 'false'}
steps: 87437
elapsed_time: 59.727207
ns_per_day: 505.93738963886244

test: pme
constraints: HBonds
hydrogen_mass: 1.5
cutoff: 0.9
ensemble: NVT
precision: single
timestep_in_fs: 4.0
platform: OpenCL
platform_properties: {'DeviceIndex': '0', 'DeviceName': 'Intel(R) Data Center GPU Max 1550', 'OpenCLPlatformIndex': '1', 'OpenCLPlatformName': 'Intel(R) OpenCL Graphics', 'Precision': 'single', 'UseCpuPme': 'false', 'DisablePmeStream': 'false'}
steps: 61423
elapsed_time: 60.235857
ns_per_day: 352.4111693139851

test: apoa1rf
constraints: HBonds
hydrogen_mass: 1.5
cutoff: 1.0
ensemble: NVT
precision: single
timestep_in_fs: 4.0
platform: OpenCL
platform_properties: {'DeviceIndex': '0', 'DeviceName': 'Intel(R) Data Center GPU Max 1550', 'OpenCLPlatformIndex': '1', 'OpenCLPlatformName': 'Intel(R) OpenCL Graphics', 'Precision': 'single', 'UseCpuPme': 'false', 'DisablePmeStream': 'false'}
steps: 46834
elapsed_time: 64.118081
ns_per_day: 252.43784822568222

test: apoa1pme
constraints: HBonds
hydrogen_mass: 1.5
cutoff: 0.9
ensemble: NVT
precision: single
timestep_in_fs: 4.0
platform: OpenCL
platform_properties: {'DeviceIndex': '0', 'DeviceName': 'Intel(R) Data Center GPU Max 1550', 'OpenCLPlatformIndex': '1', 'OpenCLPlatformName': 'Intel(R) OpenCL Graphics', 'Precision': 'single', 'UseCpuPme': 'false', 'DisablePmeStream': 'false'}
steps: 31674
elapsed_time: 60.843433
ns_per_day: 179.91316170473155

test: apoa1ljpme
constraints: HBonds
hydrogen_mass: 1.5
cutoff: 0.9
ensemble: NVT
precision: single
timestep_in_fs: 4.0
platform: OpenCL
platform_properties: {'DeviceIndex': '0', 'DeviceName': 'Intel(R) Data Center GPU Max 1550', 'OpenCLPlatformIndex': '1', 'OpenCLPlatformName': 'Intel(R) OpenCL Graphics', 'Precision': 'single', 'UseCpuPme': 'false', 'DisablePmeStream': 'false'}
steps: 26340
elapsed_time: 59.942213
ns_per_day: 151.86466338838704

test: amoebagk
epsilon: 1e-05
constraints: None
hydrogen_mass: 1
ensemble: NVT
precision: single
timestep_in_fs: 2.0
platform: OpenCL
platform_properties: {'DeviceIndex': '0', 'DeviceName': 'Intel(R) Data Center GPU Max 1550', 'OpenCLPlatformIndex': '1', 'OpenCLPlatformName': 'Intel(R) OpenCL Graphics', 'Precision': 'single', 'UseCpuPme': 'false', 'DisablePmeStream': 'false'}
steps: 2610
elapsed_time: 56.657559
ns_per_day: 7.960244104409791

test: amoebapme
epsilon: 1e-05
constraints: None
hydrogen_mass: 1
ensemble: NVT
precision: single
timestep_in_fs: 2.0
platform: OpenCL
platform_properties: {'DeviceIndex': '0', 'DeviceName': 'Intel(R) Data Center GPU Max 1550', 'OpenCLPlatformIndex': '1', 'OpenCLPlatformName': 'Intel(R) OpenCL Graphics', 'Precision': 'single', 'UseCpuPme': 'false', 'DisablePmeStream': 'false'}
steps: 3362
elapsed_time: 58.611309
ns_per_day: 9.911971083942175

Downloading https://ambermd.org/Amber20_Benchmark_Suite.tar.gz
Traceback (most recent call last):
  File "/home/bzfbnick/mambaforge/lib/python3.12/urllib/request.py", line 1344, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/home/bzfbnick/mambaforge/lib/python3.12/http/client.py", line 1336, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/home/bzfbnick/mambaforge/lib/python3.12/http/client.py", line 1382, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/home/bzfbnick/mambaforge/lib/python3.12/http/client.py", line 1331, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/home/bzfbnick/mambaforge/lib/python3.12/http/client.py", line 1091, in _send_output
    self.send(msg)
  File "/home/bzfbnick/mambaforge/lib/python3.12/http/client.py", line 1035, in send
    self.connect()
  File "/home/bzfbnick/mambaforge/lib/python3.12/http/client.py", line 1470, in connect
    super().connect()
  File "/home/bzfbnick/mambaforge/lib/python3.12/http/client.py", line 1001, in connect
    self.sock = self._create_connection(
                ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bzfbnick/mambaforge/lib/python3.12/socket.py", line 865, in create_connection
    raise exceptions[0]
  File "/home/bzfbnick/mambaforge/lib/python3.12/socket.py", line 850, in create_connection
    sock.connect(sa)
OSError: [Errno 101] Network is unreachable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/scratch/usr/bzfbnick/pvc_openmm/gcc/openmm-8.1.2/examples/benchmark.py", line 549, in <module>
    runOneTest(test, args)
  File "/scratch/usr/bzfbnick/pvc_openmm/gcc/openmm-8.1.2/examples/benchmark.py", line 301, in runOneTest
    system, positions, test_parameters = retrieveTestSystem(testName, pme_cutoff=options.pme_cutoff, bond_constraints=options.bond_constraints, polarization=options.polarization, epsilon=options.epsilon)
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/scratch/usr/bzfbnick/pvc_openmm/gcc/openmm-8.1.2/examples/benchmark.py", line 187, in retrieveTestSystem
    dirname = downloadAmberSuite()
              ^^^^^^^^^^^^^^^^^^^^
  File "/scratch/usr/bzfbnick/pvc_openmm/gcc/openmm-8.1.2/examples/benchmark.py", line 117, in downloadAmberSuite
    filename, headers = urllib.request.urlretrieve(url, filename='Amber20_Benchmark_Suite.tar.gz')
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bzfbnick/mambaforge/lib/python3.12/urllib/request.py", line 240, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
                            ^^^^^^^^^^^^^^^^^^
  File "/home/bzfbnick/mambaforge/lib/python3.12/urllib/request.py", line 215, in urlopen
    return opener.open(url, data, timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bzfbnick/mambaforge/lib/python3.12/urllib/request.py", line 515, in open
    response = self._open(req, data)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/bzfbnick/mambaforge/lib/python3.12/urllib/request.py", line 532, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bzfbnick/mambaforge/lib/python3.12/urllib/request.py", line 492, in _call_chain
    result = func(*args)
             ^^^^^^^^^^^
  File "/home/bzfbnick/mambaforge/lib/python3.12/urllib/request.py", line 1392, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bzfbnick/mambaforge/lib/python3.12/urllib/request.py", line 1347, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno 101] Network is unreachable>
```

Seems that it also sees the GPU, but some tests are not able to run (currently the GPUs are on compute nodes without internet connection)

**Comment by peastman** [comment]
I don't know of anyone who has tested on that GPU before.  I'm afraid you're living on the edge!  Clearly some things don't work correctly on it.  Figuring out what and how to fix them could take a lot of work.  If you're up for doing it, that would be great!

The first thing I'd suggest is looking at #4366.  I was trying to get OpenMM working on Intel's OpenCL for CPUs, and I had to make some code changes.  They may be unrelated, since that was for a very different device.  But it's possible some of the changes also apply to you.  I'd particularly look at the change in OpenCLFFT3D.cpp, since if they're using the same approximation on your GPU that could explain some of the failures.

Looking over the failures they fall into a few categories.

- All of the segfaults are in mixed or double precision mode.  That suggests it's something related to the use of double precision math.  No obvious explanations for that come to mind.  Try running those tests in gcc, then when it segfaults type `bt` to get a stack trace.  That should tell us something about where it's happening, which is the first step in understanding it.
- All of the errors are in single or mixed precision mode, which suggests problems in single precision math.  The low accuracy approximations for trig functions noted above could be part of it.  Another place I'd look is these lines:

https://github.com/openmm/openmm/blob/ffb3082fe7a2cec102acefb30c373db92d035968/platforms/opencl/src/OpenCLContext.cpp#L413-L417

OpenCL defines some math functions starting with `native_` that are allowed to be less accurate but may be faster.  We try to measure the accuracy of them and based on that decide whether to use them or not.  Try modifying those lines to force it to use the standard versions of those functions.

Also check these lines:

https://github.com/openmm/openmm/blob/ffb3082fe7a2cec102acefb30c373db92d035968/platforms/opencl/src/OpenCLContext.cpp#L209-L212

On most GPUs we enable some optimization flags, but not on Intel because we've found they lead to wrong results.  Make sure it's correctly identifying it as an Intel GPU and not setting any optimization flags.

- TestOpenCLCustomHbondForce times out.  That should be a really fast test.  On my laptop it takes less than a second.  Most likely that means it has hung.  See if you can identify exactly where.

**Comment by bdenhollander** [comment]
The CPU is platform 0 and the GPUs are in platform 1. benchmark.py automatically selected the fastest platform and found a GPU. I'm not sure how unit tests determine which OpenCL platform and device to run on. Based on the code below, if you run a failing test executable manually and pass 0 and 1 for the platform are the results any different?

```
TestOpenCLCustomAngleForce mixed 0
TestOpenCLCustomAngleForce mixed 1
TestOpenCLCustomAngleForce double 0
TestOpenCLCustomAngleForce double 1
```

https://github.com/openmm/openmm/blob/ffb3082fe7a2cec102acefb30c373db92d035968/platforms/opencl/tests/OpenCLTests.h#L40-L46

**Comment by nec4** [comment]
Apologies for the delay and thanks for all of the suggestions and support! I will give these a try and return soon with some updates.

**Comment by yafshar** [comment]
@nec4 this might happen on oneAPI before 2025.0. Please look at  https://github.com/openmm/openmm/pull/4366#issuecomment-1915716683 to fix the issue for older oneAPI, you need to add a `volatile` in that line. Then the test should pass `python -m openmm.testInstallation -v` Also why don't you use intel compiler ICX & ICPX instead of GNU for copiling the code?

**Comment by nec4** [comment]
Hello - thanks for the extra information - I will take a look at that next. As for not using ICX and ICPX, I encounter many problems with those compilers across many softwares (gromacs, plumed, etc) in the past - I avoid them out of habit (or perhaps naivety). I believe I tried such a build with those compilers earlier but have since deleted it so I will need to revisit that (though it must have not worked, otherwise I would have kept it :) )

**Comment by nec4** [comment]
Are there any other lines that need the `volatile` keyword?

**Comment by yafshar** [comment]
> Are there any other lines that need the `volatile` keyword?

Please also look at https://github.com/openmm/openmm/pull/4366#issuecomment-1915682726 
But this is only for CPU, it should not affect GPU run, and I do not know about anything else. When I tried oneAPI 2024.2 with these fixes and using Intel compilers, I did not find any other issues

**Comment by nec4** [comment]
Update: adding `volatile` where appropriate seems to help. Down to 13 failed/timing out tests:

```
96% tests passed, 13 tests failed out of 290

Total Test time (real) = 11252.12 sec

The following tests FAILED:
         69 - TestOpenCLCustomAngleForceMixed (SEGFAULT)
         70 - TestOpenCLCustomAngleForceDouble (SEGFAULT)
         78 - TestOpenCLCustomCVForceMixed (SEGFAULT)
         79 - TestOpenCLCustomCVForceDouble (SEGFAULT)
         92 - TestOpenCLCustomHbondForceSingle (Timeout)
         93 - TestOpenCLCustomHbondForceMixed (Timeout)
         94 - TestOpenCLCustomHbondForceDouble (Timeout)
         96 - TestOpenCLCustomIntegratorMixed (SEGFAULT)
         97 - TestOpenCLCustomIntegratorDouble (SEGFAULT)
        193 - TestCpuCustomNonbondedForce (Failed)
        215 - TestOpenCLAmoebaGeneralizedKirkwoodForceSingle (Failed)
        216 - TestOpenCLAmoebaGeneralizedKirkwoodForceMixed (Failed)
        218 - TestOpenCLAmoebaMultipoleForceMixed (Failed)
```

I will next try @peastman's suggestions in conjunction with this approach.

**Comment by nec4** [comment]
> The CPU is platform 0 and the GPUs are in platform 1. benchmark.py automatically selected the fastest platform and found a GPU. I'm not sure how unit tests determine which OpenCL platform and device to run on. Based on the code below, if you run a failing test executable manually and pass 0 and 1 for the platform are the results any different?
> 
> ```
> TestOpenCLCustomAngleForce mixed 0
> TestOpenCLCustomAngleForce mixed 1
> TestOpenCLCustomAngleForce double 0
> TestOpenCLCustomAngleForce double 1
> ```
> 
> https://github.com/openmm/openmm/blob/ffb3082fe7a2cec102acefb30c373db92d035968/platforms/opencl/tests/OpenCLTests.h#L40-L46

For sure I see different results for CPU only. On my login nodes (without any GPUs, but with the same libraries, OS, and most recent compilation strategy above), I get:

```
97% tests passed, 10 tests failed out of 290

Total Test time (real) = 11322.53 sec

The following tests FAILED:
        193 - TestCpuCustomNonbondedForce (Failed)
        213 - TestOpenCLAmoebaExtrapolatedPolarizationSingle (Failed)
        214 - TestOpenCLAmoebaExtrapolatedPolarizationMixed (Failed)
        215 - TestOpenCLAmoebaGeneralizedKirkwoodForceSingle (ILLEGAL)
        216 - TestOpenCLAmoebaGeneralizedKirkwoodForceMixed (ILLEGAL)
        217 - TestOpenCLAmoebaMultipoleForceSingle (Failed)
        218 - TestOpenCLAmoebaMultipoleForceMixed (Failed)
        223 - TestOpenCLHippoNonbondedForceSingle (Subprocess killed)
        224 - TestOpenCLHippoNonbondedForceMixed (Subprocess killed)
        229 - TestOpenCLRpmdMixed (Failed)
```
which is almost same as the GPU case and avoids the segfault problems. To be absolutely sure, I will run the tests manually as you suggest with my GPU-accessible build.

**Comment by peastman** [comment]
Try the latest code from the main branch.  I just merged the changes for Intel CPU OpenCL earlier today.

**Comment by nec4** [comment]
I will try it out today!

**Comment by nec4** [comment]
Some new update: This is the result from pulling the latest from `main` (9fe1bae6efa18a55994522a8aac4f24338a2894e), making no edits to the source (eg, not adding `volatile` keywords) and running tests in the presence of GPUs using OneAPI 2024.2:

```
84% tests passed, 45 tests failed out of 290

Total Test time (real) = 4917.97 sec

The following tests FAILED:
         62 - TestOpenCLCheckpointsSingle (Failed)
         63 - TestOpenCLCheckpointsMixed (Failed)
         64 - TestOpenCLCheckpointsDouble (Failed)
         68 - TestOpenCLCustomAngleForceSingle (Failed)
         69 - TestOpenCLCustomAngleForceMixed (Failed)
         70 - TestOpenCLCustomAngleForceDouble (Failed)
         71 - TestOpenCLCustomBondForceSingle (Failed)
         72 - TestOpenCLCustomBondForceMixed (Failed)
         73 - TestOpenCLCustomBondForceDouble (Failed)
         74 - TestOpenCLCustomCPPForceSingle (Failed)
         75 - TestOpenCLCustomCPPForceMixed (Failed)
         76 - TestOpenCLCustomCPPForceDouble (Failed)
         83 - TestOpenCLCustomCompoundBondForceSingle (Failed)
         84 - TestOpenCLCustomCompoundBondForceMixed (Failed)
         85 - TestOpenCLCustomCompoundBondForceDouble (Failed)
         86 - TestOpenCLCustomExternalForceSingle (Failed)
         87 - TestOpenCLCustomExternalForceMixed (Failed)
         88 - TestOpenCLCustomExternalForceDouble (Failed)
        101 - TestOpenCLCustomNonbondedForceSingle (Failed)
        102 - TestOpenCLCustomNonbondedForceMixed (Failed)
        103 - TestOpenCLCustomNonbondedForceDouble (Failed)
        104 - TestOpenCLCustomTorsionForceSingle (Failed)
        105 - TestOpenCLCustomTorsionForceMixed (Failed)
        106 - TestOpenCLCustomTorsionForceDouble (Failed)
        112 - TestOpenCLDispersionPMEDouble (Timeout)
        115 - TestOpenCLEwaldDouble (Timeout)
        125 - TestOpenCLHarmonicAngleForceSingle (Failed)
        126 - TestOpenCLHarmonicAngleForceMixed (Failed)
        127 - TestOpenCLHarmonicAngleForceDouble (Failed)
        128 - TestOpenCLHarmonicBondForceSingle (Failed)
        129 - TestOpenCLHarmonicBondForceMixed (Failed)
        130 - TestOpenCLHarmonicBondForceDouble (Failed)
        152 - TestOpenCLNonbondedForceSingle (Failed)
        153 - TestOpenCLNonbondedForceMixed (Failed)
        154 - TestOpenCLNonbondedForceDouble (Failed)
        158 - TestOpenCLPeriodicTorsionForceSingle (Failed)
        159 - TestOpenCLPeriodicTorsionForceMixed (Failed)
        160 - TestOpenCLPeriodicTorsionForceDouble (Failed)
        161 - TestOpenCLRBTorsionForceSingle (Failed)
        162 - TestOpenCLRBTorsionForceMixed (Failed)
        163 - TestOpenCLRBTorsionForceDouble (Failed)
        193 - TestCpuCustomNonbondedForce (Failed)
        215 - TestOpenCLAmoebaGeneralizedKirkwoodForceSingle (Failed)
        216 - TestOpenCLAmoebaGeneralizedKirkwoodForceMixed (Failed)
        246 - TestOpenCLDrudeSCFIntegratorDouble (Failed)
```

Quite a bit more failing, but no more segfaults. The `timeouts` you can ignore because I used `ctest --timeout 300` and I guess those cases are right on the edge of finishing (though I can rerun them to be sure). There are still some things to investigate. Our cluster will have (or perhaps already has, at least not publicly - need to check) OneAPI 2025 soon - I can make also some builds using that.

**Comment by peastman** [comment]
The code in the main branch assumes you're using oneAPI 2025.  It doesn't work correctly with 2024, at least on the CPU.

**Comment by peastman** [comment]
Did you get this working?  Is it ok to close it?

**Comment by nec4** [comment]
Hello,

Its totally fine to close if you wish. Unfortunately, I have not been able to look closely at this for some time due to some other obligations. If I have any luck, I will reach out again with what worked. 

Thanks for your initial suggestions and tips!
