### ISSUE TITLE
Iron (III) containing metalloprotein

### ISSUE THREAD

**Issue by meh47336** [openmm/openmm#4704]
Hi all,

I tried looking through the issues to see something in line with my issue, found things that were close.

In my CIF the residue is listed as FE (aka Fe3+).

I'm using the following:

```
forcefield = ForceField(
	'amber/protein.ff14SB.xml',
	'amber/tip3p_IOD_multivalent.xml'
	)
```

tip3p_IOD_multivalent.xml contains:

```
<Type element="Fe" name="tip3p_IOD_multivalent-Fe2+" class="tip3p_IOD_multivalent-Fe2+" mass="55.85"/>
<Type element="Fe" name="tip3p_IOD_multivalent-Fe3+" class="tip3p_IOD_multivalent-Fe3+" mass="55.85"/>
<Residue name="FE" override="1">
    <Atom name="FE" type="tip3p_IOD_multivalent-Fe3+" charge="3.0"/>
    </Residue>
<Residue name="FE2" override="1">
    <Atom name="FE2" type="tip3p_IOD_multivalent-Fe2+" charge="2.0"/>
    </Residue>
```
etc.

While performing `modeller.addHydrogens(forcefield)` I receive this exception:

`Exception: Multiple non-identical matching templates found for residue 403 (FE): FE, FE2.`

I've tried setting the following: `modeller.addHydrogens(forcefield, residueTemplates={'FE' : 'FE'})` with no luck.

Thanks for any help. Seems like there should be a simple solution that I'm missing.

**Comment by peastman** [comment]
The keys in `residueTemplates` should be Residue objects, not strings.  If the residue is called "FE" you should be able to do something like this.

```python
residueTemplates={residue: 'FE' for residue in topology.residues() if residue.name == 'FE'}
```

**Comment by meh47336** [comment]
Thanks for the quick response.

I modified the code so that:

```
iron={residue: 'FE' for residue in cif.topology.residues() if residue.name == 'FE'}
print(iron)
modeller.addHydrogens(forcefield, residueTemplates=iron)
```

When I print iron it shows:
`{<Residue 402 (FE) of chain 2>: 'FE', <Residue 403 (FE) of chain 3>: 'FE'}`

However, I'm still receiving:
```
Traceback (most recent call last):
  File "test/minimize_test.py", line 55, in <module>
    modeller.addHydrogens(forcefield, residueTemplates=iron)
  File "python3.9/site-packages/openmm/app/modeller.py", line 1012, in addHydrogens
    system = forcefield.createSystem(newTopology, rigidWater=False, nonbondedMethod=CutoffNonPeriodic, residueTemplates=residueTemplates)
  File "python3.9/site-packages/openmm/app/forcefield.py", line 1251, in createSystem
    templateForResidue = self._matchAllResiduesToTemplates(data, topology, residueTemplates, ignoreExternalBonds)
  File "python3.9/site-packages/openmm/app/forcefield.py", line 1434, in _matchAllResiduesToTemplates
    [template, matches] = self._getResidueTemplateMatches(res, data.bondedToAtom, ignoreExternalBonds=ignoreExternalBonds, ignoreExtraParticles=ignoreExtraParticles)
  File "python3.9/site-packages/openmm/app/forcefield.py", line 1039, in _getResidueTemplateMatches
    raise Exception('Multiple non-identical matching templates found for residue %d (%s): %s.' % (res.index+1, res.name, ', '.join(match[0].name for match in allMatches)))
Exception: Multiple non-identical matching templates found for residue 403 (FE): FE, FE2.
```

**Comment by peastman** [comment]
Can you try the release candidate of OpenMM 8.2?  You can install it with

```
mamba install -c conda-forge/label/openmm_rc -c conda-forge openmm
```

It includes a fix for a bug that may be the cause of that error.

**Comment by meh47336** [comment]
Thanks, that may have worked because now it's leading to a new issue.

The cif also contains butyric acid (BUA).

I attempted: 
```
butyric_acid = Molecule.from_smiles('O=C(O)CCC')
smirnoff = SMIRNOFFTemplateGenerator(molecules=butyric_acid)
forcefield.registerTemplateGenerator(smirnoff.generator)
```

And receive this:

```
Did not recognize residue BUA; did you forget to call .add_molecules() to add it?
Traceback (most recent call last):
  File "test/minimize_test2.py", line 31, in <module>
    modeller.addHydrogens(forcefield, residueTemplates=iron)
  File "python3.9/site-packages/openmm/app/modeller.py", line 1035, in addHydrogens
    system = forcefield.createSystem(newTopology, rigidWater=False, nonbondedMethod=CutoffNonPeriodic, residueTemplates=newResidueTemplates)
  File "python3.9/site-packages/openmm/app/forcefield.py", line 1257, in createSystem
    templateForResidue = self._matchAllResiduesToTemplates(data, topology, residueTemplates, ignoreExternalBonds)
  File "python3.9/site-packages/openmm/app/forcefield.py", line 1472, in _matchAllResiduesToTemplates
    raise ValueError('No template found for residue %d (%s).  %s  For more information, see https://github.com/openmm/openmm/wiki/Frequently-Asked-Questions#template' % (res.index+1, res.name, _findMatchErrors(self, res)))
ValueError: No template found for residue 402 (BUA).  The set of atoms is similar to ASP, but it is missing 6 atoms.
```

I wasn't sure if creating a new topology using OpenFF would change things, so performed:
```
butyric_acid = Molecule.from_smiles('O=C(O)CCC')
bua_list = [butyric_acid]
new_top = Topology.from_openmm(cif.topology, unique_molecules = bua_list)
smirnoff = SMIRNOFFTemplateGenerator(molecules=butyric_acid)
forcefield.registerTemplateGenerator(smirnoff.generator)
```

Which leads to:
```
Traceback (most recent call last):
  File "test/minimize_test2.py", line 29, in <module>
    new_top = Topology.from_openmm(cif.topology, unique_molecules = unique_molecules)
  File "python3.9/site-packages/openff/utilities/utilities.py", line 80, in wrapper
    return function(*args, **kwargs)
  File "python3.9/site-packages/openff/toolkit/topology/topology.py", line 1495, in from_openmm
    raise ValueError(msg)
ValueError: No match found for molecule C2109H3186N551O561S16. 
```

I realize this may be getting into OpenFF territory, but the solution feels so close.

Thanks again!

**Comment by peastman** [comment]
> It may have to do with protonation perhaps? The CIF protein and butyric acid contain no hydrogens, whereas the SMILES used above is for the protonated acid?

That seems likely.  You can call [`loadHydrogenDefinitions()`](http://docs.openmm.org/latest/api-python/generated/openmm.app.modeller.Modeller.html#openmm.app.modeller.Modeller.loadHydrogenDefinitions) to tell it what hydrogens to add.  See [this file](https://github.com/openmm/openmm/blob/master/wrappers/python/openmm/app/data/hydrogens.xml) for an example of what the format should be.

**Comment by meh47336** [comment]
I wasn't able to resolve the issue with that method. I decided to adjust the bonds in BUA and protonate the entire system using propka outside of openMM.

Currently I've made BUA molecule from SMILES and with the current protonation the PDB molecule should now match the SMILES. I then use SMIRNOFFTemplateGenerator on the BUA molecule. Finally, I register the TemplateGenerator to my forcefield. No errors appear here.

Now since I'm able to skip the protonation step in modelling that was giving the FE confusion, I attempt to create a system.

with `.createSystem ` I set residue templates to my iron dictionary (`iron={residue: 'FE' for residue in cif.topology.residues() if residue.name == 'FE'}`).

Now I receive the following error, which is new:

  ```
File "/minimize_test3.py", line 33, in <module>
    system = forcefield.createSystem(cif.topology, nonbondedMethod=PME, nonbondedCutoff=1*nanometer, constraints=HBonds, residueTemplates=iron)
  File "lib/python3.9/site-packages/openmm/app/forcefield.py", line 1257, in createSystem
    templateForResidue = self._matchAllResiduesToTemplates(data, topology, residueTemplates, ignoreExternalBonds)
  File "lib/python3.9/site-packages/openmm/app/forcefield.py", line 1437, in _matchAllResiduesToTemplates
    raise Exception('User-supplied template %s does not match the residue %d (%s)' % (tname, res.index+1, res.name))
Exception: User-supplied template FE does not match the residue 404 (FE)
```

I'm unsure why this system of butyric acid, a protein, and two metal ions is giving me so much trouble.

The end goal is simple energy minimization, likely using restraints on ions and small-molecule. Just relaxing the back bone and side chains around the ligands. Let me know if you can think of a simpler OpenMM solution if this current approach doesn't work.

Thanks again for your time!

**Comment by peastman** [comment]
Can you post your files so I can reproduce it and see what's happening?

**Comment by meh47336** [comment]
Sorry for the delay. Here are three files I've attempted using. The first is an AlphaFill output cif (msa_0_233G_test.cif). However, it doesn't appear to have correct bond orders in BUA, so I edited BUA using Schrodinger (schrod_edit.pdb). Additionally, in an attempt to bypass the OpenMM 'addHydrogens' I protonated BUA and protein using propka (schrod_edit_prot.pdb). The reason for the switch from CIF to PDB here is because the CIF output from Schrodinger didn't have the CONNECT records.

[msa_0_233G_test.cif.txt](https://github.com/user-attachments/files/17625332/msa_0_233G_test.cif.txt)

[schrod_edit.pdb.txt](https://github.com/user-attachments/files/17625337/schrod_edit.pdb.txt)

[schrod_edit_prot.pdb.txt](https://github.com/user-attachments/files/17625339/schrod_edit_prot.pdb.txt)

Thanks!

**Comment by peastman** [comment]
I also need the forcefield, and the complete script so I can see exactly what you're doing.

**Comment by meh47336** [comment]
Here are two versions of the script. Version 2 leads to `ValueError: No match found for molecule C2109H3186N551O561S16` and Version 3 leads to `Exception: Multiple non-identical matching templates found for residue 403 (FE): FE, FE2`.

Version 2 requires loading the hydrogen definitions (hydrogens.xml), which I edited to include Butyric Acid.

The two force fields are from OpenMMForceFields.

[minimize_test2.py.txt](https://github.com/user-attachments/files/17684787/minimize_test2.py.txt)
[minimize_test3.py.txt](https://github.com/user-attachments/files/17684792/minimize_test3.py.txt)
[hydrogens.xml.txt](https://github.com/user-attachments/files/17684795/hydrogens.xml.txt)
[protein.ff14SB.xml.txt](https://github.com/user-attachments/files/17684797/protein.ff14SB.xml.txt)
[tip3p_IOD_multivalent.xml.txt](https://github.com/user-attachments/files/17684800/tip3p_IOD_multivalent.xml.txt)

Thanks for the help! Ideally, this will just end with simple energy minimization but still need to successfully prepare the system.

**Comment by peastman** [comment]
I can't run your minimize_test3.py because you didn't include the file alkb_schrod_edit_prot.pdb.

I tried minimize_test2.py, but it fails at an earlier point in a call to OpenFF Toolkit:

```
  File "/Users/peastman/temp5/minimize_test2.py", line 36, in <module>
    new_top = Topology.from_openmm(cif.topology, unique_molecules = bua_list)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/peastman/miniconda3/envs/openmm/lib/python3.11/site-packages/openff/utilities/utilities.py", line 80, in wrapper
    return function(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/peastman/miniconda3/envs/openmm/lib/python3.11/site-packages/openff/toolkit/topology/topology.py", line 1506, in from_openmm
    raise ValueError(msg)
ValueError: No match found for molecule C2109H3186N551O561S16. 
```

**Comment by meh47336** [comment]
That failure for minimize_test2.py is the same problem I was encountering (post from Oct 24 @ 5pm). Hopefully you being able to reproduce the issue is helpful to some extent.

And apologies for renaming the pdb, the file I uploaded (schrod_edit_prot.pdb.txt) is the same as alkb_schrod_edit_prot.pdb

I was able to use another program to at least perform relaxation instead of EM. However, it would be great to see where I'm going wrong with OpenMM because I'd really like to learn and use it in the future.

Thanks again for your time.

**Comment by peastman** [comment]
The FE residue is failing to match because your PDB file adds a bond to it:

```
HETATM 6441 FE    FE D   1       4.572  -2.290  -9.269  1.00 97.82          Fe  
...
CONECT 6441 6430
```

The template doesn't expect it to be bonded to anything else, so it doesn't match.

The error in minimize_test2.py is coming from OpenFF Toolkit.  I'm not familiar with that code.  Possibly the OpenFF developers can help you with it.
