### ISSUE TITLE
AttributeError: 'StateDataReporter' object has no attribute '_out'

### ISSUE THREAD

**Issue by H-EKE** [openmm/openmm#4712]
Hi ,

I am trying to set a simulation with openMM, where it repports the minimization log and minimzed pdb, and then starts the equilibration and so on. 

```
# Add barostat and integrator
    system.addForce(MonteCarloMembraneBarostat(1.01325*u.bar, 0, 310*u.kelvin,
                                               MonteCarloMembraneBarostat.XYIsotropic,
                                               MonteCarloMembraneBarostat.ZFree))
    integrator = LangevinIntegrator(310*u.kelvin, 0.1/u.picoseconds, 2*u.femtoseconds)

    # Create simulation
    simulation = Simulation(psf.topology, system, integrator)
    simulation.context.setPositions(pdb.positions)

    # Minimize energy and report progress
    simulation.reporters.append(StateDataReporter(minimization_log_path, log_every, step=True, time=True,
                                                  potentialEnergy=True, temperature=True, progress=True,
                                                  remainingTime=True, speed=True, separator=';'))
    simulation.minimizeEnergy(maxIterations=5000)
    simulation.reporters.pop()  # Remove minimization reporter

    # Set up reporters for equilibration
    simulation.reporters.append(DCDReporter(equil_dcd_path, save_every, enforcePeriodicBox=False))
    simulation.reporters.append(PDBReporter(equil_pdb_path, equil_steps, enforcePeriodicBox=False))
    simulation.reporters.append(StateDataReporter(equil_log_path, log_every, step=True, time=True,
                                                  potentialEnergy=True, kineticEnergy=True, totalEnergy=True,
                                                  temperature=True, volume=True, density=True, progress=True,
                                                  remainingTime=True, speed=True, elapsedTime=True, separator=';',
                                                  totalSteps=equil_steps))

    # Run simulation with periodic restraint updates
    for percentage_sim in range(1, 101):
        update_restraint(simulation, percentage_sim, restraint_1)
        update_restraint(simulation, percentage_sim, restraint_2)
        simulation.step(int(equil_steps / 100))  # Run 1% of total steps

    # Write box size after equilibration
    write_boxsize(simulation, equil_boxsize_path)
```

when i run the code, I get this error

```
File "equilibration1.py", line 155, in <module>
    main()
  File "equilibration1.py", line 130, in main
    simulation.reporters.append(StateDataReporter(minimization_log_path, log_every, step=True, time=True,
  File "/opt/ohpc/pub/libs/miniconda/4.10.3/envs/openmm1/lib/python3.8/site-packages/openmm/app/statedatareporter.py", line 120, in __init__
    raise ValueError('Reporting progress or remaining time requires total steps to be specified')
ValueError: Reporting progress or remaining time requires total steps to be specified
Exception ignored in: <function StateDataReporter.__del__ at 0x7fe3aad9b3a0>
Traceback (most recent call last):
  File "/opt/ohpc/pub/libs/miniconda/4.10.3/envs/openmm1/lib/python3.8/site-packages/openmm/app/statedatareporter.py", line 371, in __del__
    self._out.close()
AttributeError: 'StateDataReporter' object has no attribute '_out'

```

Does anyone know how I can fix this issue? Im using OpenMM 7.0

**Comment by peastman** [comment]
That's an ancient version from more than eight years ago.  Please try with the latest release.

**Comment by H-EKE** [comment]
I would like to go to a recent version, but I cant since I wanna compare our ACEMD version (which runs with OpenMM 7.0 ) and pure OpenMM7.0, to see if I have similar behaviour in the MDs

**Comment by peastman** [comment]
I can't help with that.  We don't support versions from such a long time ago.

**Comment by H-EKE** [comment]
Oh, I understand. Thanks for you reply!
