### ISSUE TITLE
"kilojoule/mole" is not compatible with Unit "kilojoule/(nanometer*mole)" error

### ISSUE THREAD

**Issue by yazdan12555** [openmm/openmm#4719]
Hi, OpenMM community.

I have prepared my system with CHARMM-GUI and generated the openmm input files. However, when I try to run the calculation with the executable README, I get this error:

```
Traceback (most recent call last):
  File "/data/yazdan/Enhanced-sampling-MD/8GE1/charmm-gui-3/charmm-gui-3107828081/openmm/openmm_run.py", line 138, in <module>
    simulation.minimizeEnergy(tolerance=inputs.mini_Tol*kilojoule/mole, maxIterations=inputs.mini_nstep)
  File "/home/yazdan/.conda/envs/openmm/lib/python3.12/site-packages/openmm/app/simulation.py", line 143, in minimizeEnergy
    mm.LocalEnergyMinimizer.minimize(self.context, tolerance, maxIterations, reporter)
  File "/home/yazdan/.conda/envs/openmm/lib/python3.12/site-packages/openmm/openmm.py", line 9152, in minimize
    tolerance = tolerance.value_in_unit(unit.kilojoules_per_mole/unit.nanometer)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/yazdan/.conda/envs/openmm/lib/python3.12/site-packages/openmm/unit/quantity.py", line 626, in value_in_unit
    val = self.in_units_of(unit)
          ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/yazdan/.conda/envs/openmm/lib/python3.12/site-packages/openmm/unit/quantity.py", line 662, in in_units_of
    raise TypeError('Unit "%s" is not compatible with Unit "%s".' % (self.unit, other_unit))
TypeError: Unit "kilojoule/mole" is not compatible with Unit "kilojoule/(nanometer*mole)".
Warning: importing 'simtk.openmm' is deprecated.  Import 'openmm' instead.
```

Could you please help me to take care of this issue?

**Comment by peastman** [comment]
The value you pass for `tolerance` needs to be a force.  See [the API docs](http://docs.openmm.org/latest/api-python/generated/openmm.app.simulation.Simulation.html#openmm.app.simulation.Simulation.minimizeEnergy).  You passed an energy instead.  It's telling you that it can't convert the value you passed, which has units of kJ/mol, to the internally required units of kJ/mol/nm.
