### ISSUE TITLE
LocalEnergyMinimzer openmm 8.2

### ISSUE THREAD

**Issue by H-EKE** [openmm/openmm#4722]
Hi,

I noticed that in OpenMM 8, the EnergyMinimizer includes a reporter to track the evolution of energy. I was wondering if this is an efficient way to monitor energy minimization progress.

```
from openmm import LocalEnergyMinimizer
import openmm.unit as u

# Reporter
class MinimizationReporter:
    def report(self, context, step):
        energy = context.getState(getEnergy=True).getPotentialEnergy().value_in_unit(u.kilojoules_per_mole)
        with open('minimization.log', 'a') as f: f.write(f"{step}\t{energy:.2f}\n")

# Minimize and save
LocalEnergyMinimizer.minimize(simulation.context, reporter=MinimizationReporter())
with open("minimized_structure.pdb", 'w') as f: PDBFile.writeFile(simulation.topology, simulation.context.getState(getPositions=True).getPositions(), f)

```

Also there is a difference in the minimimzation algorith between LocalEnergyMiminze and .minimizeEnergy() ?

**Comment by peastman** [comment]
That isn't the correct signature for `report()`.  It should be

```python
def report(self, iteration, x, grad, args):
```

See [the API documentation](http://docs.openmm.org/latest/api-c++/generated/MinimizationReporter.html) for a description of the information passed to it.

> Also there is a difference in the minimimzation algorith between LocalEnergyMiminze and .minimizeEnergy() ?

They're the same thing.  `minimizeEnergy()` is just a thin wrapper around a call to LocalEnergyMinimizer.

**Comment by H-EKE** [comment]
Thanks a lot!!

**Comment by peastman** [comment]
Try calling it as

```python
simulation.minimizeEnergy(reporter=reporter, maxIterations=5000)
```

Does that work?

**Comment by H-EKE** [comment]
Thanks for the suggestion. I tried and I got the same log error

```
Minimizing energy...
Traceback (most recent call last):
  File "/scratch_shared/openmm_test1/trial2.py", line 141, in <module>
    simulation.minimizeEnergy(reporter=reporter, maxIterations=5000)
  File "/home/.conda/envs/opemm8.2/lib/python3.12/site-packages/openmm/app/simulation.py", line 143, i
n minimizeEnergy
    mm.LocalEnergyMinimizer.minimize(self.context, tolerance, maxIterations, reporter)
  File "/home/.conda/envs/opemm8.2/lib/python3.12/site-packages/openmm/openmm.py", line 4211, in minim
ize
    return _openmm.LocalEnergyMinimizer_minimize(context, tolerance, maxIterations, reporter)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Wrong number or type of arguments for overloaded function 'LocalEnergyMinimizer_minimize'.
  Possible C/C++ prototypes are:
    OpenMM::LocalEnergyMinimizer::minimize(OpenMM::Context &,double,int,OpenMM::MinimizationReporter *)
    OpenMM::LocalEnergyMinimizer::minimize(OpenMM::Context &,double,int)
    OpenMM::LocalEnergyMinimizer::minimize(OpenMM::Context &,double)
    OpenMM::LocalEnergyMinimizer::minimize(OpenMM::Context &)



```

**Comment by peastman** [comment]
For some reason, SWIG is rejecting any reporter class that has an `__init__()` method.  I'm not sure why.  The example shown in https://swig.org/Doc4.0/SWIGDocumentation.html#Python_nn33 does have an initializer.  The mechanisms for calling back into Python from C++ are complicated.

**Comment by H-EKE** [comment]
mmm I see.

So there is not an easy way to get a minimization log though python?

**Comment by peastman** [comment]
Here's an example of a working minimization reporter, found in one of the unit tests:

https://github.com/openmm/openmm/blob/87810125957f807e7b1688091e5e4546dbe1d3b6/wrappers/python/tests/TestSimulation.py#L209-L221

It works correctly.  But if I modify it to initialize the fields inside a constructor like this

```python
    def __init__(self):
        self.lastIteration = -1
        self.error = False
```

then it gets the error you reported.

**Comment by H-EKE** [comment]
Oh I see

```
class MyMinimizationReporter(MinimizationReporter):
    log_file_path = None
    energies = None
    initialized = False

    def report(self, iteration, x, grad, args):
        # Lazy initialization
        if not self.initialized:
            self.energies = []
            self.log_file_path = "minimization_log.csv"  # Replace with the desired file path
            with open(self.log_file_path, 'w') as f:
                f.write("iteration,energy\n")
            self.initialized = True

        current_energy = args['system energy']
        if iteration % 100 == 0:
            print(current_energy)

        self.energies.append(current_energy)
        with open(self.log_file_path, 'a') as f:
            f.write(f"{iteration},{current_energy}\n")

        return False
```

Defining my reporter like this worked. Thanks for the help!
