### ISSUE TITLE
OpenMM 8.2.0 does not support numpy 2

### ISSUE THREAD

**Issue by Sarkosos** [openmm/openmm#4725]
## Error
When importing app: `from openmm import app` the following error gets printed: 
```bash
A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.0.2 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "/home/paperspace/miniconda3/envs/folding-test/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/paperspace/miniconda3/envs/folding-test/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/paperspace/miniconda3/envs/folding-test/lib/python3.9/site-packages/ipykernel_launcher.py", line 18, in <module>
    app.launch_new_instance()
  File "/home/paperspace/miniconda3/envs/folding-test/lib/python3.9/site-packages/traitlets/config/application.py", line 1075, in launch_instance
    app.start()
  File "/home/paperspace/miniconda3/envs/folding-test/lib/python3.9/site-packages/ipykernel/kernelapp.py", line 739, in start
    self.io_loop.start()
  File "/home/paperspace/miniconda3/envs/folding-test/lib/python3.9/site-packages/tornado/platform/asyncio.py", line 205, in start
    self.asyncio_loop.run_forever()
  File "/home/paperspace/miniconda3/envs/folding-test/lib/python3.9/asyncio/base_events.py", line 601, in run_forever
    self._run_once()
  File "/home/paperspace/miniconda3/envs/folding-test/lib/python3.9/asyncio/base_events.py", line 1905, in _run_once
    handle._run()
  File "/home/paperspace/miniconda3/envs/folding-test/lib/python3.9/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/home/paperspace/miniconda3/envs/folding-test/lib/python3.9/site-packages/ipykernel/kernelbase.py", line 545, in dispatch_queue
    await self.process_one()
  File "/home/paperspace/miniconda3/envs/folding-test/lib/python3.9/site-packages/ipykernel/kernelbase.py", line 534, in process_one
    await dispatch(*args)
  File "/home/paperspace/miniconda3/envs/folding-test/lib/python3.9/site-packages/ipykernel/kernelbase.py", line 437, in dispatch_shell
    await result
  File "/home/paperspace/miniconda3/envs/folding-test/lib/python3.9/site-packages/ipykernel/ipkernel.py", line 362, in execute_request
    await super().execute_request(stream, ident, parent)
  File "/home/paperspace/miniconda3/envs/folding-test/lib/python3.9/site-packages/ipykernel/kernelbase.py", line 778, in execute_request
    reply_content = await reply_content
  File "/home/paperspace/miniconda3/envs/folding-test/lib/python3.9/site-packages/ipykernel/ipkernel.py", line 449, in do_execute
    res = shell.run_cell(
  File "/home/paperspace/miniconda3/envs/folding-test/lib/python3.9/site-packages/ipykernel/zmqshell.py", line 549, in run_cell
    return super().run_cell(*args, **kwargs)
  File "/home/paperspace/miniconda3/envs/folding-test/lib/python3.9/site-packages/IPython/core/interactiveshell.py", line 3048, in run_cell
    result = self._run_cell(
  File "/home/paperspace/miniconda3/envs/folding-test/lib/python3.9/site-packages/IPython/core/interactiveshell.py", line 3103, in _run_cell
    result = runner(coro)
  File "/home/paperspace/miniconda3/envs/folding-test/lib/python3.9/site-packages/IPython/core/async_helpers.py", line 129, in _pseudo_sync_runner
    coro.send(None)
  File "/home/paperspace/miniconda3/envs/folding-test/lib/python3.9/site-packages/IPython/core/interactiveshell.py", line 3308, in run_cell_async
    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
  File "/home/paperspace/miniconda3/envs/folding-test/lib/python3.9/site-packages/IPython/core/interactiveshell.py", line 3490, in run_ast_nodes
    if await self.run_code(code, result, async_=asy):
  File "/home/paperspace/miniconda3/envs/folding-test/lib/python3.9/site-packages/IPython/core/interactiveshell.py", line 3550, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "/tmp/ipykernel_920232/1642230143.py", line 1, in <module>
    import openmm.app as app
  File "/home/paperspace/miniconda3/envs/folding-test/lib/python3.9/site-packages/openmm/app/__init__.py", line 17, in <module>
    from .xtcfile import XTCFile
  File "/home/paperspace/miniconda3/envs/folding-test/lib/python3.9/site-packages/openmm/app/xtcfile.py", line 6, in <module>
    from openmm.app.internal.xtc_utils import (
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
Cell In[1], [line 1](vscode-notebook-cell:?execution_count=1&line=1)
----> [1](vscode-notebook-cell:?execution_count=1&line=1) import openmm.app as app

File ~/miniconda3/envs/folding-test/lib/python3.9/site-packages/openmm/app/__init__.py:17
     [15](https://vscode-remote+ssh-002dremote-002b74-002e82-002e28-002e111.vscode-resource.vscode-cdn.net/home/paperspace/szymon/folding/~/miniconda3/envs/folding-test/lib/python3.9/site-packages/openmm/app/__init__.py:15) from .topology import Topology, Chain, Residue, Atom
     [16](https://vscode-remote+ssh-002dremote-002b74-002e82-002e28-002e111.vscode-resource.vscode-cdn.net/home/paperspace/szymon/folding/~/miniconda3/envs/folding-test/lib/python3.9/site-packages/openmm/app/__init__.py:16) from .pdbfile import PDBFile
---> [17](https://vscode-remote+ssh-002dremote-002b74-002e82-002e28-002e111.vscode-resource.vscode-cdn.net/home/paperspace/szymon/folding/~/miniconda3/envs/folding-test/lib/python3.9/site-packages/openmm/app/__init__.py:17) from .xtcfile import XTCFile
     [18](https://vscode-remote+ssh-002dremote-002b74-002e82-002e28-002e111.vscode-resource.vscode-cdn.net/home/paperspace/szymon/folding/~/miniconda3/envs/folding-test/lib/python3.9/site-packages/openmm/app/__init__.py:18) from .pdbxfile import PDBxFile
     [19](https://vscode-remote+ssh-002dremote-002b74-002e82-002e28-002e111.vscode-resource.vscode-cdn.net/home/paperspace/szymon/folding/~/miniconda3/envs/folding-test/lib/python3.9/site-packages/openmm/app/__init__.py:19) from .forcefield import ForceField

File ~/miniconda3/envs/folding-test/lib/python3.9/site-packages/openmm/app/xtcfile.py:6
      [3](https://vscode-remote+ssh-002dremote-002b74-002e82-002e28-002e111.vscode-resource.vscode-cdn.net/home/paperspace/szymon/folding/~/miniconda3/envs/folding-test/lib/python3.9/site-packages/openmm/app/xtcfile.py:3) __author__ = "Raul P. Pelaez"
      [4](https://vscode-remote+ssh-002dremote-002b74-002e82-002e28-002e111.vscode-resource.vscode-cdn.net/home/paperspace/szymon/folding/~/miniconda3/envs/folding-test/lib/python3.9/site-packages/openmm/app/xtcfile.py:4) __version__ = "1.0"
----> [6](https://vscode-remote+ssh-002dremote-002b74-002e82-002e28-002e111.vscode-resource.vscode-cdn.net/home/paperspace/szymon/folding/~/miniconda3/envs/folding-test/lib/python3.9/site-packages/openmm/app/xtcfile.py:6) from openmm.app.internal.xtc_utils import (
      [7](https://vscode-remote+ssh-002dremote-002b74-002e82-002e28-002e111.vscode-resource.vscode-cdn.net/home/paperspace/szymon/folding/~/miniconda3/envs/folding-test/lib/python3.9/site-packages/openmm/app/xtcfile.py:7)     xtc_rewrite_with_new_timestep,
      [8](https://vscode-remote+ssh-002dremote-002b74-002e82-002e28-002e111.vscode-resource.vscode-cdn.net/home/paperspace/szymon/folding/~/miniconda3/envs/folding-test/lib/python3.9/site-packages/openmm/app/xtcfile.py:8)     xtc_write_frame,
      [9](https://vscode-remote+ssh-002dremote-002b74-002e82-002e28-002e111.vscode-resource.vscode-cdn.net/home/paperspace/szymon/folding/~/miniconda3/envs/folding-test/lib/python3.9/site-packages/openmm/app/xtcfile.py:9)     get_xtc_nframes,
     [10](https://vscode-remote+ssh-002dremote-002b74-002e82-002e28-002e111.vscode-resource.vscode-cdn.net/home/paperspace/szymon/folding/~/miniconda3/envs/folding-test/lib/python3.9/site-packages/openmm/app/xtcfile.py:10)     get_xtc_natoms,
     [11](https://vscode-remote+ssh-002dremote-002b74-002e82-002e28-002e111.vscode-resource.vscode-cdn.net/home/paperspace/szymon/folding/~/miniconda3/envs/folding-test/lib/python3.9/site-packages/openmm/app/xtcfile.py:11) )
     [12](https://vscode-remote+ssh-002dremote-002b74-002e82-002e28-002e111.vscode-resource.vscode-cdn.net/home/paperspace/szymon/folding/~/miniconda3/envs/folding-test/lib/python3.9/site-packages/openmm/app/xtcfile.py:12) import os
     [13](https://vscode-remote+ssh-002dremote-002b74-002e82-002e28-002e111.vscode-resource.vscode-cdn.net/home/paperspace/szymon/folding/~/miniconda3/envs/folding-test/lib/python3.9/site-packages/openmm/app/xtcfile.py:13) from openmm import Vec3

File openmm/app/internal/xtc_utils/xtc.pyx:1, in init openmm.app.internal.xtc_utils()

ImportError: numpy.core.multiarray failed to import (auto-generated because you didn't call 'numpy.import_array()' after cimporting numpy; use '<void>numpy._import_array' to disable if you are certain you don't need it).
```

The error indicates that openmm is not compatible with numpy 2, this shouldn't be true after #4622 was merged. 

## Steps to reproduce

```bash
conda create -n folding-test python=3.9
conda activate folding-test
conda install -c conda-forge openmm
pip install numpy==2.0.2 #overwrite numpy to use numpy 2
```

Then in python:
```python
from openmm import app
```

version of both packages printed:
![image](https://github.com/user-attachments/assets/bd101da0-e32e-42a6-82d5-01ddb7c86edf)

My main question: Is there anything wrong with my environment or installation methods or does openmm not support numpy 2 yet? Thanks in advance for all the support!

**Comment by peastman** [comment]
OpenMM 8.2 supports numpy 2.  I think the problem is that you're mixing packages from pip and conda.  That generally doesn't work correctly.

It also should have already installed the most recent numpy version available along with OpenMM.  What does `conda list | grep numpy` show immediately after installing OpenMM?

Note that pinning it to python 3.9 will limit the choices, since the most recent numpy versions are only available for newer python versions.

**Comment by Sarkosos** [comment]
Mixing might be the problem but the newest openmm version install an older version of numpy and conda doesn't allow installation of conflicting packages (for a good reason).

Here's the output you were asking for:
```bash
(folding-test) paperspace@psaz05r69nra:~/szymon/folding$ conda list | grep numpy
numpy                     1.26.4           py39heeff2f4_0  
numpy-base                1.26.4           py39h8a23956_0  
```

Let me try with python >3.9 to confirm that isn't the issues

**Comment by Sarkosos** [comment]
Yep that worked for me, seems there was a combination of issues. 1 issue is the older Python version and then also Conda installing the wrong version of numpy even at higher Python versions. Closing for now, thank you for all the help @peastman!

**Comment by j3mdamas** [comment]
In case someone faces similar issues, it can also be due to an old OS. OSes that have reached EoL don't like numpy>=2, but downgrading to numpy<2 still works on those.
