### ISSUE TITLE
openmm.OpenMMException: Particle coordinate is NaN

### ISSUE THREAD

**Issue by gaoxiangcao** [openmm/openmm#4745]
Hi,
I am running an OpenMM simulation involving a protein-DNA complex and encountered the following error during energy minimization and NVT equilibration:

Traceback (most recent call last):
  File "/media/storageD/gaoxiang/bioinformatics/openmm/mds/LHX2_Ldb1_EBf1_complex/simulateAmber.py", line 36, in <module>
    simulation.step(5000)
  File "/media/storageD/gaoxiang/miniconda3/envs/openmm/lib/python3.12/site-packages/openmm/app/simulation.py", line 150, in step
    self._simulate(endStep=self.currentStep+steps)
  File "/media/storageD/gaoxiang/miniconda3/envs/openmm/lib/python3.12/site-packages/openmm/app/simulation.py", line 229, in _simulate
    self.integrator.step(10) # Only take 10 steps at a time, to give Python more chances to respond to a control-c.
    ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/media/storageD/gaoxiang/miniconda3/envs/openmm/lib/python3.12/site-packages/openmm/openmm.py", line 3268, in step
    return _openmm.LangevinMiddleIntegrator_step(self, steps)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
openmm.OpenMMException: Particle coordinate is NaN.  For more information, see https://github.com/openmm/openmm/wiki/Frequently-Asked-Questions#nan

Attached with my code
[test_simulateamber_test.txt](https://github.com/user-attachments/files/17999570/test_simulateamber_test.txt)

**Comment by gaoxiangcao** [comment]
My input is also attached!
[ppcomplex_solv.inpcrd.zip](https://github.com/user-attachments/files/17999627/ppcomplex_solv.inpcrd.zip)
[ppcomplex_solv.prmtop.zip](https://github.com/user-attachments/files/17999629/ppcomplex_solv.prmtop.zip)

**Comment by gaoxiangcao** [comment]
Thank you for your response. I followed the troubleshooting steps outlined in the link you provided and made several attempts to debug the issue, but I have not been able to resolve the problem.

My simulation involves a complex system consisting of three proteins and one DNA molecule. To prepare the system, I used AmberTools with the following code:
source leaprc.protein.ff14SB
source leaprc.DNA.OL21
loadOff terminal_monophosphate.lib
source leaprc.water.tip3p

ProA = loadpdb inputA.pdb
ProB = loadpdb inputB.pdb
ProC = loadpdb inputC.pdb
DNA = loadpdb inputD.pdb

mol = combine {ProA, ProB, ProC, DNA}
check mol

solvatebox mol TIP3PBOX 12.0
addions mol Cl- 0
addions mol Na+ 0
charge mol
savepdb mol ppcomplex_solv.pdb
saveamberparm mol ppcomplex_solv.prmtop ppcomplex_solv.inpcrd
quit

Given this, I suspect there might be an issue with my input files, but I have not been able to identify the exact cause. Could you kindly help me review the input files or suggest any further debugging steps that I might have missed?

**Comment by peastman** [comment]
I started by computing the energy of your input coordinates:

```python
print(simulation.context.getState(energy=True).getPotentialEnergy())
```

which prints

```
3163942451.650424 kJ/mol
```

That's a huge energy indicating very severe clashes.  It's beyond what the local energy minimizer can deal with.  I next checked to see what particles had the largest forces on them, since that indicates where the clashes are.

```python
forces = simulation.context.getState(forces=True).getForces().value_in_unit(kilojoules_per_mole/nanometer)
for i,f in enumerate(forces):
    if sqrt(dot(f, f)) > 100000:
        print(i, f)
```

It lists hundreds of particles with huge forces on them:

```
34 Vec3(x=-4113252.75, y=-8960954.0, z=-6670408.0)
55 Vec3(x=4135954.75, y=8951748.0, z=6666623.0)
128 Vec3(x=-357933.0, y=-112751.2890625, z=-418833.53125)
146 Vec3(x=358140.0, y=112510.25, z=418589.84375)
214 Vec3(x=-521451.625, y=-200468.0625, z=224900.4375)
216 Vec3(x=-2147483648.0, y=-2147483648.0, z=-2147483648.0)
231 Vec3(x=200771.953125, y=238138.09375, z=-86652.8125)
232 Vec3(x=2147483520.0, y=-2147483648.0, z=-2147483520.0)
914 Vec3(x=-217150.484375, y=49948.65625, z=66509.6171875)
915 Vec3(x=-731558.6875, y=-367114.125, z=191474.96875)
1458 Vec3(x=-112635.03125, y=72307.234375, z=-1245.943603515625)
1719 Vec3(x=-148653.5, y=51690.93359375, z=-333253.53125)
...
```

It looks like your model has severe, widespread clashes.  You'll need to figure out where they came from in your preparation workflow.
